local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Alliance_Vanguard")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "Alliance Vanguard (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

K@ljmibqbMob*NrbpqyKyVlrtfiikbbaql`ljmibqbF`b`oltk%44*5-Ilob&coljqebIbsbifkddrfabpb`qflk_bclobvlr`^krpbqefpdrfabyyNFAy.00.1y
K@ljmibqbMob*NrbpqyKyVlrtfiikbbaql`ljmibqbPqlojMb^hp%44*5-&coljqebIbsbifkddrfabpb`qflk_bclobvlr`^krpbqefpdrfabyyNFAy.0-14y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyWy16/yyTOyyAy
>@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyWy16/yyAyyKM@y0-011y
>?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`eblkQebPhv_ob^hboyyNFAy.0003yyWy16/yyAyyKM@y0/0-/y

@@^mqrobJlobAfpm^q`ebpyKyRpbXA^oqDrkZql`^mqrob3Lodofj$pE^jjboP`lrqp^olrkaqebt^vmlfkq%15)21&yyRy11///yyNFAy.0000yyWy16/yyAyyKM@y0//-.y

>>pp^riq_vDolrkayKyPhv_ob^hboPnr^aIb^abo%3/+4)2.&yyNFAy.0/51yyWy16/yyAyyKM@y0.404y
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.0/51yyWy16/yyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.0003yyWy16/yyAyyKM@y0./25)0./34)0./3/y
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.0/51yyWy16/yyAyyKM@y0.5-5y

>>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyWy16/yyAyyKM@y0.5-5y
@>pp^riq_v>foyKyDlql%26+3)13+-&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00-6yyWy16/yyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboHlrm%3/+3)2.+0&yyNFAy.00-6yyWy16/yyAyyKM@y0.5-5y

>HfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyWy16/yyAyyKM@y0.443y
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21)26&yyNFAy.0/5-yyWy16/yyAyyKM@y0.44-y
QHfkdlcqebJlrkq^fkyKyCo^wwibDb^odofkabo%24)3/+2&yyNFAy.0/5-yyWy16/yyAyyKM@y0.443y

OQebPhv_ob^hboyKyQefpfpqeb>iif^k`bPefmqe^qcifbp^olrkaF`b`oltk%24)04&)%3-)13&)%31+1)23&yyWy16/yyTOyyAy
Q@^mqrobJlobAfpm^q`ebpyKyEfde@^mq^fkGrpqfk?^oqibqqlkQebPhv_ob^hboyyNFAy.0000yyWy16/yyAyyKM@y0-011y
Q?illalcqeb@elpbkyKyHkfdeq*@^mq^fkAolp`eblkQebPhv_ob^hboyyNFAy.0003yyWy16/yyAyyKM@y0/0-/y

OColpqeliayKyQo^sbiqlColpqElia%/6+5)42+4&yyWy162yyAy
>MrpebaQllC^oyKyCgloifkColpq_olt%/6+5)42+4&yyNFAy./536yyAyyKM@y/640/yyWy162y
@MrpebaQllC^oyKyTebkvlrpq^oqqefpnrbpq)vlr$iijlrkqrmlk^Pqloj`obpqB^dib+CivqlqebCllqPqbmmbpfkqebKloqeb^pq^kaillhcloPqlojmb^hTvojp%13+2)3.+6&+Vlro_fddbpq`e^iibkdbtfii_b`^q`efkdqebqefkdp)pfk`bqebv`^kcivc^pqboqe^kvlrob^dibalbp+Qebmobcboobamobvtfii_bqebtvojptel^obbfqeboollpqbalkqebjlrkq^fkp^kaol`hplo^ob^qq^`hfkdoefklp+Fcvlrcfkalkblcqelpb)qebv$obb^pvmf`hfkdp+Qebvjbibb^kae^sb^tb^hcolpq_ob^qe^qq^`h)_rq^obklqeob^qqlvlrob^dib+Fcvlr`^k$qcfka^kvtel^obollpqbaloafpqo^`qba)vlr`^k`^q`eqebcifbop_veb^afkdqebjlcc+Qebvj^v_bc^pqbo)_rqvlr$objr`ejlobj^kbrsbo^_ibyyNFAy./536yyAyyKM@y/6521)/6420yyWy162y
QMrpebaQllC^oyKyCgloifkColpq_olt%/6+5)42+4&yyNFAy./536yyAyyKM@y/640/yyWy162y

OPqbbiD^qbyKyQo^sbiqlPqbbiD^qb%0-+.-)/5+4.&yyNFAy..06.yyAyyWy155y
>PbbqlqebLmbo^qflkpyKyLsbopbboFobk^Pqlkbj^kqib%0-+/)/5+4&yyNFAy...43yyKM@y/056.yyWy155y
QPbbqlqebLmbo^qflkpyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy...43yyKM@y/1066yyWy155y
>F$sbDlq^CivfkdJ^`efkbyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06-yyKM@y/1066yyWy155y
@F$sbDlq^CivfkdJ^`efkbyNFAy..06-yyKyJ^hbprobvlrdbqfkqebofdeqmi^kb%qebob^obqtl+++lkbtfqetb^mlkp^kalkbtfqe^do^mmifkdellh&+Qebk_bclobvlrdllccfkqlqebjfkfkdmfqqrok^olrka^kaj^hbprobqebmi^kbcivp%pljbalklqciv&+Qebkcivfkqlqebmfq)dbq`ilpbqlqebi^odb_^d^karpbqebDo^mmifkdEllhqldbqqeb_^d+Vlr`^klkiv`^oov._^d^q^qfjbyyKM@y/1106yyWy155y
QF$sbDlq^CivfkdJ^`efkbyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06-yyKM@y/1066yyWy155y
>PqbbiD^qbM^qoliyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06.yyAyyKM@y/1066yyWy155y
@PqbbiD^qbM^qoliyKyRpbqebCivfkdj^`efkbqlhfii5uD^odlvibp^qqebafdpfqb^ob^%0.+.)/3+1&yyNFAy..06.yyAyyKM@y/111-yyWy155y
QPqbbiD^qbM^qoliyKyPqbbiD^qb@efbc>o`e^blildfpq%0-+5)/5+3&yyNFAy..06.yyAyyKM@y/1066yyWy155y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
