local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Argent_Tournament_Aspirant_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Argent Tournament|r ", "Argent Tournament (Aspirant Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

OPfisbo@lsbk^kqM^sfiflkyKyQo^sbiql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWy16/y

K>``bmq0A^fivNrbpqyKy>o`^kfpqQ^bifp%43+2).6+2&lccbop.lc0o^kalja^fivnrbpqpyyWy16/yyKM@y003/2y
>QebBadbLcTfkqboyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.034-yyWy16/yyAyyKM@y003/2y
>>?i^abCfqClo>@e^jmflkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0333yyWy16/yyAyyKM@y003/2y
>>TloqevTb^mlkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0336yyWy16/yyAyyKM@y003/2y
>Qo^fkfkdFkQebCfbiayKy>s^obqePtfcqpqofhb%43+2).6+1&)A^fivyyNFAy.034.yyWy16/yyAyyKM@y00313y
>Ib^okfkdQebObfkpyKyP`lrqPe^ivkaof^%43+2).6+2&)A^fivyyNFAy.03/2yyWy16/yyAyyKM@y00314y

KJlrkqRmySyyKyBnrfmX>iif^k`bI^k`bZ^kadbq^Jlrkq%42+6)/-+1&lo%4.+52)/-&yyRy13-36yyWy16/yyAyyNFAy.03/2y
@Ib^okfkdQebObfkpyKyBnrfmqebX>iif^k`bI^k`bZ^kajlrkqqebNrbi$alobfPqbbaclrka^qqebt^vmlfkq%42+6)/-+1&+RpbqebQorpq^_fifqvlk^JbibbQ^odbq2qfjbp)rpfkdAbcbka`lkpq^kqivqlhbbm0i^vboprm+ObcobpevlrojlrkqqebkrpbqebPefbia?ob^hbo^_fifqvlk^O^kdbaQ^odbqobmb^qfsbivrkqfisrikbo^_ibqebkrpbqebPefbia?ob^hbo^_fifqvlk^@e^odbQ^odbqqebkrpbqeb@e^odb^_fifqvqtf`btefibfqppefbiafpaltkyyNFAy.03/2yyAyyKM@y00510)00//6)00/10)00/4/y
@Qo^fkfkdFkQebCfbiayKyHfii^kvP`lrodb^olrkaqebt^vmlfkq%4.+1)04+6&yyNFAy.034.yyWy16/yyAyyKM@y0.450)0.4.5y
@>?i^abCfqClo>@e^jmflkyLyyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrkaqebt^vmlfkq%3-+2)2.+2&fkDofwwivEfiipyyRy11653yyNFAy.0333yyWy16-yyAyyKM@y00//1y

HIloaBsbo_i^wbyKyHfiiIloaBsbo_i^wb^olrkaqebt^vmlfkq%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZyyIy12--2yyWy2.-yyLyyNFAy.034-yyAyyKM@y00/56y
@QebBadbLcTfkqboyLyyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^qqebt^vmlfkq%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyNFAy.034-yyWy16.yyAyyKM@y000-0y

K1XTfkqboEv^`fkqeZyKy@liib`q1XTfkqboEv^`fkqeZ^olrkaqebt^vmlfkq%4.)41+2&fkF`b`oltkyyIy12---1yyWy16/yyQyyLyyNFAy.0336yyAyyL?Gy0/0.y
@>TloqevTb^mlkyLyyKyRpbqebXTfkqboEv^`fkqeZfkpfabqebofkdlccil^qfkdl_gb`qp^kaqebJ^fabktfii^mmb^o%6/+5)/2+1&+QebX?i^ablcAo^h$J^oZtfiipm^tkkbuqqlebo^cqbopljbaf^ildrb+Ao^dlk_ifdeqyyRy12---yyWy155yyNFAy.0336yyAyyKM@y00/40yyL?Gy5231y

OPfisbo@lsbk^kqM^sfiflkyKyQo^sbiql>odbkqQlrok^jbkqDolrkapfkF`b`oltk%4/+3)//+3&yyWy16/y

Q>?i^abCfqClo>@e^jmflkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0333yyWy16/yyAyyKM@y003/2y
QQebBadbLcTfkqboyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.034-yyWy16/yyAyyKM@y003/2y
Q>TloqevTb^mlkyLyyKy>o`^kfpqQ^bifp%43+2).6+2&)A^fivyyNFAy.0336yyWy16/yyAyyKM@y003/2y
QQo^fkfkdFkQebCfbiayKy>s^obqePtfcqpqofhb%43+2).6+1&)A^fivyyNFAy.034.yyWy16/yyAyyKM@y00313y
QIb^okfkdQebObfkpyKyP`lrqPe^ivkaof^%43+2).6+2&)A^fivyyNFAy.03/2yyWy16/yyAyyKM@y00314y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
