local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Storm_Peaks_Daily_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "Brunnhildar Village (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

K@ljmibqbMob*NrbpqyKyVlrtfiikbbaql`ljmibqbPqlojMb^hp%44*5-&coljqebIbsbifkddrfabpb`qflk_bclobvlr`^krpbqefpdrfabyyNFAy.0-14y

O?orkkefia^oSfii^dbyKyCivql?orkkefia^oSfii^db%2-+6)32+3&yyWy162y
K>``bmqA^fivNrbpqpyJAyyKy>``bmqnrbpqpcoljDobqq^qeb>o_fqbo%2-+6)32+3&)qf`hqefppqbmql`lkqfkrbyyKM@y/6463yyWy162yyJAy
>Qeb>_boo^qflkpJrpqAfbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01/2yyAyyKM@y/6463yyWy162y
>J^fkq^fkfkdAfp`fmifkbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01//yyAyyKM@y/6463yyWy162y
>?^`hqlqebMfqyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01/1yyAyyKM@y/6463yyWy162y
>AbcbkafkdVlroQfqibyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyLyyNFAy.01/0yyAyyKM@y/6463yyWy162y

@Qeb>_boo^qflkpJrpqAfbyKyDlqlS^ihvoflk%/2)3-&^kal_q^fkXSf^iplcColpqLfiZcoljqebS^ihvoflk>pmfo^kqp+RpbqebXSf^ilcColpqLfiZqlabpqolv0-Mi^drbaMolql*Ao^hbBddpyyRy1.3./yyNFAy.01/2yyLyyAyyKM@y/6236yyL?Gy056.yyWy162y
@J^fkq^fkfkdAfp`fmifkbyKyDlfkpfabqeb`^sb^qqebt^vmlfkq%1/)4-&^kacfkaqebBue^rpqbaSovhri^karpbqebXAfp`fmifkfkdOlaZqldbqqebj_^`hqltlohyyRy1/504yyNFAy.01//yyLyyAyyKM@y0-.13yyWy162y
@?^`hqlqebMfqyKyRpbXObfkplcqebF`bj^tJ^qof^o`eZ^kaabcb^qEviapjbbqT^o_b^ofkqebmfq^ob^yyRy1/166yyNFAy.01/1yyLyyAyyKM@y0-.41yyWy162y
@AbcbkafkdVlroQfqibyKyAbcb^q3Sf`qloflrp@e^iibkdbopfk?orkkefia^oSfii^dbyyNFAy.01/0yyLyyAyyKM@y0--./yyWy162y

QJ^fkq^fkfkdAfp`fmifkbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01//yyLyyAyyKM@y/6463yyWy162y
QQeb>_boo^qflkpJrpqAfbyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01/2yyLyyAyyKM@y/6463yyWy162y
Q?^`hqlqebMfqyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01/1yyLyyAyyKM@y/6463yyWy162y
QAbcbkafkdVlroQfqibyKyDobqq^qeb>o_fqbo%2-+6)32+3&yyNFAy.01/0yyLyyAyyKM@y/6463yyWy162y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
