local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Dalaran_Fishing_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Dalaran Fishing (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

OA^i^o^kyKyQo^sbiqlA^i^o^k)vlr`^kdbqqebob_vq^hfkdqebPqlojtfka?l^qql?lob^kQrkao^qebkcivqlA^i^o^k%2/+5)32+2&yyWy2-1yyTOy
K>``bmqA^fivNrbpqpyJAyyKy>``bmq^nrbpqcoljJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvqebkqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqyyWy2-1yyKM@y/541/y
>?illaFpQef`hboyLyyNFAy.0500yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
>QebDelpqcfpeyLyyNFAy.050-yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
>Afp^ojbayLyyNFAy.0503yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
>GbtbiLcQebPbtbopyLyyNFAy.050/yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
>A^kdbolrpivAbif`flrpyLyyNFAy.0501yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y

@?illaFpQef`hboyLyyKyHfii^_b^pqfk?lob^kQrkao^+Qefptfiidfsb^0jfkrqbab_rcc`^iiba>kfj^i?illa+Kltgrjmfkql^klmbk^ob^lct^qbo+>Mllilc?illatfii^mmb^o)tef`evlrcfpeifhb^kvlqebomlli+.*0?illaqllqeCobkwfbptfii_b`^rdeqcoljb^`e`^pq%2.+/)11+/&yyNFAy.0500yyAyyWy153yyTy
KXMe^kqljDelpqcfpeZyLyyKy@^q`eXMe^kqljDelpqcfpeZfkPeli^w^o?^pfk%lmbkt^qbo&+Qebnrbpqpq^qbpOfsbo$pEb^oq)_rq^kvt^qbofkPeli^w^o?^pfkpbbjpqltloh+%13+0)30+5&yyNFAy.050-yyAyyWy160yyTyyIy126-/y
@QebDelpqcfpeyLyyKyB^qqebcfpetfqefk.jfkrqblc`^q`efkdfqql`ljmibqbqebnrbpqyyNFAy.050-yyAyyWy160yyTyyRy126-/y
@Afp^ojbayLyyKy@^q`e^?il^qbaBbifkqebt^qbofkcolkqlcqebsflibqeliaql`liib`qqebXPbsboba>ojZ%3.)32+1&yyWy2-1yyNFAy.0503yyAyyTy
@GbtbiLcQebPbtbopyLyyKyA^i^o^k$pRkabo_biiv%pbtbop&+Cfpefkqebabbmm^oqcloqebX@loolabaGbtbiovZyyNFAy.050/yyAy
@A^kdbolrpivAbif`flrpyLyyKyTfkqbodo^pm+>mmolufj^qbive^iclc^ii`^q`ebptfiie^sb^Qboolocfpe^qq^`eba%46+3)10&yyNFAy.0501yyAyyTyyWy2-.y

Q?illaFpQef`hboyLyyNFAy.0500yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
QQebDelpqcfpeyLyyNFAy.050-yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
QAfp^ojbayLyyNFAy.0503yyKyLifp^oo^%03+50)04+..&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/54-3y
QGbtbiLcQebPbtbopyLyyNFAy.050/yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y
QA^kdbolrpivAbif`flrpyLyyNFAy.0501yyKyJ^o`f^@e^pb%2/+5)32+2&fkA^i^o^k`fqvyyWy2-1yyAyyKM@y/541/y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
