local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Dalaran_Cooking_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Dalaran Cooking (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

OA^i^o^kyKyQo^sbiqlA^i^o^k%1-+4)32+/&yyWy2-1y
K>``bmqA^fivNrbpqpyJAyyKy>``bmq^nrbpqcoljH^qebofkbIbb%1-+4)32+/&fkA^i^o^kqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqyyWy2-1yyKM@y/54-2yyJAy

>PbtboPqbtyLyyKyH^qebofkbIbb%1-+4)32+/&yyNFAy.0.-/yyWy2-1yyAyyKM@y/54-2y
>@ebbpbcloDiltbodliayLyyKyH^qebofkbIbb%1-+4)32+/&yyNFAy.0.-0yyWy2-1yyAyyKM@y/54-2y
>@lksbkqflk^qqebIbdboabj^fkyLyyKyH^qebofkbIbb%1-+4)32+/&yyNFAy.0.-.yyWy2-1yyAyyKM@y/54-2y
>FkcrpbaJrpeolljJb^qil^cyLyyKyH^qebofkbIbb%1-+4)32+/&yyNFAy.0.--yyWy2-1yyAyyKM@y/54-2y
>Jrpq^oaAldpyLyyKyH^qebofkbIbb%1-+4)32+/&yyNFAy.0.-4yyWy2-1yyAyyKM@y/54-2y

@PbtboPqbtyLyyKy@liib`q1uX@ovpq^iplkd@^oolqpZclrkarkaboA^i^o^k)^olrkaqebofsbo_^khafob`qiv_bkb^qeqebcil^qfkd`fqv%0-+1)05+0&^karpbqebXPqbt@llhmlqZtfqeqeb`^oolqp^ka1X@efiibaJb^qZyyRy10.14yyNFAy.0.-/yyWy2.-yyAyyL?Gy132/y
@@ebbpbcloDiltbodliayLyyKy@liib`q3uXE^icCriiDi^ppbplcTfkbZ%16)06&)%36+2)01+0&)%10)31&^kaX>dbaA^i^o^kIfj_rodboZ%20+2)0/+2&^olrkaA^i^o^kyyRy10.06yyNFAy.0.-0yyWy2-1yyAyyL?Gy5030)5.26y
KXCriiGrdlcTfkbZyLyyKyDbqqebXCriiGrdlcTfkbZfkA^i^o^k%20+1)0/+0&yyNFAy.0.-.+/yyWy2-1yyAyyL?Gy4yyQy
K1XKloqebokPqbtZyLyyKy@ob^qb1XKloqebokPqbtZ_v`llhfkd1X@efiibaJb^qZaolmcolj_b^pqfkKloqeobka)`ilpbpqmi^`bqlc^ojfpcoljIrohfkd?^pfifphfkWri$Ao^h)%10+5)3/+1&lomro`e^pbfqcolj>EyyNFAy.0.-.+.yyWy163yyAyyKM@y/5.12yyQyyTy
@FkcrpbaJrpeolljJb^qil^cyLyyKyCfkaqebXFkcrpbaJrpeolljZ^olrkaA^i^o^kPbtbop^karpbXJb^qil^cM^kZtfqe/uX@efiibaJb^qZyyRy10.-.yyNFAy.0.--yyWy2-1yyAyyL?Gy026y
@Jrpq^oaAldpyLyyKyCfkaqebXTfiaJrpq^oaZ^olrkaA^i^o^kdo^pp^ob^%02)21&)%03)1/&)%16+1)14&)%14).3&)%35)12+3&^ka`ob^qblo_rv1uXOefklAldpZyyRy10.1/yyNFAy.0.-4yyWy2-1yyAyyL?Gy501-y

QPbtboPqbtyLyyKy>g^vDobbk%3-+63)15+16&%3.+-/)2-+05&%02+6)24+2&yyNFAy.0.-/yyWy2-1yyAyyKM@y/620/y
Q@ebbpbcloDiltbodliayLyyKyO^kfaDiltbodlia%03+2)/5+2&yyNFAy.0.-0yyWy2-1yyAyyKM@y/54.5y
Q@lksbkqflk^qqebIbdboabj^fkyLyyKy>ofiib>wrobd^wb%15+2)05+.&yyNFAy.0.-.yyWy2-1yyAyyKM@y/6-16y
QFkcrpbaJrpeolljJb^qil^cyLyyKyLoqlk?bkkbq%2/+.)22+2&yyNFAy.0.--yyWy2-1yyAyyKM@y/62/4y
QJrpq^oaAldpyLyyKy>o`ej^dbMbkq^orp%35+2)1/+2&yyNFAy.0.-4yyWy2-1yyAyyKM@y/5.3-y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
