local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Darnassus_Cook_Fishing")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Darnassus Cooking & Fishing (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

K>``bmq@llhfkdA^fivNrbpqyKy>``bmq^nrbpqcolj>ibdlok%2-)03+3&fkA^ok^pprpqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqloqf`hfqkltqlphfmalfkd@llhfkdA^fivyyWy05.yyKM@y1/.-y

>Objbj_bofkdqeb>k`bpqlopyLyyKy>ibdlok%2-)03+3&yyNFAy/60.1yyWy05.yyAyyKM@y1/.-y
>?^`hql?^pf`pyLyyKy>ibdlok%2-)03+3&yyNFAy/60.3yyWy05.yyAyyKM@y1/.-y
>Of_pcloqebPbkqfkbipyLyyKy>ibdlok%2-)03+3&yyNFAy/60.5yyWy05.yyAyyKM@y1/.-y
>Pmf`b?ob^a>mibkqvyLyyKy>ibdlok%2-)03+3&yyNFAy/6024yyWy05.yyAyyKM@y1/.-y
>QebPb`obqqlMbocb`qHfj`efyLyyKy>ibdlok%2-)03+3&yyNFAy/60.0yyWy05.yyAyyKM@y1/.-y

@Pmf`b?ob^a>mibkqvyLyyKy@ob^qb2XPmf`ba?ob^aZ^iifqq^hbpfp.XCilroZ^ka.XJfiaPmf`bpZ_lqe`^k_bmro`e^pbacoljCvia^k%2-)03+3&yyNFAy/6024yyWy05.yyAyyKM@y1//0y
@?^`hql?^pf`pyLyyKyMlrkaqeb`lkqbkqplc3Of`b?^phbqpclrkafkqeb_rfiafkdplkqeb@o^cqpjbk$pQboo^`b^kaqebQo^abjbk$pQboo^`b%21+6)/1+1&%26+2)/4+.&%3/+6)0.+3&%31+3)05+/&yyNFAy/60.3yyWy05.yyAyyL?Gy.--64y
@Of_pcloqebPbkqfkbipyLyyKyRpbqebXRk`llhbaOf_pZkb^o^`^jmcfobql`llhqebj^kaqebkrpbqebjqlcbba2A^ok^pprpPbkqfkbip%2-)03+3&yyNFAy/60.5yyWy05.yyAyyRy366-1yyKM@y1/3/y
@QebPb`obqqlMbocb`qHfj`efyLyyKyCfka5X?rofbaHfj`efG^opZfkA^ok^pprp%13)04+0&%1/)30+0&yyNFAy/60.0yyWy05.yyAyyL?Gy3025y

Q?^`hql?^pf`pyLyyKy>ibdlok%2-)03+3&yyNFAy/60.3yyWy05.yyAyyKM@y1/.-y
QOf_pcloqebPbkqfkbipyLyyKy>ibdlok%2-)03+3&yyNFAy/60.5yyWy05.yyAyyKM@y1/.-y
QQebPb`obqqlMbocb`qHfj`efyLyyKy>ibdlok%2-)03+3&yyNFAy/60.0yyWy05.yyAyyKM@y1/.-y
QPmf`b?ob^a>mibkqvyLyyKy>ibdlok%2-)03+3&yyNFAy/6024yyWy05.yyAyyKM@y1/.-y

K>``bmqCfpefkdA^fivNrbpqyKy>``bmq^nrbpqcolj>pq^f^%16)3.&fkA^ok^pprpqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqloqf`hfqkltqlphfmalfkdCfpefkdA^fivyyWy05.yyKM@y1.23y

>>PifmmbovPk^`hyLyyKy>pq^f^%16)3.&yyNFAy/60/2yyWy05.yyAyyKM@y1.23y
>>kLiaC^slofqbyLyyKy>pq^f^%16)3.&yyNFAy/6026yyWy05.yyAyyKM@y1.23y
>E^mmv^p^@i^jAfddboyLyyKy>pq^f^%16)3.&yyNFAy/60/.yyWy05.yyAyyKM@y1.23y
>Pql`hfkdRmyLyyKy>pq^f^%16)3.&yyNFAy/60/0yyWy05.yyAyyKM@y1.23y
>QebPfpqbo$pMbka^kqyLyyKy>pq^f^%16)3.&yyNFAy/60/1yyWy05.yyAyyKM@y1.23y

@Objbj_bofkdqeb>k`bpqlopyLyyKy@liib`qqeb?ibppbaOf`b@^hbpcoljqebQbjmiblcqebJllk%10+/)45+1&yyNFAy/60.1yyWy05.yyAyyL?Gy2160y
QObjbj_bofkdqeb>k`bpqlopyKyPeofkblcqeb>k`bpqlop%36+/)06+6&yyNFAy/60.1yyWy05.yyAyyL?Gy/-15y

@>PifmmbovPk^`hyLyyKyD^qebo3X?^_vL`qlmrpZcoljqebpe^iiltt^qbokb^oOrq$qebo^kSfii^db)vlre^sbqlptfjaltk^kadbqfqrkabot^qbotfqelrqcfpefkd%23+/)60&yyNFAy/60/2yyWy1.yyAyyKM@y202//y
@>kLiaC^slofqbyLyyKy@^q`e5H^ialobfEboofkd_vcfpefkdfkOrq$qebo^kSfii^db%23+/)60&yyNFAy/6026yyWy1.yyAy
@E^mmv^p^@i^jAfddboyLyyKyD^qebo.-XQbiao^ppfi@i^jpZcoljqebpelobpkb^oOrq$qebo^kSfii^db%23+/)60&yyNFAy/60/.yyWy1.yyAyyL?Gy/3.y
@Pql`hfkdRmyLyyKy@^q`e2XI^hbTefqbcfpeZ_vcfpefkdfkA^ok^pprp%2-+4)3.+6&yyNFAy/60/0yyWy05.yyAy
@QebPfpqbo$pMbka^kqyLyyKy@^q`e^XDf^kq@^qcfpeZ_vcfpefkdfkA^ok^pprp^karpbfqqlcfkaX>nrfkkb$pJllkMbka^kqZ%2-+4)3.+6&yyNFAy/60/1yyWy05.yyAyyRy366.1y

Q>PifmmbovPk^`hyKy>pq^f^%16)3.&yyNFAy/60/2yyWy05.yyAyyKM@y1.23y
Q>kLiaC^slofqbyLyyKy>pq^f^%16)3.&yyNFAy/6026yyWy05.yyAyyKM@y1.23y
QE^mmv^p^@i^jAfddboyLyyKy>pq^f^%16)3.&yyNFAy/60/.yyWy05.yyAyyKM@y1.23y
QPql`hfkdRmyLyyKy>pq^f^%16)3.&yyNFAy/60/0yyWy05.yyAyyKM@y1.23y
QQebPfpqbo$pMbka^kqyLyyKy>pq^f^%16)3.&yyNFAy/60/1yyWy05.yyAyyKM@y1.23y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
