local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Darnassus_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Darnassus Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OA^ok^pprpyKyQo^sbiqlA^ok^pprp%24+5)4.+3&yyWy05.y
?Sfk^pf^9@ilqe>ojloJbo`e^kq;yKyX@fkabo`ilqeIbddfkdpZ1d05p)%24+5)4.+3&yyWy05.yyKM@y1.42y
?Qrof^k9QeoltkTb^mlkpJbo`e^kq;yKyX?ol^a?i^abaHkfcbZ0d)%26+3)34+3&yyWy05.yyKM@y1/02y
?I^kaof^9?ltJbo`e^kq;yKyXPvis^kPeloq_ltZ5d)XPqroavOb`rosbZ/d)XCfkbPeloq_ltZ0/p)%26+3)34+3&yyWy05.yyKM@y1.40y
?Dilo^kaffo9>ubJbo`e^kq;yKyXJbo`fibpp>ubZ0d)%3-+/)3/+3&yyWy05.yyKM@y1/0/y
?I^vk^H^okbo9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7E^oabkbaFolkPeloqptloaZ0-p)%23+3)2/+3&yyWy05.yyKM@y2/31.y
?Bivkk^9Q^filofkdPrmmifbp;yKyXM^qqbok7Lo^kdbJ^oqf^iPefoqZ0-p)XM^qqbok7Dob^qbo>abmq$pOl_bZ5p)XM^qqbok7?irbIfkbkOl_bZ0p)%3-+1)03+5&yyWy05.yyKM@y1.35y
?Jvqeofk$afo9Qo^abPrmmifbp;yKyAlk$q_rvXClojri^7Bk`e^kqPefbia*Dob^qboPq^jfk^Z^pvlr`^k$qobpbiifq+?rvXClojri^7Bk`e^kq?o^`bo*AladbZ25p)XClojri^7Bk`e^kq?o^`bo*AladbZ.5p)%25+/)02+-&yyWy05.yyKM@y1//6y
?Fiif^kk^Jllkp`of_b9Fkp`ofmqflkPrmmifbp;yKyXP`of_b$pP^q`ebiZ2-p)%23+5)0.+-&yyWy05.yyKM@y0-40.y
?S^b^k9Bk`e^kqfkdPrmmifbp;yKyXM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7JfkloTfw^oaLfiZ2p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)%23+3)0.+5&yyWy05.yyKM@y1//5y
?ErdlIbkqkbo9BkdfkbbofkdPrmmifbp;yKyS^oflrpifjfqbabkdfkbbofkdprmmifbp.3`*0-p)%2-+/)00+3&yyWy05.yyKM@y2/304y
?Cvia^k9@llhfkdPrmmifbp;yKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7PjlhbaP^dbcfpeZ2p)%16+3)03+3&yyWy05.yyKM@y1//0y
?Riqefo9>i`ebjvPrmmifbp;yKyXOb`fmb7Dob^qO^dbMlqflkZ/-p)XOb`fmb7Cobb>`qflkMlqflkZ.5p)%21+3)06+3&yyWy05.yyKM@y1//3y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
