local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Eastern_Kingdom_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Eastern Kingdom Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OJbkbqefiE^o_loyKyQo^sbiqlJbkbqefiE^o_lo%5+.)25+0&Tbqi^kapyyWy1-y
?Pqr^oqCibjfkd9CfpefkdPrmmifbp;yWy1-yyKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/+2p&)XOb`fmb7JfqeofiEb^aQolrqZ%//p&)XOb`fmb7O^fk_ltCfk>i_^`lobZ%1p&)XOb`fmb7Ol`hp`^ib@laZ%//p&%3+/6)24+11&yyKM@y0.45y
?AbtfkPefjjboa^tk9>i`ebjvPrmmifbp;yWy1-yyKyXEb^ifkdMlqflkZ%0p&%..+06)2.+6-&yyKM@y.120y
?Kb^i>iibk9BkdfkbbofkdPrmmifbp#Dbkbo^iDllap;yWy1-yyKyX?olkwbQr_bZ%5p&)XDvol`eolk^qljZ%0-p&%..+6)2/+4&yyKM@y.115y
?Gbkk^_fkhMltbopb^j9Q^filofkdPrmmifbp#Pmb`f^iqvDllap;yWy1-yyKyXM^qqbok7Dob^qbo>abmq$pOl_bZ%5p&)XM^qqbok7ObaTllibk?^dZ%2p&)S^oflrp@ilqe>ojlo%0/+5*04+2p&%.-+.)26+.&yyKM@y.121y
?P^jloCbpqfsrp9Pe^avAb^ibo;yWy1-yyKyXEb^ifkdMlqflkZ%0p&%.-+2-)3-+/.&Rmpq^fopfkAbbmt^qboQ^sbokyyKM@y.124y

OPrkaltkJ^opeyKyQo^sbiqlPrkaltkJ^ope%/2+3-)/2+5-&yyWy1-y
?Tbkk^Pfih_b^oa9Pmb`f^iDllapAb^ibo;yWy1-yyKyXM^qqbok7>wrobPfihDilsbpZ%.-p&)XM^qqbok7DobbkIb^qebo>ojloZ%/-p&)XM^qqbok7ObaTebimDilsbpZ%.3p&)S^oflrpDobbk>ojlo%01+/p*.+2d&%/2+3-)/2+5-&yyKM@y/346y
?Co^aaPtfcqdb^o9BkdfkbbofkdPrmmifbp;yWy1-yyKyXP`ebj^qf`7JfkloOb`lj_l_ri^qloZ%.-p2-`&%/3+5)/3+-&yyKM@y1.102y

OEfiip_o^aCllqefiipyKyQo^sbiqlEfiip_o^aCllqefiip%35+53)25+62&yyWy/1y
?HofpIbd^`b9CobbtebbifkdQo^abptlj^k;yWy/1yyKyS^oflrpIb^qeboDllap%02+/5p*.+1d&%35+53)25+62&yyKM@y0203y

OO^sbkeliaqJ^kloyWy/1yyKyQo^sbiqlO^sbkeliaqJ^klo%4.+10)12+14&y
?W^kPefspmolhbq9Pmb`f^ifqvBkdfkbbo;yWy/1yyKyXP`ebj^qf`7Dkljfpe@il^hfkdAbsf`bZ%/1p&)XDvol`eolk^qljZ%0-p&altkpq^fofkqeb_^pbjbkq%4.+10)12+14&yyKM@y3444y
?PjradbQerkabotlla9MlfplkPrmmifbp;yWy/1yyKyXOb`fmb7QefpqibQb^Z%/p&%4.+1)12+/&yyKM@y3446y

?Wfufi9Jbo`e^kqPrmobjb;yWy/1yyKyM^qolip_bqtbbkQ^oobkJfii^kaPlrqepelob)XM^qqbok7B^oqebkIb^qeboPelriabopZ%/-p&)XM^qqbok7ObaTllibk?^dZ%2p&)XP`ebj^qf`7Dl_ifkGrjmbo@^_ibpZ%/-p&)S^oflrpdobbkp%.-p*5-p/-`&%23+-)13+1&%2/+5)15&%2/+5)2/+1&%2/+3)23+/&%16+/)33+5&yyKM@y0204y
?Ol_boq>b_fp`ebo9Prmboflo>ojlopjfqe;yWy/1yyKyS^oflrpdobbk^ojlo%0-+10*42+/-p&%2.+/)24+-&yyKM@y0210yyLy

OOrfkplc>iqbo^`yKyQo^sbiqlOrfkplc>iqbo^`%11)/.+5&yyWy/1y
??ol$hfk9>i`ebjvPrmmifbp;yWy/1yyKyXOb`fmb7ColpqLfiZ%/2p&)XDob^qboEb^ifkdMlqflkZ%2p&)XJ^k^MlqflkZ%1+5p&%11)/.+5&yyKM@y/15-y

O@efiitfka@^jmyKyQo^sbiql@efiitfka@^jm)TbpqbokMi^drbi^kap%10+-)51+0&yyWy//y
?Iblk^oaMloqbo9Ib^qebotlohfkdPrmmifbp;yWy//yyKy?rv`lilobapefoqp)qll%10+-)51+0&XM^qqbok7PqlojpeolraM^kqpZ%.d3-p&)XM^qqbok7Tf`hbaIb^qeboD^rkqibqpZ%.d/-p&yyKM@y./61/y

O@^boA^ooltyKyQo^sbiql@^boA^oolt%35+.)44+2&yyWy//y
?J^dkrpColpqt^hbyKyXMi^kp7PqlojD^rkqibqpZ%1d&%35+.)44+2&yyWy//y

OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi)B^pqbokMi^drbi^kapyyWy/0y
?G^pbC^oi^kb9Qo^abPrmmifbp;yWy/0yyKyXAbpfdk7Ofkdlc?fqqboPe^altpZ%.d&%41+02)2-+6.&yyKM@y./61.y

O>bofbMb^hyWy/3yyKyQo^sbiql>bofbMb^h)QebEfkqboi^kap%.1+2)1/+4&y
?QorhTfia_b^oa9?^oqbkabo;yWy/3yyKyXOb`fmb7QbkaboTlicPqb^hZ%.d/-p&%.1+05)1/+00&yyKM@y145/y
?E^odd^k9?i^`hpjfqefkdPrmmifbp;yWy/3yyKyXMi^kp7JfqeofiP`^ib?o^`bopZ%3-p&%.0+11)12+--&yyKM@y5.3.y
?Kflj^9Ib^qebotlohfkdPrmmifbp;yWy/3yyKyXM^qqbok7Kfdeqp`^mbPelriabopZ%1-p&%.0+/6)10+04&yyKM@y5.3-y

?DfddbqWfm`lfi9Qo^abPrmmifbp;yWy/3yyKyXM^qqbok7Folkcb^qeboPelriabopZ%.d1-p&%01+2)05+2&yyKM@y./625y
?OrmmlWfm`lfi9BkdfkbbofkdPrmmifbp;yWy/3yyKyXP`ebj^qf`7JfqeofiJb`e^kf`^iAo^dlkifkdZ%1-p&)X?olkwbQr_bZ%5p&)XDvol`eolk^qljZ%0-p&%01+0)04+5&yyKM@y/355y

OPqlojcb^qeboLrqmlpqyKyQo^sbiqlPqlojcb^qeboLrqmlpq%33+3)11+/&yyWy/3yyLy
??o^kkfhFolk_biiv9>ojlopjfqe;yWy/3yyKyXEb^svKlq`eba?biqZ%.d61p0-`&%33+3)11+/&yyKM@y./-1-yyLy

OObcrdbMlfkqbyKyDrqeorjQerkabocfpq%1-)14&CivqlObcrdbMlfkqb)>o^qefEfdei^kapyyWy.3yyKM@y5-.5yyTOy
?>kaolaC^ao^k9Ib^qebotlohfkdPrmmifbp;yWy.3yyKyXM^qqbok7O^mqloEfab?biqZ%/2p&%06+.3)15+.4&yyKM@y/5.3y
?K^ogAbbmpif`b9?rq`ebo;yWy.3yyKyXOb`fmb7?^o_b`rba?rww^oaTfkdZ%.-p&%06+35)15+54&yyKM@y/5.1y
?Aolsk^oPqolkd_obt9>i`ebjvPrmmifbp;yWy.3yyKyXOb`fmb7ColpqMolqb`qflkMlqflkZ%/-p&)XDob^qboEb^ifkdMlqflkZ%2p&)XJ^k^MlqflkZ%1+5p&%1-+26)15+0.&yyKM@y/5./y
?E^jjlkH^otk9PrmbofloQo^abpj^k;yWy.3yyKyXAbpfdk7Or_v@oltklcObpqlo^qflkZ%3-p&)XM^qqbok7?^o_^of`IbddfkdpZ%3p2-`&)XOb`fmb7Ol^pqO^mqloZ%2-p&%1-+2)15+5&yyKM@y/5.-y
?G^kklpFolktfii9PrmbofloJ^`b`o^cqbo;yWy.3yyKyXMi^kp7PlifaFolkJ^riZ%0-p&%1-+5/)15+.0&yyKM@y.14.y

OQebip^j^oyKyQo^sbiqlQebip^j^o)Il`eJla^k%03+-)13+-&yyWy02y
?Ao^`Olrde`rq9Qo^abpj^k;yWy02yyKyXOb`fmb7Pjlhba?b^oJb^qZ%/+2p&%02+3)16+-&yyKM@y.132y
?O^kkCi^jbpmfkkbo9Q^filofkdPrmmifbp;yWy02yyKyXM^qqbok7Dob^qbo>abmq$pOl_bZ%5p&)XM^qqbok7ObaTllibk?^dZ%2p&%03+-)13+-&yyKM@y.141y
?Jloe^k@lmmboqlkdrb9Jbq^ipjfqe;yWy02yyKyXBk^jbiiba?ol^aptloaZ%/5p45`&)XCbo^i?i^abZ%/1p4`&%01+-)13+3&yyKM@y.34yyLy
?He^o^Abbmt^qbo9CfpefkdPrmmifbp;yWy02yyKyXOb`fmb7?ofiif^kqPj^iicfpeZ%1-`&)XOb`fmb7Il`eCobkwvAbifdeqZ%1p&)XOb`fmb7Ilkdg^tJraPk^mmboZ%1p&%06+2)06+/&yyKM@y.351y

?Kfiibk>kabj^o9J^`b`o^cqbo;yWy02yyKyXEb^svPmfhbaJ^`bZ%40p2.`&)XFolktllaJ^riZ%4-p1-`&%1/+5).-+-&yyKM@y///yyLy

OC^opqofaboIladbyKyQo^sbiqlC^opqofaboIladb%5/+15)30+06&yyWy02y
?U^ka^oDlla_b^oa9Dbkbo^iPrmmifbp;yWy02yyKyXOb`fmb7ElivMolqb`qflkMlqflkZ%5p&)XOb`fmb7O^dbMlqflkZ%.p&%5/+2)30+2&yyKM@y.352y
?H^qP^jmplk9Ib^qebo>ojloJbo`e^kq;yWy02yyKyX>dfib?llqpZ%/3p01`&)XPq^_ib?llqpZ%/-p&%5/+3)31+-&yyKM@y621yyLy

OI^hbpefobyKyQo^sbiqlI^hbpefob)ObaofadbJlrkq^fkp%/6+1)1/+5&yyWy03y
?H^o^>a^jp9Pefbia@o^cqbo;yWy03yyKyX?b^o?r`hiboZ%32p1.`&)XDr^oaf^k?r`hiboZ%50p/.`&)XLti$pAfphZ%34p13`&%/6+1)1/+5&yyKM@y460yyLy
?>jvA^sbkmloq9Qo^abptlj^k;yWy03yyKyXM^qqbok7?i^`hTebimQrkf`Z%.1p&)XM^qqbok7ObaTllibk?^dZ%2p&%/5+-2)10+35&yyKM@y444y
?SboklkE^ib9CfpefkdPrmmifbp;yWy03yyKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&%/3+46)11+-.&yyKM@y.345y
?Dilof^Cbjjbi9@llhfkdPrmmifbp;yWy03yyKyXOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&%/3+-3)1-+/6&yyKM@y0-52y
?Co^khifkE^j^o9Q^filofkdPrmmifbp;yWy03yyKyS^oflrpdobbk^ojlo%..p.3`*/4p03`&%/3+3)1.+5&yyKM@y0-6.yyLy

OPe^ibtfka@^kvlkyKyQo^sbiqlPe^ibtfka@^kvlk%45+3)30+3&yyWy03y
?@ivabO^kqe^i9Ib^qebotlohfkdPrmmifbp;yWy03yyKyXM^qqbok7?i^`hTebim@il^hZ%2p/-`&%45+3)30+3&yyKM@y/364y

OB^pqs^ibIlddfkd@^jmyKyQo^sbiqlB^pqs^ibIlddfkd@^jm%50+0.)33+35&yyWy0-y
?Ao^hbIfkadobk9Dbkbo^i#Qo^abPrmmifbp;yWy0-yyKyXM^qqbok7?irbIfkbkOl_bZ%0p&%50+0.)33+35&yyKM@y./2-y
?O^iif`Cfkk9?ltvbo;yWy0-yyKyXCfkbPeloq_ltZ%/5p34`&%50+/)33+-&yyKM@y..65yyLy
?Alkkf>kqe^kf^9@o^wv@^qI^av;yWy0-yyKyX@^q@^oofboZ%u1&%1-pb^`e&%11+/)20+1&yyKM@y3034y

ODliapefobyKyQo^sbiqlDliapefob%1.+6)34+.&yyWy0-y
?Qe^ovkk?lrabk9Qo^abPrmmifbp;yWy0-yyKyXM^qqbok7?irbIfkbkSbpqZ%/p&)XOb`fmb7?ofiif^kqPj^iicfpeZ%1-`&)XOb`fmb7Ilkdg^tJraPk^mmboZ%1p&%1.+6)34+.&yyKM@y33y

OPbkqfkbiEfiiyKyQo^sbiqlPbkqfkbiEfii)Tbpqc^ii%24+3-)20+63&yyWy06y
?Dfk^J^`Dobdlo9Qo^abPrmmifbp;yWy06yyKyXM^qqbok7?irbLsbo^iipZ%1p&)XM^qqbok7Jroil`P`^ib?biqZ%2+2p&)XM^qqbok7Jroil`P`^ib?ob^pqmi^qbZ%3p&)XM^qqbok7ObaIfkbk?^dZ%/p&%24+3-)20+63&yyKM@y510y
?Tfiif^jJ^`Dobdlo9?ltvbo;yWy06yyKyXCfkbIlkd_ltZ%15p3/`&%24+3)20+3&%23+/)14+3&yyKM@y.335yyLy

OTbpqc^iiIfdeqelrpbyKyQo^sbiqlTbpqc^iiIfdeqelrpb%03+/)6-+-&yyWy06y
?HofddlkQ^iplkb9Cfpeboj^k;yWy06yyKyXOb`fmb7@i^j@eltaboZ%5p&)XOb`fmb7O^fk_ltCfk>i_^`lobZ%1p&)XOb`fmb7PifqebophfkJ^`hbobiZ%1-`&)XOb`fmb7Pmf`ba@efif@o^_Z%.d/-p&%03+/)6-+-&yyKM@y10-2y

OArphtllayKyQo^sbiqlArphtlla%5.+6).6+6&yyWy01y
?Hwfuu9O^obDllap;yWy01yyKyXOb`fmb7ElivMolqb`qflkMlqflkZ%4p3-`&)XP`ebj^qf`7Dl_ifkGrjmbo@^_ibpZ%.6p&)XEb^ifkdMlqflkZ%0p&)XIbppboJ^k^MlqflkZ%.+/p&S^ofrpDobbkFqbjp%1-p*43p&%5.+6).6+6&yyKM@y0.01y

OA^ohpefobyKyQo^sbiqlA^ohpefob%42+5)12+2&yyWy01y
?A^kfbiibWfmpqfq`e9Q^filofkdPrmmifbp;yWy01yyKyXM^qqbok7?ofdeqVbiiltPefoqZ%5p&%42+5)12+2&yyKM@y/335y
?PebofWfmpqfq`e9Q^filofkdPrmmifbp;yWy01yyKyXM^qqbok7A^ohPfihPefoqZ%..p&)XM^qqbok7Dob^qbo>abmq$pOl_bZ%5p&%42+4)12+2&yyKM@y/336y
?>sbqqbCbiitlla9?ltvbo;yWy01yyKyXCfkbIlkd_ltZ%15p3/`&%40+/)11+5&yyKM@y//5y
?D^sfkDk^oiqobb9Tb^mlkpjfqe;yWy01yyKyX?ol^a?i^abaHkfcbZ%/d50p40`&)XJbo`fibpp>ubZ%0d.p62`&%40+3)16&yyKM@y//2yyLy
?JlodDk^oiqobb9>ojlobo;yWy01yyKyS^oflrpdobbk^ojlo%0-p10`*42p/-`&%40+5)15+3&yyKM@y//3yyLy

OQebE^o_lo^dbyKyQo^sbiqlQebE^o_lo^db)Pt^jmlcPlooltp%/6+4)00+3&yyWy05y
?J^p^qQ$^kao9PrmbofloIb^qebotlohbo;yWy05yyKyXM^qqbok7DobbkAo^dlkp`^ib?ob^pqmi^qbZ%.+/d&)X?ofiif^kqOba@il^hZ%.+45d&)XTbiiLfiba@il^hZ%/+/2d&%/6+44)00+2.&yyKM@y..541y

O?i^pqbaI^kapyKyQo^sbiql?i^pqbaI^kap%0/+6)4/+/&yyWy.6y
??bokfbEbfpqbk9Clla#Aofkh;yWy.6yyKy2uXKbqebod^oab?fqqboZ%/-p&qefpfpobnrfobaclo^nrbpqfklrqi^ka%26+1-).1+6-&yyKM@y0213y
?Kfk^Ifdeq_obt9>i`ebjvPrmmifbp;yWy.6yyKyXOb`fmb7BifufolcAbjlkpi^vfkdZ%.d&)XDob^qboJ^k^MlqflkZ%./p&)XPrmbofloEb^ifkdMlqflkZ%.-p&%3/+13).2+63&yyKM@y5.45y
?P^o^eIfdeq_obt9Bk`e^kqfkdPrmmifbp;yWy.6yyKyXIbppboJ^df`Bppbk`bZ%5p&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&%3/+1).3+3&yyKM@y110/.y
?Qlkv^Ifdeq_obt9Fkp`ofmqfkdPrmmifbp;yWy.6yyKyXP`of_b$pP^q`ebiZ%2-p&%30+-).3+/&yyKM@y110//y

OOb_bi@^jmyKyQo^sbiqlOb_bi@^jm)KloqebokPqo^kdibqelok%14+2).-+0&yyWy04y
?@lomlo^i?irqe9@^jmQo^abo;yWy04yyKyXOb`fmb7GrkdibPqbtZ%0-p&)XOb`fmb7Ol^pqO^mqloZ%2-p&%14+2).-+0&yyKM@y401y

OKbpfkdt^ov$pBumbafqflkyKyQo^sbiqlKbpfkdt^ov$pBumbafqflk%10+4-)/0+.3&yyWy04y
?G^nrfifk^Ao^jbq9Prmboflo>ub`o^cqbo;yWy04yyKyXMi^kp7J^ppfsbFolk>ubZ%11p&)%10+4-)/0+.3&yyKM@y/150y

?Dk^w?irkaboci^jb9BkdfkbbofkdPrmmifbp;yWy04yyKyXP`ebj^qf`7Jb`e^kf`^iAo^dlkifkdZ%.d&)XDvol`eolk^qljZ%0-p&)X?olkwbQr_bZ%5p&%34+2)3.&yyKM@y/354y
?Hk^w?irkaboci^jb9BkdfkbbofkdPrmmifbp;yWy04yyKyXP`ebj^qf`7Ab^aivP`lmbZ%0-p&)XDvol`eolk^qljZ%0-p&)X?olkwbQr_bZ%5p&%34+4)3.+.&yyKM@y5346y

O?llqv?^vyKyQo^sbiql?llqv?^v%1/+5)36+.&yyWy340y
?HbipbvV^k`b9@llh;yWy340yyKy@llhfkdOb`fmfbpu6%2p*/d&%1/+5)36+.&yyKM@y/331y
?K^ohh9Mfo^qbPrmmifbp;yWy340yyKyXM^qqbok7?i^`hPt^pe_r`hibo$pPefoqZ%.2p&)XM^oolq@^dbZu/%1-pb^`e&%1/+4)36+/&yyKM@y/330y
?E^obkH^kj^b9Prmboflo?ltvbo;yWy340yyKyXAbkpbPeloq_ltZ%/d25p.1`&%1/+5)36+1&yyKM@y/506yyLy
?J^whPkfmbpelq9BkdfkbbofkdPrmmifbp;yWy340yyKyXP`ebj^qf`7>``ro^qbP`lmbZ%/-p&)XDvol`eolk^qljZ%0-p&)X?olkwbQr_bZ%5p&%10+/0)4-+//&yyKM@y/352y
?C^odlkJloq^i^h9Prmboflo>ojlobo;yWy340yyKyXEb^svKlq`eba?biqZ%.d61p0-`&%11+-)4-+-&yyKM@y/512yyLy
?Hfww?irkqpqofhb9J^`b`o^cqbo;yWy340yyKyXEb^svPmfhbaJ^`bZ%40p2.`&)XFolktllaJ^riZ%4-p1-`&%10)4-&yyKM@y/51-yyLy
?W^obk^@oljtfka9PrmbofloTb^mlkpjfqe;yWy340yyKyXMi^kp7Jllkpqbbi?ol^aptloaZ%11p&%10)4-&yyKM@y/15/y
?Ofhnfw9Ib^qebotlohfkdPrmmifbp;yWy340yyKyXM^qqbok7Dbj*pqraabaIb^qebo?biqZ%0-p&)XM^qqbok7Pe^altphfkDilsbpZ%02p&%10+/)4.+4&yyKM@y/366y
?UfwhDllapqfq`e9Q^filofkdPrmmifbp;yWy340yyKyXM^qqbok7@ofjplkPfih@il^hZ%./p&)XM^qqbok7Bk`e^kqbo$p@ltiZ%.-p&%10+3)40&yyKM@y/34-y
??ifuobwDllapqfq`e9Ib^qebotlohfkdPrmmifbp;yWy340yyKyXM^qqbok7Jroil`P`^ib?o^`bopZ%/5p&)XM^qqbok7Qef`hJroil`>ojloZ%3p2-`&%1/+50)41+./&yyKM@y/513y
?@o^whPm^ohp9CfobtlohpJbo`e^kq;yWy340yyKyXP`ebj^qf`7DobbkCfobtlohZ%.5p&%10)4/+5&yyKM@y/505y
?Jop+D^kq9@llhfkdQo^fkbo#Prmmifbp;yWy340yyKyXOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&)XOb`fmb7Rkabojfkb@i^j@eltaboZ%0-p&%1/+3)4/+5&yyKM@y21/0/y
?Divu?obtofdeq9>i`ebjvPrmmifbp;yWy340yyKyXOb`fmb7ColpqMolqb`qflkMlqflkZ%/-p&)XOb`fmb7K^qrobMolqb`qflkMlqflkZ%/-p&)XDob^qboEb^ifkdMlqflkZ%2p&)XJ^k^MlqflkZ%1+5p&%1/+34)42+-3&yyKM@y/515y
?LiaJ^kEbjfkd9CfpefkdPrmmifbp;yWy340yyKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&%1.+2)40+2&yyKM@y/3/3y
?Grq^h9?i^abQo^abo;yWy340yyKyXA^ofkdAfohZ%0d/-p0-`&)XMi^kp7E^oabkbaFolkPeloqptloaZ%0-p&%1.+3)41+-&yyKM@y/510y
?@lt^oaiv@olp_v9Q^filofkdPrmmifbp;yWy340yyKyXM^qqbok7>ajfo^i$pE^qZ%4-p&%1-+6)5/+2&yyKM@y/34/y

KDrfab@ljmibqb
]]
end)	end
	
	function Guide:Unload()
	end
end
