local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Exodar_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Exodar Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OQebBula^oyKyQo^sbiqlQebBula^o%31+3)35+1&yyWy14.y
?Kbff9Q^filofkdPrmmifbp;yWy14.yyKyAlk$q_rvIbsbi52M^qqbokpXM^qqbok7Kbqebotb^sbQrkf`Z1d)XM^qqbok7?liqlcPlri`ilqeZ1d)XM^qqbok7Kbqebotb^sbOl_bZ1d)XM^qqbok7?liqlcFj_rbaKbqebotb^sbZ1d%31+3)35+1&yyKM@y.3434y
?E^cbobq9Ib^qebotlohfkdPrmmifbp;yWy14.yyKyAlk$q_rvIbsbi52?LMM^qqbokp)XM^qqbok7@ljcloq^_ibFkplibpZ.d%33+1)41&yyKM@y.3415y
?>oo^p9?i^`hpjfqefkdPrmmifbp;yWy14.yyKyAlk$q_rvIbsbi52?LMMi^kp)XMi^kp7>a^j^kqfqbO^mfboZ1d)XMi^kp7>a^j^kqfqbA^ddboZ1d)XMi^kp7>a^j^kqfqb@ib^sboZ1d)XMi^kp7>a^j^kqfqbJ^riZ1d%3.)56&yyKM@y.34.0y
?Cbbo^9BkdfkbbofkdPrmmifbp;yWy14.yyKyXP`ebj^qf`7CbiFolkQlli_luZ1d)XP`ebj^qf`7TefqbPjlhbCi^obZ3d)XP`ebj^qf`7>a^j^kqfqbOfcibZ5d)S^oflrpifjfqbaprmmivbkdfkbbofkdj^qp%20)6-&yyKM@y.3324y
?>iq^^9>i`ebjvPrmmifbp;yWy14.yyKyXOb`fmb7Qo^kpjrqbMofj^iJfdeqZ5d)XOb`fmb7Bifufolc@^jlrci^dbZ0d)S^oflrpifjfqbaprmmivebo_p%/4+5)3/+5&yyKM@y.34-2y
?Pbpple9Fkp`ofmqflkPrmmifbp;yWy14.yyKyXP`of_b$pP^q`ebiZ2-p%06+5)06+3&yyKM@y0-40/y
?Bdljfp9Bk`e^kqfkdPrmmifbp;yWy14.yyKyXClojri^7PrmbofloTfw^oaLfiZ4d)XClojri^7I^odbMofpj^qf`Pe^oaZ3d)XClojri^7PrmbofloJ^k^LfiZ2d)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)S^oflrpifjfqbaprmmivbk`e^kqfkdj^qp%1-+1)06+/&yyKM@y.34//y
?>ooba9Gbtbi`o^cqfkdPrmmifbp;yWy14.yyKyXGbtbibo$pPbqqfkdZ.d2-p`^k_bpliaclo2*.-dmolcfq_rv^cbt^kaifpqqebj+XAbpfdk7Lm^iKb`hi^`blcFjm^`qZ42p)XAbpfdk7QebG^abBvbZ/2p)XAbpfdk7Eb^svDliabkKb`hi^`blc?^qqibZ.2p)XAbpfdk7>jribqlcqebJllkZ.5p%12)/2&yyKM@y.42./y
?Meb^9@llhfkdPrmmifbp;yWy14.yyKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7PjlhbaP^dbcfpeZ2p%21+3)/3+3&yyKM@y.34.5y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
