local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Ironforge_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Ironforge Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

O@fqvlcFolkclodbyKyQo^sbiql@fqvlcFolkclodb%4/+3)33+1&yyWy01.y
?PhlijfkDliacrov9?ltJbo`e^kq;yWy01.yyKyXJ^ppfsbIlkd_ltZ3d46p)XPqroavOb`rosbZ.d61p)XCfkbPeloq_ltZ0/p)%4/+3)33+1&yyKM@y2.//y
?Pllifb?boovcfww9>i`ebjvPrmmifbp;yWy01.yyKyXOb`fmb7BifufolcPrmbofloAbcbkpbZ.d0-p)XOb`fmb7Cobb>`qflkMlqflkZ.5p)%34+/)20+1&yyKM@y2.45y
?Db^o`rqqbo@ldpmfkkbo9BkdfkbbofkdPrmmifbp;yWy01.yyKyAlk$q_rvXP`ebj^qf`7Pqb^jQlkh@lkqoliiboZ^pvlr`^k$qobpbiifq+?rvXP`ebj^qf`7?irbCfobtlohZ.5p)XP`ebj^qf`7DkljfpeRkfsbop^iObjlqbZ./p^kas^oflrpifjfqbaprmmivbkdfkbbofkdm^oqp.3`*0-p)%35+/)11+-&yyKM@y2.42y
?BjoriOfhkrpprk9@llhfkdPrmmifbp;yWy01.yyKyXOb`fmb7PjlhbaP^dbcfpeZ2p)XOb`fmb7P^dbcfpeAbifdeqZ2-p)%3-)04&yyKM@y2.3-y
?Qe^odbkEb^svnrfii9Fkp`ofmqflkPrmmifbp;yWy01.yyKyXP`of_b$pP^q`ebiZ2-p)%3-+3)11+3&yyKM@y0-400y
?QfiifQefpqibcrww9Bk`e^kqfkdPrmmifbp;yWy01.yyKyXM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7Bk`e^kq/ETb^mlk*IbppboFkqbiib`qZ2p)XClojri^7JfkloTfw^oaLfiZ2p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)%3.+3)11+5&yyKM@y2.25y
??ro_fhDb^opm^kkbo9Qo^abPrmmifbp;yWy01.yyKyXAbpfdk7QebG^abBvbZ/2p)XAbpfdk7Lm^iKb`hi^`blcFjm^`qZ42p)%13+3)/5+3&yyKM@y2.30y
?LrqcfqqboBof`9Pmb`f^ifqvQ^filofkdPrmmifbp;yWy01.yyKyXM^qqbok7QrubalG^`hbqZ2-p)XM^qqbok7QrubalM^kqpZ12p)XM^qqbok7QrubalPefoqZ12p)XM^qqbok7MfkhJ^dbtb^sbPefoqZ1-p)XM^qqbok7I^sbkaboJ^dbtb^sbPefoqZ1-p)%11+/)/6+3&yyKM@y535.y
??lj_rpCfkbpmfkaib9Ib^qebotlohfkdPrmmifbp;yWy01.yyKyXM^qqbok7Eb^svIb^qebo?^iiZ/-p)%1-+/)00+1&yyKM@y2./5y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
