local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Kalimdor_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Kalimdor Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OO^q`ebqyKyQo^sbiqlO^q`ebq%3.+6)04+3&yyWy..y
?D^dpmol`hbq9BkdfkbbofkdPrmmifbp;yWy..yyKyXP`ebj^qf`7JfkloOb`lj_l_ri^qloZ%.2p&)XP`ebj^qf`7DobbkCfobtlohZ%.5p&)s^oflrpprmmifbp%.3`*0-p&%35+1)36+/&yyKM@y0162y
?Do^wifu9>ojlobo#Pefbia`o^cqbo;yWy..yyKyS^oflrpdobbk^ojlo%0-+10*50+/.p&%34+2)4/+6&yyKM@y0160yyLy
?Sbupmfkaib9@ilqe#Ib^qebo>ojloJbo`e^kq;yWy..yyKyS^oflrpdobbk^ojlo%02+.2*02+1-p&%34+1)4/+5&yyKM@y016/yyLy
?Ifww^ofh9Tb^mlkAb^ibo;yWy..yyKyS^oflrpdobbk^ojlo%/1+4-*40+2.&%33+5)4/+3&yyKM@y0325yyLy
?Hfiuu9Cfpeboj^k;yWy..yyKyXOb`fmb7?ofpqibTefphbo@^qcfpeZ%./p&)XOb`fmb7O^fk_ltCfk>i_^`lobZ%1p&)X>nr^avk^jf`Cfpe>qqo^`qloZ%/+2p&%35+3)4/+2&yyKM@y0164y
?O^kfh9Qo^abPrmmifbp;yWy..yyKyXAbpfdk7Tf`hbaJllkpqlkbOfkdZ%.2p&)XM^qqbok7?irbIfkbkOl_bZ%0p&)XM^qqbok7Dob^qbo>abmq$pOl_bZ%5p&)XOb`fmb7O^dbMlqflkZ%.p&%34+.)40+2&yyKM@y0166y

O>pqo^k^^oyKyQo^sbiql>pqo^k^^o%02+.)2/+.&yyWy10y
?A^iof^9Qo^abDllap;yWy10yyKyXClojri^7Bk`e^kq?o^`bo*IbppboPqobkdqeZ%/2p&)XClojri^7Bk`e^kq@il^h*Jfklo>dfifqvZ%5p&)XAbpfdk7Tf`hbaJllkpqlkbOfkdZ%.2p&%02+.)2/+.&yyKM@y0621y
?I^oa^k9Ib^qebotlohfkdPrmmifbp;yWy10yyKyXM^qqbok7?^o_^of`IbddfkdpZ%3p2-`&%01+5)16+5&yyKM@y0625y

OQebPeofkblc>bppfk^yKyQo^sbiqlQebPeofkblc>bppfk^%.5+/)3-+-&yyWy10y
?E^oiltkA^ohtb^sb9Ib^qebotlohfkdPrmmifbp;yWy10yyKyXM^qqbok7Ebo_^ifpq$pDilsbpZ%.5p&%.5+/)3-+-&yyKM@y013-.y

OBsboillhyKyQo^sbiqlBsboillh)Tfkqbopmofkd%3-+5)04+5&yyWy/5.y
?BsfbTefoi_obt9>i`ebjvPrmmifbp;yWy/5.yyKyXPrmbofloEb^ifkdMlqflkZ%.-p&)XDob^qboJ^k^MlqflkZ%./p&%26+/)2-&yyKM@y...55y
?Efjjfh9Clla#Aofkh;yWy/5.yyKyXOb`fmb7JlkpqboLjbibqZ%.d/-p&%26+5)2.+2&yyKM@y...54y
?Nf^9Qo^abPrmmifbp;yWy/5.yyKyXAbpfdk7Kb`hi^`blcqebAf^jlkaQltboZ%.d02p&)XClojri^7Bk`e^kq@ebpq*J^gloEb^iqeZ%.d3-p&)XM^qqbok7Colpqp^_bo?llqpZ%.d3-p&)XM^qqbok7Jllk`ilqeZ%/d&)XM^qqbok7Orkb`ilqe?^dZ%.d/-p&%26+4)16+0&yyKM@y...56y
?UfwwboCfww_liq9BkdfkbbofkdPrmmifbp;yWy/5.yyKyXP`ebj^qf`7Abif`^qb>o`^kfqb@lksboqboZ%/d&)XP`ebj^qf`7CrpbaTfofkdZ%.p3-`&)XP`ebj^qf`7DvolcobbwbF`bObcib`qloZ%.d/-p&)XP`ebj^qf`7J^pqbotlohQ^odbqArjjvZ%.d3-p&)XP`ebj^qf`7MltbocriPb^clofrj@e^odbZ%.d3-p&)s^oflrpprmmifbp%.3`*0-p&%26+/)2-+.&yyKM@y...52y

OJllkdi^abyKyQo^sbiqlJllkdi^ab%23+3)/6+5&yyWy/1.y
?A^ok^ii9Q^filofkdPrmmifbp;yWy/1.yyKyXM^qqbok7Orkb`ilqe@il^hZ%.d/-p&)XM^qqbok7Orkb`ilqeOl_bZ%.d/-p&%2.+11)00+/1&yyKM@y461-y
?K^of^kk^9?ltvbo;yWy/1.yyKyXPvis^kPeloq_ltZ%4d55p/6`&%20+/)1/+3&yyKM@y./-/6y
?Ilobi^bTfkqboplkd9Qo^abPrmmifbp;yWy/1.yyKyXClojri^7Bk`e^kq@il^h*PrmbofloAbcbkpbZ%/d&)XM^qqbok7Cbi`ilqeM^kqpZ%.d3-p&%15+/.)1-+.2&yyKM@y./-//y

OQ^ilk_o^k`eDi^abyKyQo^sbiqlQ^ilk_o^k`eDi^ab)Cbitlla%3.+0)/3+2&yyWy.5/y
?J^ivdbk9Dbkbo^iDllap;yWy.5/yyKyXOb`fmb7JlkpqboLjbibqZ%.d/-p&%3.+0)/3+2&yyKM@y/5-0y

OTefpmbotfkaDolsbyKyQo^sbiqlTefpmbotfkaDolsb%10+/)/5+1&yyWy.5/y
?Abp^^k9@llhfkdPrmmifbp;yWy.5/yyKyXOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&%10+5)/6+5&yyKM@y1525-y
?Kfirrq9Fkp`ofmqflkPrmmifbp;yWy.5/yyKyXP`of_b$pP^q`ebiZ%2-p&%11+-)/6+5&yyKM@y1525.y

OCb^qebojllkPqolkdeliayKyQo^sbiqlCb^qebojllk)Cbo^i^p%13+4)10+.&yyWy./.y
?Ild^kk^p9>i`ebjvPrmmifbp;yWy./.yyKyXOb`fmb7DelpqAvbZ%6-p&)XOb`fmb7K^qrobMolqb`qflkMlqflkZ%/-p&)Dob^qboJ^k^Mlqflk%./p&)PrmbofloEb^ifkdMlqflk%.-p&%13+4)10+.&yyKM@y5.24y
?Mo^qqJ`Dor__bk9Ib^qebotlohfkdPrmmifbp;yWy./.yyKyXM^qqbok7DobbkTebim?o^`bopZ%/5p&)XM^qqbok7IfsfkdPelriabopZ%.d1-p&)XM^qqbok7QroqibP`^ibDilsbpZ%02p&%12+1)1.+0&yyKM@y1-//3y
?Sfsf^kk^9Qo^abPrmmifbp;yWy./.yyKyXOb`fmb7?^hbaP^ijlkZ%/d&)XOb`fmb7ElqTlicOf_pZ%2-p&)XOb`fmb7Il_pqboPqbtZ%/d&)XOb`fmb7JfdeqcfpePqb^hZ%/d&%13+0)1.+4&yyKM@y4614y

OQltbolcBpqri^kyKyQo^sbiqlQltbolcBpqri^k%23+5)21+1&yyWy./.y
?>mmobkqf`blcBpqri^k9Bk`e^kqfkdPrmmifbp;yWy./.yyKyXIbppboJ^df`Bppbk`bZ%3p1-`&)XClojri^7IbppboTfw^oaLfiZ%0/p&)XClojri^7JfkloJ^k^LfiZ%/1p&)XClojri^7JfkloTfw^oaLfiZ%1p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%15p&%23+5)21+1&yyKM@y1105.y

O@bk^oflkEliayKyQo^sbiql@bk^oflkElia)Pfifqerp%22+3-)04+/.&yyWy/3.y
?H^kf^9Bk`e^kqfkdPrmmifbp;yWy/3.yyKyXClojri^7IbppboJ^k^LfiZ%.d&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XClojri^7Tfw^oaLfiZ%/d&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&)XM^qqbok7Bk`e^kqbaOrkb`ilqe?^dZ%/d&)XIbppboJ^df`Bppbk`bZ%5p&)XPqo^kdbArpqZ%5p&%22+3-)04+/.&yyKM@y.21.6y
?Jfpeq^9Qo^abPrmmifbp;yWy/3.yyKyXAbpfdk7Bjbo^ia@oltklcAbpqor`qflkZ%.d&%20+45)01+00&yyKM@y.2.46y

OS^ilo$pObpqyKyQo^sbiqlS^ilo$pObpq%5.+06).5+03&yyWy/3.y
?W^kklhEfabmfbo`bo9Ib^qebotlohfkdPrmmifbp;yWy/3.yyKyXM^qqbok7Eb^svP`lomfa?o^`bopZ%.d/-p&)XM^qqbok7Eb^svP`lomfaEbijZ%/d2-p&%5.+06).5+03&yyKM@y./623y

OJ^ope^i$pPq^kayKyQo^sbiqlJ^ope^i$pObcrdb)Rk$Dlol@o^qbo%21+41)3/+14&yyWy/-.y
?Kbod^i9Dbkbo^iDllap;yWy/-.yyKyXM^qqbok7Absfip^roD^rkqibqpZ%/d/-p&%21+41)3/+14&yyKM@y./626y

OD^adbqw^kyKyQo^sbiqlD^adbqw^k)Q^k^ofp%2/+2)/4+6&yyWy.3.y
?FkkhbbmboCfwwdofj_ib9Fkkhbbmbo;yWy.3.yyKyXOb`fmb7QbkaboTlicPqb^hZ%.d/-p&%2/+25)/4+-.&yyKM@y4400y
?AfodbNrfh`ib^sb9?rq`ebo;yWy.3.yyKyXOb`fmb7QbkaboTlicPqb^hZ%.d/-p&%2/+23)/6+-2&yyKM@y1-256y
?HofkhibDllapqbbi9?i^`hpjfqefkdPrmmifbp;yWy.3.yyKyXMi^kp7DliabkP`^ib@lfcZ%11p&%2.+.2)0-+06&yyKM@y21..y
?Sfwwhif`h9Q^filofkdPrmmifbp;yWy.3.yyKyXM^qqbok7@ofjplkPfihOl_bZ%2-p&)XM^qqbok7PlriMlr`eZ%.d/-p&%2-+40)/5+4/&yyKM@y3235y
?E^rdeqvJlafpqb9C^peflkAbpfdkbo;yWy.3.yyKyXM^qqbok7E^ifp`^kG^`hbqZ%14p2-`&XM^qqbok7E^ifp`^kM^kq^illkpZ%14p2-`&XM^qqbok7AobppPelbpZ%14p2-`&%2-+35)/5+30&yyKM@y1-24/y
??ifwofh?r`hpelq9Drkpjfqe;yWy.3.yyKyXP`ebj^qf`7BW*QeolAvk^jfqbFFZ%2-p&%2-+4-)/5+2-&yyKM@y5.0.y
?>i`ebjfpqMbpqibwrdd9>i`ebjvPrmmifbp;yWy.3.yyKyXOb`fmb7K^qrobMolqb`qflkMlqflkZ%/-p&)XOb`fmb7Mefilplmebo$pPqlkbZ%5-p&)XOb`fmb7Qo^kpjrqb>o`^kfqbZ%2d&)XOb`fmb7Qo^kpjrqbFolkqlDliaZ%5-p&)XOb`fmb7Qo^kpjrqbJfqeofiqlQorbpfisboZ%5-p&%2-+52)/4+64&yyKM@y2261y

OQebo^jlobFpibyKyQo^sbiqlQebo^jlobFpib)Arpqt^iiltJ^ope%34+06)14+54&yyWy.1.y
?MfqboSbo^k`b9Tb^mlkpjfqe#>ojlobo;yWy.1.yyKyS^oflrpDobbktb^mlkp^ka>ojlo%45p26`*/+1d&%34+06)14+54&yyKM@y156-yyLy
?GbkpbkC^oo^k9ErkqboQo^fkbo#?ltvbo;yWy.1.yyKyXAbkpbPeloq_ltZ%/d25p.1`&%34+5)16+5&yyKM@y156/yyLy
?Ifpp^ePmbiitf`h9Bk`e^kqfkdQo^fkbo#Prmmifbp;yWy.1.yyKyXClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&%33+-)16+3&yyKM@y201.-y
?Ebibkf^Liabk9Qo^abPrmmifbp;yWy.1.yyKyXM^qqbok7Jroil`P`^ib?o^`bopZ%/5p&)XAbpfdk7?i^`hMb^oiM^kqeboZ%2-p&)XAbpfdk7Qorbpfisbo@o^_Z%3-p&)XOb`fmb7Ao^dlk_ob^qe@efifZ%4-p&)XOb`fmb7JvpqbovPqbtZ%0-p&)XOb`fmb7Ol^pqO^mqloZ%2-p&%33+1)2.+2&yyKM@y1564y
?Rj^?^oqrij9Ebo_^ifpj#>i`ebjvPrmmifbp;yWy.1.yyKyXEbo_Mlr`eZ%.-p&)XDob^qboEb^ifkdMlqflkZ%2p&)XJ^k^MlqflkZ%1p5-`&%31+-4)14+34&yyKM@y1566y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
