local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Outland_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Outland Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OEbiicfobMbkfkpri^yKyQo^sbiqlEbiicfobMbkfkpri^%/1+2)05+5&yyWy132y
?Slabpffk9Ob^dbkqp;yKyXClojri^7Orkba>a^j^kqfqbOlaZ%.-d&%/1+2)05+5&yyWy132yyKM@y.6--1y
?Q^i^^o^9Tb^mlkJbo`e^kq;yKyXJ^d$e^ofCfdeqfkd@i^tZ%/2d16p5-`&)XT^omelokPmb^oZ%0/d33p35`&%/0+/)1-+1&yyWy132yyKM@y.6--.yyLy
?@^obdfsboLmebo^Tfkacrov9Fkkhbbmbo;yKy'@eb`hdlfkdo^qbplk>E_bclob_rvfkd_^dp'XAo^bkf`Ib^qeboM^`hZ%./d&)s^oflrplqebomolcbppflk_^dp%.-*.1d&)XDob^qboJ^k^MlqflkZ%./p&%/0+1)03+2&yyWy132yyKM@y.56-3y
?Gbwb_bi?f`^k9Fkp`ofmqflkPrmmifbp;yKyXQb`ekfnrb7DivmelcJ^k^PefbiaZ%0d&)XP`of_b$pP^q`ebiZ%2-p&%20+6)32+2&yyWy132yyKM@y0-401y
?PfaIfj_^oaf9Fkkhbbmbo;yKyXOb`fmb7O^s^dboAldZ%/d&%21+0)30+2&yyWy132yyKM@y.35/3y

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%03+5)22+.&yyWy140y
?J^ofPqlkbe^ka9>ojlopjfqe;yKyXMi^kp7BqbokfrjOlaZ%./d&)XMi^kp7IbppboT^oalcPefbiafkdZ%3d&%03+5)22+.&yyWy140yyKM@y.6040y
?A^ddibFolkpe^mbo9Drkp#>jjrkfqflk;yKyXP`ebj^qf`7>a^j^kqfqbP`lmbZ%3d&%03+5)21+1&yyWy140yyKM@y.602.y
?>oolka9Q^filofkdPrmmifbp;yKyQebP`ovbopc^`qflklkiv)XM^qqbok7Fj_rbaKbqebotb^sbOl_bZ%3d&)XM^qqbok7Fj_rbaKbqebotb^sbQrkf`Z%3d&%22+6)25+/&yyWy140yyKM@y.62/.yyOBMy601)2y

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%24+4)20+2&yyWy145y
?C^_f^kI^kwlkbiif9Dbkbo^iDllap#?^dp;yKy'@eb`hdlfkdo^qbplk>E_bclob_rvfkd_^dp'XAo^bkf`Ib^qeboM^`hZ%./d&)s^oflrplqebomolcbppflk_^dp%.-*.1d&%24+4)20+2&yyWy145yyKM@y.6-20y
?Fkkhbbmbo?fof_f9Fkkhbbmbo;yKyXOb`fmb7DliabkCfpePqf`hpZ%0d&)XOb`fmb7Pmf`v@o^ta^aZ%0d&%23+4)20+0&yyWy145yyKM@y.6/63y
?IbbifIlkde^ddib9Qo^abDllap;yKyXOb`fmb7J^gloAob^jibppPibbmMlqflkZ%2d&)XOb`fmb7Pkb^hfkdMlqflkZ%0d&%24+4)20+2&yyWy145yyKM@y.6-1/y
?PrmmivLccf`boJfiip9O^qflkp;yKyXOb`fmb7?i^`hbkba?^pfifphZ%0d&)XOb`fmb7T^om?rodboZ%0d&%22+5)20+.&yyWy145yyKM@y.6-05y

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%31+-)4.+5&yyWy15.y
?>^olkEliij^k9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7>a^j^kqfqb@ib^sboZ%1d&)XMi^kp7>a^j^kqfqbA^ddboZ%1d&)XMi^kp7>a^j^kqfqbJ^riZ%1d&)XMi^kp7>a^j^kqfqbO^mfboZ%1d&)XMi^kp7>a^j^kqfqbOlaZ%1d&%31+-)4.+5&yyWy15.yyKM@y.633/y
?>kaoflkA^ohpmfkkbo9Pe^altb^sbQ^filofkdPmb`f^ifpq;yKyXM^qqbok7Pe^alt`ilqeZ%1d&%33+3)35+2&yyWy15.yyKM@y///./y
?Bffk9Pmb`f^iqvQ^filofkdPrmmifbp;yKyXM^qqbok7?liqlcFj_rbaKbqebotb^sbZ%1d&)XM^qqbok7Fj_rbaKbqebotb^sb?^dZ%1d&)XM^qqbok7Kbqebotb^sbOl_bZ%1d&)XM^qqbok7Kbqebotb^sbQrkf`Z%1d&%33+-)36+-&yyWy15.yyKM@y.6/.0y
?DfadbPmbiitb^sbo9PmbiicfobQ^filofkdPmb`f^ifpq;yKyXM^qqbok7Pmbii`ilqeZ%1d&%33+1)35+-&yyWy15.yyKM@y///.0y
?J^a^jbOr_v9Bk`e^kqfkdPrmmifbp;yKyXClojri^7Bk`e^kqPefbia*J^gloPq^jfk^Z%1d&)XClojri^7I^odbMofpj^qf`Pe^oaZ%3d&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XClojri^7OrkbaBqbokfrjOlaZ%./d&)XClojri^7PrmbofloJ^k^LfiZ%2d&)XClojri^7PrmbofloTfw^oaLfiZ%4d&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&%30+2)4-+3&yyWy15.yyKM@y.6330y
?K^pj^o^Jllkplkd9Jllk`ilqeQ^filofkdPmb`f^ifpq;yKyXM^qqbok7Mofj^iJllk`ilqeZ%1d&%33+2)35+4&yyWy15.yyKM@y///-5y
?SfddwPefkbpm^ohba9BkdfkbbofkdPrmmifbp;yKyXP`ebj^qf`7>a^j^kqfqbOfcibZ%5d&)XP`ebj^qf`7CrpbaTfofkdZ%.+3d&%31+0)36+1&yyWy15.yyKM@y.633.y
?Phob^e9>i`ebjvPrmmifbp;yKyXOb`fmb7Qo^kpjrqbMofj^iJfdeqZ%5d&%13+2)/-+2&yyWy15.yyKM@y.6-41y

OK^do^kayKyQo^sbiqlK^do^ka%23+-)40+-&yyWy144y
?Rofhr9@llhfkdPrmmifbp;yKyXOb`fmb7DofiibaJracfpeZ%0d&)XOb`fmb7Ml^`eba?irbcfpeZ%0d&)XOb`fmb7Ol^pqba@ibcqellcZ%0d&)XOb`fmb7Q^i_rhPqb^hZ%0d&%23+/)40+0&yyWy144yyKM@y/--63y

OW^kd^oj^opeyKyQo^sbiqlW^kd^oj^ope%34+5)15+-&yyWy134y
?GrklArco^fk9J^pqboCfpefkdQo^fkbo;yKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/+2p&)XOb`fmb7?i^`hbkbaPmlobcfpeZ%/d&%45+.)33+-&yyWy134yyKM@y.56..y
?Illiork^9>ojlobo;yKyXMi^kp7>a^j^kqfqb?ob^pqmi^qbZ%3d&)XMi^kp7>a^j^kqfqbMi^qb?o^`bopZ%3d&)XMi^kp7>a^j^kqfqbMi^qbDilsbpZ%3d&%35+2)2-+.&yyWy134yyKM@y.6361y
?E^^iork9>i`ebjvPrmmifbp;yKyXOb`fmb7BifufolcJ^gloAbcbkpbZ%2d&)XOb`fmb7BifufolcJ^gloColpqMltboZ%1d&)XOb`fmb7PrmboJ^k^MlqflkZ%2d&%34+5)15+-&yyWy134yyKM@y.5--2y
?JreborqebTb^sbo9Q^filofkdPrmmifbp;yKyXM^qqbok7Fj_rbaKbqebotb^sb?llqpZ%3d&)XM^qqbok7Fj_rbaKbqebotb^sbM^kqpZ%3d&%1-+2)/5+/&yyWy134yyKM@y.64//y
?Al_^9@llhfkdPrmmifbp;yKyXOb`fmb7?i^`hbkbaQolrqZ%/d&)XOb`fmb7Cbiq^fiAbifdeqZ%/d&%1/+0)/4+6&yyWy134yyKM@y/--/5y

OKbqebopqlojyKyQo^sbiqlKbqebopqloj%0/+3)33+3&yyWy146y
?Nfcc9BkdfkbbofkdPrmmifbp;yKyX>a^j^kqfqbCo^jbZ%1d&)XCbiFolk@^pfkdZ%0+/d&)XCbipqbbiPq^_fifwboZ%1+5d&)XHelofrjMltbo@lobZ%1+5d&)XE^kacrilcCbiFolk?liqpZ%3-p&)XBibjbkq^i?i^pqfkdMltaboZ%/-p&%0/+3)33+3&yyWy146yyKM@y.6242y
?Ab^iboJ^ifg9Bk`e^kqfkdPrmmifbp;yKyXClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&%11+/)01+-&yyWy146yyKM@y.6204y
?Ab^iboK^gbb_9Pm^obM^oqp;yKyS^oflrpbkdfkbbofkdm^oqp%/-p*./d&)S^oflrpjlqbp%.3pb^`e&%12+-)03+2&yyWy146yyKM@y/-65.y
?Ab^iboO^pe^^a9Bulqf`@ob^qrobp;yKy5afccbobkqmbqp%1-p*.-d&%10+2)02+/&yyWy146yyKM@y/-65-y
?Ab^iboP^a^n^q9MlqbkqMlq^_ibp;yKyXJ^glo>o`^kbMolqb`qflkMlqflkZ%/d&)XJ^gloPe^altMolqb`qflkMlqflkZ%/d&)s^oflrpeb^ifkdmlqflkp%1-p*/d&)s^oflrpj^k^mlqflkp%3-p*/d&)s^oflrpebo_p%.-*3-p&%10+0)02+-&yyWy146yyKM@y/-656y
?Ab^iboE^wwfk9Dbkbo^iMolsfpflkbo;yKyXJ^gloEb^ifkdMlqflkZ%1-p)&XJ^gloJ^k^MlqflkZ%3-p&)S^oflrpPq^qp`oliip%2*3p&%25+1)0.+1&yyWy146yyKM@y/--6/y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
