local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Ramkahen_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Cataclysm|r ", "Ramkahen (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

K@ljmibqbRiarj%50*51&yKyPbib`qqebIbsbifkdq^_fkArdfDrfabp^kapbib`qqeb@ljmibqbRiarj%50*51&drfabcfopq^ka`ljmibqbfqql.--")qefptfiidfsbvlr^_lrq./)---obmrq^qflk%Elkloba&yyNFAy/5450y
ORiarjyKyQo^sbiqlRiarj%1.+03)2+2.&yyWy4/-yyNFAy/5/63y

OMfidofj$pMob`fmf`byKyQo^sbiqlMfidofj$pMob`fmf`b%1.+03)2+2.&yyWy4/-y
>CfobColjqebPhvyNFAy/5403yyKyTb^qebobaKlj^a%1.+03)2+2.&yyAyyWy4/-yyKM@y162/0y
@CfobColjqebPhvyNFAy/5403yyKyRpbqebQ^khqlhfii.--Fkc^kqovjbk%06+3.)..+4-&yyAyyWy4/-yyKM@y15366)153/6y
QCfobColjqebPhvyNFAy/5403yyKyTb^qebobaKlj^a%1.+00)2+25&yyAyyWy4/-yyKM@y162/0y

OQ^eobqDolrkapyKyQo^sbiqlQ^eobqDolrkap%3-+/3)05+/5&yyNFAy/4.1.yyWy4/-y
>QefbsfkdIfqqibMir`hbopyNFAy/5/2-yyKyKlj^o`eQbkbqe%3-+/3)05+/5&Q^eobqDolrkapyyAyyWy4/-yyKM@y133-0y
@QefbsfkdIfqqibMir`hbopyNFAy/5/2-yyKyRpbqebXQ^eobqAvk^pqvJ^iibqZqlpj^pe0-P^kaMvdjfbp%25+40)06+25&Q^eobqDolrkapyyAyyRy3002.yyWy4/-yyKM@y12.6-y
QQefbsfkdIfqqibMir`hbopyNFAy/5/2-yyKyKlj^o`eQbkbqe%3-+/0)05+/5&Q^eobqDolrkapyyAyyWy4/-yyKM@y133-0y

KBu^iqbaObmrq^qflkyKyJlobobmrq^qflk`^klkiv_bb^okba_valfkd`ljmibqfkdqebA^fiv$QefbsfkdIfqqibMir`hbop$^ka_vibsbi%51*52&arkdblkptefibrpfkdqebXQ^_^oalcO^jh^ebkZ^s^fi^_ibcoljqebnr^qboj^pqbo?i^`hpjfqe>_^pf%21+.)00+0&fkO^jh^ebk)RiarjyyWy4/-yyKM@y153.4y
KDrfab@ljmibqb

]]
end) 	end
	
	function Guide:Unload()
	end
end
