local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Stormwind_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Stormwind City Vendor Run", nil, "Alliance", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%5+.)25+0&yyWy0-.y
?@^qebofkbIbi^ka9CfpefkdPrmmifbp;yWy0-.yyKyXOb`fmb7?ofiif^kqPj^iicfpeZ1-`)XOb`fmb7?ofpqibTefphbo@^qcfpeZ./p)XOb`fmb7O^fk_ltCfk>i_^`lobZ1p%22+-)36+3&yyKM@y2161y
?Gbpp^o^@loabii9Bk`e^kqfkdPrmmifbp;yWy0-.yyKyAlk$q_rvqebibsbi52?LMClojri^p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7JfkloTfw^oaLfiZ2p%20)41+/&yyKM@y.0.5y
?Pq^kivJ`@lojf`h9Fkp`ofmqflkPrmmifbp;yWy0-.yyKyXP`of_b$pP^q`ebiZ2-p%16+5)41+/&yyKM@y0-40-y
?A^of^kPfkde9CfobtlohpSbkalo;yWy0-.yyKyXP`ebj^qf`7?irbCfobtlohZ.5p%1/+3)43+5&yyKM@y.0-1y
?>ibu^kao^?libol9Q^filofkdPrmmifbp;yWy0-.yyKyAlk$q_rvqebibsbi52?LMM^qqbokp)XM^qqbok7?irbLsbo^iipZ1p)XM^qqbok7TefqbTbaafkdAobppZ.d%20+/)5.+3&yyKM@y.014y
?J^of^Irjbob9>i`ebjvPrmmifbp;yWy0-.yyKyXOb`fmb7BifufolcPe^altMltboZ.d)S^oflrpifjfqbaprmmivebo_p%22+3)52+3&yyKM@y.0.0y
??bok^oaDrjm9Cilofpq;yWy0-.yyKyAlk$q_rvqebLcc*E^kaciltbop)IfjfqbaprmmivEbo_p)X?orfpbtbbaZ.p)XB^oqeollqZ5-`)XHfkdp_illaZ.p/-`)XIfcbollqZ0p)XJ^dbolv^iZ5-`%36+1)4.+3&yyKM@y.0-/y
?HbkaloH^_lkh^9J^pqbolc@llhfkdOb`fmbp;yWy0-.yyKyAlk$q_rvqeb?LMXOb`fmb7@llhba@o^_@i^tZ^kaXOb`fmb7Tbpqc^iiPqbtZ+?rvlkblcb^`eobpbii^_ibob`fmb^kaob*pql`h^pvlrpbiiqebj)XOb`fmb7?bbo?^pqba?l^oOf_pZ/p1-`)XOb`fmb7?illaP^rp^dbZ1p)XOb`fmb7@ol`lifphDrj_lZ.3p)XOb`fmb7@ol`lifphPqb^hZ1p)XOb`fmb7@roflrpivQ^pqvLjbibqZ.3p)XOb`fmb7DllbvPmfabo@^hbZ.3p)XOb`fmb7DlobqrphIfsboMfbZ1p)XOb`fmb7Jroil`CfkPlrmZ.3p)XOb`fmb7ObaofadbDlri^peZ5p)XOb`fmb7Pb^plkbaTlicH^_l_Z.3p)XOb`fmb7Pr``ribkqMlohOf_pZ1p%43+3)20+3&yyKM@y01-y
??fiif_r_@ldpmfkkbo9BkdfkbbofkdPrmmifbp;yWy0-.yyKyIfjfqbaprmmivBkdfkbbofkdJ^qp)XOlrde?i^pqfkdMltaboZ.3`)X@l^opb?i^pqfkdMltaboZ15`)XPfisbo@lkq^`qZ.p)X?olkwbQr_bZ5p)X?olkwbCo^jbtlohZ/1p)XDvol`eolk^qljZ0-p%30+1)0.+1&yyKM@y22.6y
?IfiQfjjv9?lvtfqehfqqbkp;yWy0-.yyKyIfiQfjjvfp^o^obKM@qe^q^mmb^opbsbov0elroplopl)ebpbiip^mbqX@^q@^oofbo%TefqbHfqqbk&Z3-p)qe^qtfiipbiiclormql/--d)rpbqebq^odbq_rqqlkqlcfkaefj)tbt^kabop^olrkapqlojtfkaqebkabpm^tk%3.+5)12&%26+5)14+/&%3-+/)15+3&%23)23+3&%20+3)21+5&%15+3)26+/&%2.+5)30&%24)3/+1&%25+/)31+/&%30+5)3.&%33+1)31+3&%36+/)3/&%34+3)23+3&%36+3)20+/&%34+3)2-+1&%30+/)14+3&yyKM@y5333y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
