local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Venture_Bay_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "Venture Bay (200 Honor Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

O>j_bomfkbIladbyKyQo^sbiql>j_bomfkbIladbfkDofwwivEfiip%0-)26+5&yyWy16-y

>?i^`hofsboPhfojfpeyKyP`lrq@^mq^fk@^oqbo%0-)26+5&yyNFAy./111yyAyyKM@y/4450yyWy16-y
@?i^`hofsboPhfojfpeyKyHfii.-EloabKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./111yyAyyKM@y/4..5yyWy16-y
Q?i^`hofsboPhfojfpeyKyP`lrq@^mq^fk@^oqbo%0-)26+5&yyNFAy./111yyAyyKM@y/4450yyWy16-y

OSbkqrob?^vyKyQo^sbiqlSbkqrob?^v%//+.)5.+/&yyNFAy./0.3yyAyyWy16-y
>HbbmQebj^q?^vyKyIfbrqbk^kqPqr^oq%//+.)5.+/&yyNFAy./0.3yyAyyKM@y/423/yyWy16-y
>Pjlhb$BjLrqyKyPbodb^kqAltkbv%//)5-+5&yyNFAy./0/0yyAyyKM@y/43-/yyWy16-y
>AltkTfqe@^mq^fkWlok^yKy?^olkCobbj^k%//+/)5.+/&yyNFAy./0.1yyAyyKM@y/42/-yyWy16-y
>PbbhfkdPlisbkqyLyyKy?^o_ibcfkh%/0)5-+/&yyNFAy./110yyAyyKM@y/4162yyWy16-y

@Pjlhb$BjLrqyKyDlql?rkhelrpb7%.2)43&P^tjfii7%.3)43&Pq^_ibp7%.5)5-&^ka^dol^iiqebSbkqrob@ljm^kvPqo^ddibop^karpbqebXPjlhb?lj_Zqebdolrm`e^pfkdvlryyRy043/.yyNFAy./0/0yyAyyKM@y/424-yyWy16-y
@AltkTfqe@^mq^fkWlok^yKyHfii@^mq^fkWlok^%.0+2)5-+/&yyNFAy./0.1yyAyyKM@y/42..yyWy16-y
@HbbmQebj^q?^vyKyHfii.-EloabRkfqp%@lknrbpqElia?bopbohbop&loEloabmi^vbopfkSbkqrob?^v^ob^%.0+5)45+1&yyNFAy./0.3yyAyyKM@y/42-.)/42--yyWy16-y
@PbbhfkdPlisbkqyLyyKyDbqqebXBibjbkq..2ZfkqebDl_ifk_l^q%.3+2)5-+0&yyNFAy./110yyAyyL?Gy5-66yyWy16-y

QPbbhfkdPlisbkqyLyyKy?^o_ibcfkh%/0)5-+/&yyNFAy./110yyAyyKM@y/4162yyWy16-y
QHbbmQebj^q?^vyKyIfbrqbk^kqPqr^oq%//+.)5.+/&yyNFAy./0.3yyAyyKM@y/423/yyWy16-y
QPjlhb$BjLrqyKyPbodb^kqAltkbv%//)5-+5&yyNFAy./0/0yyAyyKM@y/43-/yyWy16-y
QAltkTfqe@^mq^fkWlok^yKy?^olkCobbj^k%//+/)5.+/&yyNFAy./0.1yyAyyKM@y/42/-yyWy16-y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
