local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Alliance_En_Wildhammer_Clan_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Cataclysm|r ", "Wildhammer Clan (Daily)", nil, "Alliance", "D", nil, function()
return [[
AAA

K@ljmibqbQtfifdeqEfdei^kap%51*52&yKy@if`hlkqebIbsbifkdq^_fkArdfDrfabp^kapbib`qqebQtfifdeqEfdei^kap%51*52&drfabcfopq^ka`ljmibqbfqql.--")qefptfiidfsbvlr^_lrq.-)---Ao^dlkj^t@i^kobmrq^qflkd^fkbaqeolrdenrbpqp^ptbii^pmolsfabvlrtfqeqebmob*nrbpqkb`bpp^ovql_bdfk^iiqebAo^dlkj^t@i^ka^fifbpyyNFAy/4453y
OQerkaboj^oyKyQo^sbiqlQerkaboj^o%16)/6+5&QtfifdeqEfdei^kapyyWy4--y
>HbbmfkdqebAo^dlkj^t^q?^vyNFAy/553-yyKy@lifkQerkaboj^o%16)/6+5&fkQerkaboj^oyyAyyWy4--yyKM@y1326.y
>?bboOrkyNFAy/5531yyKy@lifkQerkaboj^o%16)/6+5&fkQerkaboj^oyyAyyWy4--yyKM@y1326.y
>T^oiloaE^iqe^ofp?^`hyNFAy/5530yyKy@o^tJ^`Do^t%15+3)0-+3&fkQerkaboj^oyyAyyWy4--yyKM@y16053y
>KbsboIb^sb^Afkkbo?befkayNFAy/553/yyKyIltPe^j^k?irkav%16+4)/6+/&fkQerkaboj^oyyAyyWy4--yyKM@y15.42y
>CfdeqIfhb^Tfiae^jjboyNFAy/553.yyKyIltPe^j^k?irkav%16+4)/6+/&Qerkaboj^oyyAyyWy4--yyKM@y15.42y
@?bboOrkyNFAy/5531yyKyPmb^htfqeE^jjbie^kalkqebol^aplrqeb^pqlcQerkabopqofhbJlrkq^fk^kabp`loq^prmmiv`^o^s^kqlHfoqe^sbk%31+2)//+3&yyAyyWy4--yyKM@y15425y
@T^oiloaE^iqe^ofp?^`hyNFAy/5530yyKyHfiiT^oiloaE^iqe^o)vlrpelria_b^_ibqlplilqefpKM@lkvlroltk)fq`lriaq^hbpljbmo^`qf`b%16)04+0&yyAyyWy4--yyKM@y13160y
@CfdeqIfhb^Tfiae^jjboyNFAy/553.yyKyPj^pe.-Tfiae^jjboHbdp+Fcvlr`if`hqebHbd^d^fk^q^_lrq5-"`^pqqfjbvlrtfiiob`bfsbalr_ib`obafq+Fqtlk$qtlohfcvlr`if`hqllb^oivloqlli^qb%13+00)04+1.&%13+-5)0/+64&%15+32)04+10&yyAyyWy4--yyL?Gy416-y
@KbsboIb^sb^Afkkbo?befkayNFAy/553/yyKyD^qebo.2XTfiae^jjboCllaPqlobpZcoljqebQerkaboj^oOrfkp%13+00)04+1.&%13+-5)0/+64&%15+32)04+10&yyAyyWy4--yyL?Gy.--01y
@HbbmfkdqebAo^dlkj^t^q?^vyNFAy/553-yyKyHfiiAo^dlkj^tJ^o^rabop^ka`liib`q5XAo^dlkj^tFkpfdkf^pZ%13+00)04+1.&%13+-5)0/+64&%15+32)04+10&yyAyyWy4--yyKM@y130.-y
QHbbmfkdqebAo^dlkj^t^q?^vyNFAy/553-yyKy@lifkQerkaboj^o%16)/6+5&Qerkaboj^oyyAyyWy4--yyKM@y1326.y
Q?bboOrkyNFAy/5531yyKy@lifkQerkaboj^o%16)/6+5&fkQerkaboj^oyyAyyWy4--yyKM@y1326.y
QT^oiloaE^iqe^ofp?^`hyNFAy/5530yyKy@o^tJ^`Do^t%15+3)0-+3&Qerkaboj^oyyAyyWy4--yyKM@y16053y
QKbsboIb^sb^Afkkbo?befkayNFAy/553/yyKyIltPe^j^k?irkav%16+4)/6+/&fkQerkaboj^oyyAyyWy4--yyKM@y15.42y
QCfdeqIfhb^Tfiae^jjboyNFAy/553.yyKyIltPe^j^k?irkav%16+4)/6+/&fkQerkaboj^oyyAyyWy4--yyKM@y15.42y
KBu^iqbaObmrq^qflkyKyJlobobmrq^qflk`^k_bb^okba_valfkdibsbi%51*52&#ebolf`arkdblkptefibrpfkdqebXQ^_^oalcqebTfiae^jjbo@i^kZ^s^fi^_ibcoljqebnr^qboj^pqbo@o^tJ^`Do^t%15+3)0-+3&yyWy4--yyKM@y16053y
KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
