local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Glory_of_the_Icecrown_Raider_25_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Icecrown Raider 25 (80+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqebF`b`oltkO^fabo/2*j^k^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqebF`b_lrkaColpq_ollaS^knrfpeboZ+Qf`hqefppqbm+y

KEbolf`7Pqlojfkdqeb@fq^abiyKyAbcb^qqebcliiltfkdcfopqclro_lppbpfkF`b`oltk@fq^abifk/2*mi^vboEbolf`jlab+Qf`hqefppqbm+F`b`oltk@fq^abi%21)51&yyWy16/yy>FAy13-0yy>@y.y
HIloaJ^ooltd^oyKyAbcb^qIloaJ^ooltd^ocloEbolf`7Pqlojfkdqeb@fq^abi>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y033./yy>FAy130/yy>@y.y
HI^avAb^qetefpmboyKyAbcb^qI^avAb^qetefpmbocloEbolf`7Pqlojfkdqeb@fq^abi>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03522yy>FAy130/yy>@y/y
HDrkpefm?^qqibyKy@i^fjSf`qlovfkqebDrkpefm?^qqibcloEbolf`7Pqlojfkdqeb@fq^abi>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yy>FAy130/yy>@y0y
HAb^qe_ofkdboP^roc^kdyKyAbcb^qAb^qe_ofkdboP^roc^kdcloEbolf`7Pqlojfkdqeb@fq^abi>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y045.0yy>FAy130/yy>@y1y
KEbolf`7Qeb@ofjplkE^iiyKyAbcb^qqebcliiltfkd_lppbplcQeb@ofjplkE^iifkF`b`oltk@fq^abifk/2*mi^vboEbolf`jlab+Qf`hqefppqbm+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y0464-)04622yy>FAy13-0yy>@y0y
HMofk`bS^i^k^oyKyAbcb^qMofk`bS^i^k^ocloEbolf`7Qeb@ofjplkE^ii>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y0464-yy>FAy1301yy>@y.y
H?illa*NrbbkI^k^$qebiyKyAbcb^q?illa*NrbbkI^k^$qebicloEbolf`7Qeb@ofjplkE^ii>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yy>FAy1301yy>@y/y
K?lkbayKyAbcb^qIloaJ^ooltd^otfqelrq^kvo^fajbj_boobj^fkfkdfjm^ibaclojlobqe^k5pb`lkapfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y033./yy>FAy13-0yy>@y2y
KF$jlk^?l^qyKy@i^fjsf`qlovfkqebDrkpefm?^qqibtfqelrq^kvo^fajbj_bosfpfqfkdqebbkbjvdrkpefmjlobqe^kqtf`bfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yy>FAy13-0yy>@y4y
KA^k`bptfqeLlwbpyKyAbcb^qOlqc^`btfqelrq^?fdLlwb`^pqfkdRkpq^_ibLlwbBumilpflkfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03566)033/4yy>FAy13-0yy>@y6y
KK^rpb^)Eb^oq_rok)Fkafdbpqflk+++yKyAbcb^qMolcbpploMrqof`fabtfqelrqrpfkdObdrodfq^qbaLlwblkqeb>_ljfk^qflkfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03345yy>FAy13-0yy>@y..y
KLk`b?fqqbk)Qtf`bPevyKyAbcb^q?illa*NrbbkI^k^$qebilk`b^p^s^jmfob^ka^d^fktfqelrq_b`ljfkd^s^jmfobfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y04622yy>FAy13-0yy>@y.0y
K>iiVlr@^kB^qyKyAbcb^qPfkao^dlp^fk/2*mi^vbojlabtfqelrq^kvjbj_bolcvlroo^faob`bfsfkdjlobqe^k2pq^`hplcJvpqf`?rccbq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03520yy>FAy13-0yy>@y.2y
KKb`h*AbbmfkSfibyKyHfiibsbovSfibPmfofqqe^qpm^tkp_bclobfqbumilabp^kaqebkabcb^qqebIf`eHfkdfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03264yy>FAy13-0yy>@y.4y
KEbolf`7QebMi^drbtlohpyKyAbcb^qqebcliiltfkd_lppbplcQebMi^drbtlohpfkF`b`oltk@fq^abifk/2*mi^vboEbolf`jlab+Qf`hqefppqbm+F`b`oltk@fq^abi%21)51&yyWy16/yy>FAy13-0yy>@y/y
HCbpqbodrqyKyAbcb^qCbpqbodrqcloEbolf`7QebMi^drbtlohp>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y033/3yy>FAy1300yy>@y.y
HOlqc^`byKyAbcb^qOlqc^`bcloEbolf`7QebMi^drbtlohp>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y033/4yy>FAy1300yy>@y/y
HMolcbpploMrqof`fabyKyAbcb^qMolcbpploMrqof`fabcloEbolf`7QebMi^drbtlohp>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03345yy>FAy1300yy>@y0y
KEbolf`7QebColpqtfkdE^iipyKyAbcb^qqebcliiltfkd_lppbplcQebColpqtfkdE^iipfkF`b`oltk@fq^abifk/2*mi^vboEbolf`jlab+Qf`hqefppqbm+F`b`oltk@fq^abi%21)51&yyWy16/yy>FAy13-0yy>@y1y
KObp`rbS^ifqeof^Aob^jt^ihboyKyDbqS^ifqeof^Aob^jt^ihboqlcriieb^iqecloEbolf`7QebColpqtfkdE^iip>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03456yy>FAy1302yy>@y.y
HPfkao^dlp^yKyAbcb^qPfkao^dlp^cloEbolf`7QebColpqtfkdE^iip>`efbsbjbkq+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03520yy>FAy1302yy>@y/y
KCriiElrpbyKyAbcb^qI^avAb^qetefpmbotfqe^qib^pqcfsbafccbobkqqvmbplc@riqfpqp^`qfsb^qqebqfjblceboabjfpbfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03522yy>FAy13-0yy>@y3y
KF$sbDlkb^kaJ^ab^JbppyKyAbcb^qqebAb^qe_ofkdbo_bclobJ^ohlcqebC^iibk@e^jmflkfp`^pqqeobbqfjbpfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y045.0yy>FAy13-0yy>@y5y
KCirPelqPeloq^dbyKyAbcb^qCbpqbodrqtefiblcqebmi^vbopfkvlroo^fadolrmbsboe^a0pq^`hplcFkl`ri^qbafk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y033/3yy>FAy13-0yy>@y.-y
KQebLo_TefpmboboyKyAbcb^qqeb?illa@lrk`fitfqelrq^kvlkbfkqebo^faq^hfkdjlobqe^k/0)---pmbiia^j^dbfk^pfkdibefqfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y0464-yy>FAy13-0yy>@y./y
KMloq^iGl`hbvyKyBkqbobsbovmloq^ipm^tkba_vS^ifqeof^Aob^jt^ihbo_bclobeb^ifkdeboqlcriieb^iqefk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03456yy>FAy13-0yy>@y.1y
K?bbkT^fqfkd^IlkdQfjbcloQefpyKy>iiltKb`olqf`Mi^drbqlpq^`hql0-_bclobabcb^qfkdqebIf`eHfkdfk/2*mi^vbojlab+F`b`oltk@fq^abi%21)51&yyWy16/yyKM@y03264yy>FAy13-0yy>@y.3y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
