local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Glory_of_the_Raider_25_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Raider 25 (80+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqebO^fabo/2*j^k^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqeb?i^`hMolql*Ao^hbZ+Qf`hqefppqbm+y

KQebAbaf`^qbaCbtyKyAbcb^qqeb_lppbplcK^uuo^j^ptfqeibppqe^k/.mi^vbopfkqebwlkbfk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yy>FAy/.05yy>@y.y
KJ^hbNrf`hTbohlcEfjyKyAbcb^qM^q`etbohfkK^uuo^j^pfk0jfkrqbploibppfk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.3-/5yy>FAy/.05yy>@y0y
KJljj^P^faHkl`hVlrLrqyKyAbcb^qDo^kaTfaltC^boifk^fkK^uuo^j^ptfqelrqafpmbiifkdlomobsbkqfkdcobkwvfk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.2620yy>FAy/.05yy>@y2y
K>kaQebvTlria>iiDlAltkQldbqeboyKyAbcb^qqeb1ElopbjbkfkK^uuo^j^p)bkprofkdqe^qqebv^iiafbtfqefk.2pb`lkaplcb^`elqebofk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.3-31).3-32)0-216).3-30yy>FAy/.05yy>@y4y
KQebPmbiitb^sbo$pAltkc^iiyKyAbcb^qJ^ivdlpfk/2*mi^vbojlab+BvblcBqbokfqv%/3)/0&yyWy153yyKM@y/5526yy>FAy/.05yy>@y6y
K>MlhbfkqebBvbyKyAbcb^qJ^ivdlptfqecbtboqe^k/.mi^vbopfk/2*mi^vbojlab+BvblcBqbokfqv%/3)/0&yyWy153yyKM@y/5526yy>FAy/.05yy>@y..y
KAbkvfk$qebP`flkyKyAbifsbo^hfiifkd_iltql^P`flklcBqbokfqvtefibofafkdlk^elsboafphfk/2*mi^vbojlab+BvblcBqbokfqv%/3)/0&yyWy153yyKM@y0-/16yy>FAy/.05yy>@y.0y
KQebErkaoba@ir_yKyAbcb^qP^mmefolkfkK^uuo^j^ptfqelrq^kvjbj_bolcqebo^fae^sfkd^colpqobpfpqs^irblsbo.--fk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.2656yy>FAy/.05yy>@y.2y
K>o^`eklmel_f^yKyAbcb^qJ^buuk^fkK^uuo^j^ptfqefk/-jfkrqbplc>kr_$Obhe^k$pab^qefk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.262/yy>FAy/.05yy>@y/y
KQebP^cbqvA^k`byKyAbcb^qEbfd^kqebRk`ib^kfkK^uuo^j^ptfqelrq^kvlkbfkqebo^faavfkdfk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.2603yy>FAy/.05yy>@y1y
KPel`hfkdyKyAbcb^qQe^aafrpfkK^uuo^j^ptfqelrq^kvlkbfkqebo^fa`olppfkdqebkbd^qfsb^kamlpfqfsb`e^odbpfk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.26/5yy>FAy/.05yy>@y3y
KPr_qo^`qflkyKyAbcb^qQe^aafrpfkK^uuo^j^ptfqeibppqe^k/.mi^vbopfk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.26/5yy>FAy/.05yy>@y5y
KVlrAlk$qE^sb^kBqbokfqvyKyAbcb^qJ^ivdlpfk3jfkrqbploibppfk/2*mi^vbojlab+BvblcBqbokfqv%/3)/0&yyWy153yyKM@y/5526yy>FAy/.05yy>@y.-y
KDlkk^DlTebkqebSli`^kl?iltpyKyAbcb^qP^oqe^oflkqebLkvuDr^oaf^ktfqelrqdbqqfkdefq_vI^s^Pqofhbfk/2*mi^vbojlab+QebL_pfaf^kP^k`qrj%3-)23&yyWy155yyKM@y/553-yy>FAy/.05yy>@y./y
KQebQtfifdeqWlkbyKyTfqe^iiqeobbQtfifdeqAo^hbppqfii^ifsb)bkd^db^kaabcb^qP^oqe^oflkqebLkvuDr^oaf^kfk/2*mi^vbojlab+QebL_pfaf^kP^k`qrj%3-)23&yyWy155yyKM@y/553-yy>FAy/.05yy>@y.1y
KGrpq@^k$qDbqBklrdeyKyAbcb^qHbi$Qerw^afkK^uuo^j^ptefibhfiifkd^qib^pq.5^_ljfk^qflkpfkefp`e^j_bofk/2*mi^vbojlab+K^uuo^j^p%54)12&yyWy155yyKM@y.266-yy>FAy/.05yy>@y.3y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
