local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Glory_of_the_Cataclysm_Hero_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Cataclysm Hero (85+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqeb@^q^`ivpjEbol^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqebSli`^kf`PqlkbAo^hbZ+Qf`hqefppqbm+y

K@^q^`ivpjArkdblkEbolyKy@ljmibqbqeb@^q^`ivpjArkdblkEbol>`efbsbjbkq)fcvlr^iob^ave^sbk$qalkbpl+yy>FAy1512yy>@y.y
K>oobpqbaAbsbilmjbkqyKy>iilt^iiqeobblc@loi^$pwb^ilqpqlbslisb)qebkabcb^q@loi^^cqbopi^vfkdqebbslisbawb^ilqpfk?i^`hol`h@^sbokplkEbolf`Afccf`riqv+?i^`hol`hJlrkq^fkp%/-+2)0/+5&yyWy/5yyKM@y2-/51yy>FAy1512yy>@y0y
K>p`bka^kqAbp`bkafkdyKyAbcb^q>p`bka^kqIloaL_pfafrptfqelrq^kvm^oqvjbj_boob^`efkd1pq^`hplc@obmrp`ri^oSbfifk?i^`hol`h@^sbokplkEbolf`Afccf`riqv+?i^`hol`hJlrkq^fkp%/-+2)0/+5&yyWy/5yyKM@y064-2yy>FAy1512yy>@y2y
KMofk`blcQfabpyKyAbcb^q^kRkvfbiafkd?bebjlqetefibvlre^sbqebQfa^iProdbbccb`qarofkdqebLwrj^qbk`lrkqbofkQeolkblcqebQfabplkEbolf`Afccf`riqv+S^peg$fo7>_vpp^iAbmqep%4-+2)/6+6&yyWy3.1yyKM@y11315yy>FAy1512yy>@y4y
KKlPq^qf`^q>iiyKy@ljmibqbiv^slfaqebPq^qf`@ifkdbccb`qarofkdqeb>p^^abk`lrkqbofkqebSloqbuMfkk^`iblkEbolf`Afccf`riqvfkRiarj%42+-)52+-&yyWy4/-yyKM@y10542yy>FAy1512yy>@y6y
KHfiiFqTfqeCfobyKyAbcb^q0?rokfkdPlriparofkdqebEfdeMolmebq?^ofjbk`lrkqbofkIlpq@fqvlcqebQli$sfolkEbolf`Afccf`riqvfkRiarj%3.+3)36+/&yyWy4/-yyKM@y10601yy>FAy1512yy>@y..y
KEb^abaPlrqeyKyAbcb^qPf^j^q)IloalcqebPlrqeTfka)tfqe0pq^`hplcIfdeqkfkd@e^odbfkIlpq@fqvlcqebQli$sfolkEbolf`Afccf`riqvfkRiarj%3.+3)36+/&yyWy4/-yyKM@y115.6yy>FAy1512yy>@y.0y
KPqo^tQe^q?olhbqeb@^jbi$p?^`hyKyAbcb^qB^oqeo^dboMq^etefibjlrkqbalk^`^jbifkqebE^iiplcLofdfk^qflklkEbolf`Afccf`riqvfkRiarj%4-+-)2/+3&yyWy4/-yyKM@y061/5yy>FAy1512yy>@y.2y
KC^pqboQe^kqebPmbbalcIfdeqyKy@ljmibqbqebS^riqlcIfdeqptfqefk2jfkrqbplcbkqbofkdfkqebE^iiplcLofdfk^qflklkEbolf`Afccf`riqvfkRiarj%4-+-)2/+3&yyWy4/-yy>FAy1512yy>@y.4y
KOb^avcloO^fafkdyKyAlklqdbqefq_vCfobT^iifkqebDir_qlhbk`lrkqbofkAb^ajfkbplkEbolf`Afccf`riqv+Tbpqc^ii%10+/)4/+1&yyWy06yyKM@y14.3/yy>FAy1512yy>@y.6y
KMolqlqvmbMolafdvyKyHbbmqebMolqlqvmbOb^mbocoljc^iifkd_bilt6-"eb^iqe^q^kvqfjb_bclobqebClbOb^mbo2---fpabcb^qbafkAb^ajfkbplkEbolf`Afccf`riqv+Tbpqc^ii%10+/)4/+1&yyWy06yyKM@y16/-5yy>FAy1512yy>@y/.y
KF$jlk^AfbqyKyAlklqd^fkjlobqe^klkbpq^`hlcK^rpb^qbaarofkdqeb@llhfbbk`lrkqbofkAb^ajfkbplkEbolf`Afccf`riqv+Tbpqc^ii%10+/)4/+1&yyWy06yyKM@y14406yy>FAy1512yy>@y/0y
KM^oalkAbkfbayKyAbcb^q?^olk>pe_rovtfqelrqibqqfkdefjeb^itfqePq^vlcBub`rqflkfkPe^altc^kdHbbmlkEbolf`Afccf`riqv+PfisbomfkbClobpq%12+2)34+4&yyWy/.yyKM@y1363/yy>FAy1512yy>@y/2y
K?riibqQfjbyKyAbcb^q./?illaqefopqvDelriptfqeMfpqli?^oo^db^kaqebkabcb^qIloaDlacobvfkPe^altc^kdHbbmlkEbolf`Afccf`riqv+PfisbomfkbClobpq%12+2)34+4&yyWy/.yyKM@y2-23.)13631yy>FAy1512yy>@y/4y
K@orpefkd?lkbp^ka@o^`hfkdPhriipyKyAbcb^qOlj$ldd?lkb`orpebo^cqborpfkdefpPhrii`o^`hbo^_fifqvqlhfii.->kdbobaB^oqebibjbkq^ipfk?i^`hol`h@^sbokplkEbolf`Afccf`riqv+?i^`hol`hJlrkq^fkp%/-+2)0/+5&yyWy/5yyKM@y2-043)06332yy>FAy1512yy>@y/y
KQllElqqlE^kaibyKyAbcb^qH^opePqbbi_bkabo^cqboebe^pob^`eba.2pq^`hplcPrmboeb^qbaNrf`hpfisbo>ojlofk?i^`hol`h@^sbokplkEbolf`Afccf`riqv+?i^`hol`hJlrkq^fkp%/-+2)0/+5&yyWy/5yyKM@y06365yy>FAy1512yy>@y1y
KLiaC^fqecriyKyDbqI^avK^w$g^oqlhfiilkblcebojfkflkptfqeeboDbvpbo^_fifqvfkQeolkblcqebQfabplkEbolf`Afccf`riqv+S^peg$fo7>_vpp^iAbmqep%4-+2)/6+6&yyWy3.1yy>FAy1512yy>@y3y
KOlqqbkqlqeb@lobyKyAbcb^q3-Afp`fmibptfqefk.-pb`lkaparofkdqebEfdeMofbpqbpp>wfibk`lrkqbofkqebPqlkb`loblkEbolf`Afccf`riqvfkAbbmelij%13+5)16+4&yyWy31-yyKM@y1/1/5yy>FAy1512yy>@y5y
KBuqo^@obafq?lkrpPq^dbyKy@liib`q2DliabkLo_pfk^pfkdibsfpfqqlqebSloqbuMfkk^`iblkEbolf`Afccf`riqvfkRiarj%42+-)52+-&yyWy4/-yyKM@y2..24yy>FAy1512yy>@y.-y
K>`ol`^ivmpbKltyKyAbcb^q/-Cobkwfba@ol`lifphptfqefk.-pb`lkaparofkdqebIl`hj^tbk`lrkqbofkqebIlpq@fqvlcqebQli$sfolkEbolf`Afccf`riqvfkRiarj%3.+3)36+/&yyWy4/-yyKM@y10325yy>FAy1512yy>@y./y
KFE^qbQe^qPlkdyKyAbcb^qQbjmibDr^oaf^k>kerrotfqelrq^iiltfkdefjqlpfkdObsbo_bo^qfkdEvjkclojlobqe^k.2pb`lkapfkE^iiplcLofdfk^qflklkEbolf`Afccf`riqvfkRiarj%4-+-)2/+3&yyWy4/-yyKM@y061/2yy>FAy1512yy>@y.1y
KPrklc^++++yKyAbcb^qO^ge_bclobeb`ljmibqbp^kbkqfobob`e^odfkdme^pbfkqebE^iiplcLofdfk^qflklkEbolf`Afccf`riqvfkRiarj%4-+-)2/+3&yyWy4/-yyKM@y06045yy>FAy1512yy>@y.3y
KRj_o^dbcloRj_ofppyKyAbcb^qDbkbo^iRj_ofpptefibebfp^ccb`qbatfqeJladra$pJ^if`bfkDofj?^qlilkEbolf`Afccf`riqvfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y063/2yy>FAy1512yy>@y.5y
KO^qM^`hyKyHfii/-JfkbO^qparofkdqebEbifuDb^o_ob^hbobk`lrkqbofkAb^ajfkbplkEbolf`Afccf`riqv+Tbpqc^ii%10+/)4/+1&yyWy06yyKM@y2.13/)14/63yy>FAy1512yy>@y/-y
KFq$pColpqA^j^dbyKy>iiltqeobbCobbwfkdS^mlopql`^pq@l^ibp`barofkdqeb>ajfo^iOfmpk^oibk`lrkqbofkAb^ajfkbplkEbolf`Afccf`riqv+Tbpqc^ii%10+/)4/+1&yyWy06yyKM@y1606/yy>FAy1512yy>@y//y
KSfdlolrpS^k@ibbcSfkaf`^qloyKyBkd^dbS^kbpp^S^k@ibbctfqefk2jfkrqbplc_bfkdfkcif`qbatfqeqebKfdeqj^obBifufofkAb^ajfkbplkEbolf`Afccf`riqv+Tbpqc^ii%10+/)4/+1&yyWy06yyKM@y1621.yy>FAy1512yy>@y/1y
KQlqebDolrkayKyAbcb^q@ljj^kaboPmofkds^ibtfqelrq^iiltfkdefjqlob`bfsbRkelivBjmltbojbkqfkPe^altc^kdHbbmlkEbolf`Afccf`riqv+PfisbomfkbClobpq%12+2)34+4&yyWy/.yyKM@y1/45yy>FAy1512yy>@y/3y
KAlk$qKbbaql?ob^hBddpqlJ^hb^kLjbibqyKyAbcb^qBora^utfqelrqibqqfkd^C^`bibpp@loormqlo_bdfkql`^pqQtfifdeq@loormqflklk^kvlc>ibupqo^pw^$pBddpfkDofj?^qlilkEbolf`Afccf`riqvfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y1-3--)1-153)1-151yy>FAy1512yy>@y/5y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
