local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Hero_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Hero (80+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqebEbol^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqebObaMolql*Ao^hbZ+Qf`hqefppqbm+y

KLkQebOl`hpyKyAbcb^qMofk`bHbibpbqefkRqd^oabHbbmlkEbolf`Afccf`riqvtfqelrqpe^qqbofkd^kvColpqQlj_p+EltifkdCgloa%25+/)15+6&Rqd^oabHbbm%25+/)15+6&yyWy16.yyKM@y/0620yy>FAy/.03yy>@y.y
KPmifqMboplk^ifqvyKyAbcb^qDo^kaJ^drpQbibpqo^fkQebKburplkEbolf`Afccf`riqv^cqboe^sfkdhfiibaebofj^dbptfqefk2pb`lkaplcb^`elqeboarofkd_lqepmifqp+?lob^kQrkao^%/5+.)/5+.&QebKburp%/5+.)/5+.&yyWy153yyKM@y/340.yy>FAy/.03yy>@y/y
KFkqbkpb@liayKyAbcb^qHbofpqo^pw^fkQebKburplkEbolf`Afccf`riqvtfqelrq^iiltfkdFkqbkpb@liaqlob^`ejlobqe^kqtlpq^`hp+?lob^kQrkao^%/5+.)/5+.&QebKburp%/5+.)/5+.&yyWy153yyKM@y/34/0yy>FAy/.03yy>@y0y
K@e^lpQeblovyKyAbcb^q>klj^irpfkQebKburplkEbolf`Afccf`riqvtfqelrqabpqolvfkd^kv@e^lqf`Ofcqp?lob^kQrkao^%/5+.)/5+.&QebKburp%/5+.)/5+.&yyWy153yyKM@y/3430yy>FAy/.03yy>@y1y
KT^q`eEfjAfbyKyAbcb^qHofh$qefoqebD^qbt^q`ebofk>wgli*Kbor_lkEbolf`Afccf`riqvtefibT^q`eboD^peo^)T^q`eboK^ogf)^kaT^q`eboPfiqefh^obpqfii^ifsb+Ao^dlk_ifdeq%/3+5)15+2&>wgli*Kbor_yyWy155yyKM@y/5351yy>FAy/.03yy>@y2y
KE^aolkluAbkfbayKyAbcb^qE^aolklufk>wgli*Kbor_lkEbolf`Afccf`riqv_bclobebtb_pqebqlmallop^kamobsbkqpjlob`ob^qrobpcoljpm^tkfkd+Ao^dlk_ifdeq%/3+5)15+2&>wgli*Kbor_yyWy155yyKM@y/56/.yy>FAy/.03yy>@y3y
KDlqq^DlyKyAbcb^q>kr_$^o^hfk>wgli*Kbor_lkEbolf`Afccf`riqvfk1jfkrqbploibpp+Ao^dlk_ifdeq%/3+5)15+2&>wgli*Kbor_yyWy155yyKM@y/6./-yy>FAy/.03yy>@y4y
KSli^wg$pNrf`hAbjfpbyKyAbcb^qEbo^iaSli^wgfk>ek$h^ebqlkEbolf`Afccf`riqvfk/jfkrqbploibpp+Ao^dlk_ifdeq%/3+5)15+2&>ek$H^ebq7QebLiaHfkdaljyyWy155yyKM@y/60..yy>FAy/.03yy>@y5y
KObpmb`qVlroBiabopyKyAbcb^qBiaboK^alufk>ek$h^ebqlkEbolf`Afccf`riqvtfqelrqhfiifkd^kv>ek$h^e^oDr^oaf^kp+Ao^dlk_ifdeq%/3+5)15+2&>ek$H^ebq7QebLiaHfkdaljyyWy155yyKM@y/60-6yy>FAy/.03yy>@y6y
KSlirkqbboTlohyKyAbcb^qGbald^Pe^altpbbhbofk>ek$h^ebqlkEbolf`Afccf`riqvtfqelrqhfiifkd^kvQtfifdeqSlirkqbbop+Ao^dlk_ifdeq%/3+5)15+2&>ek$H^ebq7QebLiaHfkdaljyyWy155yyKM@y/60.-yy>FAy/.03yy>@y.-y
K@lkprjmqflkGrk`qflkyKyAbcb^qQoliidlobfkAo^h$Qe^olkHbbmlkEbolf`Afccf`riqv_bclob@lkprjbob^`ebpqbkpq^`hp+DofwwivEfiip%.4+4)/0+0&Ao^h$Qe^olkHbbmyyWy163yyKM@y/330-yy>FAy/.03yy>@y..y
K?bqqboLccAobayKyBkd^dbHfkdAobafkAo^h$Qe^olkHbbmlkEbolf`Afccf`riqv^kapi^v3Ao^hh^ofDrqofmmboploAo^hh^ofP`vqeb`i^tarofkdefpabcb^q+DofwwivEfiip%.4+4)/0+0&Ao^h$Qe^olkHbbmyyWy163yyKM@y/4150yy>FAy/.03yy>@y./y
KLeKlslpyKyAbcb^qKlslpqebPrjjlkbofkAo^h$Qe^olkHbbmlkEbolf`Afccf`riqvtfqelrq^iiltfkd^kvrkab^ajfkflkpqlob^`eqebcillo+DofwwivEfiip%.4+4)/0+0&Ao^h$Qe^olkHbbmyyWy163yyKM@y/330.yy>FAy/.03yy>@y.0y
KAbcbkpbibppyKyAbcb^q@v^kfdlp^fkQebSflibqEliatfqelrqrpfkdAbcbkpb@lkqoli@ovpq^ip^katfqeMofplkPb^iFkqbdofqv^q.--"tefibfkEbolf`Afccf`riqv+A^i^o^k%34+1)35+2&QebSflibqEliayyWy2-1yyKM@y0..01yy>FAy/.03yy>@y.1y
KIl`haltkyKyAbcb^qUbslww)I^s^kqelo)F`elolk)Wro^j^qqebL_ifqbo^qlo)Bobhbj)^kaJlo^ddfkQebSflibqElialkEbolf`Afccf`riqv+A^i^o^k%34+1)35+2&QebSflibqEliayyWy2-1yy>FAy/.03yy>@y.2y
KAbevao^qflkyKyAbcb^qF`elolkfkqebSflibqElialkEbolf`Afccf`riqvtfqelrq^iiltfkd^kvF`eloDil_ribpqljbodb+A^i^o^k%34+1)35+2&QebSflibqEliayyWy2-1yyKM@y/60.0yy>FAy/.03yy>@y.3y
K>SlfaA^k`byKyAbcb^qWro^j^qqebL_ifqbo^qlofkQebSflibqElialkEbolf`Afccf`riqvtfqelrqhfiifkd^kvslfapbkqofbp+A^i^o^k%34+1)35+2&QebSflibqEliayyWy2-1yyKM@y/60.1yy>FAy/.03yy>@y.4y
KTe^qqebB`h<yKyAbcb^qD^i$a^o^efkDrkao^hlkEbolf`Afccf`riqvtefibrkaboqebbccb`qplcB`hObpfarbWri$Ao^h%5.+3)/.+0&Drkao^hyyWy163yyKM@y/60-3yy>FAy/.03yy>@y.5y
KPe^obQebIlsbyKyAbcb^qD^i$a^o^efkDrkao^hlkEbolf`Afccf`riqv^kae^sb2rkfnrbm^oqvjbj_bopdbqfjm^ibaqeolrdelrqqebcfdeqWri$Ao^h%5.+3)/.+0&Drkao^hyyWy163yyKM@y/60-3yy>FAy/.03yy>@y.6y
KIbpp*o^_fyKyAbcb^qJllo^_ffkDrkao^hlkEbolf`Afccf`riqvtefibmobsbkqfkdefjcoljqo^kpclojfkdfkql^j^jjlqe^q^kvmlfkqarofkdqebbk`lrkqbo+Wri$Ao^h%5.+3)/.+0&Drkao^hyyWy163yyKM@y/60-2yy>FAy/.03yy>@y/-y
KPk^hbp+Tev$aFqE^sbQl?bPk^hbp<yKyAbcb^qPi^a$o^kfkDrkao^hlkEbolf`Afccf`riqvtfqelrqdbqqfkdpk^hbto^mmba+Wri$Ao^h%5.+3)/.+0&Drkao^hyyWy163yyKM@y/60-1yy>FAy/.03yy>@y/.y
KDllaDofbcyKyAbcb^qqebJ^fabklcDofbcfkqebE^iiplcPqlkblkEbolf`Afccf`riqvfk.jfkrqbloibpp+QebPqlojMb^hp%11+5).1+2&E^iiplcPqlkbyyWy162yyKM@y/4642yy>FAy/.03yy>@y//y
K?o^kkPm^khfk$KbtyKyAbcb^qqebQof_rk^ilc>dbpbk`lrkqbofkqebE^iiplcPqlkblkEbolf`Afccf`riqvtfqelrq^iiltfkd?o^kk?olkwb_b^oaqlq^hb^kva^j^db+QebPqlojMb^hp%11+5).1+2&E^iiplcPqlkbyyWy162yy>FAy/.03yy>@y/0y
K>_rpbqebLlwbyKyAbcb^qPglkkfoqebFolkpe^mbofkqebE^iiplcPqlkblkEbolf`Afccf`riqv^kahfii2FolkPiradbparofkdqebbk`lrkqbo+QebPqlojMb^hp%11+5).1+2&E^iiplcPqlkbyyWy162yyKM@y/4645yy>FAy/.03yy>@y/1y
KQfjbivAb^qeyKyAbcb^qIlhbkfkqebE^iiplcIfdeqkfkdlkEbolf`Afccf`riqvfk/jfkrqbploibpp+QebPqlojMb^hp%05+-).1+4&E^iiplcIfdeqkfkdyyWy162yyKM@y/56/0yy>FAy/.03yy>@y/2y
KIfdeqkfkdPqor`hyKyAbcb^qDbkbo^i?g^okdofjfkqebE^iiplcIfdeqkfkdlkEbolf`Afccf`riqvtefibebe^p^Qbjmlo^ovBib`qof`^i@e^odb+QebPqlojMb^hp%05+-).1+4&E^iiplcIfdeqkfkdyyWy162yyKM@y/5253yy>FAy/.03yy>@y/3y
KPe^qqboObpfpq^kqyKyAbcb^qSlihe^kfkqebE^iiplcIfdeqkfkdlkEbolf`Afccf`riqvtfqelrq^iiltfkdefjqlpe^qqbojlobqe^k1?ofqqibDlibjp+QebPqlojMb^hp%05+-).1+4&E^iiplcIfdeqkfkdyyWy162yyKM@y/5254yy>FAy/.03yy>@y/4y
KQeb@riifkdlcQfjbyKyAbcb^qqebFkcfkfqb@loormqlofkQeb@riifkdlcPqo^qelijblkEbolf`Afccf`riqv+Q^k^ofp%32+5)15+6&Qeb@riifkdlcPqo^qelijbyyWy.3.yyKM@y0//40yy>FAy/.03yy>@y/5y
KWlj_fbcbpqyKyHfii.--OfpbkWlj_fbpfk.jfkrqbfkQeb@riifkdlcPqo^qelijblkEbolf`Afccf`riqv+Q^k^ofp%32+5)15+6&Qeb@riifkdlcPqo^qelijbyyWy.3.yyKM@y/4404yy>FAy/.03yy>@y/6y
KQebFk`obaf_ibErihyKyClo`bPs^i^Plooltdo^sbqlhfii^P`lrodbErihlkEbolf`Afccf`riqvfkRqd^oabMfkk^`ib+EltifkdCgloa%25+/)15+6&Rqd^oabMfkk^`ibyyWy16.yyKM@y/3222yy>FAy/.03yy>@y0-y
KIlafAlafTbIlsbpqebPh^afyKyAbcb^qPh^afqebOrqeibppfkRqd^oabMfkk^`iblkEbolf`Afccf`riqvtfqefk0jfkrqbplcpq^oqfkdqebd^rkqibqbsbkq+EltifkdCgloa%25+/)15+6&Rqd^oabMfkk^`ibyyWy16.yyKM@y/3360yy>FAy/.03yy>@y0.y
KJvDfoiIlsbpqlPh^af>iiqebQfjbyKyAbcb^qPh^afqebOrqeibppfkRqd^oabMfkk^`iblkEbolf`Afccf`riqv^cqboe^sfkdhfiibaDo^rccolj.--"qlab^afk^pfkdibm^pp+EltifkdCgloa%25+/)15+6&Rqd^oabMfkk^`ibyyWy16.yyKM@y/3360yy>FAy/.03yy>@y0/y
KHfkd$p?^kbyKyAbcb^qHfkdVjfolkfkRqd^oabMfkk^`iblkEbolf`Afccf`riqvtfqelrq^kvlkbfkqebm^oqvqofddbofkd?^kb+EltifkdCgloa%25+/)15+6&Rqd^oabMfkk^`ibyyWy16.yyKM@y/353.yy>FAy/.03yy>@y00y
KBumbofbk`baAo^hbOfabo*>j_boyKyAbcb^qfkdIbv*Dr^oaf^kBobdlptefibofafkd^k>j_boao^hblkEbolf`Afccf`riqv+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy.54.yy>@y.y
KBumbofbk`baAo^hbOfabo*Bjbo^iayKyAbcb^qfkdIbv*Dr^oaf^kBobdlptefibofafkd^kBjbo^iaao^hblkEbolf`Afccf`riqv+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy.54.yy>@y/y
KBumbofbk`baAo^hbOfabo*Or_vyKyAbcb^qfkdIbv*Dr^oaf^kBobdlptefibofafkd^kOr_vao^hblkEbolf`Afccf`riqv+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy.54.yy>@y0y
KJ^hbFq@lrkqyKyAbcb^qIbv*Dr^oaf^kBobdlpfkQebL`rirplkEbolf`Afccf`riqvtfqefk/-jfkrqbplcAo^hlpqebFkqboold^qlo$pab^qe+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy/.03yy>@y02y
KOr_vSlfayKyAbcb^qIbv*Dr^oaf^kBobdlpfkQebL`rirplkEbolf`Afccf`riqvtfqelrq^kvlkbfkvlrom^oqvrpfkd^Or_vAo^hb+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy/.03yy>@y03y
KBjbo^iaSlfayKyAbcb^qIbv*Dr^oaf^kBobdlpfkQebL`rirplkEbolf`Afccf`riqvtfqelrq^kvlkbfkvlrom^oqvrpfkd^kBjbo^iaAo^hb+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy/.03yy>@y04y
K>j_boSlfayKyAbcb^qIbv*Dr^oaf^kBobdlpfkQebL`rirplkEbolf`Afccf`riqvtfqelrq^kvlkbfkvlrom^oqvrpfkd^k>j_boAo^hb+?lob^kQrkao^%/5+.)/5+.&QebL`rirp%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy/.03yy>@y05y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
