local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Glory_of_the_Dragon_Soul_Raider_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Dragon Soul Raider (85+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqebAo^dlkPlriO^fabo^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqebQtfifdeqE^o_fkdboZ+Qf`hqefppqbm+y

HEbolf`7Jlo`elhyKyAbcb^qJlo`elhfkAo^dlkPlrilkEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y22/32yy>FAy3.36yy>@y.y
HEbolf`7T^oiloaWlk$lwwyKyAbcb^qT^oiloaWlk$lwwfkAo^dlkPlrilkEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y220-5yy>FAy3.36yy>@y/y
HEbolf`7Vlo$p^egqebRkpibbmfkdyKyAbcb^qVlo$p^egqebRkpibbmfkdfkAo^dlkPlrilkEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y220./yy>FAy3.36yy>@y0y
HEbolf`7E^d^o^qebPqloj_fkaboyKyAbcb^qE^d^o^qebPqloj_fkabofkAo^dlkPlrilkEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y22356yy>FAy3.36yy>@y1y
HEbolf`7Riqo^uflkyKyAbcb^qRiqo^uflkfkAo^dlkPlrilkEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y22/61yy>FAy3.36yy>@y2y
HEbolf`7T^oj^pqbo?i^`helokyKyAbcb^qT^oj^pqbo?i^`helokfkAo^dlkPlrilkEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y231/4yy>FAy3.36yy>@y3y
KAlk$qPq^kaPl@ilpbqlJbyKyAbcb^qJlo`elhfkAo^dlkPlrilkKloj^iloEbolf`Afccf`riqvtfqelrq^kvqtlmi^vbop%qeobbmi^vboplk/2*mi^vbojlab&bsbo_bfkdtfqefk2v^oaplcb^`elqebotefibJlo`elhfp`e^kkbifkd?i^`h?illalcqebB^oqe+Ao^dlkPlri%32)15&yyWy.3.yyKM@y22/32yy>FAy3.36yy>@y4y
KQ^pqbqebO^fk_ltyKyBumbofbk`bqebcliiltfkd`lilo`lj_fk^qflkp)^kaqebkabcb^qVlo$p^egqebRkpibbmfkdlkKloj^iloEbolf`Afccf`riqv+J^v_b_balkb^`olppjriqfmib^qqbjmqp+Ao^dlkPlri%32)15&yyWy.3.yyKM@y220./yy>FAy3.36yy>@y5y
KMfkdMlkd@e^jmflkyKy?lrk`bqebSlfalcRkj^hfkd.-qfjbplcclcmi^vbop)^kaqebkabcb^qT^oiloaWlk$lwwlkKloj^iloEbolf`Afccf`riqv+Ao^dlkPlri%32)15&yyWy.3.yyKM@y220-5yy>FAy3.36yy>@y6y
KEliafkdE^kapyKyAbpqolvqebcfk^i@ovpq^i@lkar`qloarofkdE^d^o^$pifdeqkfkdme^pblkKloj^iloEbolf`Afccf`riqv)tefib^iio^fajbj_bop^obm^oqlcqebcfk^iIfdeqkfkd@lkarfq+Ao^dlkPlri%32)15&yyWy.3.yyKM@y23.32yy>FAy3.36yy>@y.-y
KJfkrqbpqlJfakfdeqyKyAbcb^qRiqo^uflkfkAo^dlkPlrilkKloj^iloEbolf`Afccf`riqvtfqelrq^kvo^fajbj_bo_bfkdefq_vElrolcQtfifdeqjlobqe^klk`b+Ao^dlkPlri%32)15&yyWy.3.yyKM@y22/61yy>FAy3.36yy>@y..y
KAb`hAbcbkaboyKyAbcb^qT^oj^pqbo?i^`heloklkKloj^iloEbolf`Afccf`riqvtfqelrq^iiltfkd^kvQtfifdeq?^oo^dbpqla^j^dbqebPhvcfob+Ao^dlkPlri%32)15&yyWy.3.yyKM@y231/4yy>FAy3.36yy>@y./y
KJ^v_bEb$iiDbqAfwwv+++yKyAbcb^qqebPmfkblcAb^qetfkdbk`lrkqbolkKloj^iloEbolf`Afccf`riqv^cqboqof`hfkdAb^qetfkdfkqlmboclojfkdqebcliiltfkdoliipbnrbk`b7Ibcq)Ofdeq)Ibcq)Ofdeq+Ao^dlkPlri%32)15&yyWy.3.yyKM@y20546yy>FAy3.36yy>@y.0y
K@eolj^qf`@e^jmflkyKyAbpqolvAb^qetfkdfkAo^dlkPlrilkKloj^iloEbolf`Afccf`riqv^cqbo_bdfkkfkdqebbk`lrkqbolkb^`e>pmb`q$pmi^qcloj+Alkblsbopbsbo^i^qqbjmqp+Ao^dlkPlri%32)15&yyWy.3.yyKM@y20546yy>FAy3.36yy>@y.1y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
