local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Glory_of_the_Firelands_Raider_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Firelands Raider (85+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqebCfobi^kapO^fabo^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebX@loormqbaBddlcJfii^d^wloZ+Qf`hqefppqbm+y

KAb^qecolj>_lsbyKyLkivhfii@fkabotb_Aolkbptefibqebv^ob^qlmqebtb_`^klmvarofkdqeb?bqe$qfi^`bk`lrkqbofkCfobi^kap+Cfobi^kap%14)46&yyWy3-3yyKM@y20302)2/25.yy>FAy25/5yy>@y.y
KAl^?^oobiOliiyKyAbcb^q>ivpo^wlofkqebCfobi^kaptfqelrq^kvo^fajbj_bodbqqfkdefq_vqebcliiltfkd^qq^`hp8?orpecfob%CivfkdMe^pb&)Fk`bkaf^ov@ilra%CivfkdMe^pb&)I^s^Pmbt%CivfkdMe^pb&)CfbovQlok^al%Qo^kpfqflk^cqboCivfkdMe^pb&+Cfobi^kap%14)46&yyWy3-3yyKM@y2/20-yy>FAy25/5yy>@y0y
KPe^obqebM^fkyKyAbcb^q?^ibol`fkqebCfobi^kaptfqelrq^iiltfkd^kvjbj_bolcvlroo^faqlprccboQlojbkqjlobqe^kqeobbqfjbp+Cfobi^kap%14)46&yyWy3-3yyKM@y20161yy>FAy25/5yy>@y2y
HEbolf`7?bqe$qfi^`yKyAbcb^q?bqe$qfi^`fkCfobi^kaplkEbolf`Afccf`riqv+Cfobi^kap%14)46&yyWy3-3yyKM@y2/165yy>FAy25/5yy>@y4y
HEbolf`7Pe^kkluyKyAbcb^qPe^kklufkCfobi^kaplkEbolf`Afccf`riqv+Cfobi^kap%14)46&yyWy3-3yyKM@y2036.yy>FAy25/5yy>@y6y
HEbolf`7?^ibol`yKyAbcb^q?^ibol`fkCfobi^kaplkEbolf`Afccf`riqv+Cfobi^kap%14)46&yyWy3-3yyKM@y20161yy>FAy25/5yy>@y..y
KKlq^k>j_f*QrokboyKyAbcb^qIloaOevlifqefkqebCfobi^kaptfqelrqbsbo`^rpfkdefjqlqrokibcqtefibefp^ojlofpfkq^`q+Cfobi^kap%14)46&yyWy3-3yyKM@y2/225yy>FAy25/5yy>@y/y
K?r`hbqIfpqyKyArofkd^pfkdibbkd^dbjbkq)_ofkdPe^kkluqlb^`elcqebcliiltfkdil`^qflkpfkqebCfobi^kap_bclobafpm^q`efkdefj7%01+-)0-+5&%/6+.)3/+0&%01+.)42+.&%3.+3)22+6&%3.+/)12+1&yyWy5--yyKM@y2036.yy>FAy25/5yy>@y1y
KLkivqebMbkfqbkq+++yKy>`qfs^qb_lqelcC^kao^i$pCi^jbp^qlk`bfkCfobi^kaptfqelrq^kvo^fajbj_bodbqqfkdefq_vHkbbiqlqebCi^jbCfobi^kap%14)46&yyWy3-3yyKM@y2/24.yy>FAy25/5yy>@y3y
HEbolf`7IloaOevlifqeyKyAbcb^qIloaOevlifqefkCfobi^kaplkEbolf`Afccf`riqv+Cfobi^kap%14)46&yyWy3-3yyKM@y2/225yy>FAy25/5yy>@y5y
HEbolf`7>ivpo^wloyKyAbcb^q>ivpo^wlofkCfobi^kaplkEbolf`Afccf`riqv+Cfobi^kap%14)46&yyWy3-3yyKM@y2/20-yy>FAy25/5yy>@y.-y
HEbolf`7J^gloaljlC^kao^iPq^debijyKyAbcb^qJ^gloaljlC^kao^iPq^debijfkCfobi^kaplkEbolf`Afccf`riqv+Cfobi^kap%14)46&yyWy3-3yyKM@y2/24.yy>FAy25/5yy>@y./y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
