local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Glory_of_the_Cataclysm_Raider_A")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Cataclysm Raider (85+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqeb@^q^`ivpjO^fabo^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqebAo^hblcqebB^pqTfkaZ+Qf`hqefppqbm+y

HJ^dj^tyKyAbcb^qJ^dj^tfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.24-yy>FAy1520yy>@y.y
HJ^ilof^hyKyAbcb^qJ^ilof^hfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.045yy>FAy1520yy>@y0y
H@efj^bolkyKyAbcb^q@efj^bolkfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y10/63yy>FAy1520yy>@y2y
HE^icrpTvoj_ob^hboyKyAbcb^qE^icrpTvoj_ob^hbofkqeb?^pqflklcQtfifdeqlkEbolf`Afccf`riqvfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y113--yy>FAy1520yy>@y4y
H>p`bka^kq@lrk`fiyKyAbcb^qqeb>p`bka^kq@lrk`fifkqeb?^pqflklcQtfifdeqlkEbolf`Afccf`riqvfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y10402yy>FAy1520yy>@y6y
H@lk`i^sblcTfkayKyAbcb^qqeb@lk`i^sblcTfkafkqebQeolkblcqebClroTfkaplkEbolf`Afccf`riqvfkRiarj%03+0)51+5&yyWy4/-yyKM@y1254-)1254.)1254/yy>FAy1520yy>@y..y
KM^o^pfqbBsbkfkdyKyAbcb^qJ^dj^tfk?i^`htfkdAbp`bkqtfqelrq^kvlkbfkqebo^fa_b`ljfkdfkcb`qbatfqe^m^o^pfqb+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.24-yy>FAy1520yy>@y.0y
KPfibk`bfpDliabkyKyAbcb^q>qo^jbabpfk?i^`htfkdAbp`bkqtfqelrq^kvo^fajbj_bo$pplrka_^odlfkdlsbo2-"+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.11/yy>FAy1520yy>@y.2y
K>_boo^kq?be^sfloyKyHfii./>_boo^qflkptfqefk.-pb`lkaplkqebJ^ilof^hbk`lrkqbofk?i^`htfkdAbp`bkq^kaqebkabcb^qJ^ilof^h+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.11-)1.045yy>FAy1520yy>@y.4y
KQebLkivBp`^mbyKyAbcb^qE^icrpTvoj_ob^hbofk?^pqflklcQtfifdeq^cqboabcb^qfkdqtlao^hbptfqefk.-pb`lkaplcb^`elqebo+QebBjbo^iaTebimm^`h`lrkqp^plkbao^hbcloqefpmromlpbfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y113--yy>FAy1520yy>@y.6y
KBibjbkq^ovyKyAbcb^qqebBibjbkqfrjJlkpqolpfqvfkqeb?^pqflklcQtfifdeqtefiblkiv^iiltfkdfqql`ob^qb^pfkdibIfnrfaF`bm^q`efkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y10402yy>FAy1520yy>@y/.y
KPq^v@efiiyKyAbcb^qqeb@lk`i^sblcTfkafkqebQeolkblcqebClroTfkaptefibbsbovlkbfkqebo^fae^p^qib^pq4pq^`hplcTfka@efiifkRiarj%03+0)51+5&yyWy4/-yyKM@y1.11-)1.045yy>FAy1520yy>@y/0y
HLjklqolkAbcbkpbPvpqbjyKyAbcb^qqebLjklqolkAbcbkpbPvpqbjfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1/.5-yy>FAy1520yy>@y/y
H>qo^jbabpyKyAbcb^q>qo^jbabpfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.11/yy>FAy1520yy>@y1y
HKbc^of^kyKyAbcb^qKbc^of^kfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.043yy>FAy1520yy>@y3y
HS^iflk^^kaQebo^iflkyKyAbcb^qS^iflk^^kaQebo^iflkfkqeb?^pqflklcQtfifdeqlkEbolf`Afccf`riqvfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4/-yyKM@y1266/)12660yy>FAy1520yy>@y5y
H@el$d^iiyKyAbcb^q@el$d^iifkqeb?^pqflklcQtfifdeqlkEbolf`Afccf`riqvfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y100/1yy>FAy1520yy>@y.-y
H>i$>hfoyKyAbcb^q>i$>hfofkqebQeolkblcqebClroTfkaplkEbolf`Afccf`riqvfkRiarj%03+0)51+5&yyWy4/-yyKM@y13420yy>FAy1520yy>@y./y
K>`efbsb*^*qolkyKyAbcb^qqebLjklqolkAbcbkpbPvpqbjfk?i^`htfkdAbp`bkqtefibkbrqo^ifwfkdqebcliiltfkd^qq^`hp8Klmi^vboefq_vPq^qf`Pel`h)Klmi^vboefq_vMlfplk?lj_)Klmi^vboefq_v>o`^kb>kkfefi^qlo)Kljlobqe^klkbmi^vboefq_vb^`eCi^jbqeoltbo?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1/.5-yy>FAy1520yy>@y.1y
KCriilcPlrka^kaCrovyKyAbcb^q@efj^bolkfk?i^`htfkdAbp`bkqtfqekljlobqe^k/o^fajbj_boab^qep+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y10/63yy>FAy1520yy>@y.3y
KHbbmfkdfqfkqebC^jfivyKyA^j^dbKbc^of^k_bilt2-"eb^iqe_bclobebi^kapcloqebcfk^i`lkcolkq^qflk^kaqebkabcb^qKbc^of^kfk?i^`htfkdAbp`bkq+?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y1.043yy>FAy1520yy>@y.5y
KAlr_ibAo^dlkyKyHfii3QtfifdeqCfbkapfkqebQtfifdeqOb^ij^kaqebkabcb^qS^iflk^^kaQebo^iflkfkqeb?^pqflklcQtfifdeqfkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y1266/)12660yy>FAy1520yy>@y/-y
KQeb>_vppTfiiD^wb?^`hFkqlVlryKyAbcb^q@el$d^iifkqeb?^pqflklcQtfifdeq_bclob^kvo^fajbj_bob^okpjlobqe^k0-"@loormqba?illafkQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y100/1yy>FAy1520yy>@y//y
KClroMi^vyKyAbcb^q>i$>hfofkqebQeolkblcqebClroTfkaptefibebfp^ccb`qba_vCbba_^`hfkRiarj%03+0)51+5&yyWy4/-yyKM@y13420yy>FAy1520yy>@y/1y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
