local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Lost_and_Found_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Exploration|r ", "Lost and Found Achievements (85+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabfp^J^kr^iqf`hdrfab+Lk`bvlre^sb`ljmibqbaqebpqbm)qf`hfqqljlsblkqlqebkbuqpqbm+Pljblcqebpbfqbjp`lrkqqlt^oapqeb>`efbsbjbkqp8Ilpq^kaClrka)CfkabopHbbmbop)LkbJ^k$pQo^pe+++)^kaFp>klqeboJ^k$pQob^prob+Pljblcqebpbfqbjp^ob^t^oaUM^kadlia)_rqalklq`lrkqqlt^oaqeb^`efbsbjbkqp+Qf`hqefppqbm+y

OQebG^abClobpqyKyQo^sbiqlQebG^abClobpq%13+0)5-+4&y
KLccbofkdlcObjbj_bo^k`byKy%13+0)5-+4&+{0-dyyL?Gy/.1005yyWy5-3y
KPefm$pIl`hboyKyClrkafkqeb_lqqljlcqeb_l^q^qqebt^vmlfkq%2-+6)66+6&+{63dyyWy5-3y
K>k`fbkqGfkvrPq^ccyKy%11+6)31+3&%12+2)31+1&%13+/)4.+/&%13+1)32+0&%13+1)4-+.&%14+.)34+1&+?l>Pq^cc+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.041.yyWy5-3y
KG^abFkcrpba?i^abyKyG^abT^oofloPq^qrb%06+0)13+3&+?l>ptloa+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyKM@y31/4/yyWy5-3y
KM^ka^obkOfqr^iPqlkbyKyKloqetbpqlc@^jmKllh^Kllh^)fkqebjfaaiblcI^hbHfqqfq^q^%/0+2)02+-&+Sbkalopclo.-2dyyL?Gy/.0415yyWy5-3y
K>k`fbkqM^ka^obkQb^MlqyKyPbobkfqvC^iip%/3+/)0/+1&+Sbkalopclo.--dyyL?Gy/.0033yyWy5-3y
KIr`hvM^ka^obk@lfkyKyFkpfab^tbiikb^oqebPqolkd^oj>fopefm+%0.+6)/4+5&+Sbkalopclo{62dyyL?Gy/.0035yyWy5-3y
K>k`fbkqM^ka^obkJfkfkdMf`hyKyDobbkpqlkbSfii^db%25+5)//+1&%13+.)/6+.&%11+.)/4+-&%10+5)0-+4&+?l>JfkfkdMf`h+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0031yyWy5-3y
KPq^pelcDbjpyKy@^sblkTfkat^oaFpib+%25+5)//+1&%3/+1)/4+2&+@lkq^fkpJfp`DbjpyyL?Gy/.1004yyWy5-3y
KE^jjbolcQbkQerkabopyKyPb^qlcqebPmfofqT^ihbo%10+-)..+3&%1.+5).4+3&%1.+/).0+5&+?l>/*e^kabaJ^`b+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.041/yyWy5-3y
KTlafk$pJ^kqfaPe^khboyKyFkpfabLtbk$pTfpefkdTbii%06+1)4+0&+?l>A^ddbo+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0030yyWy5-3y

OS^iibvlcqebClroTfkapyKyQo^sbiqlS^iibvlcqebClroTfkap%55+2)2-+2&yyWy5-4y
K?l^q*?rfiafkdFkpqor`qflkpyKyC^ob^pqpelob)fkpfab^_l^qelrpb%55+2)2-+2&%56+2)12+.&%6/+1)1/+1&%6/+-)06+-&il`^qbalkqebV^k*WebOfsbo+Sbkalopclo.-dyyL?Gy/.101-yyWy5-4y

OHo^p^o^kdTfiapyKyQo^sbiqlHo^p^o^kdTfiap%4.+-)-6+-&yyWy524y
KP^rolhPqlkbQ^_ibqyKyBkqboqeb`^sb%4.+-)-6+-&fkHo^p^o^kdTfiap+Fqbjfp_befkapljbgrkh%42+-)22+/&+Sbkalopclo.--dyyL?Gy/.042-yyWy524y
KM^ka^obkCfpefkdPmb^oyKy%2-+5)16+0&?l>mlib^oj+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0320yyWy524y
KOb`fmb7?^k^k^FkcrpbaOrjyKyClrkafk?^oobilc?^k^k^FkcrpbaOrjlkJ^ofpq^Fpi^kafkK^vbifI^dllk%2/+0)55+4&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.1106yyWy524y
KPq^`hlcM^mbopyKyJ^ofpq^Fpi^kafkK^vbifI^dllk%2/+/)40+0&)_vK^vbifI^dllk+Sbkalopclo.2dyyL?Gy/.11-0yyWy524y
KBnrfmjbkqIl`hboyKyJ^ofpq^Fpi^kafkK^vbifI^dllk%1/+0)6/+-&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqp+yyL?Gy/.032.yyWy524y

OS^iibvlcqebClroTfkapyKyQo^sbiqlS^iibvlcqebClroTfkap%.2+1)/6+.&yyWy5-4y
KPq^cclcqebEfaabkJ^pqboyKyM^lnr^kEliilt**e^oaqlpbb^jlkdqeb_^j_llpellqp+%.2+1)/6+.&%.4+2)02+4&%.6+.)04+6&%.2+-)00+4&%.6+-)1/+2&?l>pq^cc+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0416yyWy5-4y
KSfojbkQob^prob@^`ebyKyFkpfabqebSfojbk`^sb%/0+/)0-+5&%/0+4)/5+1&kloqeb^pqlcM^lnr^kEliilt+CIVFKDJLRKQOBNRFOBA+Bkqo^k`befaabk_v_rpebp+{65dyyL?Gy/.032-yyWy5-4y
K>k`fbkqM^ka^obkTlla`rqqboyKyQ^ihqlDelpqivM^ka^obk@o^cqpj^k%12+1)05+/&kb^oqebE^icefiiJ^ohbq+yyKM@y31.6.yyWy5-4y
K@^`eblcMficbobaDllapyKy%10+2)04+1&kb^oqebE^icefiiJ^ohbq+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0316yyWy5-4y
K>k`fbkqM^ka^obkCfpefkd@e^ojyKyQ^ihqlDelpqivM^ka^obkCfpeboj^k%13+5)/1+3&kloqelc@^qq^fiI^hb+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyKM@y31--1yyWy5-4y

OQebSbfibaPq^foyKyQo^sbiqlQebSbfibaPq^fo%21+4)4.+0&yyWy540y
KClodlqqbkIl`h_luyKyPb`lkacilloQ^sboklcqebJfpqp%21+4)4.+0&+{.-dyyL?Gy/.10/2yyWy540y
KQebE^jjbolcCliivyKyLkqlmlcJ^plk$pCliiv%34+3)45+1&%4-+1)43+/&%4/+0)43+0&%40+-)46+.&%41+6)43+2&+Sbkalopclo.--dyyL?Gy/.0512yyWy540y

OHrk*I^fPrjjfqyKyQo^sbiqlHrk*I^fPrjjfq%41+4)41+6&yyWy5-6y
KPmofqb$p@ilqe@ebpqyKyIl`^qbafkqeb`^sbKloqelcFkhdfiiJbob%41+4)41+6&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.042.yyWy5-6y
KPqroavV^rkdliPmb^oyKyPq^pelcV^rkdliTb^mlkp%4.+/)3/+3&%4-+-)30+5&+?l>Mlib^oj+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.051/yyWy5-6y
KQboo^`lqq^Eb^ayKyQboo^`lqq^orfkp+%26+/)40+-&%24+-)42+2&Sbkalopclo.--+yyL?Gy/.045/yyWy5-6y
KElwbkT^oofloPmb^oyKyIl`^qbafkqeb`^sb%2/+5)4.+0&%2.+2)41+-&?l>Mlib^oj+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0435yyWy5-6y
KJl*Jl$pQob^prob@ebpqyKy?befkaJl*Jl%14+-)40+-&+{6dyyL?Gy/.11-4yyWy5-6y
KIlpq>asbkqrobo$p?bilkdfkdpyKyFkqebqbkq%03+-)46+-&+{64dyyL?Gy/.0441yyWy5-6y
KElwbkQob^prob@^`ebyKyFkqeb`^sb%16+1)26+1&+{.--dyyL?Gy/.0436yyWy5-6y
KColwbkQo^fiM^`hboyKy?^`hlcqeb`^sb%04+2)44+6&%02+/)43+1&+@lrkqpqlt^oapIlpq^kaClrka^`efbsbjbkqyyKM@y31//4yyWy5-6y
KQ^_ibqlcObkVrkyKyQlmlcJlrkqKbsbobpq)_vqebIlobt^ihbo$pPeofkb%11+4)2/+1&+Qb^`ebpqebob`fmbXClroPbkpbp?obtZ+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.042-yyWy5-6y
KOfhhqfh$pQf`hObjlsboyKyClrkafkOfhhqfh$pQfkv@ebpq%2/+3)2.+2&+Sbkalopclo.-2dyyL?Gy/.0460yyWy5-6y
KPqlibkPmofqbQob^probyKyClrkafkqeb_^`hlcEltifkdtfka@^sbok%26+0)2/+5&%23+0)2.+2&+{.-1dyyL?Gy/.044-yyWy5-6y
K>k`fbkqJldrQ^_ibqyKyIl`^qbalkqebM^qelc@lknrbolop_befkaqebofdeqpq^qrbfkqeb`^sb+%31+/)12+.&+Sbkalopclo62dyyL?Gy/.1105yyWy5-6y
KPq^qrblcUrbkyKy?lqqljlcqebi^hbplrqelcWlr`efkSfii^db+%4/+-)00+6&+Sbkalopclo.--dyyL?Gy/.044.yyWy5-6y

OQltkilkdPqbmmbpyKyQo^sbiqlQltkilkdPqbmmbp%3/+5)01+.&yyWy5.-y
K>_^kalkba@o^qblcDllapyKyFkpfab^_rokfkdqbkq%3/+5)01+.&fkPbombkq$pPmfkb+{.--dyyL?Gy/.063.yyWy5.-y
KV^rkdliCfob@^oofboyKyCfob@^jmLpri)_vHr*Qlkd+%33+0)11+4&%33+5)15+-&+?l>J^`b+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.063-yyWy5.-y
KE^oabkbaP^mlcHof$sbppyKyOllqplcqebdf^kqqobbHof$sbpp%2/+5)23+/&%22+2)3.+-&%22+3)21+.&+Sbkalopclo..-dyyL?Gy/.0626yyWy5.-y
KCo^djbkqlcAob^ayKyFk^`^sbqlqebtbpqlcKfwf^lQbjmib%22+6)31+6&%15+/)56+-&%03+6)54+3&%02+5)30+0&+Sbkalopclo6-dyyL?Gy/.0623yyWy5.-y
KColwbkQo^fiM^`hboyKyClrkafk`^sb%04+2)45+-&%02+/)43+0&+{.-0dyyKM@y31//4yyWy5.-y
K>j_boBk`^pbaJlqeyKyArphifdeqEliilt%32+5)53+.&+Sbkalopclo.-2dyyL?Gy/.0511yyWy5.-y

OAob^aT^pqbpyKyQo^sbiqlqebAob^aT^pqbp%00+-)0-+.&yyWy525y
KIr`fa>jribqlcqeb>dfibJfkayKy>j_boBk`^pbaKb`hi^`b%00+-)0-+.&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.063.yyWy525y
K?i^ablcqebMlfplkbaJfkayKyKb^oqebjlrqelcqeb`^sb%/5+5)1.+6&+?l>Lkb*E^kabaPtloa+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.064/yyWy525y
K?illapl^hba@efqfkCo^djbkqyKyJrohp`^ibDolqql%/2+6)2-+0&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.064-yyWy525y
KAfppb`qlo$pPq^cclcJrq^qflkyKyW^k$sbpp%0-+/)6-+5&?l>pq^cc+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0636yyWy525y
KJ^kfmri^qlo$pQ^ifpj^kyKyQ^ihqlqebO^m^k^Tebih%1/+-)3/+/&%1/+/)30+3&%1.+3)31+3&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyKM@y3222/yyWy525y
KPt^ojfkd@ib^sbolcH^$olwyKy%23+5)44+3&?l>/*e^kabaptloa+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0635yyWy525y
K?i^ablcqebMofjbyKyPqf`hfkdlrqlc^`^sbt^iifkqebplrqe+%33+5)30+5&?l>ptloa+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0634yyWy525y
KPt^ojhbbmbo$pJba^iiflkyKyClrka^qArphollqCbk%21+/)23+1&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.064.yyWy525y
KJ^ifh$pPq^it^oqPmb^oyKyClrka^qqebt^vmlfkq%15+4)0-+-&+?l>mlib^oj+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.0631yyWy525y
KTfka*Ob^sbo$pA^ddbolcNrf`hPqofhbpyKyClrka^qqeb_lqqljlcqebmfii^o%4.+5)03+.&+@lrkqpqlt^oaIlpq^kaClrka>`efbsbjbkqpyyL?Gy/.063/yyWy525y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
