local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Sporeggar_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Burning Crusade Reputation|r ", "Sporeggar Reputation (62+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsbo^iiqebnrbpqpkbbabaqldbqBu^iqbatfqePmlobdd^o+Lk`b^iiqebnrbpqp^obalkbclo^m^oqf`ri^oc^`qflk)qebkfpgrpqdofkafkdlrqqebobmb^q^_ibarkdblkp,qrok*fkpqldbqqlBu^iqba+Qefpdrfab^pprjbpqe^qvlr^obibsbi5-)_rqqefp`^k_balkb^qibsbi4-^ptbii)fqtfiigrpqq^hbjr`eilkdboql`ljmibqb+y
KIltIbsbiNrbpqpyKyJ^hbprobvlr^obqo^hfkdiltibsbinrbpqpqlj^hbfqb^pfboqlpbbqebnrbpqpdfsbop+y

OW^kd^oj^opeyKyQo^sbiqlW^kd^j^ope%5/)60&yyWy134y

>QebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406yyWy134yyKM@y.46/0y
>K^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410yyWy134yyKM@y.46/0y
@QebPmlobifkdp$MifdeqyKyIllq.-XJ^qrobPmlobP^`pZtef`e`^k_bclrka^iilsboqebPmt^kfkdDibk%.3)3-&yyNFAy6406yyWy134yyL?Gy36..y
@K^qro^iBkbjfbpyKyHfiiqeb?ldIloap^qqebPm^tkfkdDibk%.2)3-&clo3X?ldIloaQbkaofipZyyNFAy6410yyWy134yyKM@y.5./2).62.6y
QQebPmlobifkdp$MifdeqyKyC^eppk%.6)31&yyNFAy6406yyWy134yyKM@y.46/0y
QK^qro^iBkbjfbpyKyC^eppk%.6)31&yyNFAy6410yyWy134yyKM@y.46/0y

KKbrqo^itfqePmlobdd^oyKyJ^hbprobvlr^obKbrqo^itfqePmlobdd^o)lqebotfpb`lkqfkrbd^qebofkdXJ^qrobPmlobP^`pZlohfiifkd?ldIloaprkqfivlr^ob+yyNFAy66.6y

>Pmlobdd^oyKyC^eppk%.6)31&yyNFAy66.6yyWy134yyKM@y.46/0y
QPmlobdd^oyKyJppef$ck)fkPmlobdd^o)grpqkloqe*b^pqlcqebPm^tkfkdDibk%.6)2.&yyNFAy66.6yyWy134yyKM@y.46/1y
>Dilt`^mJrpeolljpyKyJppef$ck%.6)2.&yyNFAy65-5yyWy134yyKM@y.46/1y
@Dilt`^mJrpeolljpyKyD^qebo.-XDilt`^mpZtef`e`^k_bclrka^iilsboW^kd^oj^ope)alqov%0-)02&fcvlre^sbmol_ibjpcfkafkdqebjyyNFAy65-5yyWy134yyL?Gy3541y
QDilt`^mJrpeolljpyKyJppef$ck%.6)2.&yyNFAy65-5yyWy134yyKM@y.46/1y
>CboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3yyWy134yyKM@y.46/2y
KXCboqfibPmlobpZyQyyKyD^qebo3XCboqfibPmlobZfcvlrafak$qe^sbqebj^iob^av+Qebvaolmlccpmlob_^qp^kaj^opet^ihbopyyNFAy65-3yyWy134yyKM@y.5./6).5.01).5./5).5.02y
QCboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-3yyWy134yyKM@y.46/2y

KCofbkaiv*Pmlobdd^oyKy@ljmibqbbsbovobmb^q^_ibvlr`^krkqfivlr$obcofbkaiv+Vlr`^kqrokfkXDilt`^mpZ)X?ldIloaQbkaofipZ^kaXJ^qrobPmlobp^`pZ+>iiqebpbobmb^qpbkalk`bvlr$obcofbkaiv)plrpbqebjtefibvlr`^kyyNFAy64/3yyWy134y

>KltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3yyWy134yyKM@y.4523y
>?ofkdJb>Peor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.2yyWy134yyKM@y.4523y
@KltQe^qTb$obCofbkap+++yKyHfii./?illap`^ibPi^sbaofsbop^ka3?illap`^ibBk`e^kqobppbp%/.)1.&%/4)1/&)^kaqebkobqrokqlDwerk$qq+yyNFAy64/3yyWy134yyKM@y.5-56).5-55y
@?ofkdJb>Peor__bovyKy@liib`q2XP^kdrfkbEf_fp`rpZ^kaobqrokqebjqlDwerk$qq^qPmlobdd^ofkW^kd^oj^ope+Qebpb^obclrkafkQebRkabo_ld%2-+0)1.+.&yyNFAy64.2yyWy134yyL?Gy2-0.y
QKltQe^qTb$obCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/3yyWy134yyKM@y.4523y
Q?ofkdJb>Peor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.2yyWy134yyKM@y.4523y

K@lkqfkrb++yKytfqeqebcliiltfkdobmb^q^_ibnrbpqrkqfiBu^iqba+y
>KltQe^qTb$obPqfiiCofbkap+++yKyDwerk$qq%.6+2)2-+.&yyNFAy64/4yyWy134yyKM@y.4523y
>?ofkdJb>klqeboPeor__bovyKyDwerk$qq%.6+2)2-+.&yyNFAy64.1yyWy134yyKM@y.4523y
>JlobCboqfibPmlobpyKyDpe^cc%.6+/)16+2&yyNFAy65-4yyWy134yyKM@y.46/2y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
