local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Tabards_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Tabard Locations", nil, "Alliance", "A", nil, function()
return [[
AAA

KQ^_^oaDrfabyKyQefpdrfabfp^pqf`hvco^jbdrfab+Qlrpbqefpdrfab)lmbkqebi^odbco^jb^karpbqebpb^o`ecb^qrobqlcfkaqebQ^_^oavlr^obillhfkdclo)qebkPefcq*Ibcq@if`hlkqe^qpqbmclob^`eQ^_^oa+yyKQy
K>ialoQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeQeb>ialo).dyyWy0-.yyKM@y2.60y
K>o^qelo?^qqibQ^_^oayQ>?yyKyCfbiaJ^ope^iLpifdeq%1-+-)13+5&)Obt^oaclonrbpq@lkqoliCfsb?^pbp)MSMyyNFAy5..2yyWy.3yyKM@y.1650y
K>odbkq@orp^abo$pQ^_^oayQ>?yyKyA^jbBskfhfH^mp^ifp%36+1)/0+/&)Bu^iqba>odbkq@e^jmflklcqeb>iif^k`b)2-@e^jmflkPb^ipyyWy16/yyKM@y01552y
K?^o^afk$pT^oabkpQ^_^oayQ>?yyKyNr^oqboj^pqbo?o^wfb%4/+3)3/+3&)Bu^iqba?^o^afk$pT^oabkp)1-Qli?^o^a@ljjbka^qflkpyyWy4-5yyKM@y140/5y
K@bk^oflkBumbafqflkQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqe@bk^oflkBumbafqflk).dyyWy0-.yyKM@y2.60y
K@lkploqfrjQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeQeb@lkploqfrj).dyyWy0-.yyKM@y2.60y
KA^ok^pprpQ^_^oayQ>?yyKyJllkMofbpqbppI^p^o^%03+3)16+-&)CofbkaivtfqeA^ok^pprp).-pyyWy05.yyKM@y2-0-2y
KBula^oQ^_^oayQ>?yyKyH^ar%21+3)03+5&)CofbkaivtfqeQebBula^o).-pyyWy14.yyKM@y2-0-3y
KDfikb^pQ^_^oayQ>?yyKyIloa@^kaobk%03+3)16+-&)CofbkaivtfqeDfikb^p).-pyyWy05.yyKM@y2-0-4y
KDkljbobd^kQ^_^oayQ>?yyKyJ^pqboQfkhboQofkf%23+/)14+5&)CofbkaivtfqeDkljbobd^k).-pyyWy01.yyKM@y2-0-5y
KDobbkQolmevQ^_^oalcqebFiifa^ofyQ>?yyKyClrkafkNrbpqObt^oaXLccbofkdlcqebPe^$q^oZ+Nrbpq`e^fkpq^oqpcoljXQebGlrok^ilcS^i$w^obnZ)aolmmbacoljS^i$w^obnqeb@lknrbolo%2.+/)25+5&%2/+5)35+5&yyWy140yyKM@y/.646y
KDrfiaQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&yyWy0-.yyKM@y2.60y
KElkloEliaQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeElkloElia).dyyWy0-.yyKM@y2.60y
KFolkclodbQ^_^oayQ>?yyKy@^mq^fkPqlkbebij%23+/)14+5&)CofbkaivtfqeFolkclodb).-pyyWy01.yyKM@y2-0-6y
KHbbmboplcQfjbQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeQebHbbmboplcQfjb).dyyWy0-.yyKM@y2.60y
KHkfdeq$p@lilopyQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)MsM).--ElkloMlfkqpyyWy0-.yyKM@y2.60y
KHrobk^fQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeQebHrobk^f).dyyWy0-.yyKM@y2.60y
KIlobj^pqbo$p@lilopyQ>?yyKyObt^oacloIlobj^pqbo>`efbsbjbkqy
KIltbo@fqvQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeIltbo@fqv).dyyWy0-.yyKM@y2.60y
KLdof$i^Q^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeLdof$i^).->mbufpPe^oapyyWy0-.yyKM@y2.60y
KMofs^qb$pQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)MsM)2-ElkloMlfkqpyyWy0-.yyKM@y2.60y
KMromibQolmevQ^_^oalcqebFiifa^ofyQ>?yyKyClrkafkNrbpqObt^oaXLccbofkdlcqebPe^$q^oZ+Nrbpq`e^fkpq^oqpcoljXQebGlrok^ilcS^i$w^obnZ)aolmmbacoljS^i$w^obnqeb@lknrbolo%2.+/)25+5&%2/+5)35+5&yyWy140yyKM@y/.646y
KObibkqibppDi^af^qlo$pQ^_^oayQ>?yyKyL_q^fkbacolje^sfkd^k^obk^O^qfkdlc/0--(%MSM&y
KP`ovbopQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeQebP`ovbop).dyyWy0-.yyKM@y2.60y
KPe^$q^oQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeQebPe^$q^o).dyyWy0-.yyKM@y2.60y
KPfisbo@lsbk^kqQ^_^oayQ>?yyKyEfobkIlobplkd%43+/).6+3&)Bu^iqbatfqePfisbo@lsbk^kq)2-@e^jmflk$pPb^ipyyWy16/yyKM@y0155.y
KPfisbotfkd?^qqibQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)MsM)/-26ElkloMlfkqpyyWy0-.yyKM@y2.60y
KPhvdr^oaQ^_^oayQ>?yyKyDobii^%31+0)33+0&)Bu^iqbatfqePe^$q^ofPhvdr^oa).dyyWy145yyKM@y/0034y
KPmlobdd^oQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqePmlobdd^o).-Dilt`^mpyyWy0-.yyKM@y2.60y
KPqlojmfhb?^qqibQ^_^oayQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)MsM)/346ElkloMlfkqpyyWy0-.yyKM@y2.60y
KPqlojtfkaQ^_^oayQ>?yyKy@^mq^fkI^k`vObspelk%34+3)4/+5&)CofbkaivtfqePqlojtfka@fqv).-pyyWy0-.yyKM@y16544y
KQ^_^oalc?orqbClo`byQ>?yyKyObt^oaclo?orq^iivAbaf`^qba>`efbsbjbkq%MSM&y
KQ^_^oalc@lknrbpqyQ>?yyKyObt^oacloJ^pqbolcFpiblc@lknrbpq>`efbsbjbkqy
KQ^_^oalcO^jh^ebkyQ>?yyKy?i^`hpjfqe>_^pf%21+-)00+/&)CofbkaivtfqeO^jh^ebk).dyyWy4/-yyKM@y153.4y
KQ^_^oalcPrjjboCi^jbpyQ>?yyKyNrbpqobt^oaclo`ljmibqfkdPe^oaplc>erkb)nrbpqpq^oqpcoljXPe^oaplc>erkbZ)tef`efpaolmmbacolj>erkbfkPi^sbMbkparofkdqebJfaprjjboCbpqfs^iTloiaBsbkq+y
KQ^_^oalcPrjjboPhfbpyQ>?yyKyNrbpqobt^oaclo`ljmibqfkdPe^oaplc>erkb)nrbpqpq^oqpcoljXPe^oaplc>erkbZ)tef`efpaolmmbacolj>erkbfkPi^sbMbkparofkdqebJfaprjjboCbpqfs^iTloiaBsbkq+y
KQ^_^oalcqeb>`efbsboyQ>?yyKyObt^oacloQtbkqv*CfsbQ^_^oap>`efbsbjbkqy
KQ^_^oalcqeb>odbkq@orp^abyQ>?yyKySbqbo^k@orp^abo>ifl`e^Pbd^oa%54+3)42+3&)CofbkaivtfqeQeb>odbkq@orp^ab).dyyWy16/yyKM@y0-10.y
KQ^_^oalcqebB^oqebkOfkdyQ>?yyKyMolsfpflkbo>olh%16+-)1/+-&)CofbkaivtfqeqebB^qebokOfkd).dyyWy3.2yyKM@y2-0/1y
KQ^_^oalcqebB_lk?i^abyQ>?yyKyAr`ebppJvku%10+1)/-+3&)CofbkaivtfqeqebB_lk?i^ab).dyyWy16/yyKM@y0/205y
KQ^_^oalcqebBumiloboyQ>?yyKyObt^oacloBumilobKloqeobka>`efbsbjbkqy
KQ^_^oalcqebDr^oaf^kplcEvg^iyQ>?yyKyMolsfpflkboTefqb`ilra%3/+5)/0+5&)CofbkaivtfqeqebDr^oaf^kplcEvg^i).dyyWy3-3yyKM@y2-0.1y
KQ^_^oalcqebE^kayQ>?yyKyNrbpqobt^oacloQebRktofqqbkMolmeb`v+Nrbpq`e^fkpq^oqp^qAbjlifqflkfpqIbdlpl%0-+5)13+3&yyNFAy6426yyWy143yyKM@y.465/yyOyAo^bkbfy
KQ^_^oalcqebHfofkQloyQ>?yyKy>o`ej^db>is^ob^ru%/2+2)14+5&)CofbkaivtfqeqebHfofkQlo).dyyWy2-1yyKM@y0//54y
KQ^_^oalcqebP`^oibq@orp^abyQ>?yyKyAolmpcoljP`^oibqQo^fkbbfkP`^oibqJlk^pqbov*>ojlov+Qebpb^obqebKM@$pqe^qpm^tk^cqboEbolafpabcb^qba+yyWy/-yyKM@y3242y
KQ^_^oalcqebPe^qqbobaPrkyQ>?yyKyOb_b``^I^rdeifk%31+-)44+/&)Bu^iqbatfqeqebPe^qqbobaPrkLccbkpfsb).dyyWy0-.yyKM@y2.60y
KQ^_^oalcqebTfiae^jjbo@i^kyQ>?yyKy@o^tJ^`Do^t%15+3)0-+3&)CofbkaivtfqeQebTfiae^jjbo@i^k).dyyWy4--yyKM@y16053y
KQ^_^oalcqebTvojobpq>``loayQ>?yyKy@fbipqo^pw^%26+5)20+-&)Bu^iqbatfqeTvojobpq>``loa).dyyWy155yyKM@y0/200y
KQ^_^oalcQebo^w^kbyQ>?yyKyA$iljqeb@liib`qlo%23+5).0+/&)CofbkaivtfqeQebo^w^kb).dyyWy31-yyKM@y121-5y
KTo^qecriDi^af^qlo$pQ^_^oayQ>?yyKyKlilkdbo^s^fi^_ibfk*d^jb+yyWy.3.yyKM@y/-/45y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
