local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Well_Read_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Well Read Achievement (70+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob^qib^pq4-+Pljblcqebpb_llhp^obfkelpqfibwlkbplofkpq^k`bp+y

OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%51+3)/3+-&yy>FAy./11yy>@y1-yyWy0-.y
RQebH^ialobf^kaqebTbiilcBqbokfqvyKy%51+3)/3+-&Kbuqql^mfii^olkqebofdeq^pvlrbkqboqebOlv^iIf_o^ov+yy>FAy./11yy>@y/6yyWy0-.y
RQeb>iif^k`blcIloa^bolkyKy%52+.)/3+/&Lkqebq^_ibqlqebofdeq^pvlrbkqboqebif_o^ov+yy>FAy./11yy>@y/.yyWy0-.y
RQebDr^oaf^kplcQfofpc^iyKy%52+.)/3+/&P^jbQ^_ib+yy>FAy./11yy>@y/4yyWy0-.y
R>cqboj^qelcqebPb`lkaT^oyKy%52+.)/3+/&P^jbQ^_ib+yy>FAy./11yy>@y/yyWy0-.y
RQebKbtEloabyKy%53+.)/2+1&Kb^oqebmfii^oqlqebibcqlcqeb>o`e^blildvQo^fkbo+yy>FAy./11yy>@y0/yyWy0-.y
R>bdtvkk^kaqebAo^dlkErkqyKy%52+5)/0+3&Kbuqqlqebmfii^ofkqeb_^`hlcqebIf_o^ov+yy>FAy./11yy>@y.yyWy0-.y
RQebTloiaQobb^kaqebBjbo^iaAob^jyKy%52+1)/0+0&Lkqebq^_ibfkqeb_^`h`lokbolcIf_o^ov+yy>FAy./11yy>@y06yyWy0-.y
RQebT^olcqeb>k`fbkqpyKy%52+1)/0+0&Lkqebq^_ibfkqeb_^`h`lokbolcIf_o^ov+yy>FAy./11yy>@y05yyWy0-.y
R@fsfiT^ofkqebMi^drbi^kapyKy%51+6)/0+1&Kb^omfii^o+yy>FAy./11yy>@y4yyWy0-.y
RQebA^ohMloq^i^kaqebC^iilcPqlojtfkayKyT^oOllj%53+4)02+5&yy>FAy./11yy>@y/2yyWy0-.y
RT^olcqebPmfaboyKyT^oOllj%53+4)02+5&yy>FAy./11yy>@y1-yyWy0-.y

OA^ohpefobyKyQo^sbiqlA^ohpefob%4/+.)13+3&yy>FAy./11yy>@y/3yyWy01y
RQeb?foqelcqebIf`eHfkdyKyFkqebqltke^ii%4/+.)13+3&yy>FAy./11yy>@y/1yyWy01y
RHfi$g^babk^kaqebPe^altM^`qyKyPb`lkacillolcqebFkk%41+/)12+0&yy>FAy./11yy>@y.0yyWy01y
RQebClrkafkdlcNrbi$Qe^i^pyKyPb`lkacillolcqebFkk%40+4)12+.&yy>FAy./11yy>@y/3yyWy01y

OFolkclodbyKyQo^sbiqlFolkclodb%41+6)5+5&yyWy01.yy>FAy./11yy>@y00y
RFolkclodb*qeb>t^hbkfkdlcqebAt^osbpyKy%41+6)5+5&)Eb^afkd@il`htfpb^olrkaollj+yy>FAy./11yy>@y..yyWy01.y
RT^olcqebQeobbE^jjbopyKy%41+6)5+5&yy>FAy./11yy>@y1.yyWy01.y
R>o^qelo^kaqebQoliiT^opyKy%44+/)6+/&yy>FAy./11yy>@y0yyWy01.y
ROfpblcqebEloabyKy%43+6)./+2&yy>FAy./11yy>@y.5yyWy01.y
RQeb?^qqiblcDofj?^qliyKyQ^_ibfk`bkqbolcollj%42+5).-+4&yy>FAy./11yy>@y//yyWy01.y
RQebLiaDlap^kaqebLoabofkdlc>wbolqeyKy%42+5).-+4&yy>FAy./11yy>@y00yyWy01.y

OQebip^j^oyKyQo^sbiqlQebip^j^o%04)14&fkIl`eJla^kyyWy02yy>FAy./11yy>@y0-y
RQebI^pqDr^oaf^kyKy%04+/)14+-&Altkpq^foplkq^_ibkbuqql_ba+yy>FAy./11yy>@y0-yyWy02y

OP`elilj^k`byKyNrbrbloQo^sbiqlP`elilj^k`b%36+.)40+.&yyWy//yy>FAy./11yy>@y/5y
KQebFks^pflklcAo^bkloyKyClrkafkqebolljtfqeIfif^kSlpp%23+3)1.+/&yyWy565/yy>FAy./11yy>@y/5y

OPqo^qelijbyKyNrbrbloQo^sbiqlPqo^qelijb%/3+6)..+5&yyWy/0yy>FAy./11yy>@y./y
RQebPbsbkHfkdaljpyKy%0-+2)1-+4&yy>FAy./11yy>@y03yyWy432.y
RHfi$g^babk^kaqebPe^altM^`qyKy%0-+2)1-+4&yy>FAy./11yy>@y.0yyWy432.y
RT^olcqebPmfaboyKy%/2+5)4.+2&yy>FAy./11yy>@y1-yyWy432.y
RQebIf`eHfkdQofrjme^kqyKy%/2+2)4-+3&yy>FAy./11yy>@y0.yyWy432.y
RF`b`oltk^kaqebColwbkQeolkbyKy%/2+5)4.+2&yy>FAy./11yy>@y.-yyWy432.y
RHbi$Qerw^a^kaqebClojfkdlcqebP`lrodbyKy%/2+2)4-+1&yy>FAy./11yy>@y./yyWy432.y

OA^ok^pprpyKyQo^sbiqlA^ok^pprp%3.+6)41+4&yyWy05.yy>FAy./11yy>@y.5y
RQeb?bqo^vbo>p`bka^kqyKy%3.+6)41+4&Lkqebaobppbo+yy>FAy./11yy>@y/0yyWy05.y
ROfpblcqeb?illaBisbpyKy%2-+-)00+2&Lkqebq^_ib+yy>FAy./11yy>@y.5yyWy05.y

OO^q`ebqyKyQo^sbiqlO^q`ebq%35+1)36+.&yyWy..yy>FAy./11yy>@y.1y
R@e^odblcqebAo^dlkcifdeqpyKyKb^oD^wiltb%35+1)36+.&O^`ebqyy>FAy./11yy>@y3yyWy..y
R>o`efjlkab$pObqrok^kaqebCifdeqqlH^ifjaloyKyKb^oIfsOfwwibcfu%35+-)40+2&O^`ebqyy>FAy./11yy>@y1yyWy..y
RBufiblcqebEfdeBisbpyKyPb`lkacillo_^i`lkvlcG^wwfh$pDbkbo^iDllapkbuqqlFkk%34+.)40+1&O^`ebqyy>FAy./11yy>@y6yyWy..y
RP^odbo^p^kaqeb?bqo^v^iyKyQebFkk%34+-)42+-&O^`ebqyy>FAy./11yy>@y.6yyWy..y
RJlrkqEvg^i^kaFiifa^k$pDfcqyKyQebFkk%33+6)41+4&O^`ebqyy>FAy./11yy>@y.2yyWy..y
RIbqe^odvlcqebLo`pyKy%32+2)13+4&Lk^`e^fofkpfabqebrmmbojlpqqltbofkKloqet^q`eEliayy>FAy./11yy>@y.1yyWy3-4y

OD^adbqw^kyKyQo^sbiqlD^adbqw^k%2/+-)/5+-&yy>FAy./11yy>@y.3yyWy.3.y
RLiaE^qobap*Qeb@lilkfw^qflklcH^ifjaloyKyKb^oqebclodb%2.+-)0-+0&yy>FAy./11yy>@y.3yyWy.3.y

O?llqv?^vyKyQo^sbiql?llqv?^v%1/)40&yyWy340yy>FAy./11yy>@y2y
RBjmfobp$C^iiyKyDlAltkqebo^jmqlqeb_lqqljibsbilc?llqv?^v^kabkqboqeb^iibvlkqebibcq)qebkbkqboqeb_rfiafkdlkqebofdeq+%1/+.)40+5&?llhpebiclkIbcq^pvlrbkqboollj+yy>FAy./11yy>@y5yyWy340y
RQebQtfkBjmfobpyKy%1/+.)40+5&P^jb_llhpebic+yy>FAy./11yy>@y04yyWy340y
RTo^qelcPlrici^vboyKy%1/+.)40+5&P^jb_llhpebic+yy>FAy./11yy>@y1/yyWy340y
RQebP`lrodblcIloa^bolkyKy%1.+6)40+1&Lk?llhpebic^`olppollj+yy>FAy./11yy>@y01yyWy340y
RQebPbkqfkbip^kaqebIlkdSfdfiyKy%1/+/)40+3&Ib^sb_rfiafkdqebt^vvlr`^jbfk)^kabkqboqeb_rfiafkd^`olppqeb^iibv+@ifj_qlsbovqlm^kaork^`olpp_ofadb+Qlmcillokbuqqlqeb_ba+yy>FAy./11yy>@y02yyWy340y
RPrktbii*QebC^iilcNrbi$Qe^i^pyKy%1.+-)41+1&?llqv?^v+Pb`lkacillolcfkklk^q^_ib+yy>FAy./11yy>@y/-yyWy340y
R?bvlkaqebA^ohMloq^iyKy%1-+3)40+5&?llqv?^v+Qlmcillolcfkklkq^_ibkbuqqlpqlsb+yy>FAy./11yy>@y2yyWy340y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
