local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Alliance_En_Wintersaber_A")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Classic Reputation|r ", "Wintersaber (55+)", nil, "Alliance", "A", nil, function()
return [[
AAA

KIltIbsbiNrbpqyKyFcvlr^obfkvlro4-$plo^q5-)qefpnrbpqtfii_b^iltibsbinrbpqclovlr)qroklkvlroiltibsbinrbpqqo^`hfkdql_b^_ibqlpbbqebnrbpqlkvlrojfkfj^m+yyNFAy/6-01y

OTfkqbopmofkdyKyQo^sbiqlTfkqbopmofkdyyNFAy/6-0/yyWy/5.y
>DbqQebjTefibQebv$obVlrkdyKyOfsbokColpqtfka%13+3).4+3&yyNFAy/6-0/yyWy/5.yyKM@y.-3.5y
KD^qeboColpqp^_bo@r_pyQyyKyD^qebo5Colpqp^_bo@r_pcoljqebabkp%13+.).5+3&%12+2).6+3&%13+/).3+2&%11+6).2+2&%13+1).1+1&%16+-).4+-&%15+4).6+1&^olrkaColpqp^_boOl`h+yyNFAy/6-0/yyWy/5.yyKM@y2.35.y
QDbqQebjTefibQebv$obVlrkdyKyOfsbokColpqtfka%13+3).4+3&yyNFAy/6-0/yyWy/5.yyKM@y.-3.5y

>QebvDoltRmPlC^pqyKyOfsbokColpqtfka%13+3).4+3&yyNFAy/6-01yyWy/5.yyKM@y.-3.5y

RTfkqbopmofkd@r_yKyPrjjlkvlroTfkqbopmofkd@r_+@^klkiv_bprjjlkbafkTfkqbopmofkd+yyRy35313yyWy/5.y

K>``bmqqebA^fivyKy>``bmqqebA^fivNrbpqcoljvlroTfkqbopmofkd@r_)qebkqf`hqefppqbm+yyWy/5.y
>>@r_$p@o^sfkdpyLyyKyTfkqbopmofkd@r_yyNFAy/6-02yyAyyKM@y2.344y
>>@r_$p@o^sfkdpyLyyKyTfkqbopmofkd@r_yyNFAy/6-2/yyAyyKM@y2.344y
>@r_$pCfopqQlvyLyyKyTfkqbopmofkd@r_yyNFAy/6-1-yyAyyKM@y2.344y
>@r_$pCfopqQlvyLyyKyTfkqbopmofkd@r_yyNFAy/6-2.yyAyyKM@y2.344y
>$?looltfkd$ColjqebTfkqboc^iiyLyyKyTfkqbopmofkd@r_yyNFAy/6-04yyAyyKM@y2.344y
>$?looltfkd$ColjqebTfkqboc^iiyLyyKyTfkqbopmofkd@r_yyNFAy/6-20yyAyyKM@y2.344y
>ErkqfkdMo^`qf`byLyyKyTfkqbopmofkd@r_yyNFAy/6-05yyAyyKM@y2.344y
>ErkqfkdMo^`qf`byLyyKyTfkqbopmofkd@r_yyNFAy/6-06yyAyyKM@y2.344y

@>@r_$p@o^sfkdpyLyyKyD^qebo3mfb`bplcPe^oaqllqeJb^qcolj^kvlcqebPe^oaqllqe_b^op%2.)0/&%26)0/&%00)24&%/4)24&fkTfkqbopmofkd^kacbbaqebjqlvlroTfkqbopmofkd@r_+yyNFAy/6-02yyAyyWy/5.yyKM@y4111)4112)4110y
@>@r_$p@o^sfkdpyLyyKyD^qebo3mfb`bplcPe^oaqllqeJb^qcolj^kvlcqebPe^oaqllqe_b^op%2.)0/&%26)0/&%00)24&%/4)24&fkTfkqbopmofkd^kacbbaqebjqlvlroTfkqbopmofkd@r_+yyNFAy/6-2/yyAyyWy/5.yyKM@y4111)4112)4110y
HLti_b^pqpyLyyQyyKy@liib`q2uXTfiahfkCb^qeboZcoljqebLti_b^pqp%26)/4&%32)0-&%33)02&yyIy3533/2yyNFAy/6-1-yyAyyWy/5.yyKM@y412-)412.y
HF`bQefpqibVbqfyLyyQyyKyHfiiF`bQefpqibVbqfpclo.XQlrdeVbqfEfabZ+yyIy35330yyNFAy/6-1-yyAyyWy/5.yyKM@y4126)413-)4125y
RXQlrdeVbqfEfabZyLyyKy@ob^qbXTfkqbopmofkd@^qQlvZ_v`lj_fkfkd2XTfiahfkCb^qeboZ^ka.XQlrdeVbqfEfabZ+yyRy35330yyNFAy/6-1-yyAyyWy/5.y
@@r_$pCfopqQlvyLyyKyRpbqebXTfkqbopmofkd@^qQlvZqlmi^vtfqevlroTfkqbopmofkd@r_yyNFAy/6-1-yyAyyWy/5.yyKM@y2.344y
HLti_b^pqpyLyyQyyKy@liib`q2uXTfiahfkCb^qeboZcoljqebLti_b^pqp%26)/4&%32)0-&%33)02&yyIy3533/2yyNFAy/6-2.yyAyyWy/5.yyKM@y412-)412.y
HF`bQefpqibVbqfyLyyQyyKyHfiiF`bQefpqibVbqfpclo.XQlrdeVbqfEfabZ+yyIy35330yyNFAy/6-2.yyAyyWy/5.yyKM@y4126)413-)4125y
RXQlrdeVbqfEfabZyLyyKy@ob^qbXTfkqbopmofkd@^qQlvZ_v`lj_fkfkd2XTfiahfkCb^qeboZ^ka.XQlrdeVbqfEfabZ+yyRy35330yyNFAy/6-2.yyAyyWy/5.y
@@r_$pCfopqQlvyLyyKyRpbqebXTfkqbopmofkd@^qQlvZqlmi^vtfqevlroTfkqbopmofkd@r_yyNFAy/6-2.yyAyyWy/5.yyKM@y2.344y
@$?looltfkd$ColjqebTfkqboc^iiyLyyKyL_q^fk3mfb`bplcXPjlhbaJb^qZcoljbfqeboTfkqboc^iicro_lid`^jm%34+5)16+-&%02+1)24+-&%/1+/)16+/&fkTfkqbopmofkd^kacbbaqebjqlvlroTfkqbopmofkd@r_+yyRy35312yyNFAy/6-04yyAyyWy/5.yyL?Gy1-6y
@$?looltfkd$ColjqebTfkqboc^iiyLyyKyL_q^fk3mfb`bplcXPjlhbaJb^qZcoljbfqeboTfkqboc^iicro_lid`^jm%34+5)16+-&%02+1)24+-&%/1+/)16+/&fkTfkqbopmofkd^kacbbaqebjqlvlroTfkqbopmofkd@r_+yyRy35312yyNFAy/6-20yyAyyWy/5.yyL?Gy1-6y
@ErkqfkdMo^`qf`byLyyKy?ofkdvlro`r_kb^opklt*`lsboba_rooltpfkkloqebokTfkqbopmofkd2qfjbpqlebimfqib^okeltqlerkq^o`qf`e^obp+yyNFAy/6-05yyAyyWy/5.y
@ErkqfkdMo^`qf`byLyyKy?ofkdvlro`r_kb^opklt*`lsboba_rooltpfkkloqebokTfkqbopmofkd2qfjbpqlebimfqib^okeltqlerkq^o`qf`e^obp+yyNFAy/6-06yyAyyWy/5.y

Q>@r_$p@o^sfkdpyLyyKyTfkqbopmofkd@r_yyNFAy/6-02yyAyyKM@y2.344y
Q>@r_$p@o^sfkdpyLyyKyTfkqbopmofkd@r_yyNFAy/6-2/yyAyyKM@y2.344y
Q@r_$pCfopqQlvyLyyKyTfkqbopmofkd@r_yyNFAy/6-1-yyAyyKM@y2.344y
Q@r_$pCfopqQlvyLyyKyTfkqbopmofkd@r_yyNFAy/6-2.yyAyyKM@y2.344y
Q$?looltfkd$ColjqebTfkqboc^iiyLyyKyTfkqbopmofkd@r_yyNFAy/6-04yyAyyKM@y2.344y
Q$?looltfkd$ColjqebTfkqboc^iiyLyyKyTfkqbopmofkd@r_yyNFAy/6-20yyAyyKM@y2.344y
QErkqfkdMo^`qf`byLyyKyTfkqbopmofkd@r_yyNFAy/6-05yyAyyKM@y2.344y
QErkqfkdMo^`qf`byLyyKyTfkqbopmofkd@r_yyNFAy/6-06yyAyyKM@y2.344y

KTfkqbopmofkd@r_TefphboyKyTebkvlre^sb`liib`qba/-XTfkqbopmofkd@r_TefphboZ)qebk`ljmibqbqebi^pqnrbpqqldbqvlroTfkqbopmofkdColpqp^_bo+y

@QebvDoltRmPlC^pqyKy/-XTfkqbopmofkd@r_TefphboZ)qebTfkqbopmofkd@r_)/-XOrkb`ilqeZ)/-XOrddbaIb^qeboZ)^ka5-dliaqlOfsbokColpqtfka%13+3).4+3&fkTfkqbopmofkdyyNFAy/6-01yyWy/-.y
QQebvDoltRmPlC^pqyKyOfsbokColpqtfka%13+3).4+3&yyNFAy/6-01yyWy/-.yyKM@y.-3.5y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
