local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Champion_of_the_Frozen_Waste_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Champion of the Frozen Waste (80+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqb@e^jmflklcqebColwbkT^pqb^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebqfqib9@e^jmflklcqebColwbkT^pqbp;+Qf`hqefppqbm+y

HP^oqe^oflkyKyAbcb^qP^oqe^oflkfkQebL_pfaf^kP^k`qrjAo^dlk_ifdeq%3-+-)23+-&yyWy155yyKM@y/553-yy>FAy.325yy>@y.y
HHbi$Qerw^ayKyAbcb^qHbi$Qerw^afkK^uuo^j^pAo^dlk_ifdeq%54+1)13+1&yyWy155yyKM@y.266-yy>FAy.325yy>@y/y
HJ^ivdlpyKyAbcb^qJ^ivdlpfkBvblcBqbokfqv?lob^kQrkao^%/5+.)/5+.&yyWy153yyKM@y/5526yy>FAy.325yy>@y0y
H>kr_$^o^hyKyAbcb^q>kr_$^o^hfkEbolf`7>wgli*Kbor_Ao^dlk_ifdeq%/3+5)15+2&yyWy155yyKM@y/6./-yy>FAy.325yy>@y1y
HPglkkfoQebFolkpe^mboyKyAbcb^qPglkkfoQebFolkpe^mbofkEbolf`7E^iiplcPqlkbQebPqlojMb^hp%11+5).1+2&yyWy162yyKM@y/4645yy>FAy.325yy>@y2y
HHbofpqo^pw^yKyAbcb^qHbofpqo^pw^fkEbolf`7QebKburp?lob^kQrkao^%/5+.)/5+.&yyWy153yyKM@y/34/0yy>FAy.325yy>@y3y
HEbo^iaSli^wgyKyAbcb^qEbo^iaSli^wgfkEbolf`7>ek$h^ebqAo^dlk_ifdeq%/3+5)15+2&yyWy155yyKM@y/60..yy>FAy.325yy>@y4y
HIlhbkyKyAbcb^qIlhbkfkEbolf`7E^iiplcIfdeqkfkdQebPqlojMb^hp%05+-).1+4&yyWy162yyKM@y/56/0yy>FAy.325yy>@y5y
HIbv*Dr^oaf^kBobdlpyKyAbcb^qIbv*Dr^oaf^kBobdlpfkEbolf`7QebL`rirp?lob^kQrkao^%/5+.)/5+.&yyWy153yyKM@y/4323yy>FAy.325yy>@y6y
HFkds^oqebMirkaboboyKyAbcb^qFkds^oqebMirkabobofkEbolf`7Rqd^oabHbbmEltifkdCgloa%25+/)15+6&yyWy16.yyKM@y/0621yy>FAy.325yy>@y.-y
HHfkdVjfolkyKyAbcb^qHfkdVjfolkfkEbolf`7Rqd^oabMfkk^`ibEltifkdCgloa%25+1)12+-&yyWy16.yyKM@y/353.yy>FAy.325yy>@y..y
HJ^i$d^kfpyKyAbcb^qJ^i$d^kfpfkEbolf`7Qeb@riifkdlcPqo^qelijbQ^k^ofp%32+5)15+6&yyWy.3.yyKM@y/3200yy>FAy.325yy>@y./y
HQebMolmebqQe^olk$g^yKyAbcb^qQebMolmebqQe^olk$g^fkEbolf`7Ao^h$Qe^olkHbbmDofwwivEfiip%.4+4)/0+0&yyWy16-yyKM@y/330/yy>FAy.325yy>@y.0y
H@v^kfdlp^yKyAbcb^q@v^kfdlp^fkEbolf`7SflibqEliaA^i^o^k%34+1)35+2&yyWy2-1yyKM@y0..01yy>FAy.325yy>@y.1y
HD^i$a^o^eyKyAbcb^qD^i$a^o^efkEbolf`7Drkao^hWri$Ao^h%5.+3)/.+0&yyWy163yyKM@y/60-3yy>FAy.325yy>@y.2y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
