local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Defender_of_a_Shattered_World_H")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Defender of a Shattered World (85+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbAbcbkabolc^Pe^qqbobaTloia^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebqfqib89Abcbkabolc^Pe^qqbobaTloia;+Qf`hqefppqbm+y

H>p`bka^kqIloaL_pfafrpyKyAbcb^q>p`bka^kqIloaL_pfafrpfkEbolf`7?i^`hol`h@^sbokp?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yyKM@y064-2yy>FAy22-3yy>@y.y
HLwrj^qyKyAbcb^qLwrj^qfkEbolf`7QeolkblcqebQfabpS^peg$fo7>_vpp^iAbmqep%4-+2)/6+6&yyWy3.1yyKM@y11233yy>FAy22-3yy>@y/y
HEfdeMofbpqbpp>wfiyKyAbcb^qEfdeMofbpqbpp>wfifkEbolf`7QebPqlkb`lobAbbmelij%13+5)16+04&yyWy31-yyKM@y1/000yy>FAy22-3yy>@y0y
H>p^^ayKyAbcb^q>p^^afkEbolf`7QebSloqbuMfkk^`ibRiarj%42+-)52+-&yyWy4/-yyKM@y10542yy>FAy22-3yy>@y1y
HBora^uyKyAbcb^qBora^ufkEbolf`7Dofj?^qliQtfifdeqEfdei^kap%.6+-)20+2&yyWy4--yyKM@y1-151yy>FAy22-3yy>@y2y
HO^geyKyAbcb^qO^gefkEbolf`7E^iiplcLofdfk^qflkRiarj%4-+-)2/+3&yyWy4/-yyKM@y06045yy>FAy22-3yy>@y3y
HPf^j^q)IloalcqebPlrqeTfkayKyAbcb^qPf^j^q)IloalcqebPlrqeTfkafkEbolf`7Ilpq@fqvlcqebQli$sfoRiarj%3.+3)36+/&yyWy4/-yyKM@y115.6yy>FAy22-3yy>@y4y
HS^kbpp^S^k@ibbcyKyAbcb^qS^kbpp^S^k@ibbcfkEbolf`7Ab^ajfkbpTbpqc^ii%10+/)4/+1&yyWy06yyKM@y1621.yy>FAy22-3yy>@y5y
HIloaDlacobvyKyAbcb^qIloaDlacobvfkEbolf`7Pe^altc^kdHbbmPfisbomfkbClobpq%12+2)34+4&yyWy/.yyKM@y13631yy>FAy22-3yy>@y6y
KQeb?^pqflklcQtfifdeqyKyAbcb^q^iiqeb_lppbpfkQeb?^pqflklcQtfifdeqQtfifdeqEfdei^kap%01+-)45+-&yyWy4--yy>FAy22-3yy>@y.-y
H>i$>hfoyKyAbcb^q^iiqebTfka?lppbp^ka>i$>hfofkQeolkblcqebClroTfkapO^faRiarj%03+0)51+5&yyWy4/-yyKM@y13420yy>FAy22-3yy>@y..y
K?i^`htfkdAbp`bkqyKyAbcb^q^iiqeb_lppbpfk?i^`htfkdAbp`bkq?rokfkdPqbmmbp%/-+2)0/+5&yyWy/6yy>FAy22-3yy>@y./y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
