local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Dragonmaw_Tour_of_Duty")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Quests|r ", "Dragonmaw Tour of Duty (84+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefp^`efbsbjbkqfpalkb^p^ibsbi51*52fkQtfifdeqEfdei^kap+Qebjl_pqe^qvlrtfiibk`lrkqbo`ljbfkm^`hplc/*1)pl_bfkdrkabo51fkklq^asfp^_ib+y

OQtfifdeqEfdei^kapyKyQo^sbiqlQtfifdeqEfdei^kap%2/+2)/5+-&yyWy4--y

HHloqe^ilkyKyPi^vHloqe^ilk%2/+2)/5+-&Ebfpaltkfkqeb@bii^o+DlfkdfkqlQerkaboj^otfiici^dvlrMSM)plqovqlpq^vlrqlcQerkaboj^o+yyWy4--yy>FAy215/yy>@y3yyKM@y14.4.y
H@ifccQerkaboj^oyKyPi^v@ifccQerkaboj^o%2.+3)/5+3&+DlfkdfkqlQerkaboj^otfiici^dvlrMSM)plqovqlpq^vlrqlcQerkaboj^o+yyWy4--yy>FAy215/yy>@y1yyKM@y13044y
HEfdePe^j^kJ^`Hfiifd^kyKyPi^vEfdePe^j^kJ^`Hfiifd^k%13+-)00+2&yyWy4--yy>FAy215/yy>@y.yyKM@y13552y
H?i^`hOb`irpbyKyPi^v?i^`hOb`irpb%13+-)0/+2&)altkfkqeb`bii^o+yyWy4--yy>FAy215/yy>@y2yyKM@y14..2y
HAfii^kJ^`EroibvyKyPi^vAfii^kJ^`Eroibv%13+1)04+/&yyWy4--yy>FAy215/yy>@y/yyKM@y13045y
HDrkt^iaDobv_b^oayKyPi^vDrkt^iaDobv_b^oa%12+0)1/+6&yyWy4--yy>FAy215/yy>@y0yyKM@y13043y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
