local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Glory_of_the_Ulduar_Raider_25_H")
function Guide:Initialize()
 function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Dungeons & Raids|r ", "Glory of the Ulduar Raider 25 (80+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabdlbplsboqeb`ofqbof^kbbabaql`ljmibqbDilovlcqebRiar^oO^fabo/2*j^k^`efbsbjbkq+Rmlk`ljmibqflk)vlrtfii_b^t^oabaqebXObfkplcqebFolk_lrkaMolql*Ao^hbZ+Qf`hqefppqbm+y

KLo_fq*r^ovyKyAbcb^qCi^jbIbsf^qe^ktfqe^ii1Lo_fq^iAbcbkpbPvpqbjp^`qfsbfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y00..0yy>FAy/625yy>@y.y
KFolkAt^oc)JbafrjO^obyKyAbcb^q/2A^ohOrkbDr^oaf^kAt^osbptfqeO^wlop`^ib$pCi^jb?ob^qefk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y00055yy>FAy/625yy>@y0y
KF@ellpbVlr)Pqbbi_ob^hboyKyAbcb^qqeb>ppbj_ivlcFolktfqePqbbi_ob^hbo^pqebi^pqjbj_bo^ifsbfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y0/534yy>FAy/625yy>@y2y
K@o^wv@^qI^avyKyAbcb^q>rof^v^tfqelrqabpqolvfkdeboP^k`qrjPbkqofbpfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y002.2yy>FAy/625yy>@y4y
KIlpbVlroFiirpflkyKyAbcb^qQelofjtefibPfcfpmobpbkqfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y0/532yy>FAy/625yy>@y6y
KCfobcfdeqboyKyAbcb^qJfjfolk^cqbo^`qfs^qfkdefpPbic*Abpqor`qjb`e^kfpjfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y0002-yy>FAy/625yy>@y..y
KLkbIfdeqfkqebA^ohkbppyKyAbcb^qVldd*P^olktfqeqeb^ppfpq^k`blclkblocbtboHbbmbopfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y00/55yy>FAy/625yy>@y.0y
KPqlhfk$qebCrok^`byKyAbcb^qFdkfpqebCrok^`bJ^pqbofk1jfkrqbpfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y00..5yy>FAy/625yy>@y/y
KEb^oq_ob^hboyKyAbcb^qUQ*--/Ab`lkpqor`qlo^cqboabpqolvfkdefpeb^oqfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y00/60yy>FAy/625yy>@y1y
KAfp^ojbayKyAbpqolv_lqelcHlild^ok$p^ojp^kaqebkHlild^okefjpbictfqefk./pb`lkapfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y0/60-yy>FAy/625yy>@y3y
KF@lriaP^vQe^qQefp@^`ebT^pO^obyKyAbcb^qElafo_bclobebpe^qqbopefpo^ob`^`ebfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y0/512yy>FAy/625yy>@y5y
KHkl`h)Hkl`h)Hkl`hlkTllayKyAbcb^qCobv^tefibib^sfkd^ii0Biabop^ifsbfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y0/6-3yy>FAy/625yy>@y.-y
KFIlsbqebPjbiilcP^olkfqbfkqebJlokfkdyKyAbcb^qDbkbo^iSbw^u^cqboabcb^qfkdqebP^olkfqb>kfjrpfk/2*mi^vbojlab+Riar^o%1.).3&yyWy162yyKM@y002/1)00/4.yy>FAy/625yy>@y./y

KDrfab@ljmibqb

]]
end) end
 
 function Guide:Unload()
 end
end
