local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Higher_Learning")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Higher Learning Achievement", nil, "Horde", "A", nil, function()
return [[
AAA

KEfdeboIb^okfkdyKyQebpb_llhp^obO>OBPM>TKPclrkafkA^i^o^k+Qebv^oblk^0*1elropm^tkqfjbo+L``^pflk^iiv)qo^pe_llhptfiipmt^kfkqebfomi^`b)plob^aqebqo^peqlobpbqqebqfjbo+?llhpabpm^tktfqefk0*1jfkrqbplk`bqebv^obob^a+Vlrjrpq_b^_ibqldbqqlA^i^o^kqlalqefp>`efbsbjbkq+Qefpfp^ipl^sfabllkqebpm^tkmlfkqpfkqebJbj_bo$p^ob^lcqebtb_pfqb+Lk`b^ii_llhp^obob^a)vlr$iidbq^klk*`lj_^qmbq)HfofkQloC^jfif^o+y

RQebP`elliplc>o`^kbJ^df`*Fkqolar`qflkyKyFkqebQbibmloq^qflkOlljlcqebSflibqD^qb+%23+2)12+4&yy>FAy.623yy>@y.yyWy2-1yyL?Gy5.00y
RQebP`elliplc>o`^kbJ^df`*FiirpflkyKyFkqeb`lokbolcqebSflibqEliakb^o>o`ej^dbQfjb^o+%31+1)2/+1&yy>FAy.623yy>@y3yyWy2-1yyL?Gy5./5y
RQebP`elliplc>o`^kbJ^df`*>_gro^qflkyKyLkqebcillolcqebA^i^o^kSfpfqlo@bkqbokb^oqebifqqibq^_ib+%2/+0)21+5&yy>FAy.623yy>@y/yyWy2-1yyL?Gy5./5y
RQebP`elliplc>o`^kbJ^df`*Bk`e^kqjbkqyKyRmpq^fop_^i`lkvlcQebQeob^aplcC^qbpelm+%10+1)13+4&yy>FAy.623yy>@y2yyWy2-1yyL?Gy5-2.y
RQebP`elliplc>o`^kbJ^df`*@lkgro^qflkyKyLkqeb_llhpebicqlqebofdeq^pvlrbkqboqebSflibq@fq^abi+%0-+5)13+.&yy>FAy.623yy>@y0yyWy2-1yyL?Gy5012y
RQebP`elliplc>o`^kbJ^df`*Afsfk^qflkyKyPb`lkacilloSflibq@fq^abi_bqtbbkqeb_llhpebisbpqlqebibcq)kb^oqebmloq^iql@^sbokplcQfjb+%/3+2)2/+/&yy>FAy.623yy>@y1yyWy2-1yyL?Gy5-2.y
RQebP`elliplc>o`^kbJ^df`*Qo^kpjrq^qflkyKyCfopqcillolcqebIbdboabj^fkIlrkdb)lkqebofdeq_llhpebickb^oqebpqlsb+%13+5)06+/&yy>FAy.623yy>@y5yyWy2-1yyL?Gy5-2.y
RQebP`elliplc>o`^kbJ^df`*Kb`olj^k`vyKyPb`lkacillolcqebIbdboabj^fkIlrkdb)lkqeb_llhpebicfkqebolljtfqe1_bap+%13+5)1-+-&yy>FAy.623yy>@y4yyWy2-1yyL?Gy5.00y

KDrfab@ljmibqb
]]
end)	end
	
	function Guide:Unload()
	end
end
