local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Misc_Achievement_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Misc Quest Achievements (45+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfabtfiidllsboqebil^`qflkp^kanrbpqkbbabacloqebcliiltfkd^`efbsbjbkqp8GlvOfab)DirqqlkcloCfbovMrkfpejbkq)DirqqlkcloF`vMrkfpejbkq)DirqqlkcloPe^altvMrkfpejbkq)^kaOb^av)Pbq)Dl^qy

eLodofjj^oyKyFkkhbbmboDovpeh^%20+4)45+5&J^hbLodofjj^ovlroeljbyyWy0/.yyKM@y36/6y

OPlrqebokOl`hbqQbojfkrpyKyQo^sbiqlqeb>wpe^o^%2-+5)41+.&fk>wpe^o^yyWy.5.yy>FAy2121y
KOfabqebOl`hbq++yKyQ^hbqebOl`hbqt^vqlqebKloqebokOl`hbqQbojfkrp%33+0)/-+1&yyWy.5.yy>FAy2121y

O>o`^kbMfkk^`ibyKyEb^aqlqeb>o`^kbMfkk^`ib%23+/)./+-&yy>FAy2115yyWy.5.y
KDirqqlkclo++yKyEbobvlrtfiialqebDirqqlkcloCfbov)F`v^kaPe^altvMrkfpejbkq>`efbsbjbkqp%clrkarkaboNrbpq*;H^ifjalofkvlro^`efbsbjbkqm^kb&+@if`hlk`loobpmlkafkd`ovpq^iqllmbkqebmloq^i)qebk`if`hlkqebmloq^iqlbkqboqebqof^i+Qebobfpklqfjbifjfq)grpqalqebqof^irkqfivlr`ljmibqbqeb^`efbsbjbkq+Qebobfp^ifkhqllrosfablplktlteb^a+`ljyy>FAy2115y
KCfbovMrkfpejbkqyKyD^fk.-pq^`hplcCfobA^k`fkdtfqelrqq^hfkda^j^db+Cliiltqeb?illaBic^mmobkqf`b)ebpbbjpql^it^vporkql^p^cb^ob^+yy>FAy2115y
KF`vMrkfpejbkqyKyD^fk/-pq^`hplcBppbk`blcF`btfqelrqq^hfkda^j^db+Orkfk^`lrkqbo`il`htfpbolq^qflkqovfkdql^slfaqebf`vjfpqcoljqebi^odblo_ptefiborkkfkdlsboqebpj^iibof`bbppbk`b+Qeborkbplkqebdolrkatfiipellqvlrfkqlqeb^fo+Qebv`^k_brpbaql^slfaqebf`vjfpq^pkbbaba+yy>FAy2213y
KPe^altvMrkfpejbkqyKyQo^m/-TbbmfkdPlriptfqelrqq^hfkda^j^db+Pq^v`ilpbqlqeb`ovpq^i^ka^kqf`fm^qbtebobqebTbbmfkdPlriptfiibjbodb_vt^q`efkdcloqeb_i^`hpe^altqo^sbifkdlkqebcillo+Qefpfp^qlrde^`efbsbjbkq+Fcvlralklqdbqfqqebcfopqqfjb^olrka)grpqob*^`qfs^qbqeb`ovpq^i^kaqov^d^fk+yy>FAy2214y

OCrpbifdeqyKyQo^sbiql?^ai^kap%32+1)02+2&yyWy.4yy>FAy2111y
>TebkqebDlfkdDbqpQlrde)@eb^qyKyD^ov^kkbCibbwib_lm%31+0)05+.&yyWy.4yyNFAy/4442yyKM@y13320y
KXFkpqor`qlo$pOlaZyQyyKyHfii^Arpq_bi`eboFkpqor`qlo^ka`liib`q^kXFkpqor`qlo$pOlaZ^q@^jmHlpe+%25+-)/2+1&yyWy.4yyNFAy/4442yyKM@y13360y
QTebkqebDlfkdDbqpQlrde)@eb^qyKyD^ov^kkbCibbwib_lm%31+0)05+.&yyWy.4yyNFAy/4442yyKM@y13320y

>Fq$pDl^qQfjb)?^_vyKyD^ov^kkbCibbwib_lm%31+0)05+.&yyNFAy/4443yyWy.4yyKM@y13320y
KOb^av)Pbq++yKyDl^qQl`ljmibqbqefp^`efbsbjbkq)hkl`h^ii./?fiivDl^qplccqeb`ifccfk.jfkrqb+Pq^oqkb^oqebcifdeqj^pqbo^kaqo^sbifk^`il`htfpbolrqb^olrkaCrpbifdeq+Qf`hqefppqbm+yyNFAy/4443yyWy.4yyKM@y13060y
RX?fiivDl^q?i^pqboZyKyRpbD^ov^kkb$pX?fiivDl^q?i^pqboZlk./?fiivDl^qpfkCrpbifdeq+yyWy.4yyRy3/064yyNFAy/4443yyKM@y13060y
QFq$pDl^qQfjb)?^_vyKyD^ov^kkbCibbwib_lm%31+0)05+.&yyWy.4yyNFAy/4443yyKM@y13320y

K?i^pqboAUyKyFcvlre^sb^iob^av`ljmibqbaqebnrbpq)alk$qcobq+vlr`^k_rv^X?fiivDl^q?i^pqboAUZcoljDfk^DlqdllapfkCrpbifdeq+Ql`ljmibqbqefp^`efbsbjbkq)hkl`h^ii./?fiivDl^qplccqeb`ifccfk.jfkrqb+Pq^oqkb^oqebcifdeqj^pqbo^kaqo^sbifk^`il`htfpbolrqb^olrkaCrpbifdeq+yy>FAy2111yyWy.4yyKM@y15-34y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
