local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Sha'tari_Skyguard_Dailies_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Burning Crusade Reputation|r ", "Sha'tari Skyguard / Ogri'la  (70+ Dailies)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQebpb^obqeba^fivnrbpqcloPe^$q^of,Ld$ofi^obm+Qebob^obpbsbo^iobmb^q^_ibnrbpqfkPhbqqfpqe^q`^k_balkb^ptbii+y

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%31+2)33+2&yyWy145y
KP^sbXPe^altArpqZyKyP^sb^qib^pq3uXPe^altArpqZcloobmqrok*fky
>CfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWy145yyAyyKM@y/0-15y
@CfobpLsboPhbqqfpyKyPbbhlrqJlkpqolrpH^ifofBddplkqebqlmplcPhbqqfpatbiifkdp^karpbqebPhvdr^oa?i^pqfkd@e^odbplkqebj+%33+1)46+/&yyNFAy..--5yyRy0/1-3yyWy145yyAyyL?Gy045y
>Bp`^mbcoljPhbqqfpyKyPhvdr^oaMofplkbo%3.+/)41+0&%36+-)41+.&%42+.)53+6&yyNFAy..-52yyWy145yyAyyKM@y/0050y
@Bp`^mbcoljPhbqqfpyKyBp`loqqebPhvdr^oaMofplkboqlp^cbqvyyNFAy..-52yyWy145yyAyyKM@y/0050y
QCfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWy145yyAyyKM@y/0-15y
QBp`^mbcoljPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..-52yyWy145yyAyyKM@y/0-15y
KXBifufolcPe^altpZyKyL_q^fkXBifufolcPe^altpZcoljPbsbofk%31+.)33+5&clo3uXPe^altArpqZyyWy145yyQyyKM@y/0-1/y

O?i^ab$pBadbJlrkq^fkpyKyQo^sbiql?i^ab$pBadbJlrkq^fkp%/4+3)2/+6&yyWy142y
>?lj_Qebj>d^fkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy..-/0yyWy142yyAyyKM@y/0./-y
>To^kdibJlob>bqeboO^vpyKyPhvdr^oaHe^qfb%/5+-)2.+1&yyNFAy..-33yyWy142yyAyyKM@y/0002y
@?lj_Qebj>d^fkyKyCivlsbo@^jm7To^qe_lj_fkdqeboba^ooltp%00)1-&)%03)06&)%01)10&yyNFAy..-/0yyWy142yyRy0/123yyAyyL?Gy4046y
@To^kdibJlob>bqeboO^vpyKyRpbqebTo^kdifkdOlmbql`^mqrob2>bqeboO^vp+yyNFAy..-33yyRy0/365yyWy142yyAyyKM@y//.5.y
Q?lj_Qebj>d^fkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy..-/0yyWy142yyAyyKM@y/0./-y
QTo^kdibJlob>bqeboO^vpyKyPhvdr^oaHe^qfb%/5+-)2.+1&yyNFAy..-33yyWy142yyAyyKM@y/0002y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
