local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Surveying_the_Damage_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Exploration|r ", "Surveying the Damage (45+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob12(+Fcvlralk$qdbqqeb^ob^prk`lsboba^qqebil`^qflkmolsfaba)jlsb^olrka^_fqfkqe^qil`^qflk)fq$pqebob+J^hbprobvlrpq^vfkqebil`^qflkilkdbklrdeqlafp`lsbofq+yy>FAy15/4y

KA^j^dbfkArolq^oyKyPlrqecrovT^qbopebafkArolq^o%03)/6&yy>FAy15/4yy>@y4yyWy1y
KA^j^dbfk>pebks^ibyKyQerkaboMb^hfk>pebks^ib%2-)24&yy>FAy15/4yy>@y3yyWy10y
KA^j^dbfkA^ohpelobyKyQebOrfkplc>r_boafkbfkA^ohpelob%05)11&yy>FAy15/4yy>@y1yyWy1/y

KA^j^dbfkPlrqebok?^oobkpyKyQeb?^qqibp`^ofkPlrqebok?^oobkp%12)32&yy>FAy15/4yy>@y.yyWy3-4y
KA^j^dbfkAbpli^`byKy@bk^oflkTfiai^kapfkAbpli^`b%23)2.&yy>FAy15/4yy>@y5yyWy.-.y
KA^j^dbfkQelrp^kaKbbaibpyKyQebPefjjbofkdAbbmfkQelrp^kaKbbaibp%40)60&yy>FAy15/4yy>@y6yyWy3.y
KA^j^dbfkQ^k^ofpyKyQebS^iibvlcqebT^q`ebopfkQ^k^ofp%04)42&yy>FAy15/4yy>@y2yyWy.3.y

OPfisbomfkbClobpqyKyQo^sbiqlPfisbomfkbClobpq%11)52&yyWy/.yy>FAy15/4y

KA^j^dbfkPfisbomfkbyKyQebDobvj^kbT^iifkPfisbomfkb%11)52&yy>FAy15/4yy>@y.-yyWy/.y
KA^j^dbfkEfiip_o^aCllqefiipyKyOrfkplcPlrqepelobfkEfiip_o^aCllqefiip%16)35&yy>FAy15/4yy>@y.0yyWy/1y
KA^j^dbfk?^ai^kapyKyQebP`^olcqebTloia_ob^hbofk?^ai^kap%0-)22&yy>FAy15/4yy>@y0yyWy.4y
KA^j^dbfkIl`eJla^kyKyQebPqlkbtolrdeqA^jfkIl`eJla^k%15).1&yy>FAy15/4yy>@y./yyWy02y
KA^j^dbfkPqo^kdibqelokyKyQebPrkabofkdfkqeb@^mblcPqo^kdibqelok%25).0&yy>FAy15/4yy>@y/yyWy340y
KA^j^dbfkTbpqc^iiyKyQebO^dfkd@e^pjfkTbpqc^ii%05)10&yy>FAy15/4yy>@y..yyWy06y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
