local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Tabards_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Tabard Locations",  nil, "Horde", "A", nil, function()
return [[
AAA

KQ^_^oaDrfabyKyQefpdrfabfp^pqf`hvco^jbdrfab+Qlrpbqefpdrfab)lmbkqebi^odbco^jb^karpbqebpb^o`ecb^qrobqlcfkaqebQ^_^oavlr^obillhfkdclo)qebkPefcq*Ibcq@if`hlkqe^qpqbmclob^`eQ^_^oa+y
K>ialoQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQeb>ialo).dyyWy0/.yyKM@y2.55y
K>odbkq@orp^abo$pQ^_^oayQ>?yyKyA^jbBskfhfH^mp^ifp%36+1)/0+/&)Bu^iqba>odbkq@e^jmflklcqebEloab)2-@e^jmflkPb^ipyyWy16/yyKM@y01552y
K?^qqibQ^_^oalcqebAbcfibopyQ>?yyKyAb^qej^pqboAtfob%35+1)0-+3&)Obt^oaclonrbpqQ^hbCfsb?^pbp>o^qef?^pfk)MSMyyNFAy5.//yyWy.3yyKM@y.2-/.y
K?fidbt^qbo@^oqbiQ^_^oayQ>?yyKyCofwwlSfii^j^o%2-+.)25+2&)CofbkaivtfqeQeb?fidbt^qbo@^oqbi).-pyyWy0/.yyKM@y2-0/0y
K?illaHkfdeqQ^_^oayQ>?yyKyM^i^afkNrbpqyy@yM^i^afky
K@bk^oflkBumbafqflkQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqe@bk^oflkBumbafqflk).dyyWy0/.yyKM@y2.55y
K@lkploqfrjQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQeb@lkploqfrj).dyyWy0/.yyKM@y2.55y
KA^ohpmb^oQ^_^oayQ>?yyKy@e^jmflkRor$wfk%2-+.)25+2&)CofbkaivtfqeA^ohpmb^oQoliip).-pyyWy0/.yyKM@y2-144y
KColpqtlic?^qqibQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)MsM)/346ElkloMlfkqpyyWy0/.yyKM@y2.55y
KDobbkQolmevQ^_^oalcqebFiifa^ofyQ>?yyKyClrkafkNrbpqObt^oaXLccbofkdlcqebPe^$q^oZ+Nrbpq`e^fkpq^oqpcoljXQebGlrok^ilcS^i$w^obnZ)aolmmbacoljS^i$w^obnqeb@lknrbolo%2.+/)25+5&%2/+5)35+5&yyWy140yyKM@y/.646y
KDrfiaQ^_^oayQ>?yyKyD^ovi%14+3)42+3&yyWy0/.yyKM@y2.55y
KEbiip`ob^j$pOb^`eQ^_^oayQ>?yyKyMldd%21+3)5.+.&)Bu^iqbaEbiip`ob^j$pOb^`e)1-Qli?^o^a@ljjbka^qflkpyyWy4-5yyKM@y1520.y
KHbbmboplcQfjbQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQebHbbmboplcQfjb).dyyWy0/.yyKM@y2.55y
KIlobj^pqbo$p@lilopyQ>?yyKyObt^oacloIlobj^pqbo>`efbsbjbkqy
KIltbo@fqvQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeIltbo@fqv).dyyWy0/.yyKM@y2.55y
KJ^d$e^oQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQebJ^d$e^o).dyyWy0/.yyKM@y2.55y
KLdof$i^Q^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeLdof$i^).->mbufpPe^oapyyWy0/.yyKM@y2.55y
KLodofjj^oQ^_^oayQ>?yyKyPqlkbdr^oaK^odli%2-+.)25+2&)CofbkaivtfqeLodofjj^o).-pyyWy0/.yyKM@y2-155y
KMromibQolmevQ^_^oalcqebFiifa^ofyQ>?yyKyClrkafkNrbpqObt^oaXLccbofkdlcqebPe^$q^oZ+Nrbpq`e^fkpq^oqpcoljXQebGlrok^ilcS^i$w^obnZ)aolmmbacoljS^i$w^obnqeb@lknrbolo%2.+/)25+5&%2/+5)35+5&yyWy140yyKM@y/.646y
KObibkqibppDi^af^qlo$pQ^_^oayQ>?yyKyL_q^fkbacolje^sfkd^k^obk^O^qfkdlc/0--(%MSM&y
KP`lrq$pQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)MsM)2-ElkloMlfkqpyyWy0/.yyKM@y2.55y
KP`ovbopQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQebP`ovbop).dyyWy0/.yyKM@y2.55y
KPe^$q^oQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQebPe^$q^o).dyyWy0/.yyKM@y2.55y
KPfisbojllk@fqvQ^_^oayQ>?yyKyJ^dfpqofuKfw^o^%21+0)2-+6&)CofbkaivtfqePfisbojllk@fqv).-pyyWy13/yyKM@y2-151y
KPhvdr^oaQ^_^oayQ>?yyKyDobii^%31+0)33+0&)Bu^iqbatfqePe^$q^ofPhvdr^oa).dyyWy145yyKM@y/0034y
KPmlobdd^oQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqePmlobdd^o).-Dilt`^mpyyWy0/.yyKM@y2.55y
KPqlkbDr^oa$pEbo^iayQ>?yyKyD^ovi%14+3)42+3&)MsM).--ElkloMlfkqpyyWy0/.yyKM@y2.55y
KPrkob^sboQ^_^oayQ>?yyKyS^p^ofkObajlok%43+/)/1+-&)Bu^iqbatfqePrkob^sbop)2-@e^jmflk$pPb^ipyyWy16/yyKM@y0144/y
KQ^_^oalc?orqbClo`byQ>?yyKyObt^oaclo?orq^iivAbaf`^qba>`efbsbjbkq%MSM&y
KQ^_^oalc@lknrbpqyQ>?yyKyObt^oacloJ^pqbolcFpiblc@lknrbpq>`efbsbjbkqy
KQ^_^oalcO^jh^ebkyQ>?yyKy?i^`hpjfqe>_^pf%21+-)00+/&)CofbkaivtfqeO^jh^ebk).dyyWy4/-yyKM@y153.4y
KQ^_^oalcPrjjboCi^jbpyQ>?yyKyNrbpqobt^oaclo`ljmibqfkdPe^oaplc>erkb)nrbpqpq^oqpcoljXPe^oaplc>erkbZ)tef`efpaolmmbacolj>erkbfkPi^sbMbkparofkdqebJfaprjjboCbpqfs^iTloiaBsbkq+y
KQ^_^oalcPrjjboPhfbpyQ>?yyKyNrbpqobt^oaclo`ljmibqfkdPe^oaplc>erkb)nrbpqpq^oqpcoljXPe^oaplc>erkbZ)tef`efpaolmmbacolj>erkbfkPi^sbMbkparofkdqebJfaprjjboCbpqfs^iTloiaBsbkq+y
KQ^_^oalcqeb>`efbsboyQ>?yyKyObt^oacloQtbkqv*CfsbQ^_^oap>`efbsbjbkqy
KQ^_^oalcqeb>odbkq@orp^abyQ>?yyKySbqbo^k@orp^abo>ifl`e^Pbd^oa%54+3)42+3&)CofbkaivtfqeQeb>odbkq@orp^ab).dyyWy16/yyKM@y0-10.y
KQ^_^oalcqebAo^dlkj^t@i^kyQ>?yyKyDolqAb^qe_ilt%20+5)1/+-&)CofbkaivtfqeqebAo^dlkj^t@i^k).dyyWy4--yyKM@y16054y
KQ^_^oalcqebB^oqebkOfkdyQ>?yyKyMolsfpflkbo>olh%16+-)1/+-&)CofbkaivtfqeqebB^qebokOfkd).dyyWy3.2yyKM@y2-0/1y
KQ^_^oalcqebB_lk?i^abyQ>?yyKyAr`ebppJvku%10+1)/-+3&)CofbkaivtfqeqebB_lk?i^ab).dyyWy16/yyKM@y0/205y
KQ^_^oalcqebBumiloboyQ>?yyKyObt^oacloBumilobKloqeobka>`efbsbjbkqy
KQ^_^oalcqebDr^oaf^kplcEvg^iyQ>?yyKyMolsfpflkboTefqb`ilra%3/+5)/0+5&)CofbkaivtfqeqebDr^oaf^kplcEvg^i).dyyWy3-3yyKM@y2-0.1y
KQ^_^oalcqebHfofkQloyQ>?yyKy>o`ej^db>is^ob^ru%/2+2)14+5&)CofbkaivtfqeqebHfofkQlo).dyyWy2-1yyKM@y0//54y
KQ^_^oalcqebP`^oibq@orp^abyQ>?yyKyAolmpcoljP`^oibqQo^fkbbfkP`^oibqJlk^pqbov*>ojlov+Qebpb^obqebKM@$pqe^qpm^tk^cqboEbolafpabcb^qba+yyWy/-yyKM@y3242y
KQ^_^oalcqebPe^qqbobaPrkyQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeqebPe^qqbobaPrkLccbkpfsb).dyyWy0/.yyKM@y2.55y
KQ^_^oalcqebTvojobpq>``loayQ>?yyKy@fbipqo^pw^%26+5)20+-&)Bu^iqbatfqeTvojobpq>``loa).dyyWy155yyKM@y0/200y
KQ^_^oalcQebo^w^kbyQ>?yyKyA$iljqeb@liib`qlo%23+5).0+/&)CofbkaivtfqeQebo^w^kb).dyyWy31-yyKM@y121-5y
KQeo^iij^oQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)Bu^iqbatfqeQeo^iij^o).dyyWy0/.yyKM@y2.55y
KQerkabo?irccQ^_^oayQ>?yyKy?o^sbQrel%13+6)2-+.&)CofbkaivtfqeQerkabo?ircc).-pyyWy03/yyKM@y2-150y
KRkabo`fqvQ^_^oayQ>?yyKy@^mq^fkAlk^ia>a^jp%30+3)15+5&)CofbkaivtfqeRkabo`fqv).-pyyWy05/yyKM@y2-0-1y
KT^oplkd?^qqibQ^_^oayQ>?yyKyD^ovi%14+3)42+3&)MsM)/-26ElkloMlfkqpyyWy0/.yyKM@y2.55y
KTo^qecriDi^af^qlo$pQ^_^oayQ>?yyKyKlIlkdbo>s^fli^_ibfk*d^jb+yyWy.3.yyKM@y/-/45y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
