local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Titles_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Titles",  nil, "Horde", "A", nil, function()
return [[
AAA

KQfqibDrfabyKyQefpdrfabfp^pqf`hvco^jbdrfab)j^kr^iqf`he^p_bbkafp^_ibacloqefppqbm+Qlrpbqefpdrfab)lmbkqebi^odbco^jb^karpbqebpb^o`ecb^qrobqlcfkaqebQfqibpvlr^obillhfkdclo)qebkPefcq*Ibcq@if`hlkqe^qpqbmclob^`eQfqib+yyKQy
K>j_^pp^aloyKyObt^oaclo`ljmibqfkd>j_^pp^alolcqebEloab>`efbsbjbkq*B^okbu^iqbaobmrq^qflktfqe2eljb`fqfbp+yy>FAy43/y
K>obk^J^pqboyKyObt^oaclo`ljmibqfkdQeb>obk^J^pqbo>`efbsbjbkq+yy>FAy..41y
K?^kblcqebC^iibkHfkdyKyObt^oaclo`ljmibqfkd?^kblcqebC^iibkHfkd>`efbsbjbkq*Abcb^qqebIf`eHfkdfkF`b`oltk@fq^abifk.-*mi^vboEbolf`jlab+yy>FAy1250y
K?^qqibj^pqboyKyObt^oaclo`ljmibqfkd?^qqibj^pqbo>`efbsbjbkq+yy>FAy..42y
K?i^`htfkd$p?^kbyKyObt^oacloAbcb^qKbc^of^kfk?i^`htfkdAbp`bkqlkEbolf`Afccf`riqv+yy>FAy2..3yyKM@y1.043y
K?illap^fi>ajfo^iyKyObt^oaclo`ljmibqfkd>s^pqVb)>ajfo^i>`efbsbjbkq+yy>FAy54.y
K?obtj^pqboyKyObt^oaclo`ljmibqfkd?obtj^pqbo>`efbsbjbkqarofkdqeb?obtcbpqTloiaBsbkq+yy>FAy.350y
K@e^jmflklcqebColwbkT^pqbpyKyObt^oaclo`ljmibqfkd@e^jmflklcqebColwbkT^pqbp>`efbsbjbkq+yy>FAy.325y
K@e^jmflklcRiar^oyKyObt^oaclo`ljmibqfkd@e^jmflklcRiar^o>`efbsbjbkq*Abcb^qb^`e_lppfkRiar^ofk.-*mi^vbojlabtfqelrq^iiltfkd^kvo^fajbj_boqlafbqlqe^q_lpp^q^kvmlfkqarofkdqe^qo^fail`hlrqmbofla+yy>FAy/6-0y
K@ebcyKyObt^oaclo`ljmibqfkdE^fiqlqeb@ebc>`efbsbjbkq+yy>FAy.451y
K@lknrboloyKyObt^oacloQeb@lknrbolo>`efbsbjbkq*O^fpbvlros^irbpfkT^oplkdDri`e)>o^qef?^pfk^ka>iqbo^`S^iibvqlBu^iqba+yy>FAy4.1y
K@lknrbololcRiar^oyKyObt^oaclo`ljmibqfkd@lknrbololcRiar^o>`efbsbjbkq*Abcb^qb^`e_lppfkRiar^ofk/2*mi^vbojlabtfqelrq^iiltfkd^kvo^fajbj_boqlafbqlqe^q_lpp^q^kvmlfkqarofkdqe^qo^fail`hlrqmbofla+yy>FAy/6-1y
K@orp^aboyKyObt^oacloBu^iqba>odbkq@e^jmflklcqebEloab*B^okbu^iqbapq^qrptfqe^kaqebofdeqqlobmobpbkqbsbovEloabo^`b$pc^`qflkfkqeb>odbkqQlrok^jbkq+yy>FAy/5.3y
KAbpqolvbo$pBkayKyAbcb^qAb^qetfkdlkKloj^iloEbolf`Afccf`riqvfkqebAo^dlkPlrio^fa+yy>FAy3.44yyKM@y23.40y
KAo^dlkpi^vboyKyAbcb^qPfkbpqo^fkqeb?^pqflklcQtfifdeqlkEbolf`Afccf`riqv+yy>FAy2./.yyKM@y12/.0y
KBiaboyKyObt^oaclo`ljmibqfkdQlElkloLkb$pBiabop>`efbsbjbkqarofkdqebIrk^oCbpqfs^iTloiaBsbkq+yy>FAy6.0y
KCfobiloayKyAbcb^qO^dk^olpfkCfobi^kaplkEbolf`Afccf`riqv+yy>FAy25-0yyKM@y2/1-6y
KCi^jbHbbmboyKyObt^oaclo`ljmibqfkdQebCi^jbHbbmbo>`efbsbjbkqarofkdJfaprjjboCfobCbpqfs^iTloiaBsbkqyy>FAy.-06y
KDr^oaf^klc@bk^ofrpyKyObt^oaclo`ljmibqfkdDr^oaf^klc@bk^ofrp>`efbsbjbkq*B^okbu^iqbapq^qrptfqeqeb@bk^oflk@fo`ib^ka@bk^oflkBumbafqflk+yy>FAy620y
KEbo^ialcqebQfq^kpyKyObt^oaclo`ljmibqfkdEbo^ialcqebQfq^kp>`efbsbjbkq*Abcb^q>id^ilkqebL_pbosbofk.-*mi^vbojlab^qibsbi5-tfqelrq^kvlkbfkqebo^fatb^ofkd^kvbnrfmjbkqtfqe^kfqbjibsbiefdeboqe^kfp^s^fi^_ibfk.-*mi^vboRiar^o+yy>FAy00.3y
KGbkhfkpyKyObt^oaclo`ljmibqfkdqebIbbbbbbbbbbbbbolv>`efbsbjbkq*Hfii2-ollhbovtebimptfqefk.2pb`lkap+yy>FAy/.55y
KIlobj^pqboyKyObt^oaclo`ljmibqfkdQebIlobj^pqbo>`efbsbjbkq+yy>FAy.35/y
KJ^qolkyKyObt^oaclo`ljmibqfkdCloQeb@efiaobk>`efbsbjbkqarofkd@efiaobk$pTbbhTloiaBsbkq+yy>FAy.460yyDyCbj^iby
KJboovj^hboyKyObt^oaclo`ljmibqfkdJboovj^hbo>`efbsbjbkqarofkdqebTfkqboSbfiTloiaBsbkq+yy>FAy.36.y
KlcLodofjj^oyKyObt^oaclo?bfkdBu^iqbatfqeLodofjj^o>KA`ljmibqfkdQebS^if^kq$p@e^iibkdb^qqeb>odbkqQlrok^jbkqyy>FAy/432y
KlcPbk$gfkyKyObt^oaclo?bfkdBu^iqbatfqeA^ohpmb^oQoliip>KA`ljmibqfkdQebS^if^kq$p@e^iibkdb^qqeb>odbkqQlrok^jbkqyy>FAy/433y
KlcPfisbojllkyKyObt^oaclo?bfkdBu^iqbatfqePfisbojllk>KA`ljmibqfkdQebS^if^kq$p@e^iibkdb^qqeb>odbkqQlrok^jbkqyy>FAy/434y
Klcqeb>pebkSboaf`qyKyObt^oaclo`ljmibqfkdQeb>pebkSboaf`q>`efbsbjbkq*B^okbu^iqbapq^qrptfqeqeb>pebkSboaf`q+yy>FAy1265y
KlcqebEloabyKyObt^oaclo.-----Elklo^_ibHfiip*Dbq.--)---elklo^_ibhfiipyy>FAy54-y
KlcqebClroTfkapyKyAbcb^q>i$>hfofkqebQeolkblcqebClroTfkaplkEbolf`Afccf`riqv+yy>FAy2./0yyKM@y13420y
KlcqebKfdeqc^iiyKyObt^oaclo`ljmibqfkdQebQtfifdeqWlkb%.-mi^vbo&>`efbsbjbkq*Tfqe^iiqeobbQtfifdeqAo^hbppqfii^ifsb)bkd^db^kaabcb^qP^oqe^oflkqebLkvuDr^oaf^kfk.-*mi^vbojlab+yy>FAy/-2.y
KlcqebPe^qqbobaPrkyKyObt^oaclo`ljmibqfkdVlr$obPlLccbkpfsb>`efbsbjbkq*B^okbu^iqbapq^qrptfqeqebPe^qqbobaPrkLccbkpfsb+yy>FAy564y
KlcqebRkabo`fqvyKyObt^oaclo?bfkdBu^iqbatfqeQebRkabo`fqv>KA`ljmibqfkdQebS^if^kq$p@e^iibkdb^qqeb>odbkqQlrok^jbkqyy>FAy/436y
KlcQerkabo?irccyKyObt^oaclo?bfkdBu^iqbatfqeQerkabo?ircc>KA`ljmibqfkdQebS^if^kq$p@e^iibkdb^qqeb>odbkqQlrok^jbkqyy>FAy/435y
KM^qolkyKyObt^oaclo`ljmibqfkdCloQeb@efiaobk>`efbsbjbkqarofkd@efiaobk$pTbbhTloiaBsbkq+yy>FAy.460yyDyJ^iby
KP^iqvyKyObt^oaclo`ljmibqfkd>``ljmifpeba>kdibo>`efbsbjbkq+yy>FAy.2.3y
KP^sflolc>wbolqeyKyAbpqolvAb^qetfkdfkAo^dlkPlrilkEbolf`Afccf`riqv+yy>FAy3..3yyKM@y23.40y
KPq^o`^iiboyKyObt^oaclo`ljmibqfkdL_pbosba%.-mi^vbo&>`efbsbjbkq*Abcb^q>id^ilkqebL_pbosbofk.-*mi^vbojlab+yy>FAy0-03y
Kqeb>odbkq@e^jmflkyKyObt^oaclo`ljmibqfkdQeb>odbkq@e^jmflk>`efbsbjbkq*B^okbu^iqbapq^qrptfqeqeb>odbkqA^tk^kaqeb>odbkq@orp^ab+yy>FAy612y
Kqeb>odbkqAbcbkaboyKyObt^oaclo`ljmibqfkd>Qof_rqbqlAbaf`^qbaFkp^kfqv>`efbsbjbkq*Jbbqqeb`ofqbof^clo>Qof_rqbqlFkp^kfqvtfqelrq^kvo^fajbj_boe^sfkdrpba^kfqbjlkivl_q^fk^_ibcolj/2*mi^vbo@lifpbrj)lo^kvjlobmltbocrifqbj+yy>FAy1-5-y
Kqeb>pqo^iT^ihboyKyObt^oaclo`ljmibqfkdyKyObt^oaclo`ljmibqfkdL_pbosba%/2mi^vbo&>`efbsbjbkq*Abcb^q>id^ilkqebL_pbosbofk/2*mi^vbojlab+yy>FAy0-04y
Kqeb?illaqefopqvyKyObt^oaclo/2----Elklo^_ibHfiip*Dbq/2-)---elklo^_ibhfiipyy>FAy2030y
KqebAfmilj^qyKyObt^oaclo`ljmibqfkdQebAfmilj^q>`efbsbjbkq*O^fpbvlroobmrq^qflkibsbicoljrkcofbkaivqlbu^iqbatfqeQfj_boj^tElia)Pmlobdd^o^kaQebJ^d$e^o+yy>FAy610y
KqebBu^iqbayKyObt^oaclo`ljmibqfkd12Bu^iqbaObmrq^qflkp>`efbsbjbkq+yy>FAy2041y
KqebBumiloboyKyObt^oaclo`ljmibqfkdTloiaBumilobo>`efbsbjbkq*BumilobB^pqbokHfkdaljp)H^ifjalo)Lrqi^ka^kaKloqeobka+yy>FAy13y
KqebE^iiltbayKyObt^oaclo`ljmibqfkdE^iiltba?bQevK^jb>`efsbjbkqarofkdqebE^iilt$pBkaTloiaBsbkq+yy>FAy.324y
KqebFjjloq^iyKyObt^oaclo`ljmibqfkdQebFjjloq^i>`efbsbjbkq*Tfqefklkbo^fail`hlrqmbofla)abcb^qbsbov_lppfkK^uuo^j^ptfqelrq^iiltfkd^kvo^fajbj_boqlafbarofkd^kvlcqeb_lppbk`lrkqbopfk/2*mi^vbojlab+yy>FAy/.53y
KqebFkp^kbyKyObt^oaclo`ljmibqfkdFkp^kbfkqebJbj_o^kb>`efbsbjbkq*B^okBu^iqbapq^qrptfqeBsboillh)O^q`ebq)O^sbkeliaq)?llqv?^v)D^adbqw^k)A^ohjllkC^fob^kaElklobapq^qrptfqe?illap^fi?r``^kbbop+yy>FAy/003y
KqebHfkdpi^vbo*.-J^kyKyObt^oaclo`ljmibqfkdQebColwbkQeolkb>`efbsbjbkq%.-mi^vbo&*Abcb^qqebIf`eHfkdfkF`b`oltk@fq^abiyy>FAy120-y
KqebHfkdpi^vbo*/2J^kyKyObt^oaclo`ljmibqfkdQebColwbkQeolkb>`efbsbjbkq%/2mi^vbo&*Abcb^qqebIf`eHfkdfkF`b`oltk@fq^abiyy>FAy1264y
KqebIfdeqlcA^tkyKyObt^oaclo`ljmibqfkdQebIfdeqlcA^tk>`efbsbjbkq*Abcb^qqebIf`eHfkdfkF`b`oltk@fq^abifk/2*mi^vboEbolf`jlab+yy>FAy1251y
KqebIlsbClliyKyObt^oaclo`ljmibqfkdClliCloIlsb>`efbsbjbkqarofkdqebIlsbfpfkqeb>foTloiaBsbkq+yy>FAy.360y
KqebKl_ibyKyObt^oaclo`ljmibqfkdKl_ibD^oabkbo>`efbsbjbkqarofkdqebKl_ibd^oabkTloiaBsbkq+yy>FAy/465y
KqebM^qfbkqyKyObt^oaclo`ljmibqfkdIllhfkdCloJ^kv>`efbsbjbkq*RpbqebArkdblkCfkaboqlliqlcfkfpeo^kaljebolf`arkdblkprkqfivlre^sbdolrmbatfqe2-o^kaljmi^vbopqlq^i+yy>FAy1144y
KqebMfidofjyKyObt^oaclo`ljmibqfkdMfidofj>`efbsbjbkqarofkdqebMfidofj$p?lrkqvTloiaBsbkq+yy>FAy0323y
KqebPbbhboyKyObt^oaclo`ljmibqfkd0---Nrbpqp@ljmibqba>`efbsbjbkq+yy>FAy645y
KqebRkavfkdyKyObt^oaclo`ljmibqfkdQebRkavfkd>`efbsbjbkq*Tfqefklkbo^fail`hlrqmbofla)abcb^qbsbov_lppfkK^uuo^j^ptfqelrq^iiltfkd^kvo^fajbj_boqlafbarofkd^kvlcqeb_lppbk`lrkqbopfk.-*mi^vbojlab+yy>FAy/.54y
KQtfifdeqS^knrfpeboyKyObt^oaclo`ljmibqfkdQebQtfifdeqWlkb%/2mi^vbo&>`efbsbjbkq*Tfqe^iiqeobbQtfifdeqAo^hbppqfii^ifsb)bkd^db^kaabcb^qP^oqe^oflkqebLkvuDr^oaf^kfk/2*mi^vbojlab+yy>FAy/-21y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
