local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Venomhide_Ravasaur_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Classic Reputation|r ", "Venomhide Ravasaur Quest and Dailies (50+)", nil, "Horde", "A", nil, function()
return [[
AAA

KIltIbsbiNrbpqyKyFcvlr^obfkvlro4-$plo^q5-)qefpnrbpqtfii_b^iltibsbinrbpqclovlr)qroklkvlroiltibsbinrbpqqo^`hfkdql_b^_ibqlpbbqebnrbpqlkvlrojfkfj^m+yyNFAy.0554y

ORk$Dlol@o^qboyKyQo^sbiqlRk$Dlol@o^qbo%4.+2)40+1&yyNFAy.052-yyWy/-.y
>Qluf`Qlibo^k`byKyJlo$sbh%4.+2)40+1&yyNFAy.052-yyWy/-.yyKM@y..4-.y
@Qluf`Qlibo^k`byKyDbqpmi^peba_vSbkljefabO^s^p^ro_illa/-qfjbp+>qq^`hSbkljefabO^s^p^rop%33+0)2.+2&clo^`e^k`bql_bmlfplkba+Jrpq?bSbkljefabO^s^p^rop+yyNFAy.052-yyWy/-.yyKM@y32-5y
QQluf`Qlibo^k`byKyJlo$sbh%4.+2)40+1&yyNFAy.052-yyWy/-.yyKM@y..4-.y

>SbkljefabBddpyKyJlo$sbh%4.+2)40+1&yyNFAy.0554yyWy/-.yyKM@y..4-.y
@SbkljefabBddpyKy?ofkd1SbkljefabO^s^p^roBddp%3.+2)25+-&%35+3)21+1&%4.+2)3-+-&%34+-)3/+4&%30+6)3/+6&3.+-)4/+0&qlJlo$sbhfkqebplrqeb^pqm^oqlcqebJ^opei^kap+yyNFAy.0554yyWy/-.yyL?Gy4/-/y
QSbkljefabBddpyKyJlo$sbh%4.+2)40+1&yyNFAy.0554yyWy/-.yyKM@y..4-.y

>QebvDoltRmPlC^pqyKyJlo$sbh%4.+2)40+1&yyNFAy.06-3yyWy/-.yyKM@y..4-.y

RSbkljefabE^q`eifkdyKyPrjjlkvlroSbkljefabE^q`eifkd+@^klkiv_bprjjlkbafkRk$Dlol@o^qbo)Q^k^ofp)loPfifqerp+yyRy1303/y
K>``bmqqebA^fivyKy>``bmqqebA^fivNrbpqcoljvlroSbkljefabe^q`eifkd+y
>Pb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06-2yyAyyKM@y010/-y
>Pb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06.1yyAyyKM@y010/-y
>Erkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.06.2yyAyyKM@y010/-y
>Erkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.0556yyAyyKM@y010/-y
>Ml^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyyNFAy.06.3yyAyyKM@y010/-y
>Ml^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyyNFAy.06-1yyAyyKM@y010/-y
>DlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06.4yyAyyKM@y010/-y
>DlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06-0yyAyyKM@y010/-y

@Pb^ofkdOl`Cb^qebopyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqldbq2mfb`bplcPb^ofkdOl`Mirj^db%04+.)35+6&%1.+2)31+3&%0.+6)3-+6&yyWy.3.yyNFAy.06-2yyAyyKM@y210-y
@Pb^ofkdOl`Cb^qebopyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqldbq2mfb`bplcPb^ofkdOl`Mirj^db%04+.)35+6&%1.+2)31+3&%0.+6)3-+6&yyWy.3.yyNFAy.06.1yyAyyKM@y210-y
@Erkdov)ErkdovE^q`eifkdyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.2mfb`bplcCobpeAfklp^roJb^q+HfiiAfklp^ropfkRk$dlol@o^qbocloqebjb^q%00+5)33+2&%0/+4)04+5&%22+-)3/+.&yyWy/-.yyNFAy.06.2yyAyyKM@y6.30)6.33)32-.)32-/y
@Erkdov)ErkdovE^q`eifkdyLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.2mfb`bplcCobpeAfklp^roJb^q+HfiiAfklp^ropfkRk$dlol@o^qbocloqebjb^q%00+5)33+2&%0/+4)04+5&%22+-)3/+.&yyWy/-.yyNFAy.0556yyAyyKM@y6.30)6.33)32-.)32-/y
@Ml^`eba)P`o^j_iba)LoO^t<yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq./PfifqefaBddp+Qebbddp`^k_bclrka^iilsboQebKluflrpI^fo%00+3)06+2&yyWy.3.yyNFAy.06.3yyAyyL?Gy4316y
@Ml^`eba)P`o^j_iba)LoO^t<yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq./PfifqefaBddp+Qebbddp`^k_bclrka^iilsboQebKluflrpI^fo%00+3)06+2&yyWy.3.yyNFAy.06-1yyAyyL?Gy4316y
@DlofpefDor_yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.-PfifqefaJb^q+HfiiPfifqefap^qqebPifqebofkdP`^o%2-+1)45+5&yyWy/-.yyNFAy.06.4yyAyyKM@y322.)322/)3220)3221)3222y
@DlofpefDor_yLyyKyVlroSbkljefabE^q`eifkdt^kqpvlrqlcbbafq.-PfifqefaJb^q+HfiiPfifqefap^qqebPifqebofkdP`^o%2-+1)45+5&yyWy/-.yyNFAy.06-0yyAyyKM@y322.)322/)3220)3221)3222y

QPb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06-2yyAyyKM@y010/-y
QPb^ofkdOl`Cb^qebopyLyyKySbkljefabE^q`eifkdyyNFAy.06.1yyAyyKM@y010/-y
QErkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.06.2yyAyyKM@y010/-y
QErkdov)ErkdovE^q`eifkdyLyyKySbkljefabE^q`eifkdyyNFAy.0556yyAyyKM@y010/-y
QMl^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyyNFAy.06.3yyAyyKM@y010/-y
QMl^`eba)P`o^j_iba)LoO^t<yLyyKySbkljefabE^q`eifkdyyNFAy.06-1yyAyyKM@y010/-y
QDlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06.4yyAyyKM@y010/-y
QDlofpefDor_yLyyKySbkljefabE^q`eifkdyyNFAy.06-0yyAyyKM@y010/-y

KSbkljefab?^_vQllqeyKyTebkvlre^sb`liib`qba/-XSbkljefab?^_vQllqeZ)qebk`ljmibqbqebi^pqnrbpqqldbqvlroO^s^p^ro+y

@QebvDoltRmPlC^pqyKy/-XSbkljefab?^_vQbbqeZ)qebSbkljefabE^q`eifkd)/-XOrkb`ilqeZ)/-XOrddbaIb^qeboZ)^ka5-dliaqlJlo$sbhRk$Dlol@o^qbo+yyNFAy.06-3yyWy/-.y
QQebvDoltRmPlC^pqyKyJlo$sbh%4.+2)40+1&yyNFAy.06-3yyWy/-.yyKM@y..4-.y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
