local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Veteran_of_the_Molten_Fronts_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Quests|r ", "Veteran of the Molten Front (85+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyVlrjrpq_b52qlpq^oqqefp^`efbsbjbkq+Qebpb^`efbsbjbkqprpr^iiv^obalkbfk`lkgr`qflktfqeqeba^fifbp^kanrbpqlccbobafkqebJliqbkColkq^kaObdoltqe^ob^p+Cfopq)pq^oqqebJliqbkColkqnrbpqifkbqlrkil`hme^pb.^kaqebcfopqpbqlca^fifbp+Lk`bvlre^sb^``bmqbaqeba^fivnrbpq`ljb_^`hqlqefpdrfabqlpbbte^q^`efbsbjbkqp`^k_balkb+yyNFAy/6.65y

K>kdovIfqqibPnrfoobiyKyMrii^jl_qlt^oapqebdobbk^ob^plcqebobdoltqe%02+.)20+1&%06+-)20+1&%06+0)23+.&ql^iiltpnrfooibpql_lj_qebjtqfe^`lokp+J^hbprobvlr^obkb^oqebjl__bfkd_lkhba_v^`lokp+yyWy3-3yy>FAy2535yy>@y.y

KAr^i>`efbsbjbkqpyKy>``bmqqeba^fifbpcoljqebobdoltqecfopq+Qebar^inrbpqfkqebobdoltqee^sbar^i^`efbsbjbkqp^qq^`ebaqlqebj+J^hbprobqe^qlk`bqebcfopqm^oqfp`ljmibqb)vlr`ljb_^`h^kapbbte^q^`efbsbjbkqfp^qq^`ebaqlqebpb`lkam^oq+Qf`hqefppqbm+yy>FAy2546yy>@y3y
KEvg^i?b^o@r_yKyArofkdqeba^fivQelpb?b^opRmQebob)qeolt^_b^o`r_^q^pibbmfkd?ofjpqlkbElrka%.1+-)0/+5&+J^hbprobfqfp^qlkbqe^qfp^t^vcoljqebqobbvlr^obfk)^kaj^hbprobqlefqfqab^alk+yy>@y/yy>FAy2535yyNFAy/6.3.yyLyyKM@y2/462yyWy3-3y
K@efialcQloqlii^yKyArofkdqeba^fivMrkqfkdPb^plk)mrkq^@efialcQloqlii^%/1+-)3-+6&%/0+/)26+-&%/.+4)26+6&^q^Ci^jbQbooloyy>@y1yy>FAy2535yyNFAy/6.-.yyLyyKM@y2//.6yyWy3-3y
KIraf`olrpPmbbayKyTefiblkqebnrbpq@^iiqebCil`hfkJlrkqEvg^i%./+2)1/+3&)l_q^fk32pq^`hplcPl^o_vrpfkdvlro`^ii^_fifqvkb^oqeb_foap+Fqe^p^`llialtk)plalk$qibqfqc^iilcc+B^dibpdfsb.2Pl^o)Ltipdfsb2pl^o)^ka_foapdfsb.Pl^o+yy>FAy253/yyNFAy/6.14yyLyyWy3-3y
K>imfkbPlkd_foayKyTebkJfii^d^wlo%.0+/)11+3&^qqbjmqpqlbp`^mb)nrfqampfkd^ka^iiltqebQebPlkd_foapvlrd^qeboqlcfkfpeefjlcc+Qf`hqefppqbm+yy>@y0yy>FAy2535yyNFAy/6.14yyLyyWy3-3y

KFkcbok^i>j_^pp^alopyKyJ^hbprobvlre^sb^``bmqbaqeb^rqlnrbpq+Vlrjrpq_bqebmboplkqe^qprjjlkpqebjl_qldbq^`efbsbjbkq`obafqclofq+Qf`hqefppqbm+yy>FAy2546yy>@y6y
HFkcbok^i>j_^pp^alop7Mvo^`ekfpyKyPi^vMvo^`ekfp%.0+0.)11+43&tfqelrqrpfkdqebBjbo^ialc>bppfk^ql`ib^kpbqebmlfplk+yy>FAy2536yy>@y.yyNFAy/6.3/yyLyyKM@y2/416yyWy3-3y
HFkcbok^i>j_^pp^alop7Ivi^d^oyKyPi^vIvi^d^o%1.+62)22+30&tfqelrqq^hfkda^j^dbcoljIv^id^o?ob^qe+yy>FAy2536yy>@y0yyNFAy/6.32yyLyyKM@y2/433yyWy3-3y
HFkcbok^i>j_^pp^alop7KbjbpfpyKyPi^vKbjbpfp%/1+-3)22+46&^q>pebkI^hbtfqelrqq^hfkda^j^dbcoljJliqbkCrov+GrpqdbqrkaboQlld^$ppebiitebkeb`^pqpJliqbkCrov+Vlr^iplkbbaql_bprobvlrq^defjcfopqqlob`fbsb`obafq+yy>FAy2536yy>@y2yyNFAy/6.//yyLyyKM@y2/050yyWy3-3y
HFkcbok^i>j_^pp^alop7Jfii^d^wloyKyPi^vJfii^d^wlo%.0+/3)11+04&tfqelrqq^hfkda^j^dbcoljDlrqlcCi^jb+Grpqhbbmjlsfkd^t^vcoljqebcfobpmlqplkqebdolrka+yy>FAy2536yy>@y/yyNFAy/6.15yyLyyKM@y2/316yyWy3-3y
HFkcbok^i>j_^pp^alop7D^ibkdbpyKyPi^vD^ibkdbp%1.+41)23+/.&_bclobebfptb^hbkba^pb`lkaqfjb+P^sbvlro`llialtkpclotebkebfptbbhbkaqebcfopqqfjb)qebk_rokefjaltk+yy>FAy2536yy>@y1yyNFAy/6./3yyLyyKM@y2/066yyWy3-3y

KE^sb+++E^sbTbJbq<yKyT^sb^qqebcliiltfkdKM@$pfkPbqeof^$pOllpq%0.+.)43+3&8Ifkhbk)K^qM^dib)J^khofh)EbjbqKbpfkdt^ov)@eoljfb)^kaQe^pp^of^kcloqebE^sb+++E^sbTbJbq<>`efbsbjbkq+Qefp`^k_balkbtebkbsbovlr`ellpb+QebMolqb`qloplcEvg^inrbpqe^plkbrkfnrbKM@^ka0aorfakm`pm^tk)plqebob^ob^ilqlc`e^k`bpqldbqqebpb^plqebomblmibnrbpq+yyNFAy/6./5yyLyyWy3-3yy>FAy2532y

KMe^pb/yKyVlrjrpq_bfkMe^pb/lcqebJliqbkColkqql`lkqfkrb++fcvlre^sbk$qrkil`hbame^pb/)Obpbq^kaObil^aqebdrfab+yyNFAy/6.66y

KPmb^htfqeJ^ql`i^tyKy%/4+-)3/+3&yyWy3-3yy>FAy254-yy>@y/yyKM@y2/336y
KPmb^htfqeAloa^$bkKfdeqtb^sboyKy%/4+3)3/+1&yyWy3-3yy>FAy254-yy>@y1yyKM@y2/653y

KD^kdT^oyKyTfk^arbi^d^fkpq^klqebomi^vbofkPbqeof^$pOllpq%0.+.)43+3&tefiblkqebnrbpqQebMolqb`qloplcEvg^inrbpq+yyWy3-3yy>FAy2546yy>@y4yyNFAy/6./5yyLy

KQebCfbovIloaplcPbqeof^$pOllpqyKyErkqaltk^kapi^vqebcliiltfkdjfkflkplcO^dk^olpfkPbqeof^$pOllpq)qelrdefqfpklqkb`bpp^ovql_blkQebMolqb`qloplcEvg^inrbpq)fqfpob`ljjbkabacloqeb^aafqflk^iebim+Vlrlovlrodolrmjrpq_bqebcffopqqlq^dqebpbjl_p+>iplqebpbjl_p^obbuqobjbive^oaqlplilclojlpq`i^ppbp)pldo^_^cofbkaloqtlqlebimlrq+Qebv^obo^kaljpm^tkk^jbajl_p+Qf`hqefppqbm+yy>FAy2546yy>@y0yyNFAy/6./5yyLy
HPb^oofpyKyPi^vPb^oofp%00+1)63+3&fkPbqeof^$pOllpq)tefiblkQebMolqb`qloplcEvg^inrbpq+yyWy3-3yy>FAy253.yy>@y.yyNFAy/6./5yyLyyKM@y20/31y
H>kao^wloyKyPi^v>kao^wlo%0.+3)51+5&fkPbqeof^$pOllpq)tefiblkQebMolqb`qloplcEvg^inrbpq+yyWy3-3yy>FAy253.yy>@y0yyNFAy/6./5yyLyyKM@y20/34y
HHbi_k^oyKyPi^vHbi_k^o%0-+5)5/+/&fkPbqeof^$pOllpq)tefiblkQebMolqb`qloplcEvg^inrbpq+yyWy3-3yy>FAy253.yy>@y/yyNFAy/6./5yyLyyKM@y20/32y
HC^eG^o^hhyKyPi^vC^eG^o^hh%0-+-)54+3&fkPbqeof^$pOllpq)tefiblkQebMolqb`qloplcEvg^inrbpq+yyWy3-3yy>FAy253.yy>@y1yyNFAy/6./5yyLyyKM@y20/4.y

OJliqbkColkqyWy3-3yyKyRpbqebmloq^iqlqo^sbiqlJliqbkColkq%/4+2.)23+/6&y
KPmb^htfqeJ^icroflkPqlojo^dbyKyfkqebJliqbkColkq%14+.)6.+1&yyWy462yy>FAy254-yy>@y.yyKM@y2/.02y
KPmb^htfqeDbkbo^iQ^iaofpJllkc^iiyKyfkqebJliqbkColkq%12+2)52+5&yyWy462yy>FAy254-yy>@y5yyKM@y2/5/1y
KPmb^htfqeG^olaPe^altplkdyKyfkqebJliqbkColkq%12+.)5/+5&yyWy462yy>FAy254-yy>@y0yyKM@y2/.01y

KCi^tibppSf`qlovyKyPlilhfii^Jliqbk?bebjlqefkqebJliqbkColkq%16+.)15+6&tfqelrqq^hfkd^kva^j^dbcoljJliqbkPqljmloCfbov?lriabo+J^hbprobvlrcfkalkb^t^vcoljlqebopplqebvtlk$q_bqbjmqbaqlebimvlr+Jlsbtebkeb`^pqpCfbov?lriabo)^kajlsb_befkaefjtebkeb`^pqJliqbkPqljm+QebpbBifqbp^obklqqle^aqlplilclo^obi^qfsbivdb^oba`e^o^`qboyy>FAy2546yy>@y.-yyKM@y2/22/yyWy462y

KAorfalcqebQ^ilkyKyVlrjrpq_bfkMe^pb0lcqebJliqbkColkq^kae^sb_lqeAorfalcqebQ^ilk^kaQebPe^altT^oabknrbpqer_rkil`hbaql`ljmibqbqebobpqlcqeb^`efbsbjbkqp+Pq^oqtfqeAorfalcqebQ^ilk)qebve^sb^cbtjloblmmloqrkfqfbpql`ljmibqb^`efbsbjbkqp+++fcvlre^sbk$qrkil`hbame^pb0)Obpbq^kaObil^aqebdrfab+yyNFAy/6.5.y

KPmb^htfqeQefp^ibb@oltyKy%1/+1)26+6&fkqebJliqbkColkqyyWy462yy>FAy254-yy>@y2yyKM@y2/111y

KJ^pqbolcqebJliqbkCiltyKyQebcliiltfkd^`effbsbjbkqab^iptfqejl_pfkqebJliqbkCilt+Qf`hqefppqbm+yy>FAy2546yy>@y..y
HCi^jbt^hboPe^j^k++yKyHfii^Ci^jbt^hboPe^j^k%2-+15)06+.0&tfqeefpltkCi^jbt^sb*JlsbqebCi^jbt^hboPe^j^kfkqlefpltkCi^jbt^sblkqebdolrka)j^hbprobqe^qebfppq^kafkdfkfq)qebkhfiiefj+yy>FAy254.yy>@y.yyKM@y20-60yyWy462y
HCi^jbt^hboErkqbo$p++yKyProsfsb^Ci^jbt^hboErkqbo$p%2-+15)06+.0&Tfia?^oo^dbtfqelrqdbqqfkdefq)grpqhbbmfkdjlsfkd^peb`e^kkbip_^oo^db+yy>FAy254.yy>@y0yyKM@y20.10yyWy462y
HCi^jbt^hboPbkqfkbi++yKyHfii^Ci^jbt^hboPbkqfkbi%2-+15)06+.0&tefibfqfp`^oovfkd^m^oqvjbj_bo+B^pfpqt^vqlalqefpfk^m^oqv+Grpqibqlkbmboplkdbq^iiqeb^ddol)^kalk`bebfpmf`hbarmqebobpqlcqebdolrm_rokpaltkqebkPbkqfkbi+Ofkpb^kaObmb^qclo^iijbj_boplcvlrom^oqv+yy>FAy254.yy>@y/yyKM@y20-52yyWy462y

KPmb^htfqe>oqelokTfkaplkdyKy%01+1)23+1&fkqebJliqbkColkqyyWy462yy>FAy254-yy>@y3yyKM@y20/26y

KAb^qeColj>_lsbyKy?lj_lkblcqebk^jbaCfobiloaparofkdqebCfobfkqebPhfbpa^fiv+Vlrgrpqkbbaql_lj_qebjl_)klqhfiifq+QebCfobiloap^obo^kalj+yy>FAy2546yy>@y.0yyNFAy/6/6-yyLy
K?lj_O^dbmvoby>FAy2541yy>@y.yyNFAy/6/6-yyLyyKM@y21/2/y
K?lj_Ci^pecfoby>FAy2541yy>@y0yyNFAy/6/6-yyLyyKM@y21/21y
K?lj_Eb^qci^vboy>FAy2541yy>@y2yyNFAy/6/6-yyLyyKM@y21/23y
K?lj_?i^wbcrovy>FAy2541yy>@y/yyNFAy/6/6-yyLyyKM@y21/20y
K?lj_E^qbpm^ohy>FAy2541yy>@y1yyNFAy/6/6-yyLyyKM@y21/22y
K?lj_Pfkdbpi^vboy>FAy2541yy>@y3yyNFAy/6/6-yyLyyKM@y21/24y

KQebPe^altT^oabkpyKyLk`bvlre^sbbklrdeJ^ohp)rkil`hqebPe^altT^oabknrbpqer_+++fcvlre^sbk$qrkil`hbaqebPe^altT^oabkp)Obpbq^kaObil^aqebdrfab+yyNFAy/6/.1y

KPmb^htfqeAbiaobkO^sbkbijyKy%33+-)31+0&fkqebJliqbkColkqyyWy462yy>FAy254-yy>@y4yyKM@y2/6/.y

KHfkdlcqebPmfabo*EfiiyKyOb^`eqebefdebpqmlfkqfkqebTfalt$p@irq`e%33+.)22+5&tfqefkqebJliqbkColkq+Grpqefqqebpmfaboprmqlmtfqe^o^kdbalo^lb^_fifqv^kaibqqebktb_vlrqlqebfoqfbo)ofkpb)obmb^qqlqebqlm+yy>FAy2546yy>@y./yyWy462y

K@^iifkdqeb>k`fbkqpyKyLk`bvlre^sbbklrdeJ^ohp)`ljmibqb@^iifkdqeb>k`fbkqp+Obpbq^kaObil^aqebdrfab+yy>FAy2533yy>@y2yyNFAy/6/50y

K@^iifkdqeb>k`fbkqp++yKyKbbapql_b`ljmibqbqlalqefp^`efbsbjbkq+yyNFAy/6/50y
>Pqoffhb^qqebEb^oqyKy>``bmqPqofhb^qqebEb^oqcoljPhviloaLjkrolk%10+3)5.+1&yyNFAy/60-2yyKM@y2/16-yyWy462y
OO^dk^olp$Ob^`eyKyQo^sbiqlO^dk^olp$Ob^`e%2-+5)/-+1&yyWy462yyNFAy/60-2y

KOb^avcloO^fafkdFFyKyPi^vqeblkblcqebcliiltfkdIfbrqbk^kqplcCi^jbfkO^dk^olp$Ob^`etfqelrqdbqqfkdefq_vqebfopmb`f^i^qq^`hp+Lk`bvlrpbbtelvlr^obbkd^dfkd)grpqqf`hlccqebcliiltfkdpqbmprkqfivlrdbqqlqebofdeqKM@+Qf`hqefppqbm+yy>FAy2546yy>@y.1yyNFAy/60-2yyLy
H>k`fbkq@e^op`^ibyKy%2-+5)/0+-&EfpIfkblcCfobmrqpqo^fiplccfoblkqebdolrkaqe^qtfiicliiltvlr)j^hbprob^ka^slfaqelpb+Jlsbtebkebq^odbqpvlrtfqeefpG^sbifk?ob^`e^_ffifqv+yy>FAy2540yy>@y.yyKM@y20-22yyWy462y
H>k`fbkqPjliabofkd?bebjlqeyKy%2-+5)/0+-&Dolrkacfobfp^k>LBpmbiiqe^qo^af^qbpcoljefpcbbq+Fcvlr^objbibb)tebkvlrpbbefjpq^oqql`^pqqefp)jlsbc^o^t^vcoljefj+Efppb`lka^_fifqvfpO^fklcCfob)grpqhbbmjlsfkd^ka^slfaqlcfobcoljqebphv+yy>FAy2540yy>@y0yyKM@y2044.yyWy462y
H>k`fbkqCfobiloayKy%2-+5)/0+-&Jlsb^t^vcoljqebCi^jbPmlrq^_fifqvtebk`^pq+Fk`fkbo^qbfpfkqbormq^_ib+J^hbprobqlpq^v_befkaefj^peb`^pqCfobQloobkq)ebolq^qbp`il`htfpbtfqeqefp)pl_bob^avqljlsb+y>FAy2540yy>@y2yyKM@y20531yyWy462y
H@fkabotb_NrbbkyKy%2-+5)/0+-&Qebobfpklt^vql^slfaTofqefkdFkgb`qflk)_rqfqtfii`^rpbpj^iipmfabo^aapqlpm^tklkvlr)pl^ppllk^pqebval)_rokqebjaltk+>slfaebo@fkaboTb_^kaCi^jbPmfq^_fifqfbp+yy>FAy2540yy>@y/yyKM@y20426yyWy462y
HAbslrqE^o_fkdboyKy%2-+5)/0+-&Qefplkbfp^_fqqof`hv+Pebtfii`^pq@obbmfkdFkcbokl^qvlr)fqfp^pbsbo^ipb`lka`^pq+Tebkfq`ljmibqbpvlrtfii_befqtfqeqeb@obbmfkdFkcboklab_rcc^ka^erdbcfob_^iitfii_beroiba^qvlr+Vlrkbbaql_bjlsfkd^kagrjmgrpq^pqebcfob_^iiob^`ebpvlr+Fcvlr^oblkqebdolrkatebkfqefqp)vlrtlk$qdbq`obafq+Pb`lkaqeb@obbmfkdFkcbokltfiipm^tkpilt_rokfkdifkbplcci^jbqe^qtfiicliiltvlr)plj^hbprob^ka^slfaqebpb^ptbii+yy>FAy2540yy>@y1yyKM@y20501yyWy462y

KCfiifkdqebJllktbiiyKyLk`bvlre^sbbklrdeJ^ohp)`ljmibqbCfiifkdqebJllktbii+Obpbq^kaObil^aqebdrfab+yy>FAy2533yy>@y4yyNFAy/6/46y

>FkqlqebAbmqepyKyJ^icroflkPqlojo^db%14+-)6.+-&yyNFAy/6/-0yyWy462yyKM@y2/.02y
OFdkblrpAbmqepyKyQo^sbiqlqebFdkblrpAbmqep%25+1)2-+3&fkqebJliqbkColkqyyNFAy/6/-0yyWy462y
HIbv^o^yKyPi^vIbv^o^%32)25+/&+J^icroflkPqlojo^db^ka>o`eAorfaE^jrriOrkbqlqbjtfiipeltrmqmebim+yyNFAy/6/-0yyWy462yyKM@y20033y
QFkqlqebAbmqepyKyJ^icroflkPqlojo^db%14+-)6.+-&yyNFAy/6/-0yyWy462yyKM@y2/.02y

KQebJliqbkColkqLccbkpfsbyKy@lkqfkrbalfkda^fifbprkqfivlr`ljmibqba>aafqflk^i>oj^jbkqp+yy>FAy2546yy>@y/y
K>aafqflk^i>oj^jbkqpyKyLk`bvlre^sbbklrdeJ^ohp)`ljmibqb>aafqflk^i>oj^jbkqp+Obpbq^kaObil^aqebdrfab+yy>FAy2533yy>@y3yyNFAy/6/5.y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
