local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Ach_Horde_En_Well_Read_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502General|r ", "Well Read Achievement (70+)", nil, "Horde", "A", nil, function()
return [[
AAA

KMib^pbOb^ayKyQefpdrfab^pprjbpvlr^ob^qib^pq4-+Pljblcqebpb_llhp^obfkelpqfibwlkbplofkpq^k`bp+y

OA^i^o^kyKyQo^sbiqlA^i^o^k%33)02&yyWy2-1yy>FAy./11yy>@y/4y
RQebDr^oaf^kplcQfofpc^iyKy%33)02&Pb`lkaCillolcqebCfiqev>kfj^ifkA^io^kyy>FAy./11yy>@y/4yyWy2-1y

O@^sbokplcQfjbyKyQo^sbiqlqeb@^sbokplcQfjb%33+2)16+5&yyWy2-1yy>FAy./11yy>@y/6y
RQebH^ialobf^kaqebTbiilcBqbokfqvyKyALK$Qq^hbao^dlkfkqlqeb@^sbokp+%33+2)16+5&Orkfkqlqeb`^sbokrkqfivlrcfkafqfk^olljqlqebofdeq+yy>FAy./11yy>@y/6yyWy.3.y

OD^adbqw^kyKyQo^sbiqlD^adbqw^k%2/+-)/5+-&yy>FAy./11yy>@y.3yyWy.3.y
RLiaE^qobap*Qeb@lilkfw^qflklcH^ifjaloyKyKb^oqebclodb%2.+-)0-+0&yy>FAy./11yy>@y.3yyWy.3.y

OJridlobyKyQo^sbiqlJridlob%0/+3)16+2&yyWy6yy>FAy./11yy>@y1.y
K?llhpyKy>iiQeobb?llhp^obkbuqqlb^`elqebo+Qf`hqefppqbm+y
RFolkclodb*qeb>t^hbkfkdlcqebAt^osbpyKy%0/+3)16+2&yy>FAy./11yy>@y..yyWy6y
RQeb?^qqiblcDofj?^qliyKy%0/+3)16+2&yy>FAy./11yy>@y//yyWy6y
RT^olcqebQeobbE^jjbopyKy%0/+3)16+2&yy>FAy./11yy>@y1.yyWy6y

OO^q`ebqyKyQo^sbiqlO^q`ebq%35+1)36+.&yyWy..yy>FAy./11yy>@y.1y
R@e^odblcqebAo^dlkcifdeqpyKyKb^oD^wiltb%35+1)36+.&O^`ebqyy>FAy./11yy>@y3yyWy..y
R>o`efjlkab$pObqrok^kaqebCifdeqqlH^ifjaloyKyKb^oIfsOfwwibcfu%35+-)40+2&O^`ebqyy>FAy./11yy>@y1yyWy..y
RBufiblcqebEfdeBisbpyKyPb`lkacillo_^i`lkvlcqeb?i^`hpjfqe)kbuqqlFkk%34+.)40+1&O^`ebqyy>FAy./11yy>@y6yyWy..y
RP^odbo^p^kaqeb?bqo^v^iyKyQebFkk%34+-)42+-&O^`ebqyy>FAy./11yy>@y.6yyWy..y
RJlrkqEvg^i^kaFiifa^k$pDfcqyKyQebFkk%33+6)41+4&O^`ebqyy>FAy./11yy>@y.2yyWy..y
RIbqe^odvlcqebLo`pyKyMSM>iboq%32+2)13+4&Lk^`e^fofkpfabqebrmmbojlpqqltbofkKloqet^q`eEliayy>FAy./11yy>@y.1yyWy3-4y

O?llqv?^vyKyQo^sbiql?llqv?^v%1/+.)40+5&yyWy340yy>FAy./11yy>@y2y
RBjmfobp$C^iiyKyDlAltkqebo^jm^kabkqboqeb^iibvlkqebibcq^kabkqboqeb_rfiafkdlkqebofdeq+%1/+.)40+5&?llhpebiclkIbcq^pvlrbkqboollj+yy>FAy./11yy>@y5yyWy340y
RQebQtfkBjmfobpyKy%1/+.)40+5&P^jb_llhpebic+yy>FAy./11yy>@y04yyWy340y
RTo^qelcPlrici^vboyKy%1/+.)40+5&P^jb_llhpebic+yy>FAy./11yy>@y1/yyWy340y
RQebP`lrodblcIloa^bolkyKy%1.+6)40+1&Lk?llhpebic^`olppollj+yy>FAy./11yy>@y01yyWy340y
RQebPbkqfkbip^kaqebIlkdSfdfiyKy%1/+/)40+3&Ib^sb_rfiafkdqebt^vvlr`^jbfk)^kabkqboqeb_rfiafkd^`olppqeb^iibv+@ifj_qlsbovqlm^kaork^`olpp_ofadb+Qlmcillokbuqqlqeb_ba+yy>FAy./11yy>@y02yyWy340y
RPrktbii*QebC^iilcNrbi$Qe^i^pyKy%1.+-)41+1&?llqv?^v+Pb`lkacillolcfkklk^q^_ib+yy>FAy./11yy>@y/-yyWy340y
R?bvlkaqebA^ohMloq^iyKy%1-+3)40+5&?llqv?^v+Qlmcillolcfkklkq^_ibkbuqqlpqlsb+yy>FAy./11yy>@y2yyWy340y

OPqlk^oayKyQo^sbiqlPqlk^oa)Pt^jmlcPlooltp%16+0)22+1&yyWy05yy>FAy./11yy>@y0/y
RQebA^ohMloq^i^kaqebC^iilcPqlojtfkayKy%16+0)22+1&Pqlk^oa+?lqqljCillolc_rfiafkdkbuqqlfkk+yy>FAy./11yy>@y/2yyWy05y
ROfpblcqebEloabyKy%16+0)22+1&Pqlk^oa+Qlmcillolcp^jb_rfiafkd+yy>FAy./11yy>@y.5yyWy05y
RQebKbtEloabyKy%16+0)22+1&Pqlk^oa+Qlmcillolcp^jb_rfiafkd+yy>FAy./11yy>@y0/yyWy05y

OArphtllayKyQo^sbiqlArphtlla%40+4)12+.&yy>FAy./11yy>@y/3yyWy01y
RQebClrkafkdlcNrbi$Qe^i^pyKyMSM>IBOQClrkafkqebFkk^qA^ohpefob)Arphtlla%40+4)12+.&+Qefptfiici^dvlrMSM+yy>FAy./11yy>@y/3yyWy01y

OTbpqc^iiyKyQo^sbiqlTbpqc^ii%34)3/&yyWy06yy>FAy./11yy>@y0-y
RQebI^pqDr^oaf^kyKyMSM>iboq%2/+3)20+-&PbkqfkbiEfii+Lkq^_ibkbuqql_bap+yy>FAy./11yy>@y0-yyWy06y

OE^jjboc^iiyKyQo^sbiqlE^jjboc^ii%36+/)00+.&yy>FAy./11yy>@y.4yyWy.3y
ROfpblcqeb?illaBisbpyKyQlmcillolcFkk%36+/)00+.&yy>FAy./11yy>@y.4yyWy.3y

OQ^oobkJfiiyKyQo^sbiqlEfiip_o^aCllqefiip%23+4)14+2&yyWy/1yy>FAy./11yy>@y/1y
R>o^qelo^kaqebQoliiT^opyKyLkqebcillo%23+4)14+2&yy>FAy./11yy>@y0yyWy/1y
RQeb?foqelcqebIf`eHfkdyKyFk^`^phbqfkqebdo^sbv^oa%25+-)13+.&yy>FAy./11yy>@y/1yyWy/1y

O?ofiiyKyQo^sbiql?ofii%3-+6)2/+.&yy>FAy./11yy>@y.yyWy/-y
R>bdtvkk^kaqebAo^dlkErkqyKy?ofii%3-+6)2/+.&yy>FAy./11yy>@y.yyWy/-y

ORkabo`fqvyKyQo^sbiqlRkabo`fqv%16+3).1+5&yyWy05/y
R@fsfiT^ofkqebMi^drbi^kapyKy%34+3)04+/&Rkabo`fqv+Kb^oFkkhbbmboKloj^kyy>FAy./11yy>@y4yyWy05/y
RQebLiaDlap^kaqebLoabofkdlc>wbolqeyKy%23+-)2-+6&Rkabo`fqv+Qeb>mlqeb`^ofrjlkqebq^_ib+yy>FAy./11yy>@y00yyWy05/y
RF`b`oltk^kaqebColwbkQeolkbyKy%23+-)2-+6&Rkabo`fqv+Qeb>mlqeb`^ofrjlkqebq^_ib+yy>FAy./11yy>@y.-yyWy05/y
RHbi$Qerw^a^kaqebClojfkdlcqebP`lrodbyKy%23+-)2-+6&Rkabo`fqv+Qeb>mlqeb`^ofrjlkqebq^_ib+yy>FAy./11yy>@y./yyWy05/y

OPfisbojllk@fqvyKyQo^sbiqlPfisbojllk@fqv%35+2)31+.&yyWy15-y
RQeb?bqo^vbo>p`bka^kqyKy%35+2)31+.&Pfisbojllk@fqv+FkpfabSbi^^kf$p>o`^kbDllap+yy>FAy./11yy>@y/0yyWy15-y
RQeb>iif^k`blcIloa^bolkyKy%33+5)40+6&Pfisbojllk@fqv+Pb`lkacillolcT^vc^obo$pObpqlkcillokbuqql_ba+yy>FAy./11yy>@y/.yyWy15-y

OP`elilj^k`byKyNrbrbloQo^sbiqlP`elilj^k`b%36+.)40+.&yyWy//yy>FAy./11yy>@y/5y
KQebFks^pflklcAo^bkloyKyClrkafkqebolljtfqeIfif^kSlpp%23+3)1.+/&yyWy565/yy>FAy./11yy>@y/5y

OPqo^qelijbyKyNrbrbloQo^sbiqlPqo^qelijb%/3+6)..+5&yyWy/0yy>FAy./11yy>@y0.y
RQebPbsbkHfkdaljpyKy%0-+2)1-+4&yy>FAy./11yy>@y03yyWy432.y
RHfi$g^babk^kaqebPe^altM^`qyKy%0-+2)1-+4&yy>FAy./11yy>@y.0yyWy432.y
RT^olcqebPmfaboyKy%/2+5)4.+2&yy>FAy./11yy>@y1-yyWy432.y
RQebIf`eHfkdQofrjme^kqyKy%/2+2)4-+3&yy>FAy./11yy>@y0.yyWy432.y

KLmqflk^iyKyQebcliiltfkd_llhp^obclrkafk>iif^k`b`lkqoliiba^ob^p+Vlr$ii_bci^ddbaMSMfcvlr^qqbjmqqlbkqboPqlojtfkalovlr`lriaptfq`eql^k>iif^k`b`e^o^`qboqldbqqebpb_llhp+Qf`hqefppqbm+yy>FAy./11yy>@y05y
OPqlojtfka@fqvyKyQo^sbiqlPqlojtfka@fqv%52+.)/3+/&yy>FAy./11yy>@y05yyWy0-.y
R>cqboj^qelcqebPb`lkaT^oyKy%52+.)/3+/&Lkqebq^_ibqlqebofdeq^pvlrbkqboqebif_o^ov+yy>FAy./11yy>@y/yyWy0-.y
RQebTloiaQobb^kaqebBjbo^iaAob^jyKy%52+1)/0+0&Lkqebq^_ibfkqeb_^`h`lokbolcIf_o^ov+yy>FAy./11yy>@y06yyWy0-.y
RQebT^olcqeb>k`fbkqpyKy%52+1)/0+0&Lkqebq^_ibfkqeb_^`h`lokbolcIf_o^ov+yy>FAy./11yy>@y05yyWy0-.y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
