local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Argent_Tournament_Aspirant_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Argent Tournament|r ", "Argent Tournament (Aspirant Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

OPrkob^sboM^sfiflkyKyQo^sbiqlPrkob^sboM^sfiflkfkF`b`oltk%4/+3)//+3&yyWy16/y

K>``bmq0A^fivNrbpqyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&lccbop.lc0o^kalja^fivnrbpqpyyWy16/yyKM@y0021/y
>QebBadbLcTfkqboyLyyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&)A^fivyyNFAy.0342yyWy16/yyAyyKM@y0021/y
>>?i^abCfqClo>@e^jmflkyLyyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&)A^fivyyNFAy.0340yyWy16/yyAyyKM@y0021/y
>>TloqevTb^mlkyLyyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&)A^fivyyNFAy.0341yyWy16/yyAyyKM@y0021/y
>Qo^fkfkdFkQebCfbiayKy>j^ofbiPrkptlok%43+0)/1+1&)A^fivyyNFAy.0343yyWy16/yyAyyKM@y00325y
>Ib^okfkdQebObfkpyKyD^i^qef^?ofdeqa^tk%43+0)/1+1&)A^fivyyNFAy.0344yyWy16/yyAyyKM@y00326y

KJlrkqRmySyyKyBnrfmXEloabI^k`bZ^kadbq^Jlrkq%42+3)/0+3&lo%4.+52)/-&yyRy13-4-yyWy16/yyNFAy.0344y
@Ib^okfkdQebObfkpyKyBnrfmqebXEloabI^k`bZ^kajlrkqqebPrkob^sboE^thpqofaboclrka^qqebt^vmlfkq%4/+6).5+6&+RpbqebQorpq^_fifqvlk^JbibbQ^odbq2qfjbp)rpfkdAbcbka`lkpq^kqivqlhbbm0i^vboprm+ObcobpevlrojlrkqqebkrpbqebPefbia?ob^hbo^_fifqvlk^O^kdbaQ^odbqobmb^qfsbivrkqfisrikbo^_ibqebkrpbqebPefbia?ob^hbo^_fifqvlk^@e^odbQ^odbqqebkrpbqeb@e^odb^_fifqvqtf`btefibfqppefbiafpaltkyyNFAy.0344yyRy13-4-yyWy16/yyAyyKM@y0051/)00//6)00/10)00/4/y
@Qo^fkfkdFkQebCfbiayKyHfii^kvP`lrodb^olrkaqebt^vmlfkq%4.+1)04+6&yyNFAy.0343yyWy16/yyAyyKM@y0.450)0.4.5y
@>?i^abCfqClo>@e^jmflkyLyyKy>mmivqebXT^oqp*?*DlkbIfm?^ijZqebk,hfppqebcoldp^olrkaqebt^vmlfkq%3-+2)2.+2&fkDofwwivEfiip+Ob^mmivqebifm_^ij_bclobhfppfkdb^`ecoldyyRy11653yyNFAy.0340yyWy16-yyAyyKM@y00//1y

HIloaBsbo_i^wbyKyHfiiIloaBsbo_i^wb^olrkaqebt^vmlfkq%22)42+/&fk@ovpq^iplkdClobpq^kaillqefpXBsbo_rokfkdBj_boZqebkqf`hqefpl_gb`qfsbyyIy12--2yyWy2.-yyLyyAyyNFAy.0342yyKM@y00/56y
@QebBadbLcTfkqboyLyyKyCfkaQebJ^fabklcTfkqbo$p?ob^qeI^hb^qqebt^vmlfkq%1/+/).6+4&fkEltifkdCgloa^karpbXBsbo_rokfkdBj_boZyyRy12--2yyNFAy.0342yyWy16.yyAyyKM@y000-0y

K1XTfkqboEv^`fkqeZyKy@liib`q1XTfkqboEv^`fkqeZ^olrkaqebt^vmlfkq%4.)41+2&fkF`b`oltkqebkqf`hqefpl_gb`qfsbyyIy12---1yyWy16/yyLyyAyyQyyNFAy.0341yyL?Gy0/0.y
@>TloqevTb^mlkyLyyKyRpbqebXTfkqboEv^`fkqeZfkpfabqebofkdlccil^qfkdl_gb`qp^kaqebJ^fabktfii^mmb^o%6/+5)/2+1&+QebX?i^ablcAo^h$J^oZtfiipm^tkkbuqqlebo^cqbopljbaf^ildrb+Ao^dlk_ifdeqyyRy12---yyWy155yyNFAy.0341yyAyyKM@y00/40yyL?Gy5231y

OPrkob^sboM^sfiflkyKyQo^sbiqlPrkob^sboM^sfiflkfkF`b`oltk%4/+3)//+3&yyWy16/y

Q>?i^abCfqClo>@e^jmflkyLyyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&)A^fivyyNFAy.0340yyWy16/yyAyyKM@y0021/y
QQebBadbLcTfkqboyLyyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&)A^fivyyNFAy.0342yyWy16/yyAyyKM@y0021/y
Q>TloqevTb^mlkyLyyKyJ^dfpqboBafbkPrkeliilt%43+0)/1+1&)A^fivyyNFAy.0341yyWy16/yyAyyKM@y0021/y
QQo^fkfkdFkQebCfbiayKy>j^ofbiPrkptlok%43+0)/1+1&)A^fivyyNFAy.0343yyWy16/yyAyyKM@y00325y
QIb^okfkdQebObfkpyKyD^i^qef^?ofdeqa^tk%43+0)/1+1&)A^fivyyNFAy.0344yyWy16/yyAyyKM@y00326y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
