local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Dalaran_Jewelcrafting_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Dalaran Jewelcrafting (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

OA^i^o^kyKyQo^sbiqlA^i^o^k%1-+2)02+/&yyWy2-1y
K>``bmqA^fivNrbpqpyJAyyKy>``bmq^nrbpqcoljQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqyyWy2-1yyKM@y/54-.y
>Pefmjbkq7?illaG^ab>jribqyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./625yyWy2-1yyAyyKM@y/54-.y
>Pefmjbkq7?ofdeq>ojloObif`yLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63/yyWy2-1yyAyyKM@y/54-.y
>Pefmjbkq7DiltfkdFslovCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./626yyWy2-1yyAyyKM@y/54-.y
>Pefmjbkq7Fkqof`^qb?lkbCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63.yyWy2-1yyAyyKM@y/54-.y
>Pefmjbkq7PefcqfkdPrk@roflyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./630yyWy2-1yyAyyKM@y/54-.y
>Pefmjbkq7Tf`hbaPrk?oll`eyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63-yyWy2-1yyAyyKM@y/54-.y

@Pefmjbkq7?illaG^ab>jribqyLyyKyHfiiPfcobia^oOrkbhbbmbop^kaPfcobia^oPqlojJ^fabkp^kacfkaqebXSovhri>jribqZ^olrkaqebt^vmlfkq%1-)40&fkPqlojMb^hprpbfqtfqeDobbkXA^ohG^abZ^kaObaX?illapqlkbZyyRy1.656yyNFAy./625yyWy162yyAyyKM@y/600.)/60/0y
@Pefmjbkq7?ofdeq>ojloObif`yLyyKyCivqlTvojobpqQbjmib^kahfiiF`bObsbk^kqpfkAo^dlk_ifdeq%35)2-&ql`liib`qXBibjbkq^i>ojloP`o^mZ^karpbfqtfqeLo^kdbXErdb@fqofkbZ^kaObaX?illapqlkbZyyRy1/.-4yyNFAy./63/yyWy155yyAyyKM@y/3/50y
@Pefmjbkq7DiltfkdFslovCfdrofkbyLyyKyCivqlEltifkdCgloa^kahfiiPelsbiqrphClo^dbo%/3)//&ql`liib`qXPelsbiqrphFslovZ^karpbfqtfqe?irbX@e^i`balkvZ^kaMromibXPe^alt@ovpq^iZyyRy1/.-1yyNFAy./626yyWy16.yyAyyKM@y/6146y
@Pefmjbkq7Fkqof`^qb?lkbCfdrofkbyLyyKyCivqlH0fkQebPqlojMb^hp^kahfiiPqlojmb^hE^q`eifkdp%2/+2)40+2&cloXMolqlAo^dlk?lkbZrpbfqtfqeVbiiltXPrk@ovpq^iZ^kaDobbkXA^ohG^abZyyRy1/.-3yyNFAy./63.yyWy162yyAyyKM@y/6422y
@Pefmjbkq7PefcqfkdPrk@roflyLyyKyCiv_biltA^i^o^k^kahfiiIlpqPe^ka^o^iPmfofq%.6+3)1-+2&)%04+/)22+5&cloXP`lrodb@roflZrpbfqtfqeVbiiltXPrk@ovpq^iZ^kaMromibXPe^alt@ovpq^iZyyRy1/.-5yyNFAy./630yyWy2.-yyAyyKM@y0./0.y
@Pefmjbkq7Tf`hbaPrk?oll`eyLyyKyHfiiPqlojclodbaIlobpbbhbo%/3)35&fkpfabqeb`^sbfkQebPqlojMb^hpcloXFolkAt^oc?oll`eZrpbfqtfqeLo^kdbXErdb@fqofkbZ^kaVbiiltXPrk@ovpq^iZyyRy1/.-2yyNFAy./63-yyWy162yyAyyKM@y/6510y

QPefmjbkq7?illaG^ab>jribqyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./625yyWy2-1yyAyyKM@y/54-.y
QPefmjbkq7?ofdeq>ojloObif`yLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63/yyWy2-1yyAyyKM@y/54-.y
QPefmjbkq7DiltfkdFslovCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./626yyWy2-1yyAyyKM@y/54-.y
QPefmjbkq7Fkqof`^qb?lkbCfdrofkbyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63.yyWy2-1yyAyyKM@y/54-.y
QPefmjbkq7PefcqfkdPrk@roflyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./630yyWy2-1yyAyyKM@y/54-.y
QPefmjbkq7Tf`hbaPrk?oll`eyLyyKyQfjlqevGlkbp%1-+2)02+/&fkA^i^o^kyyNFAy./63-yyWy2-1yyAyyKM@y/54-.y

KDrfab@ljmibqb*Riqfj^qbTlTDrfab+`lj
]]
end)	end
	
	function Guide:Unload()
	end
end
