local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Eastern_Kingdom_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Eastern Kingdom Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

O?llqv?^vyKyQo^sbiql?llqv?^v%1/+5)36+.&yyWy340y
?HbipbvV^k`b9@llh;yWy340yyKy@llhfkdOb`fmfbpu6%2p*/d&%1/+5)36+.&yyKM@y/331y
?K^ohh9Mfo^qbPrmmifbp;yWy340yyKyXM^qqbok7?i^`hPt^pe_r`hibo$pPefoqZ%.2p&)XM^oolq@^dbZu/%1-pb^`e&%1/+4)36+/&yyKM@y/330y
?E^obkH^kj^b9Prmboflo?ltvbo;yWy340yyKyXAbkpbPeloq_ltZ%/d25p.1`&%1/+5)36+1&yyKM@y/506yyLy
?J^whPkfmbpelq9BkdfkbbofkdPrmmifbp;yWy340yyKyXP`ebj^qf`7>``ro^qbP`lmbZ%/-p&)XDvol`eolk^qljZ%0-p&)X?olkwbQr_bZ%5p&%10+/0)4-+//&yyKM@y/352y
?C^odlkJloq^i^h9Prmboflo>ojlobo;yWy340yyKyXEb^svKlq`eba?biqZ%.d61p0-`&%11+-)4-+-&yyKM@y/512yyLy
?Hfww?irkqpqofhb9J^`b`o^cqbo;yWy340yyKyXEb^svPmfhbaJ^`bZ%40p2.`&)XFolktllaJ^riZ%4-p1-`&%10)4-&yyKM@y/51-yyLy
?W^obk^@oljtfka9PrmbofloTb^mlkpjfqe;yWy340yyKyXMi^kp7Jllkpqbbi?ol^aptloaZ%11p&%10)4-&yyKM@y/15/y
?Ofhnfw9Ib^qebotlohfkdPrmmifbp;yWy340yyKyXM^qqbok7Dbj*pqraabaIb^qebo?biqZ%0-p&)XM^qqbok7Pe^altphfkDilsbpZ%02p&%10+/)4.+4&yyKM@y/366y
?UfwhDllapqfq`e9Q^filofkdPrmmifbp;yWy340yyKyXM^qqbok7@ofjplkPfih@il^hZ%./p&)XM^qqbok7Bk`e^kqbo$p@ltiZ%.-p&%10+3)40&yyKM@y/34-y
??ifuobwDllapqfq`e9Ib^qebotlohfkdPrmmifbp;yWy340yyKyXM^qqbok7Jroil`P`^ib?o^`bopZ%/5p&)XM^qqbok7Qef`hJroil`>ojloZ%3p2-`&%1/+50)41+./&yyKM@y/513y
?@o^whPm^ohp9CfobtlohpJbo`e^kq;yWy340yyKyP`ebj^qf`7DobbkCfobtloh%.5p&%10)4/+5&yyKM@y/505y
?Jop+D^kq9@llhfkdQo^fkbo#Prmmifbp;yWy340yyKyXOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&)XOb`fmb7Rkabojfkb@i^j@eltaboZ%0-p&%1/+3)4/+5&yyKM@y21/0/y
?Divu?obtofdeq9>i`ebjvPrmmifbp;yWy340yyKyXOb`fmb7ColpqMolqb`qflkMlqflkZ%/-p&)XOb`fmb7K^qrobMolqb`qflkMlqflkZ%/-p&)XDob^qboEb^ifkdMlqflkZ%2p&)XJ^k^MlqflkZ%1+5p&%1/+34)42+-3&yyKM@y/515y
?Grq^h9?i^abQo^abo;yWy340yyKyXMi^kp7E^oabkbaFolkPeloqptloaZ%0-p&%1.+3)41+-&yyKM@y/510y
?@lt^oaiv@olp_v9Q^filofkdPrmmifbp;yWy340yyKyXM^qqbok7>ajfo^i$pE^qZ%4-p&%1-+6)5/+2&yyKM@y/34/y

ODolj$dli?^pb@^jmyKyQo^sbiqlDolj$dli?^pb@^jm)KloqebokPqo^kdibqelok%04+13)16+-1&yyWy04y
?Rqelh9Dbkbo^iPrmmifbp;yWy04yyKyXOb`fmb7Pmf`ba@efif@o^_Z%.d/-p&%04+13)16+-1&yyKM@y..16y
?Se^oo9PrmbofloTb^mlkpjfqe;yWy04yyKyXA^ofkdAfohZ%/d23p/1`&)XJfakfdeq>ubZ%0d//p41`&)XMi^kp7J^ppfsbFolk>ubZ%02p/-`&%05+3)16+-&yyKM@y..13y
?Kboofpq9Qo^abDllap;yWy04yyKyXAbpfdk7Qorbpfisbo@o^_Z%3-p&)XOb`fmb7@roflrpivQ^pqvLjbibqZ%.3p&)XOb`fmb7GrkdibPqbtZ%0-p&)XOb`fmb7Ol^pqO^mqloZ%2-p&%06+/3)2.+-2&yyKM@y..15y

?Dk^w?irkaboci^jb9BkdfkbbofkdPrmmifbp;yWy04yyKyXP`ebj^qf`7Jb`e^kf`^iAo^dlkifkdZ%.d&)XDvol`eolk^qljZ%0-p&)X?olkwbQr_bZ%5p&%34+2)3.&yyKM@y/354y
?Hk^w?irkaboci^jb9BkdfkbbofkdPrmmifbp;yWy04yyKyXP`ebj^qf`7Ab^aivP`lmbZ%0-p&)XDvol`eolk^qljZ%0-p&)X?olkwbQr_bZ%5p&%34+4)3.+.&yyKM@y5346y

OKbpfkdt^ov$pBumbafqflkyKyQo^sbiqlKbpfkdt^ov$pBumbafqflk%10+4-)/0+.3&yyWy04y
?G^nrfifk^Ao^jbq9Prmboflo>ub`o^cqbo;yWy04yyKyXMi^kp7J^ppfsbFolk>ubZ%11p&)XJfakfdeq>ubZ%1+0d&%10+4-)/0+.3&yyKM@y/150y

OPqlk^oayKyQo^sbiqlPqlk^oa)Pt^jmlcPlooltp%13+5)2/&yyWy05y
?Qeo^ilpe9@ilqe#Ib^qebo>ojloJbo`e^kq;yWy05yyKyX@fkabo`ilqeIbddfkdpZ%1d05p/5`&)XM^ibIbddfkdpZ%0d16p55`&%13+5)2/&yyKM@y651yyLy
??^k^i^pe9Qo^abPrmmifbp;yWy05yyKyXClojri^7Bk`e^kq?o^`bo*Abcib`qflkZ%25p&)XAbpfdk7?i^`hMb^oiM^kqeboZ%2-p&)XOb`fmb7@^ooflkPromofpbZ%2-p&)XOb`fmb7Pmf`ba@efif@o^_Z%.+/d&%13+24)23+56&yyKM@y656y
?O^oq^o9>i`ebjvPrmmifbp;yWy05yyKyXOb`fmb7BifufolcAbjlkpi^vfkdZ%.d&)XPrmbofloEb^ifkdMlqflkZ%.-p&)XDob^qboJ^k^MlqflkZ%./p&%14+.3)24+..&yyKM@y5.44y
?Qeriq^wlo9>i`ebjvPrmmifbp#Ob^dbkqp;yWy05yyKyXPrmbofloEb^ifkdMlqflkZ%.-p&)XDob^qboJ^k^MlqflkZ%./p&%14+2.)20+1/&yyKM@y650y
?De^o^pe9?i^`hpjfqefkdPrmmifbp;yWy05yyKyXMi^kp7JfqeofiP`^ib?o^`bopZ%3-p&%14+//)2/+.-&yyKM@y5.43y

OE^jjboc^iiyKyQo^sbiqlE^jjboc^ii)>o^qefEfdei^kap%36+/.)00+2-&yyWy.3y
?Hbbk^9Qo^abDllap;yWy.3yyKyXAbpfdk7Or_v@oltklcObpqlo^qflkZ%3-p&)XM^qqbok7?^o_^of`IbddfkdpZ%3p2-`&)XOb`fmb7@roflrpivQ^pqvLjbibqZ%.3p&)XOb`fmb7Ol^pqO^mqloZ%2-p&%36+/.)00+2-&yyKM@y/5/.y
?Qrkhh9Ib^qebotlohfkdPrmmifbp;yWy.3yyKyXM^qqbok7O^mqloEfabE^okbppZ%/2p&%4-+-2)02+1-&yyKM@y/5.6y
?Grk$e^9Q^filofkdPrmmifbp;yWy.3yyKyXM^qqbok7>wrobPfih@il^hZ%.2p&%34+44)04+1-&yyKM@y3241y
?Jr$rq^9?ltvbo;yWy.3yyKyXAbkpbPeloq_ltZ%/d3p2/`&%34+3)01+/&yyKM@y6222yyLy
?A^ohFolkBkqobmobkbro9Pmb`f^ifqvDllap;yWy.3yyKyS^oflrpdobbk^ojlo^katb^mlkp%45p26`*/d1p4/`&%1/+3)6-+3&yyKM@y0.5-yyLy

OObs^kqrphSfii^dbyKyQo^sbiqlObs^kqrphSfii^db)QebEfkqboi^kap%5-+02)5.+15&yyWy05/y
?H^qlljqeb>kdibo9CfpefkdQo^fkbo#Prmmifbp;yWy/3yyKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&%5-+02)5.+15&yyKM@y.141-y
?LqelJlgf$hl9@llhfkdPrmmifbp;yWy/3yyKyXOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&%46+05)46+-4&yyKM@y.1405y

?DfddbqWfm`lfi9Qo^abPrmmifbp;yWy/3yyKyXM^qqbok7Folkcb^qeboPelriabopZ%.d1-p&%01+2)05+2&yyKM@y./625y
?OrmmlWfm`lfi9BkdfkbbofkdPrmmifbp;yWy/3yyKyXP`ebj^qf`7JfqeofiJb`e^kf`^iAo^dlkifkdZ%1-p&)X?olkwbQr_bZ%5p&)XDvol`eolk^qljZ%0-p&%01+0)04+5&yyKM@y/355y

OEfiip_o^aCllqefiipyWy/1yyKyQo^sbiqlEfiip_o^aCllqefiip%43+3)25+2&y
?Dblodb@^ka^oqb9Ib^qebotlohfkdPrmmifbp;yWy/1yyKyXM^qqbok7DobbkIb^qebo>ojloZ%.3p&%43+3)25+2&yyKM@y/365y
?HofpIbd^`b9CobbtebbifkdQo^abptlj^k;yWy/1yyKyS^oflrpIb^qeboDllap%02+/5p*.+1d&%35+53)25+62&yyKM@y0203y

OO^sbkeliaqJ^kloyWy/1yyKyQo^sbiqlO^sbkeliaqJ^klo%4.+10)12+14&y
?W^kPefspmolhbq9Pmb`f^ifqvBkdfkbbo;yWy/1yyKyXP`ebj^qf`7Dkljfpe@il^hfkdAbsf`bZ%/1p&)XDvol`eolk^qljZ%0-p&altkpq^fofkqeb_^pbjbkq%4.+10)12+14&yyKM@y3444y
?PjradbQerkabotlla9MlfplkPrmmifbp;yWy/1yyKyXOb`fmb7QefpqibQb^Z%/p&%4.+1)12+/&yyKM@y3446y

OQ^oobkJfiiyKyQo^sbiqlQ^oobkJfii%24+3)12+/&yyWy/1y
?Abo^hKfdeqc^ii9@llh;yWy/1yyKyXOb`fmb7?ofpqibTefphbo@^qcfpeZ%6p3-`&)XOb`fmb7P^dbcfpeAbifdeqZ%1-p&)XOb`fmb7PjlhbaP^dbcfpeZ%1p&%24+3)12+/&yyKM@y/064y
?@eofpqlmeGbcc`l^q9Qo^abpj^k;yWy/1yyKyXM^qqbok7Qef`hJroil`>ojloZ%2p/-`&)XOb`fmb7Pe^altMolqb`qflkMlqflkZ%4p/-`&%24+1)14+3&yyKM@y/060y
?Lqq9Tb^mlkpjfqe;yWy/1yyKyS^oflrpdobbktb^mlkp%.d.1p.6`*/d22p03`&%24+3)14+3&yyKM@y0206y
?J^iibkPt^fk9Q^filofkdPrmmifbp;yWy/1yyKyXM^qqbok7?irbLsbo^iipZ%0p/-`&)XM^qqbok7A^ohPfihPefoqZ%5p5-`&%25+-)14+5&yyKM@y/061y
?Wfufi9Jbo`e^kqPrmobjb;yWy/1yyKyM^qolip_bqtbbkQ^oobkJfii^kaPlrqepelob)XM^qqbok7B^oqebkIb^qeboPelriabopZ%/-p&)XM^qqbok7ObaTllibk?^dZ%2p&)XP`ebj^qf`7Dl_ifkGrjmbo@^_ibpZ%/-p&)S^oflrpdobbkp%.-p*5-p/-`&%23+-)13+1&%2/+5)15&%2/+5)2/+1&%2/+3)23+/&%16+/)33+5&yyKM@y0204y
?E^oi^kaT^iabh9Tb^mlkpjfqe;yWy/1yyKyX?ibppba@i^vjlobZ%65p16`&)XBub`rqflkbo$pPtloaZ%.d.1p.6`&%/5+5)31+-&yyKM@y144./yyLy

OOrfkplc>iqbo^`yKyQo^sbiqlOrfkplc>iqbo^`%11)/.+5&yyWy/1y
??ol$hfk9>i`ebjvPrmmifbp;yWy/1yyKyXOb`fmb7ColpqLfiZ%/2p&)XDob^qboEb^ifkdMlqflkZ%2p&)XJ^k^MlqflkZ%1+5p&%11)/.+5&yyKM@y/15-y

OPfisbomfkbClobpqyKyQo^sbiqlPfisbomfkbClobpq%21+-)5/+0&yyWy/.y
?IblP^ok9Bk`e^kqfkdPrmmifbp;yWy/.yyKyXClojri^7Bk`e^kq/ETb^mlk*IbppboFkqbiib`qZ%2p&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&)XIbppboJ^df`Bppbk`bZ%5p&)XPqo^kdbArpqZ%5p&%21+-)5/+0&yyKM@y2425y

OQebPbmri`eboyKyQo^sbiqlQebPbmri`ebo%11+3)06+3&yyWy/.y
?>ibu^kaobIbcbsob9Ib^qebo>ojloJbo`e^kq;yWy/.yyKyX>dfib?llqpZ%/.p5`&)XPq^_ib?llqpZ%.3p&%11+3)06+3&yyKM@y022/yyLy
?>kaob^?lvkqlk9@ilqefbo;yWy/.yyKyS^oflrpdobbk`ilqe^ojlo%..p52`*/1p30`&%11+3)06+/&yyKM@y0221yyLy
?K^af^Sboklk9?ltvbo;yWy/.yyKyXCfkbIlkd_ltZ%05p6-`&%11+5)06+5&yyKM@y6220yyLy
?>kaobtEfi_boq9Qo^abPrmmifbp;yWy/.yyKyXM^qqbok7?irbIfkbkOl_bZ%0p&)XM^qqbok7Jroil`P`^ib?biqZ%2p2-`&)XM^qqbok7Jroil`P`^ib?ob^pqmi^qbZ%3p&)XM^qqbok7ObaIfkbk?^dZ%/p&)XOb`fmb7Pjlhba?b^oJb^qZ%/p2-`&%10+/)1-+3&yyKM@y0223y
?Ifiiv9Bk`e^kqfkdPrmmifbp;yWy/.yyKyXClojri^7Bk`e^kq@ebpq*IbppboJ^k^Z%1p&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&)XIbppboJ^df`Bppbk`bZ%5p&)XPqo^kdbArpqZ%5p&%13+56)1-+03&yyKM@y2424y

OQebAb`obmfqCfbiapyKyQo^sbib^pqlcQebPbmri`eboqlqebal`hp%26+1)00+1&yyWy/.y
?Hfiif^kP^k^qe^9Cfpeboj^k;yWy/.yyKyXOb`fmb7Ilkdg^tJraPk^mmboZ%0p/-`&)XOb`fmb7O^fk_ltCfk>i_^`lobZ%0p/-`&%26+1)00+1&yyKM@y2415y
?T^ii^`bqeb?ifka9Tb^mlkpjfqe;yWy/.yyKyS^oflrpdobbktb^mlkp%15p3/`*.d1/p40&%00+-).4+5&yyKM@y0201yyLy

O?ofiiyKyQo^sbiql?ofii%3.+-)2/+2&)Qfofpc^iDi^abpyyWy/-y
?>_fd^fiPefbi9Qo^abPrmmifbp;yWy/-yyKyXOb`fmb7@ofpmv?^qTfkdZ%/2`&%3.+.3)2-+65&yyKM@y/..5y
?Pbifk^Tbpqlk9>i`ebjv#Ebo_^ifpjPrmmifbp;yWy/-yyKyXEbo_Mlr`eZ%.-p&)s^oflrpEbo_p%1-`*.p&)XIbppboEb^ifkdMlqflkZ%.p&%26+30)2/+/3&yyKM@y0215y
?@lkpq^k`b?ofp_lfpb9>mmobkqf`b@ilqefbo;yWy/-yyKyXM^qqbok7?irbIfkbkSbpqZ%.p6-`&%2/+3)22+3&yyKM@y02//y
?J^oqfkbQo^j_i^v9CfpefkdPrmmifbp;yWy/-yyKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/+2p&)XOb`fmb7?ofiif^kqPj^iicfpeZ%1-`&)XOb`fmb7PifqebophfkJ^`hbobiZ%1-`&%32+5)26+4&yyKM@y022-y

OQeb?rit^ohyKyQo^sbiqlQeb?rit^oh%50+0)36+1&yyWy/-y
?TbodQef`h_i^ab9Ib^qebotlohfkdPrmmifbp;yWy/-yyKyXM^qqbok7PqlojpeolraM^kqpZ%.d3-p&)XM^qqbok7Tf`hbaIb^qeboD^rkqibqpZ%.d/-p&%50+00)36+11&yyKM@y./610y

O@^boA^ooltyKyQo^sbiql@^boA^oolt%35+.)44+2&yyWy//y
?J^dkrpColpqt^hbyKyXMi^kp7PqlojD^rkqibqpZ%1d&%35+.)44+2&yyWy//y

OIfdeq$pElmb@e^mbiyKyQo^sbiqlIfdeq$pElmb@e^mbi)B^pqbokMi^rdbi^kap%41+02)2-+6.&yyWy/0y
?G^pbC^oi^kb9Qo^abPrmmifbp;yWy/0yyKyXAbpfdk7Ofkdlc?fqqboPe^altpZ%.d&%41+02)2-+6.&yyKM@y./61.y

KDrfab@ljmibqb
]]
end)	end
	
	function Guide:Unload()
	end
end
