local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Horde_Expedition")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "Horde Expedition (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

K@ljmibqbMob*NrbpqyKyVlrtfiikbbaql`ljmibqbF`b`oltk%44*5-Ilob&coljqebIbsbifkddrfabpb`qflk_bclobvlr`^krpbqefpdrfabyyNFAy.00.0y

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWy16/yyTOy
>Hbbmfkdqeb>iif^k`b?ifkayKyPhv*Ob^sboHloj?i^`hp`^olkLodofj$pE^jjboyyNFAy.000.yyWy16/yyAyyKM@y0-5/1y
>?illalcqeb@elpbkyKyT^o_ofkdboA^slpOfleqlkLodofj$pE^jjboyyNFAy.000-yyWy16/yyAyyKM@y0/0-.y

@Hbbmfkdqeb>iif^k`b?ifkayKyRpbXPDJ*0Zqlhfii3Phv_ob^hboOb`lkCfdeqbop)rpbqebq^odbq_rqqlkqlj^hbfqb^pv%14+0)1-&yyRy11/./yyNFAy.000.yyWy16/yyAyyKM@y0/.56y

>>pp^riq_vDolrkayKyHlo$holkPnr^aIb^abo%25+0)13+.&yyNFAy.00-.yyWy16/yyAyyKM@y0.500y
@>pp^riq_vDolrkayKyBp`loqqebPhv_ob^hboqollmpyyNFAy.00-.yyWy16/yyAy
@?illalcqeb@elpbkyKyHfii/-VjfoebfjSovhri^qVjfoebfj%26)21&yyNFAy.000-yyWy16/yyAyyKM@y0./25)0./34)0./3/y
Q>pp^riq_vDolrkayKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00-.yyWy16/yyAyyKM@y0.501y

>>pp^riq_v>foyKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00.-yyWy16/yyAyyKM@y0.501y
@>pp^riq_v>foyKyDlql%26+3)13+-&^kajlrkqqeb>fomi^kb)j^hbprobqebob^obfkcfiqo^qlopfkqebmi^kb_bclobvlrdlyyNFAy.00.-yyWy16/yyAy
Q>pp^riq_v>foyKyDolrka@ljj^kaboUrqgg^%25+0)13&yyNFAy.00.-yyWy16/yyAyyKM@y0.501y

>HfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWy16/yyAyyKM@y0.45.y
@HfkdlcqebJlrkq^fkyKyJlrkqQerkabo_lj_$pGrjm_lqkbuqqlvlr^kagrjmvlrot^vrmqlqebmfiblc_lkbp%21)26&yyNFAy.0/50yyWy16/yyAyyKM@y0.44-y
QHfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWy16/yyAyyKM@y0.45.y
@Pi^sbpqlP^olkfqbyKyDlqlqebP^olkfqbJfkbp%23)24&)pfjmivq^ihqlqebP^olkfqbJfkbPi^sbpfkqebjfkb)vlre^sb^`e^k`bqe^qqebvtfiiorklrqlcqebjfkb^kadfsbvlrnrbpq`obafq)loqrokelpqfiblkvlryyNFAy.00-/yyWy16/yyAyyKM@y0.064y

QHfkdlcqebJlrkq^fkyKy?i^pqQerkabo_lj_%2/)24+3&yyNFAy.0/50yyWy16/yyAyyKM@y0.45.y

OLodofj$pE^jjboyKyQefpfpqebEloabPefmqe^qcifbp^olrkaF`b`oltk%33)00&)%36+2)/4+1&)%34+1)2/+2&yyWy16/yyTOy
QHbbmfkdqeb>iif^k`b?ifkayKyPhv*Ob^sboHloj?i^`hp`^olkLodofj$pE^jjboyyNFAy.000.yyWy16/yyAyyKM@y0-5/1y
Q?illalcqeb@elpbkyKyT^o_ofkdboA^slpOfleqlkLodofj$pE^jjboyyNFAy.000-yyWy16/yyAyyKM@y0/0-.y

O@lknrbpqEliayKyQo^sbiql@lknrbpqEliafkDofwwivEfiip%/3+2)32+5&yyNFAy./.4-yyAyyWy16-y

>?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyWy16-yyAyyKM@y/4./-y
@?i^`hofsbo?o^tiyKyHfii.->iif^k`bKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./.4-yyWy16-yyAyyKM@y/4..4y
Q?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyWy16-yyAyyKM@y/4./-y

>Hbbm$BjlkQebfoEbbipyKy@ljj^kabo?^odlh%01+2)00&yyNFAy.//51yyWy16-yyAyyKM@y/412.y
>Peobaqeb>iif^k`byKyDobhh%01+2)0/+3&yyNFAy.//4-yyWy16-yyAyyKM@y/41/0y
>J^hfkdObm^fopyKyIrow%01+0)0/+3&yyNFAy.//5-yyWy16-yyAyyKM@y/41//y
>LsbotebijbayKy>rj^k^%00+6)0/+5&yyNFAy.//63yyWy16-yyAyyKM@y/4131y

@LsbotebijbayKyCfkaqebTlrkabaPhfojfpebop%02)1-&^karpbqebXObkbtfkd?^ka^dbZlkqebjyyRy04243yyNFAy.//63yyWy16-yyAyyKM@y/4130y
@J^hfkdObm^fopyKy@liib`q1Dollsba@ldp)0Klq`ebaPmol`hbqp^ka/EfdeQbkpflkPmofkdp^olrkaqebt^vmlfkq%02)1-&yyNFAy.//5-yyWy16-yyAyyL?Gy12.)4---)335.y
@Peobaqeb>iif^k`byKy>``bmq^Peobaabo%02)1-&^ka_ofkdfq_^`hqlDobhh%01+2)0/+3&yyNFAy.//4-yyWy16-yyAyyKM@y/4021y
@Hbbm$BjlkQebfoEbbipyKyHfii.2>iif^k`bKM@ploMi^vbopfk?irbPhvIlddfkdDolrkap%02)1-&yyNFAy.//51yyWy16-yyAyyKM@y/4142)/4130)/4123y

QPeobaqeb>iif^k`byKyDobhh%01+2)0/+3&yyNFAy.//4-yyWy16-yyAyyKM@y/41/0y
QJ^hfkdObm^fopyKyIrow%01+0)0/+3&yyNFAy.//5-yyWy16-yyAyyKM@y/41//y
QLsbotebijbayKy>rj^k^%00+6)0/+5&yyNFAy.//63yyWy16-yyAyyKM@y/4131y
QHbbm$BjlkQebfoEbbipyKy@ljj^kabo?^odlh%01+2)00&yyNFAy.//51yyWy16-yyAyyKM@y/412.y

KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
