local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Kalimdor_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Kalimdor Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OLodofjj^oyKy?bdfkfkLodofjj^oyyWy0/.y

OBsboillhyKyQo^sbiqlBsboillh)Tfkqbopmofkd%3-+5)04+5&yyWy/5.y
?BsfbTefoi_obt9>i`ebjvPrmmifbp;yWy/5.yyKyXPrmbofloEb^ifkdMlqflkZ%.-p&)XDob^qboJ^k^MlqflkZ%./p&%26+/)2-&yyKM@y...55y
?Efjjfh9Clla#Aofkh;yWy/5.yyKyXOb`fmb7JlkpqboLjbibqZ%.d/-p&%26+5)2.+2&yyKM@y...54y
?Nf^9Qo^abPrmmifbp;yWy/5.yyKyXAbpfdk7Kb`hi^`blcqebAf^jlkaQltboZ%.d02p&)XClojri^7Bk`e^kq@ebpq*J^gloEb^iqeZ%.d3-p&)XM^qqbok7Colpqp^_bo?llqpZ%.d3-p&)XM^qqbok7Jllk`ilqeZ%/d&)XM^qqbok7Orkb`ilqe?^dZ%.d/-p&%26+4)16+0&yyKM@y...56y
?UfwwboCfww_liq9BkdfkbbofkdPrmmifbp;yWy/5.yyKyXP`ebj^qf`7Abif`^qb>o`^kfqb@lksboqboZ%/d&)XP`ebj^qf`7CrpbaTfofkdZ%.p3-`&)XP`ebj^qf`7DvolcobbwbF`bObcib`qloZ%.d/-p&)XP`ebj^qf`7J^pqbotlohQ^odbqArjjvZ%.d3-p&)XP`ebj^qf`7MltbocriPb^clofrj@e^odbZ%.d3-p&)s^oflrpprmmifbp%.3`*0-p&%26+/)2-+.&yyKM@y...52y

OJllkdi^abyKyQo^sbiqlJllkdi^ab%23+3)/6+5&yyWy/1.y
?He^obalk9Ifdeq>ojloJbo`e^kq;yWy/1.yyKyXTbiiLfiba@il^hZ%/d/1p.3`&%23+3)/6+5&yyKM@y./-/0yyLy
?A^ok^ii9Q^filofkdPrmmifbp;yWy/1.yyKyXM^qqbok7Orkb`ilqe@il^hZ%.d/-p&)XM^qqbok7Orkb`ilqeOl_bZ%.d/-p&%2.+11)00+/1&yyKM@y461-y
?K^of^kk^9?ltvbo;yWy/1.yyKyXPvis^kPeloq_ltZ%4d55p/6`&%20+/)1/+3&yyKM@y./-/6yyLy
?Ilobi^bTfkqboplkd9Qo^abPrmmifbp;yWy/1.yyKyXClojri^7Bk`e^kq@il^h*PrmbofloAbcbkpbZ%/d&)XM^qqbok7Cbi`ilqeM^kqpZ%.d3-p&%15+/.)1-+.2&yyKM@y./-//y

OWlo^j$d^oLrqmlpqyKyQo^sbiqlWlo^j$d^oLrqmlpq)>pebks^ib%..+5)01+.&yyWy10y
?Tfh$Q^o9CfpeJbo`e^kq#Prmmifbp;yWy10yyKyXOb`fmb7JfqeofiEb^aQolrqZ%//p&)XOb`fmb7Ol`hp`^ib@laZ%//p&%.-+52)00+46&yyKM@y./63/y

OPrkOl`hObqob^qyKyQo^sbiqlPrkOl`hObqob^q)Pqlkbq^ilkJlrkq^fkp%12+2)26+2&yyWy5.y
?Hritf^9Qo^abPrmmifbp;yWy5.yyKyXClojri^7Bk`e^kq?o^`bo*IbppboPqobkdqeZ%/2p&)XClojri^7Bk`e^kq@il^h*Jfklo>dfifqvZ%5p&%15+36)3.+2/&yyKM@y./-10y
??lo^ka9?ltvbo;yWy5.yyKyXCfkbIlkd_ltZ%15p3/`&%15+3)3.+1&yyKM@y6216yyLy

O?illaellcSfii^dbyKyQo^sbiql?illaellcSfii^db)Jridlob%14+2)22+.&yyWy6y
?E^okIlkd`^pq9CfpefkdPrmmifbp;yWy6yyKyXOb`fmb7?ofiif^kqPj^iicfpeZ%1-`&)XOb`fmb7Ilkdg^tJraPk^mmboZ%1p&)X>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&%14+33)21+44&yyKM@y261-y
?Trkk^A^ohj^kb9Qo^abDllap;yWy6yyKyXOb`fmb7Ol^pqbaHlalJb^qZ%/p1-`&%13+04)24+44&yyKM@y0-5.y

OPe^altmobvSfii^dbyKyQo^sbiqlPe^altmobvSfii^db)Abpli^`b%//+4)4/+.&yyWy.-.y
?Tri^k9@llhfkdPrmmifbp;yWy.-.yyKyXOb`fmb7JfqeofiEb^aQolrqZ%//p&)XOb`fmb7Ol`hp`^ib@laZ%//p&)XOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&%/3+/)36+5&yyKM@y./-00y
?E^b$Tfi^kf9>ub`o^cqbo;yWy.-.yyKyXJbo`fibpp>ubZ%0d.p62`&)XJfakfdeq>ubZ%0d//p41`&%/2+3)4-+5&yyKM@y./-12y

ODelpqT^ihboMlpqyKyQo^sbiqlDelpqT^ihboMlpq%2-+64)20+22&yyWy.-.y
?Hfobbk^9Qo^abDllap;yWy.-.yyKyXM^qqbok7>wrobPfihDilsbpZ%.-p&)XOb`fmb7@^ooflkPromofpbZ%2-p&)XOb`fmb7Eb^svHlalPqbtZ%4-p&%2-+64)20+22&yyKM@y6303y
?Jrro^k9PrmbofloJ^`b`o^cqbo;yWy.-.yyKyXMi^kp7PlifaFolkJ^riZ%0-p&%22+4)23+2&yyKM@y5545y

O@^jm>q^v^yKyQo^sbiql@^jm>q^v^)Cbo^i^p%1-+5).2+/&yyWy./.y
?JlolPrkdo^fk9Qo^abPrmmifbp;yWy./.yyKyXOb`fmb7P^dbcfpeAbifdeqZ%1-p&)XOb`fmb7PjlhbaP^dbcfpeZ%1p&%1-+5).2+/&yyKM@y1-141y

OPqlkbj^riEliayKyQo^sbiqlPqlkbj^riElia%2/+50)14+./&yyWy./.y
?G^kdaloPtfcqpqofabo9Ib^qebotlohfkdPrmmifbp;yWy./.yyKyXM^qqbok7DobbkTebim?o^`bopZ%/5p&)XM^qqbok7Kfdeqp`^mbPelriabopZ%1-p&)XM^qqbok7IfsfkdPelriabopZ%.d1-p&)XM^qqbok7QroqibP`^ibDilsbpZ%02p&%2/+50)14+./&yyKM@y4521y

O@^jmJlg^`ebyKyQo^sbiql@^jmJlg^`eb%43+-)10+2&yyWy./.y
??olkh9>i`ebjvPrmmifbp;yWy./.yyKyXOb`fmb7DelpqAvbZ%6-p&)XOb`fmb7K^qrobMolqb`qflkMlqflkZ%/-p&)XDob^qboJ^k^MlqflkZ%./p&)XPrmbofloEb^ifkdMlqflkZ%.-p&%43+-2)10+/2&yyKM@y5.25y
?@^tfkaQorb^fj9Drkpjfqe#?ltvbo;yWy./.yyKyXPvis^kPeloq_ltZ%3d0-p31`&%41+5)12+3&yyKM@y6215yyLy
?Pebbkao^Q^iido^pp9Qo^abPrmmifbp;yWy./.yyKyXOb`fmb7?^hbaP^ijlkZ%/d&)XOb`fmb7ElqTlicOf_pZ%2-p&)XOb`fmb7Il_pqboPqbtZ%/d&)XOb`fmb7JfdeqcfpePqb^hZ%/d&%41+2)1/+5&yyKM@y5.12y
?Tlo_Pqolkdpqfq`e9Ifdeq>ojloJbo`e^kq;yWy./.yyKyX?ofiif^kqOba@il^hZ%.d44p&)XTbiiLfiba@il^hZ%/d/1p&%41+4)1/+3&yyKM@y5.26yyLy

O@bk^oflkEliayKyQo^sbiql@bk^oflkElia)Pfifqerp%42+2)11+1&yyWy/3.y
?H^kf^9Bk`e^kqfkdPrmmifbp;yWy/3.yyKyXClojri^7IbppboJ^k^LfiZ%.d&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XClojri^7Tfw^oaLfiZ%/d&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&)XM^qqbok7Bk`e^kqbaOrkb`ilqe?^dZ%/d&)XIbppboJ^df`Bppbk`bZ%5p&)XPqo^kdbArpqZ%5p&%22+3-)04+/.&yyKM@y.21.6y
?Jfpeq^9Qo^abPrmmifbp;yWy/3.yyKyXAbpfdk7Bjbo^ia@oltklcAbpqor`qflkZ%.d&%20+45)01+00&yyKM@y.2.46y

OS^ilo$pObpqyKyQo^sbiqlS^ilo$pObpq%5.+06).5+03&yyWy/3.y
?W^kklhEfabmfbo`bo9Ib^qebotlohfkdPrmmifbp;yWy/3.yyKyXM^qqbok7Eb^svP`lomfa?o^`bopZ%.d/-p&)XM^qqbok7Eb^svP`lomfaEbijZ%/d2-p&%5.+06).5+03&yyKM@y./623y

OJ^ope^i$pPq^kayKyQo^sbiqlJ^ope^i$pObcrdbRk$Dlol@o^qbo%21+41)3/+14&yyWy/-.y
?Kbod^i9Dbkbo^iDllap;yWy/-.yyKyXM^qqbok7Absfip^roD^rkqibqpZ%/d/-p&%21+41)3/+14&yyKM@y./626y

OD^adbqw^kyKyQo^sbiqlD^adbqw^k)Q^k^ofp%2/+2)/4+6&yyWy.3.y
?FkkhbbmboCfwwdofj_ib9Fkkhbbmbo;yWy.3.yyKyXOb`fmb7QbkaboTlicPqb^hZ%.d/-p&%2/+25)/4+-.&yyKM@y4400y
?AfodbNrfh`ib^sb9?rq`ebo;yWy.3.yyKyXOb`fmb7QbkaboTlicPqb^hZ%.d/-p&%2/+23)/6+-2&yyKM@y1-256y
?HofkhibDllapqbbi9?i^`hpjfqefkdPrmmifbp;yWy.3.yyKyXMi^kp7DliabkP`^ib@lfcZ%11p&%2.+.2)0-+06&yyKM@y21..y
?Sfwwhif`h9Q^filofkdPrmmifbp;yWy.3.yyKyXM^qqbok7@ofjplkPfihOl_bZ%2-p&)XM^qqbok7PlriMlr`eZ%.d/-p&%2-+40)/5+4/&yyKM@y3235y
?E^rdeqvJlafpqb9C^peflkAbpfdkbo;yWy.3.yyKyXM^qqbok7E^ifp`^kG^`hbqZ%14p2-`&XM^qqbok7E^ifp`^kM^kq^illkpZ%14p2-`&XM^qqbok7AobppPelbpZ%14p2-`&%2-+35)/5+30&yyKM@y1-24/y
??ifwofh?r`hpelq9Drkpjfqe;yWy.3.yyKyXP`ebj^qf`7BW*QeolAvk^jfqbFFZ%2-p&%2-+4-)/5+2-&yyKM@y5.0.y
?>i`ebjfpqMbpqibwrdd9>i`ebjvPrmmifbp;yWy.3.yyKyXOb`fmb7K^qrobMolqb`qflkMlqflkZ%/-p&)XOb`fmb7Mefilplmebo$pPqlkbZ%5-p&)XOb`fmb7Qo^kpjrqb>o`^kfqbZ%2d&)XOb`fmb7Qo^kpjrqbFolkqlDliaZ%5-p&)XOb`fmb7Qo^kpjrqbJfqeofiqlQorbpfisboZ%5-p&%2-+52)/4+64&yyKM@y2261y

O?o^`hbkt^iiSfii^dbyKyQo^sbiql?o^`hbkt^iiSfii^db)Arpqt^iiltJ^ope%03+2)0-+2&yyWy.1.y
?Delh$h^e9Q^filofkdPrmmifbp;yWy.1.yyKyXM^qqbok7F`v@il^hZ%.2p&%02+/)0-+5&yyKM@y3234y
?Ldd$j^oo9?rq`ebo;yWy.1.yyKyXOb`fmb7@^ooflkPromofpbZ%2-p&)XOb`fmb7Ao^dlk_ob^qe@efifZ%4-p&)XOb`fmb7Eb^sv@ol`lifphPqbtZ%/-p&)XOb`fmb7Ol^pqO^mqloZ%2-p&%03+4-)0-+65&yyKM@y1546y

OQeb@olppol^apyKyQo^sbiqlQeb@olppol^ap)Kloqebok?^oobkp%16)25+/&yyWy..y
?E^ifg^Tefqbpqofabo9@ilqefbo;yWy..yyKyS^oflrpdobbk>ojlo%.0p61`*1.p26`&%2-)3.+1&yyKM@y0153yyLy
?To^eh9Q^filofkdPrmmifbp;yWy..yyKyXM^qqbok7?irbIfkbkOl_bZ%0p&)XM^qqbok7?irbIfkbkSbpqZ%/p&)XM^qqbok7ObaTllibk?^dZ%2p&%2-)3.+.&yyKM@y0152y
?W^ode9?rq`ebo;yWy..yyKyXOb`fmb7ElqIflk@elmpZ%.5p&%2-+3)24+5&yyKM@y0156y
?Q^of$n^9Qo^abPrmmifbp;yWy..yyKyXOb`fmb7@ofpmvIfw^oaQ^fiZ%1p&)XOb`fmb7PqofaboPqbtZ%1p1-`&%16)25+/&yyKM@y015/y
?Eri^$j^ef9Ob^dbkqp)Ebo_p#MlfplkPrmmifbp;yWy..yyKyXOb`fmb7ElivMolqb`qflkMlqflkZ%5p&)S^oflrpEbo_p%1-*5-`&%15+3)25+1&yyKM@y016-y
?K^od^iAb^qebvb9Tb^mlkpjfqe;yWy..yyKyS^oflrpdobbk^ojlo%/1+4*/5+45p&%15+/)23+3&yyKM@y0146yyLy

?Q^o_^kEb^oqedo^fk9?^hbo;yWy..yyKyXOb`fmb7P^dbcfpeAbifdeqZ%2-p&)XOb`fmb7PjlhbaP^dbcfpeZ%2p&%22+.)3.+4&yyKM@y50-4y
?Ifww^ofh9Tb^mlkAb^ibo;yWy..yyKyQo^sbipol^a_bqtbbkqlmlfkqp%2-+0)26+0&%24+30)4-+/.&%33+5)4/+3&S^oflrpDobbkTb^mlkp%/1p*4-p1-`&)XIbppboEb^ifkdMlqflkZ%.p&)XJfkloJ^k^MlqflkZ%1-`&yyKM@y0325y

OO^q`ebqyKyQo^sbiqlO^q`ebq%3.+6)04+3&yyWy..y
?D^dpmol`hbq9BkdfkbbofkdPrmmifbp;yWy..yyKyXP`ebj^qf`7JfkloOb`lj_l_ri^qloZ%.2p&)XP`ebj^qf`7DobbkCfobtlohZ%.5p&)s^oflrpprmmifbp%.3`*0-p&%35+1)36+/&yyKM@y0162y
?Do^wifu9>ojlobo#Pefbia`o^cqbo;yWy..yyKyS^oflrpdobbk^ojlo%0-+10*50+/.p&%34+2)4/+6&yyKM@y0160yyLy
?Sbupmfkaib9@ilqe#Ib^qebo>ojloJbo`e^kq;yWy..yyKyS^oflrpdobbk^ojlo%02+.2*02+1-p&%34+1)4/+5&yyKM@y016/yyLy
?Hfiuu9Cfpeboj^k;yWy..yyKyXOb`fmb7?ofpqibTefphbo@^qcfpeZ%./p&)XOb`fmb7O^fk_ltCfk>i_^`lobZ%1p&)X>nr^avk^jf`Cfpe>qqo^`qloZ%/+2p&%35+3)4/+2&yyKM@y0164y
?O^kfh9Qo^abPrmmifbp;yWy..yyKyXAbpfdk7Tf`hbaJllkpqlkbOfkdZ%.2p&)XM^qqbok7?irbIfkbkOl_bZ%0p&)XM^qqbok7Dob^qbo>abmq$pOl_bZ%5p&)XOb`fmb7O^dbMlqflkZ%.p&%34+.)40+2&yyKM@y0166y
?Wfwwbh9CfpefkdPrmmifbp;yWy..yyKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&%34+/)41+.&yyKM@y024/y

OPbk$GfkSfii^dbyWy1yyKyQo^sbiqlPbk$GfkSfii^db)Arolq^o%23+/)40+2&y
?W^kpl^9CfpefkdPrmmifbp;yWy1yyKyXOb`fmb7O^fk_ltCfk>i_^`lobZ%1p&)XOb`fmb7PifqebophfkJ^`hbobiZ%1-`&)X>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&%24+2)44&yyKM@y261/y

OO^wloEfiiyKyQo^sbiqlO^wloEfii%2-+5)1/+5&yyWy1y
?Dofjq^h9?rq`ebo;yWy1yyKyXOb`fmb7P`lomfaPromofpbZ%.p1-`&%2-+36)1/+50&yyKM@y055.y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
