local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Knights_of_the_Ebon_Blade")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "Knights of the Ebon Blade (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

K@ljmibqbMob*NrbpqyKyVlrtfiikbbaql`ljmibqbF`b`oltk%44*5-Ilob&coljqebIbsbifkddrfabpb`qflk_bclobvlr`^krpbqefpdrfabyyNFAy.00.0y

OQebPe^altS^riqyKyCivqlQebPe^altS^riq%10+.)/1+/&yyWy16/y
>SfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWy16/yyAyyKM@y0-/.3y
>Pellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWy16/yyAyyKM@y0--41y
>Ib^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWy16/yyAyyKM@y/6010y
@Pellq$BjRmyKyDlql%0/)/1&^ka`ellpblkblcqebe^omllkp+T^fqrkqfiqebMolql*Ao^hbpcivkb^o_v)fcvlrkbbajlobqe^k{2pelqp^kaqebvalk$qafb)qebkqebv^obk$q`ilpbbklrdeyyNFAy.0-36yyWy16/yyAyyKM@y0-004)0-00-y
@Ib^sbLroJ^ohyKyHfiiqebSvhrip%0-)/5&^karpbXB_lk?i^ab?^kkboZlkqeb`lompbpyyRy1/15-yyNFAy./662yyWy16/yyAyyKM@y/655-)0-/10y
@SfibIfhbCfobyKyDlql%/4)06&^kajlrkq^Ao^hb)^ka_rok5_rfiafkdpfkqeb^ob^yyNFAy.0-4.yyWy16/yyAyyKM@y0-/4/y
QPellq$BjRmyKyQebIb^mbo%10+3)/2+.&yyNFAy.0-36yyWy16/yyAyyKM@y0--41y
QSfibIfhbCfobyKySfib%10+2)/1+2&yyNFAy.0-4.yyWy16/yyAyyKM@y0-/.3y
QIb^sbLroJ^ohyKy?^olkPifsbo%1/+6)/2&yyNFAy./662yyWy16/yyAyyKM@y/6010y

OAb^qe$pOfpbyKyCivqlAb^qe$pOfpb%.6+6)14+3&yyWy16/y
>Fkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505yyWy16/yyAyyKM@y/6123y
>KlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2yyWy16/yyAyyKM@y/61-2y
>ColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0yyWy16/yyAyyKM@y/6063y
@KlCivWlkbyKyEb^alsboqlLkpi^rdeqE^o_loqlqebtbpqlcAb^qe$pOfpb^kacfka^p^cbpmlqqli^ka+RpbX?lkbDovmelkZqlprjjlkqebdovmelk^kaelmlk+Rpb?lkb>ojlotebkbsboqeb`llialtkfpcfkfpeba+TebkcfdeqfkdqebLkpi^rdeqDovmelkOfabop)pq^oqlcctfqeMi^drbPqofhb^kapm^jColpq?ob^qerkqfiqebofabofpab^a+Hfiiqbkofabopql`ljmibqbqebnrbpq+Fcvlro?lkbDovmelk$peb^iqefpilt)cfka^p^cbpmlqqlafpjlrkq^kaob*prjjlkfq+Vlr$iielmlk^kbt?lkbDovmelktfiicriieb^iqeyyRy1-3--yyNFAy./5.2yyWy16/yyAyyKM@y/6315)/6000y
@ColjQebfo@lompbp)OfpbyKyHfiiP`^oibqLkpi^rdeq%4)1.&^kaillqqeb`lompbpclohbvp^karpbXA^ohjbkabo$pQfk`qrobZlkqeb`lompbpyyRy1-254yyNFAy./5.0yyWy16/yyAyyKM@y/61--y
@Fkqbiifdbk`bD^qebofkdyKyDlqlqeb_b^`e^qqebt^vmlfkq%5)10&tef`efp^qqeb_^`hlcqebe^o_lo^karkil`hqeb`ebpqpqebobyyNFAy./505yyWy16/yyAyyL?Gy1.y
QFkqbiifdbk`bD^qebofkdyKy>rol`epDofj_^kb%.6+6)14+3&yyNFAy./505yyWy16/yyAyyKM@y/6123y
QKlCivWlkbyKyRwlAb^qe`^iibo%.6+4)14+6&yyNFAy./5.2yyWy16/yyAyyKM@y/61-2y
QColjQebfo@lompbp)OfpbyKyPbq^^iA^ohjbkabo%.6+4)15+0&yyNFAy./5.0yyWy16/yyAyyKM@y/6063y

?XB_lk?i^ab@ljjbka^qflk?^adbZyKyXB_lk?i^ab@ljjbka^qflk?^adbZtef`eobt^oap2/-obmrq^qflkmlfkqp^ob^ipl^s^fi^_ibqlmro`e^pbclo.3Grpqf`bMlfkqpcoljqebIbd^`vGrpqf`bNr^oqboj^pqbofkA^i^o^k%31+3)/1+3&yyKM@y02162yyWy2-1y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
