local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Netherwing_Honor_Dailies")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Outland|r ", "Netherwing (Neutral-Honored Daily)", "Netherwing (Revered-Exalted Daily)", "Horde", "D", nil, function()
return [[
AAA

K@ljmibqb$Kbqebotfkd%4-(Mob*Nrbpq&$yKyVlrkbbaql`ljmibqbqeb$Kbqebotfkd%4-(Mob*Nrbpq&$drfabcfopq_bclobvlr`^k_bdfkqefpdrfabyyNFAy.-54-y
OKbqebotfkaIbadbyKyQo^sbiqlKbqebotfkaIbadb%33+/)52+4&yyWy140y

>>PiltAb^qeyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-/-yyWy140yyAyyKM@y/0.1.y
>QebKlq*Pl*CofbkaivPhfbp+++yKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-02yyWy140yyAyyKM@y/0.1.y
>Kbqebotfkd@ovpq^ipyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.2yyWy140yyAyyKM@y/0.1-y
>Kbqebo`fqbLobyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.5yyWy140yyAyyLyyKM@y/0.1-y
>KbqeboarpqMliibkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.4yyWy140yyAyyLyyKM@y/0.1-y
>KbqebojfkbCi^vboEfabyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.3yyWy140yyAyyLyyKM@y/0.1-y

>Qeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-22yyWy140yyAyyKM@y/0/6.yyOBMy.-.2)2y
>AfpormqfkdqebQtfifdeqMloq^iyNFAy..-53yyKyLsboiloaJlo$delo%33+/)52+4&yyAyyKM@y/0.06yyWy140yyOBMy.-.2)3y

@QebKlq*Pl*CofbkaivPhfbp+++yKy>qq^`h^kvAo^dlkj^tQo^kpmloqbopqe^qcivm^pq+@liib`q.-XKbqebotfkdObif`pZ%41+3)42+4&%4/+-)41+5&yyNFAy..-02yyWy140yyAyyKM@y/0.55y
HCbi_l^oploAfbjbqo^alkpyKyHfiiCbi_l^oploAfbjbqo^alkp^ka`liib`q./XCbiDi^kapZ%00+-)10+2&%24+-)10+3&yyNFAy..-/-yyWy140yyAyyKM@y/.13/)/.545yyIy0/2-/./y
@>PiltAb^qeyKyRpbqebjrqqlk^olrka^kvlcqebMblk@^jmp)qebmblkptfii`ljb^kab^qfq^kaafb%33+6)5.+6&yyNFAy..-/-yyRy0/2-0yyWy140yyAyyKM@y///2/y
@Qeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKyRpbqeb?llqbo^kdlk^kvlcqebmblkplkKbqebotfkaIbadb%33+6)5.+6&yyNFAy..-22yyRy0/35-yyWy140yyAyyKM@y/00..yyOBMy.-.2)2y

@KbqeboarpqMliibkyKy@liib`q1-XKbqeboarpqMliibkZcoljKbqeboarpq?rpebp%33+6)5.+6&KbqebotfkaIbadbyyNFAy..-.4yyWy140yyAyyLyyL?Gy345y
@Kbqebo`fqbLobyKy@liib`q1-XKbqebo`fqbLobZcoljjfkfkdqebKbqebo`fqbAbmlpfq^qKbqebotfkaIbadb%33+6)5.+6&yyNFAy..-.5yyWy140yyAyyLyyL?Gy332-y

>Mf`hfkdRmQebMfb`bp+++yKyJfpqobpplcqebJfkbp%32+1)6-+/&yyNFAy..-43yyWy140yyAyyKM@y/0.16y
>Ao^dlkp^obqebIb^pqlcLroMol_ibjpyKyAo^dlkj^tClobj^k%32+.)54+2&yyNFAy..-44yyWy140yyAyyKM@y/0043y
@Mf`hfkdRmQebMfb`bp+++yKy@liib`q.2XKbqebojfkb@^odlZqe^q^obclrkafkqebjfkbplrqelcqeb`^jm%33+6)51+-&yyNFAy..-43yyWy140yyAyyL?Gy/6-y
@Ao^dlkp^obqebIb^pqlcLroMol_ibjpyKyHfii.2KbqebojfkbCi^vbop^ka2KbqebojfkbO^s^dbopclrkaqeolrdelrqKbqebotfkaIbadbjlpqiv^olrkaqebt^vmlfkq%36+-)5.+0&yyNFAy..-44yyWy140yyAyyKM@y/0.36)/00/3y
@Kbqebotfkd@ovpq^ipyKy@liib`q0-XKbqebotfkd@ovpq^ipZcoljqebjl_p^qKbqebotfkaIbadb%4-+5)51+1&yyNFAy..-.2yyWy140yyAyyKM@y/00/3)/0/52)/0.36y
@KbqebojfkbCi^vboEfabyKy@liib`q02XKbqebojfkbCi^vboEfabpZ_vphfkkfkd^kvlcqebKbqebojfkbjl_p%4-+5)51+1&KbqebotfkaIbadbyyNFAy..-.3yyWy140yyAyyLyyKM@y/00/3)/0/52)/0.36y

QMf`hfkdRmQebMfb`bp+++yKyJfpqobpplcqebJfkbp%32+1)6-+/&yyNFAy..-43yyWy140yyAyyKM@y/0.16y
QAo^dlkp^obqebIb^pqlcLroMol_ibjpyKyAo^dlkj^tClobj^k%31+2)54+-&yyNFAy..-44yyWy140yyAyyKM@y/0043y

OK^do^kayKyQo^sbiqlK^do^ka%./+4)05+6&yyNFAy..-53yyAyyOBMy.-.2)3yyWy144y
@AfpormqfkdqebQtfifdeqMloq^iyNFAy..-53yyKyHfii/-Ab^qepe^alt>dbkq%./+4)05+6&yyAyyKM@y//060)//030)//01/)//010)//01.yyOBMy.-.2)3yyWy144y

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%33+-)53+2&yyWy140yyAy
Q>PiltAb^qeyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-/-yyWy140yyAyyKM@y/0.1.y
QQebKlq*Pl*CofbkaivPhfbp+++yKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-02yyWy140yyAyyKM@y/0.1.y
QQeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-22yyWy140yyAyyKM@y/0/6.yyOBMy.-.2)2y
QKbqebotfkd@ovpq^ipyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.2yyWy140yyAyyKM@y/0.1-y
QKbqebo`fqbLobyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.5yyWy140yyAyyLyyKM@y/0.1-y
QKbqeboarpqMliibkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.4yyWy140yyAyyLyyKM@y/0.1-y
QKbqebojfkbCi^vboEfabyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.3yyWy140yyAyyLyyKM@y/0.1-y
QAfpormqfkdqebQtfifdeqMloq^iyNFAy..-53yyKyLsboiloaJlo$delo%33+/)52+4&yyAyyKM@y/0.06yyWy140yyOBMy.-.2)3y

>Ofpb)LsbopbboyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&)CofbkaivyyNFAy..-20yyWy140yyKM@y/0.1-yyOBMy.-.2)2y
QOfpb)LsbopbboyKyLsboiloaJlo$delo%33+/)52+4&)CofbkaivyyNFAy..-20yyWy140yyKM@y/0.06yyOBMy.-.2)2y
>QebKbqebotfkdJfkbpyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&)CofbkaivyyNFAy..-42yyWy140yyKM@y/0.1-yyOBMy.-.2)2y
>Lsbopbbfkd^kaVlr7J^hfkdqebOfdeq@elf`bpyKy@efbcLsbopbboJrairjm%33+5)53+.&)CofbkaivyyNFAy..-21yyWy140yyKM@y/0/6.yyOBMy.-.2)2y
QQebKbqebotfkdJfkbpyKyJfpqobpplcqebJfkbp%32+1)6-+/&)CofbkaivyyNFAy..-42yyWy140yyKM@y/0.16yyOBMy.-.2)2y
>@o^wba^ka@lkcrpbayKyOlk^dqebPi^sbAofsbo%4.+3)54+3&)CofbkaivyyNFAy..-50yyWy140yyKM@y/0.33yyOBMy.-.2)2y
@@o^wba^ka@lkcrpbayKyHfiiqeb@o^wbaJroh_illaClobj^k^ka2@o^wbaJroh_illaJfkbopyyNFAy..-50yyWy140yyKM@y/00-2)/00/1yyOBMy.-.2)2y
Q@o^wba^ka@lkcrpbayKyOlk^dqebPi^sbAofsbo%4.+3)54+3&)CofbkaivyyNFAy..-50yyWy140yyKM@y/0.33yyOBMy.-.2)2y
H?i^`h?illalcAo^bkloyKyHfii?i^`h?illalcAo^bklo^ka`liib`qXPiradb*`lsbobaL_gb`qZ%31+5)52+3&yyNFAy..-5.yyKM@y/0/53yyIy0/4/1yyWy140yyOBMy.-.2)2y
KXJroh_illaBp`^mbMi^kpZyKyLmbkqebXPiradb*`lsbobaL_gb`qZ^ka`liib`qXJroh_illaBp`^mbMi^kpZyyNFAy..-5.yyRy0/4/1yyIy0/4/3yyWy140yyOBMy.-.2)2y
>QebDob^qJroh_illaObsliqyKyRpbXJroh_illaBp`^mbMi^kpZql^``bmqqebnrbpqyyNFAy..-5.yyRy0/4/3yyWy140yyOBMy.-.2)2y
QQebDob^qJroh_illaObsliqyKyJfpqobpplcqebJfkbp%32+1)6-+/&)CofbkaivyyNFAy..-5.yyOBMy.-.2)2yyWy140yyKM@y/0.16y
>PbbhbolcQorqeyKyJfpqobpplcqebJfkbp%32+1)6-+/&)CofbkaivyyNFAy..-5/yyOBMy.-.2)2yyWy140yyKM@y/0.16y
KD^qeboJroh_illaFkcloj^qflkyKyDlfkpfabqebjfkb^kacliiltqebm^qeql^kaq^ihql^Jroh_illaLsbopbbo^kaqbiiefjvlr^obebobcloefj%40+-)5/+/&)CofbkaivyyNFAy..-5/+.yyOBMy.-.2)2yyWy140yyKM@y/00-6y
KXE^kalcqebLsbopbboZyKy@liib`qXE^kalcqebLsbopbboZ%40+-)5/+/&)CofbkaivyyNFAy..-5/+/yyOBMy.-.2)2yyWy140yyQy
QPbbhbolcQorqeyKyJfpqobpplcqebJfkbp%32+1)6-+/&)CofbkaivyyNFAy..-5/yyWy140yyOBMy.-.2)2yyKM@y/0.16y
K.-XHklqefabIb^qeboZyNFAy..-21+.yyKyVlr`^kdbqqeb.-HklqefabIb^qebocoljqeb>r`qflkElrpb)lo_vPhfkkfkdjl_pcloqebib^qebo)Fcvlrt^kqqldbqqeb.-HklqefabIb^qebo_vphfkkfkd)hfiiqebjl_p^olrkaqebt^vmlfkq%3-+1)12+/&yyQyyWy140yyOBMy.-.2)2y

OKbqebopqlojyKyQo^sbiqlKbqebopqloj%13+1).-+5&yyNFAy..-21yyOBMy.-.2)2yyWy146y
HQvo^kqrpyNFAy..-21+/yyKyHfiiQvo^kqrp^ka`liib`qXE^oabkbaEfablcQvo^kqrpZ%13+1).-+5&yyKM@y/-60.yyOBMy.-.2)2yyWy146y

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%33+5)53+.&yyOBMy.-.2)2yyWy140y
QLsbopbbfkd^kaVlr7J^hfkdqebOfdeq@elf`bpyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-21yyWy140yyKM@y/0/6.yyOBMy.-.2)2y

KCofbkaivObmrq^qflkObnrfobayKyObpbq^kaobil^aqebdrfabrkqfivlrob^`ecofbkaivobmrq^qflktfqeqebKbqebotfkdqlob`bfsbjloba^fifbpyyNFAy..-20y

>Pq^kaQ^ii)@^mq^fkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&)ElklobayyNFAy..-51yyWy140yyKM@y/0.1-yyOBMy.-.2)3y
QPq^kaQ^ii)@^mq^fkyKyLsboiloaJlo$delo%33+/)52+4&)ElklobayyNFAy..-51yyWy140yyKM@y/0.06yyOBMy.-.2)3y
>B^okfkdVlroTfkdp+++yKyG^$vKlpift%32+6)54+/&)ElklobayyNFAy..-30yyWy140yyKM@y//100yyByyOBMy.-.2)3y
>Ao^dlkj^tO^`b7Qeb?^ii^alcLiafbJ`LiayKyJrodLiafbJr`hg^t%33+-)53+0&)ElklobayyNFAy..-31yyWy140yyKM@y/001-yyOBMy.-.2)3y
@Ao^dlkj^tO^`b7Qeb?^ii^alcLiafbJ`LiayKyCliiltJrodLiafbJr`hg^t)ebtfiiqeoltmrjmhfkp^qvlr^pebcifbp)^kavlre^sbqlaladbqebj+Qebb^pfbpqpqo^qbdvfpqlcivploqlcc^o_befkaefj)^ka^_lsbefj)plqe^qvlr^obillhfkdaltklkefj^pvlrciv+Alk$qibq^kvlcqebmrjmhfkpefqvlr^kavlrtfiitfkqebo^`b+yyNFAy..-31yyWy140yyKM@y/001-yyOBMy.-.2)3y
QAo^dlkj^tO^`b7Qeb?^ii^alcLiafbJ`LiayKyG^$vKlpift%32+6)54+/&yyNFAy..-31yyWy140yyKM@y//100yyOBMy.-.2)3y
>Ao^dlkj^tO^`b7QolmbqebCfiqe*?bi`eboyKyQolmbqebCfiqe*?bi`ebo%32+/)52+2&)ElklobayyNFAy..-34yyWy140yyKM@y/001/yyOBMy.-.2)3y
@Ao^dlkj^tO^`b7QolmbqebCfiqe*?bi`eboyKyCliiltQolmbqebCfiqe*?bi`ebo)ebtfiiqeoltdobbk_lj_p^qvlr^pebcifbp)^kavlre^sbqlaladbqebj+Qebb^pfbpqpqo^qbdvfpqlcivc^o_befkaefj)^karkaboefj+Pqo^cbqlqebpfabptebkebqeoltpqeb_lj_p^kavlr`^kaladbqebjb^pfiv+Alk$qibq^kvlcqeb_lj_pefqvlr^kavlrtfiitfkqebo^`b+yyNFAy..-34yyWy140yyKM@y/001/yyOBMy.-.2)3y
QAo^dlkj^tO^`b7QolmbqebCfiqe*?bi`eboyKyG^$vKlpift%32+6)54+/&)ElklobayyNFAy..-34yyWy140yyKM@y//100yyOBMy.-.2)3y
>Ao^dlkj^tO^`b7Tfkd@ljj^kaboF`ej^kyKyTfkd@ljj^kaboF`ej^k%32+/)52+-&)ElklobayyNFAy..-36yyWy140yyKM@y/0012yyOBMy.-.2)3y
@Ao^dlkj^tO^`b7Tfkd@ljj^kaboF`ej^kyKyCliiltTfkd@ljj^kaboF`ej^k)ebtfiiqeoltcfob_^iip^qvlr^pebcifbp)^kavlre^sbqlaladbqebj+Qebb^pfbpqpqo^qbdvfpqlciv_befkaefj)_rqc^o^_lsbefj)tefibillhfkdaltk^qefj+Pqo^cbqlqebpfabptebkebqeoltpqebcfob_^iip^kavlr`^kaladbqebjb^pfiv+Alk$qibq^kvlcqebcfob_^iipefqvlr^kavlrtfiitfkqebo^`b+>ipl)_b`^obcri_b`^rpbebalbppe^omqrokp^kaj^kbrsbop)plfq$pb^pvqlilpbqo^`hlcefjfcvlr^obk$q`^obcri+yyNFAy..-36yyKM@y/0012yyOBMy.-.2)3y
QAo^dlkj^tO^`b7Tfkd@ljj^kaboF`ej^kyKyG^$vKlpift%32+6)54+/&)ElklobayyNFAy..-36yyWy140yyKM@y//100yyOBMy.-.2)3y
>Ao^dlkj^tO^`b7Tfkd@ljj^kaboJrisbof`hyKyTfkd@ljj^kaboJrisbof`h%32+/)51+6&)ElklobayyNFAy..-4-yyWy140yyKM@y/0013yyOBMy.-.2)3y
@Ao^dlkj^tO^`b7Tfkd@ljj^kaboJrisbof`hyKyCliiltTfkd@ljj^kaboJrisbof`h)ebtfiiqeoltifdeqkfkd_liqp^qvlr^pebcifbp)^kavlre^sbqlaladbqebj+Qebifdeqkfkd_liqptfiicliiltvlr)rkifhbqebmobsflrpo^`bnrbpqp)tebobqebl_gb`qpqebvqeoltafaklqcliiltvlr+Qebb^pfbpqpqo^qbdvfpqlciv_bpfabefj)tefibpqo^cfkd)^ka^ijlpq^eb^alcefj)fcvlr`^k+Alk$qibq^kvlcqebifdeqkfkd_liqpefqvlr^kavlrtfiitfkqebo^`b+yyNFAy..-4-yyWy140yyKM@y/0013yyOBMy.-.2)3y
QAo^dlkj^tO^`b7Tfkd@ljj^kaboJrisbof`hyKyG^$vKlpift%32+6)54+/&)ElklobayyNFAy..-4-yyWy140yyKM@y//100yyOBMy.-.2)3y
>Ao^dlkj^tO^`b7@^mq^fkPhvpe^qqboyKy@^mq^fkPhvpe^qqbo%32+2)52+0&)ElklobayyNFAy..-4.yyWy140yyKM@y/0015yyOBMy.-.2)3y
@Ao^dlkj^tO^`b7@^mq^fkPhvpe^qqboyKyCliilt@^mq^fkPhvpe^qqbo)Jbqblopc^ii^ii^olrkavlr^pvlrcivtfqe@^mq^fkPhvpe^qqbo)^kavlre^sbqlaladbqebj+Qebb^pfbpqpqo^qbdvfpqlciv_bpfabefj)tefibpqo^cfkd)^ka^ijlpq^eb^alcefj)fcvlr`^k+Pq^v`ilpbqlefj^kaqebjbqbloptfiiefqefj)^ptbii^pvlr)tef`etfiipqlmefjclo^pb`lka)^iiltfkdvlrql`^q`ermqlefj)fckbbaba+Vlrtfiiklqdbqhkl`hbalccvlrojlrkq_vqebjbqblop)grpqpqrkkbaclo^pb`lka)plqebob$pklqefkdqltloov^_lrq+yyNFAy..-4.yyWy140yyKM@y/0015yyOBMy.-.2)3y
QAo^dlkj^tO^`b7@^mq^fkPhvpe^qqboyKyG^$vKlpift%32+6)54+/&)ElklobayyNFAy..-4.yyWy140yyKM@y//100yyOBMy.-.2)3y

KElklobaObmrq^qflkObnrfobayKyObpbq^kaobil^aqebdrfabrkqfivlrob^`eelklobaobmrq^qflktfqeqebKbqebotfkdqlob`bfsbjloba^fifbpyyNFAy..-51y

>E^fi)@ljj^kaboyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&)ObsbobayyNFAy..-6/yyWy140yyKM@y/0.1-yyOBMy.-.2)4y
QE^fi)@ljj^kaboyKyLsboiloaJlo$delo%33+/)52+4&)ObsbobayyNFAy..-6/yyWy140yyKM@y/0.1-yyOBMy.-.2)4y

KObsbobaObmrq^qflkObnrfobayKyObpbq^kaobil^aqebdrfabrkqfivlrob^`eobsbobaobmrq^qflktfqeqebKbqebotfkdqlob`bfsbjloba^fifbpyyNFAy..-6/y

>HfiiQebj>iiyKyLsboiloaJlo$delo%33+/)52+4&P`ovbopyyNFAy..-61yyWy140yyKM@y/0.1-yyOBMy601)2y
>HfiiQebj>iiyKyLsboiloaJlo$delo%33+/)52+4&>ialoyyNFAy..-66yyWy140yyKM@y/0.1-yyOBMy60/)2y

H>osl^oqebO^m^`flrpyKyHfii>osl^oqebO^m^`flrp^ka`liib`qXM^oqf^iivAfdbpqbaE^kaZ%41+2)53+0&yyIy0/3/.yyWy140yyNFAy..-1.yyKM@y/0/34y
>>Gl_Rkcfkfpeba+++yNFAy..-1.yyKyRpbXM^oqf^iivAfdbpqbaE^kaZql^``bmqnrbpqyyNFAy..-1.yyWy140yyRy0/3/.y
H?^o^peqebAbkJlqeboyNFAy..-1.+/yyKyHfii?^o^peqebAbkJlqebo%4-+/)51+0&yyWy140yyKM@y/0/36y
H.-LsbojfkbCi^vbopyNFAy..-1.+.yyKyHfii.-LsbojfkbCi^vbop%4-+/)51+0&yyWy140yyKM@y/0/36y
Q>Gl_Rkcfkfpeba+++yNFAy..-1.yyKyLsboiloaJlo$delo%33+/)52+4&yyNFAy..-1.yyWy140yyKM@y/0.1-y

QHfiiQebj>iiyKy>o`^kfpqQebifp%23+0)26+3&P`ovbopyyNFAy..-61yyWy140yyKM@y/.622yyOBMy601)2y
>@ljj^kaboEl__yNFAy..-62yyKy>o`^kfpqQebifp%23+0)26+3&P`ovbopyyWy140yyKM@y/.622yyOBMy601)2y
Q@ljj^kaboEl__yNFAy..-62yyKy@ljj^kaboEl__%23+0)26+3&P`ovbopyyWy140yyKM@y/0101yyOBMy601)2y

QHfiiQebj>iiyKy>k`elofqb@bvi^%3/+3)/5+1&>ialoyyNFAy..-66yyWy140yyKM@y/.1-/yyOBMy60/)2y
>@ljj^kabo>o`rpyKy>k`elofqb@bvi^%3/+3)/5+1&>ialoyyNFAy...--yyWy140yyKM@y/.1-/yyOBMy60/)2y
Q@ljj^kabo>o`rpyKy@ljj^kabo>o`rp%3/+1)/6+0&>ialoyyNFAy...--yyWy140yyKM@y/012/yyOBMy60/)2y

K@lkqfkrbql$KbqebotfkdObsboba*Bu^iqba%4-(A^fifbp&$yKyQf`hql`lkqfkrbqlqebkbuqdrfaby

]]
end)	end
	
	function Guide:Unload()
	end
end
