local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Netherwing_Revered_Dailies")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Outland|r ", "Netherwing (Revered-Exalted Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

K@ljmibqb$Kbqebotfkd%4-(Mob*Nrbpq&$yKyVlrkbbaql`ljmibqbqeb$Kbqebotfkd%4-(Mob*Nrbpq&$drfabcfopq_bclobvlr`^k_bdfkqefpdrfabyyNFAy.-54-y
KObsbobaObmrq^qflkObnrfobayKyObpbq^kaobil^aqebdrfabrkqfivlrob^`eobsbobaobmrq^qflktfqeqebKbqebotfkdqlob`bfsbjloba^fifbpyyNFAy..-6/y

OKbqebotfkaIbadbyKyQo^sbiqlKbqebotfkaIbadb%33+/)52+4&yyWy140y

>>PiltAb^qeyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-/-yyWy140yyAyyKM@y/0.1.y
>QebKlq*Pl*CofbkaivPhfbp+++yKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-02yyWy140yyAyyKM@y/0.1.y
>Kbqebotfkd@ovpq^ipyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.2yyWy140yyAyyKM@y/0.1-y
>Kbqebo`fqbLobyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.5yyWy140yyAyyLyyKM@y/0.1-y
>KbqeboarpqMliibkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.4yyWy140yyAyyLyyKM@y/0.1-y
>KbqebojfkbCi^vboEfabyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.3yyWy140yyAyyLyyKM@y/0.1-y
>Qeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-22yyWy140yyAyyKM@y/0/6.yyOBMy.-.2)2y
>AfpormqfkdqebQtfifdeqMloq^iyNFAy..-53yyKyLsboiloaJlo$delo%33+/)52+4&yyAyyKM@y/0.06yyWy140yyOBMy.-.2)3y

@QebKlq*Pl*CofbkaivPhfbp+++yKy>qq^`h^kvAo^dlkj^tQo^kpmloqbopqe^qcivm^pq+@liib`q.-XKbqebotfkdObif`pZ%41+3)42+4&%4/+-)41+5&yyNFAy..-02yyWy140yyAyyKM@y/0.55y

>QebAb^aifbpqQo^mBsboI^fayNFAy..-64yyKy@ljj^kaboEl__%23+2)25+4&)P`ovbopyyWy140yyKM@y/0101yyAyyOBMy601)2y
@QebAb^aifbpqQo^mBsboI^fayNFAy..-64yyKyMolqb`q@ljj^kaboEl__^kaebimefjcfdeqqebAo^dlkj^tPhv_ob^hbop%24+2)24+5&yyWy140yyKM@y/0101yyAyyOBMy601)2y

HCbi_l^oploAfbjbqo^alkpyKyHfiiCbi_l^oploAfbjbqo^alkp^ka`liib`q./XCbiDi^kapZ%00+-)10+2&%24+-)10+3&yyNFAy..-/-yyWy140yyAyyKM@y/.13/)/.545yyIy0/2-/./y

>QebAb^aifbpqQo^mBsboI^fayNFAy...-.yyKy@ljj^kabo>o`rp%3/+1)/6+0&)>ialoyyWy140yyKM@y/0101yyAyyOBMy60/)2y
@QebAb^aifbpqQo^mBsboI^fayNFAy...-.yyKyMolqb`q@ljj^kabo>o`rp^kaebimefjcfdeqqebAo^dlkj^tPhv_ob^hbop%31+2)0.+.&yyWy140yyKM@y/0101yyAyyOBMy60/)2y

@>PiltAb^qeyKyRpbqebjrqqlk^olrka^kvlcqebMblk@^jmp)qebmblkptfii`ljb^kab^qfq^kaafb%33+6)5.+6&yyNFAy..-/-yyRy0/2-0yyWy140yyAyyKM@y///2/y
@Qeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKyRpbqeb?llqbo^kdlk^kvlcqebmblkplkKbqebotfkaIbadb%33+6)5.+6&yyNFAy..-22yyRy0/35-yyWy140yyAyyKM@y/00..yyOBMy.-.2)2y

@KbqeboarpqMliibkyKy@liib`q1-XKbqeboarpqMliibkZcoljKbqeboarpq?rpebp%33+6)5.+6&KbqebotfkaIbadbyyNFAy..-.4yyWy140yyAyyLyyL?Gy345y
@Kbqebo`fqbLobyKy@liib`q1-XKbqebo`fqbLobZcoljjfkfkdqebKbqebo`fqbAbmlpfq^qKbqebotfkaIbadb%33+6)5.+6&yyNFAy..-.5yyWy140yyAyyLyyL?Gy332-y

>Mf`hfkdRmQebMfb`bp+++yKyJfpqobpplcqebJfkbp%32+1)6-+/&yyNFAy..-43yyWy140yyAyyKM@y/0.16y
>Ao^dlkp^obqebIb^pqlcLroMol_ibjpyKyAo^dlkj^tClobj^k%32+.)54+2&yyNFAy..-44yyWy140yyAyyKM@y/0043y
@Mf`hfkdRmQebMfb`bp+++yKy@liib`q.2XKbqebojfkb@^odlZqe^q^obclrkafkqebjfkbplrqelcqeb`^jm%33+6)51+-&yyNFAy..-43yyWy140yyAyyL?Gy/6-y
@Ao^dlkp^obqebIb^pqlcLroMol_ibjpyKyHfii.2KbqebojfkbCi^vbop^ka2KbqebojfkbO^s^dbopclrkaqeolrdelrqKbqebotfkaIbadbjlpqiv^olrkaqebt^vmlfkq%36+-)5.+0&yyNFAy..-44yyWy140yyAyyKM@y/0.36)/00/3y
@Kbqebotfkd@ovpq^ipyKy@liib`q0-XKbqebotfkd@ovpq^ipZcoljqebjl_p^qKbqebotfkaIbadb%4-+5)51+1&yyNFAy..-.2yyWy140yyAyyKM@y/00/3)/0/52)/0.36y
@KbqebojfkbCi^vboEfabyKy@liib`q02XKbqebojfkbCi^vboEfabpZ_vphfkkfkd^kvlcqebKbqebojfkbjl_p%4-+5)51+1&KbqebotfkaIbadbyyNFAy..-.3yyWy140yyAyyLyyKM@y/00/3)/0/52)/0.36y

QMf`hfkdRmQebMfb`bp+++yKyJfpqobpplcqebJfkbp%32+1)6-+/&yyNFAy..-43yyWy140yyAyyKM@y/0.16y
QAo^dlkp^obqebIb^pqlcLroMol_ibjpyKyAo^dlkj^tClobj^k%31+2)54+-&yyNFAy..-44yyWy140yyAyyKM@y/0043y

OK^do^kayKyQo^sbiqlK^do^ka%./+4)05+6&yyAyyNFAy..-53yyOBMy.-.2)3yyWy144y
@AfpormqfkdqebQtfifdeqMloq^iyNFAy..-53yyKyHfii/-Ab^qepe^alt>dbkq%./+4)05+6&yyAyyKM@y/0.06yyKM@y//060)//030)//01/)//010)//01.yyOBMy.-.2)3yyWy144y

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%33+-)53+2&yyWy140yyAy
Q>PiltAb^qeyKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-/-yyWy140yyAyyKM@y/0.1.y
QQebKlq*Pl*CofbkaivPhfbp+++yKyV^owfiiqebJbo`%33+-)53+2&yyNFAy..-02yyWy140yyAyyKM@y/0.1.y
QQeb?llqbo^kd7>@robCloQeb@ljjlkTloqeibppMblkyKy@efbcLsbopbboJrairjm%33+5)53+.&yyNFAy..-22yyWy140yyAyyKM@y/0/6.yyOBMy.-.2)2y
QKbqebotfkd@ovpq^ipyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.2yyWy140yyAyyKM@y/0.1-y
QKbqebo`fqbLobyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.5yyWy140yyAyyLyyKM@y/0.1-y
QKbqeboarpqMliibkyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.4yyWy140yyAyyLyyKM@y/0.1-y
QKbqebojfkbCi^vboEfabyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&yyNFAy..-.3yyWy140yyAyyLyyKM@y/0.1-y
QAfpormqfkdqebQtfifdeqMloq^iyNFAy..-53yyKyLsboiloaJlo$delo%33+/)52+4&yyAyyKM@y/0.06yyWy140yyOBMy.-.2)3y
QQebAb^aifbpqQo^mBsboI^fayNFAy..-64yyKy@ljj^kaboEl__%23+2)25+4&)P`ovbopyyWy140yyKM@y/0101yyAyyOBMy601)2y
QQebAb^aifbpqQo^mBsboI^fayNFAyy...-.yyKy@ljj^kaboEl__%23+2)25+4&)>ialoyyWy140yyKM@y/0101yyAyyOBMy60/)2y

>?ltqlqebEfdeiloayNFAy...-4yyKyQ^phj^pqboS^ohribAo^dlk_ob^qe%33+-)53+0&)Bu^iqbayyWy140yyKM@y/0.1-yyOBMy.-.2)5y
Q?ltqlqebEfdeiloayNFAy...-4yyKyLsboiloaJlo$delo%33+/)52+4&)Bu^iqbayyWy140yyKM@y/0.06yyOBMy.-.2)5y
>IloaFiifa^kPqlojo^dbyNFAy...-5yyKyLsboiloaJlo$delo%33+/)52+4&)Bu^iqbayyWy140yyKM@y/0.06yyOBMy.-.2)5y
QIloaFiifa^kPqlojo^dbyNFAy...-5yyKy?^oqe^jrp%33+3).3+1&)Bu^iqbayyWy15.yyKM@y/0100yyOBMy.-.2)5y

KBu^iqbaObmrq^qflkObnrfobayKyObpbq^kaobil^aqebdrfabrkqfivlrob^`ebu^iqbaobmrq^qflktfqeqebKbqebotfkdqlob`bfsbqebjlrkqobt^oayyNFAy...-4y
KDrfab@ljmibqb

]]
end)
	end
	
	function Guide:Unload()
	end
end
