local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Orgrimmar_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Orgrimmar Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OLodofjj^oyKyQo^sbiqlLodofjj^o%3-+3)25+3&yyWy0/.y
?Mrko^9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7E^oabkbaFolkPeloqptloaZ0-p)%12+-)44+3&yyKM@y13026yyWy0/.y
?Ifwk^Dliatb^sbo9Q^filofkdPrmmifbp;yKyXM^qqbok7MfkhJ^dbtb^sbPefoqZ1-p)XM^qqbok7I^sbkaboJ^dbtb^sbPefoqZ1-p)XM^qqbok7ObaTllibk?^dZ2p)XM^qqbok7?irbLsbo^iipZ1p)XM^qqbok7?irbIfkbkSbpqZ/p)%1.+-)46+5&yyKM@y12225yyWy0/.y
?H^ofwfMlohm^qqv9@llhfkdPrmmifbp;yKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7PjlhbaP^dbcfpeZ2p)%06+-)52+3&yyKM@y1222.yyWy0/.y
?Sfwk^?^kdtobk`e9BkdfkbbofkdPrmmifbp;yKyAlk$q_rvXP`ebj^qf`7Pqb^jQlkh@lkqoliiboZ^pvlr`^k$qobpbiifq+?rvXP`ebj^qf`7ObaCfobtlohZ.5p^kas^oflrpifjfqbaprmmivbkdfkbbofkdm^oqp.3`*0-p)%03+3)53+5&yyKM@y12213yyWy0/.y
?WfalEbij_ob^hbo9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7E^oabkbaFolkPeloqptloaZ0-p)%03+/)50+/&yyKM@y12216yyWy0/.y
?U^kqfif9Fkp`ofmqflkPrmmifbp;yKyXP`of_b$pP^q`ebiZ2-p)%03+/)36+5&yyKM@y0-4/0yyWy0/.y
?Ubk$ql9@llhfkdPrmmifbp;yKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7PjlhbaP^dbcfpeZ2p)%0/+3)35+3&yyKM@y01--yyWy0/.y
?H^g^9?lt#OfcibSbkalo;yKyXJ^ppfsbIlkd_ltZ3d46p)XPqroavOb`rosbZ.d61p)XCfkbPeloq_ltZ0.p)%1-+5)16+3&yyKM@y00//yyWy0/.y
?Hfqe^p9Bk`e^kqfkdPrmmifbp;yKyXM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7Bk`e^kq/ETb^mlk*IbppboFkqbiib`qZ2p)XClojri^7Bk`e^kq@ebpq*IbppboJ^k^Z1p)XClojri^7JfkloTfw^oaLfiZ2p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)%20+/)15+5&yyKM@y0013yyWy0/.y
?Hlo$dbia9>i`ebjvPrmmifbp;yKyXOb`fmb7BifufolcPrmbofloAbcbkpbZ.d0-p)XOb`fmb7Cobb>`qflkMlqflkZ.5p)%22+3)13+1&yyKM@y0015yyWy0/.y
?Pe^khvp9CfpefkdPrmmifbp;yKyXOb`fmb7JfqeofiEb^aQolrqZ//p)XOb`fmb7Ol`hp`^ib@laZ//p)XOb`fmb7O^fk_ltCfk>i_^`lobZ1p)%33+3)1.+3&yyKM@y0000yyWy0/.y
?Prjf9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7E^oabkbaFolkPeloqptloaZ0-p)%42+5)02+/&yyKM@y0023yyWy0/.y
?E^kalo9@ilqe#Ib^qebo>ojloJbo`e^kq;yKyX@fkabo`ilqeIbddfkdpZ1d05p/5`)%3-+5)21+3&yyKM@y00.3yyWy0/.y
?Plsfh9BkdfkbbofkdPrmmifbp;yKyAlk$q_rvXP`ebj^qf`7Pqb^jQlkh@lkqoliiboZ^pvlr`^k$qobpbiifq+?rvXP`ebj^qf`7ObaCfobtlohZ.5p^kas^oflrpifjfqbaprmmivbkdfkbbofkdm^oqp.3`*0-p)%23+3)23+/&yyKM@y01.0yyWy0/.y
??lov^9Q^filofkdPrmmifbp;yKyXM^qqbok7MfkhJ^dbtb^sbPefoqZ1-p)XM^qqbok7I^sbkaboJ^dbtb^sbPefoqZ1-p)XM^qqbok7ObaTllibk?^dZ2p)XM^qqbok7?irbLsbo^iipZ1p)XM^qqbok7?irbIfkbkSbpqZ/p)%3-+3)25+3&yyKM@y0031yyWy0/.y
?Qlo$me^k9@ilqe#Ib^qebo>ojloJbo`e^kq;yKyXM^ibIbddfkdpZ0d16p55`)%3-+5)26+3&yyKM@y00.2yyWy0/.y
?Prg^9@llhfkdPrmmifbp;yKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7PjlhbaP^dbcfpeZ2p)%23+3)3.+/&yyKM@y134-5yyWy0/.y
?Jlo^h^9Fkp`ofmqflkPrmmifbp;yKyXP`of_b$pP^q`ebiZ2-p)%22+5)22+3&yyKM@y134.5yyWy0/.y
?Cbifh^9Qo^abPrmmifbp;yKyXAbpfdk7Eb^svDliabkKb`hi^`blc?^qqibZ.2p+QefpKM@m^qolipqebao^d%15+1)14+5&%21+-)14+3&%25+3)22+1&%25+5)3-+3&%23+3)31+5&%2/+3)31+3&yyKM@y0034yyWy0/.y
?E^dorp9Ob^dbkqp;yKyEbfpfkqeb@ibcqlcPe^alt)_biltLodofjj^oXOb`fmb7Dob^qO^dbMlqflkZ/-p)XOb`fmb7O^dbMlqflkZ.p)%10+6)03+1&yyKM@y0002yyWy0/./y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
