local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Orgrimmar_Jewecrafting_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Orgrimmar Jewelcrafting (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

KObnrfobpBk`e^kqfkdIbsbi142yMyBk`e^kqfkd142y
KObnrfobpMi^vboIbsbi42yMIy42y
OLodofjj^oyKyQo^sbiqlLodofjj^o%30+4)3.+0&yyWy0/.y
K>``bmqA^fivNrbpqpyJAyyKy>``bmq^nrbpqcoljJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqyyWy0/.yyKM@y2-15/y
>>MobpbkqcloIfi^yNFAy/2.3-yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
>Bibjbkq^iDllyNFAy/2.3/yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
>Kf__iboKlyNFAy/2.25yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
>Ldobwlkf^kpfkqebJllayNFAy/2.3.yKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
>QebI^qbpqC^peflkyNFAy/2.26yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y

@>MobpbkqcloIfi^yNFAy/2.3-yyKy@rqqeobbXQfjbibppKfdeqpqlkbpZ%klqmbocb`q&vlrtfiikbbaqldbqpljbmromibXKfdeqpqlkbZbfqebocoljJfkfkdlocoljqeb>r`qflkElrpbyyLyyAyyWy0/.y
@Ldobwlkf^kpfkqebJllayNFAy/2.3.yKy@rqqeobbXG^ddbaG^pmboZ%klqmbocb`q&vlrtfiikbbaqldbqpljbdobbkXG^pmboZbfqebocoljJfkfkdlocoljqeb>r`qflkElrpbyyLyyAyyWy0/.y
@Kf__iboKlyNFAy/2.25yyKy@rqqeobbXPlifaWbmevofqbZ%klqmbocb`q&vlrtfiikbbaqldbqpljb_irbXWbmevofqbZbfqebocoljJfkfkdlocoljqeb>r`qflkElrpbyyLyyAyyWy0/.y

OJlrkqEvg^iyKyQo^sbiqlJlrkqEvg^i%2.+-1)05+/4&yyWy0/.yyNFAy/2.3/yyLyyAyyWy0/.y
@Bibjbkq^iDllyNFAy/2.3/yyKy@liib`q.-XBibjbkq^iDllZcoljqebOl`hBibjbkq^i)%32+6)/0+-&)vlr`^k^ipl`ljmibqbqefpqldbqebotfqeqebQebo^w^kbA^fiv$PlcqOl`h$yyLyyAyyWy3-3yyKM@y1-//6y

@QebI^qbpqC^peflkyNFAy/2.26yyKyRpbXPq^oarpqKl+/Zlk^kvErj^klfaq^odbq)vlr`^krpbfqlkvlropbic)lqebomi^vbop^kaKM@fkPqlojtfkayyLyyAyyWy0/.yyRy2/2-4y

OLodofjj^oyKyQo^sbiqlLodofjj^o%4/+2)01+2&y
Q>MobpbkqcloIfi^yNFAy/2.3-yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
QBibjbkq^iDllyNFAy/2.3/yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
QKf__iboKlyNFAy/2.25yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
QLdobwlkf^kpfkqebJllayNFAy/2.3.yKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y
QQebI^qbpqC^peflkyNFAy/2.26yyKyJ^ofqeI^wrof^%4/+2)01+2&)Lodofjj^oyyLyyAyyWy0/.yyKM@y2-15/y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
