local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Outland_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Outland Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OEbiicfobMbkfkpri^yKyQo^sbiqlEbiicfobMbkfkpri^%3.+.)5.+2&yyWy132y
?JfufbC^opelq9DrkJbo`e^kq;yKyXP`ebj^qf`7>a^j^kqfqbP`lmbZ%3d&)XP`ebj^qf`7@ldpmfkkboDlddibpZ%3d&%3.+.)5.+2&yyWy132yyKM@y.6503y
?HriFkhpmfiibo9Fkp`ofmqflkPrmmifbp;yKyXQb`ekfnrb7DivmelcBqbok^iT^qboZ%0d&%2/+2)03+-&yyWy132yyKM@y0-402y
?@llhfbLkb*Bvb9Clla#Aofkh;yKyXOb`fmb7O^s^dboAldZ%/d&%21+3)1.+.&yyWy132yyKM@y.3252y

OPe^altjllkS^iibvyKyQo^sbiqlPe^altjllkS^iibv%/6+0)0.+-&yyWy140y
?Hobh@o^d`orpe9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7>a^j^kqfqb?ob^pqmi^qbZ%3d&)XMi^kp7>a^j^kqfqbMi^qb?o^`bopZ%3d&)XMi^kp7>a^j^kqfqbMi^qbDilsbpZ%3d&%/6+0)0.+-&yyWy140yyKM@y.601/y
?>oolka9Q^filofkdPrmmifbp;yKyQebP`ovbopc^`qflklkiv)XM^qqbok7Fj_rbaKbqebotb^sbOl_bZ%3d&)XM^qqbok7Fj_rbaKbqebotb^sbQrkf`Z%3d&%22+6)25+/&yyWy140yyKM@y.62/.yyOBMy601)2y

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%15+5)13+.&yyWy145y
?Orkdlo9Qo^abDllap;yKyXOb`fmb7DliabkCfpePqf`hpZ%0d&)XOb`fmb7Pmf`v@o^ta^aZ%0d&%15+5)13+.&yyWy145yyKM@y.563-y

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%31+-)4.+5&yyWy15.y
?>^olkEliij^k9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7>a^j^kqfqb@ib^sboZ%1d&)XMi^kp7>a^j^kqfqbA^ddboZ%1d&)XMi^kp7>a^j^kqfqbJ^riZ%1d&)XMi^kp7>a^j^kqfqbO^mfboZ%1d&)XMi^kp7>a^j^kqfqbOlaZ%1d&%31+-)4.+5&yyWy15.yyKM@y.633/y
?>kaoflkA^ohpmfkkbo9Pe^altb^sbQ^filofkdPmb`f^ifpq;yKyXM^qqbok7Pe^alt`ilqeZ%1d&%33+3)35+2&yyWy15.yyKM@y///./y
?Bffk9Pmb`f^iqvQ^filofkdPrmmifbp;yKyXM^qqbok7?liqlcFj_rbaKbqebotb^sbZ%1d&)XM^qqbok7Fj_rbaKbqebotb^sb?^dZ%1d&)XM^qqbok7Kbqebotb^sbOl_bZ%1d&)XM^qqbok7Kbqebotb^sbQrkf`Z%1d&%33+-)36+-&yyWy15.yyKM@y.6/.0y
?DfadbPmbiitb^sbo9PmbiicfobQ^filofkdPmb`f^ifpq;yKyXM^qqbok7Pmbii`ilqeZ%1d&%33+1)35+-&yyWy15.yyKM@y///.0y
?J^a^jbOr_v9Bk`e^kqfkdPrmmifbp;yKyXClojri^7Bk`e^kqPefbia*J^gloPq^jfk^Z%1d&)XClojri^7I^odbMofpj^qf`Pe^oaZ%3d&)XClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XClojri^7OrkbaBqbokfrjOlaZ%./d&)XClojri^7PrmbofloJ^k^LfiZ%2d&)XClojri^7PrmbofloTfw^oaLfiZ%4d&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&%30+2)4-+3&yyWy15.yyKM@y.6330y
?K^pj^o^Jllkplkd9Jllk`ilqeQ^filofkdPmb`f^ifpq;yKyXM^qqbok7Mofj^iJllk`ilqeZ%1d&%33+2)35+4&yyWy15.yyKM@y///-5y
?SfddwPefkbpm^ohba9BkdfkbbofkdPrmmifbp;yKyXP`ebj^qf`7>a^j^kqfqbOfcibZ%5d&)XP`ebj^qf`7CrpbaTfofkdZ%.+3d&%31+0)36+1&yyWy15.yyKM@y.633.y
?Phob^e9>i`ebjvPrmmifbp;yKyXOb`fmb7Qo^kpjrqbMofj^iJfdeqZ%5d&%13+2)/-+2&yyWy15.yyKM@y.6-41y

OK^do^kayKyQo^sbiqlK^do^ka%23+-)1-+-&yyWy144y
?J^qe^oD$l`e^o9Qo^abPrmmifbp;yKyM^qolip_bqtbbk%23+-)1-+-&%22+-)04+-&XM^qqbok7?liqlcPlri`ilqeZ%1d&)XM^qqbok7Fj_rbaKbqebotb^sb?^dZ%1d&)XM^qqbok7Plri`ilqeDilsbpZ%5d&yWy144yyKM@y.6-.2y
?Kri^qeb?rq`ebo9@llhfkdPrmmifbp;yKyXOb`fmb7DofiibaJracfpeZ%0d&)XOb`fmb7Ml^`eba?irbcfpeZ%0d&)XOb`fmb7Ol^pqba@ibcqellcZ%0d&)XOb`fmb7Q^i_rhPqb^hZ%0d&%25+.)02+4&yyWy144yyKM@y/--64y

OW^kd^oj^opeyKyQo^sbiqlW^kd^oj^ope%0/+2)15+-&yyWy134y
?@^mqrobaDkljb9FqbjObm^fo;yKyXP`ebj^qf`7Riqo^*Pmb`qolmf`Abqb`qflkDlddibpZ%5d&)XP`ebj^qf`7TefqbPjlhbCi^obZ%3d&)s^oflrpj^qbof^ip%.3`*6-p&%0/+2)15+-&yyWy134yyKM@y.6050y
?D^j_^ofkh^9Qo^abpj^k;yKyXOb`fmb7?i^`hbkbaQolrqZ%/d&%0.+4)16+0&yyWy134yyKM@y.5-.2y
?PbboG^kfaf9Ob^dbkqp;yKyXOb`fmb7BifufolcJ^gloColpqMltboZ%1d&)XOb`fmb7Pkb^hfkdMlqflkZ%0d&%0/+2)2.+4&yyWy134yyKM@y.5-.4y
?Wro^f9Jbo`e^kq;yKyXM^qqbok7Fj_rbaKbqebotb^sb?llqpZ%3d&)XM^qqbok7Fj_rbaKbqebotb^sbM^kqpZ%3d&)XOb`fmb7Cbiq^fiAbifdeqZ%/d&%52+/)21+4&yyWy134yyKM@y.5-..y

?GrklArco^fk9J^pqboCfpefkdQo^fkbo;yKyX>nr^avk^jf`Cfpe>qqo^`qloZ%/p2-`&)XOb`fmb7?i^`hbkbaPlobcfpeZ%/d&%45+.)33+-&yyWy134yyKM@y.56..y

O?i^ab$pBadbJlrkq^fkpyKyQo^sbiql?i^ab$pBadbJlrkq^fkp%2/+-)24+.&yyWy142y
?A^d^O^j_^9Mlqflkp;yKyXOb`fmb7BifufolcJ^gloAbcbkpbZ%2d&)XOb`fmb7J^gloAob^jibppPibbmMlqflkZ%2d&)XOb`fmb7PrmboJ^k^MlqflkZ%2d&)XJ^gloEb^ifkdMlqflkZ%1-p&)XJ^gloJ^k^MlqflkZ%3-p&%2.+.)24+5&yyWy142yyKM@y.6504y

OKbqebopqlojyKyQo^sbiqlKbqebopqloj%0/+3)33+3&yyWy146y
?Nfcc9BkdfkbbofkdPrmmifbp;yKyX>a^j^kqfqbCo^jbZ%1d&)XCbiFolk@^pfkdZ%0+/d&)XCbipqbbiPq^_fifwboZ%1+5d&)XHelofrjMltbo@lobZ%1+5d&)XE^kacrilcCbiFolk?liqpZ%3-p&)XBibjbkq^i?i^pqfkdMltaboZ%/-p&%0/+3)33+3&yyWy146yyKM@y.6242y
?Ab^iboJ^ifg9Bk`e^kqfkdPrmmifbp;yKyXClojri^7IbppboTfw^oaLfiZ%1-p&)XClojri^7JfkloJ^k^LfiZ%0-p&)XClojri^7JfkloTfw^oaLfiZ%2p&)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ%3-p&%11+/)01+-&yyWy146yyKM@y.6204y
?Ab^iboK^gbb_9Pm^obM^oqp;yKyS^oflrpbkdfkbbofkdm^oqp%/-p*./d&)S^oflrpjlqbp%.3pb^`e&%12+-)03+2&yyWy146yyKM@y/-65.y
?Ab^iboO^pe^^a9Bulqf`@ob^qrobp;yKy5afccbobkqmbqp%1-p*.-d&%10+2)02+/&yyWy146yyKM@y/-65-y
?Ab^iboP^a^n^q9MlqbkqMlq^_ibp;yKyXJ^glo>o`^kbMolqb`qflkMlqflkZ%/d&)XJ^gloPe^altMolqb`qflkMlqflkZ%/d&)s^oflrpeb^ifkdmlqflkp%1-p*/d&)s^oflrpj^k^mlqflkp%3-p*/d&)s^oflrpebo_p%.-*3-p&%10+0)02+-&yyWy146yyKM@y/-656y
?Ab^iboE^wwfk9Dbkbo^iMolsfpflkbo;yKyXJ^gloEb^ifkdMlqflkZ%1-p)&XJ^gloJ^k^MlqflkZ%3-p&)S^oflrpPq^qp`oliip%2*3p&%25+1)0.+1&yyWy146yyKM@y/--6/y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
