local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Sha'tari_Skyguard_Dailies_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Outland|r ", "Sha'tari Skyguard / Ogri'la (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%31+2)33+2&yyWy145y
>CfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWy145yyAyyKM@y/0-15y
@CfobpLsboPhbqqfpyKyPbbhlrqJlkpqolrpH^ifofBddplkqebqlmplcPhbqqfpatbiifkdp^karpbqebPhvdr^oa?i^pqfkd@e^odbplkqebj%33+1)46+/&yyNFAy..--5yyRy0/1-3yyWy145yyAyyL?Gy045y
>Bp`^mbcoljPhbqqfpyKyPhvdr^oaMofplkbo%3.+/)41+0&%36+-)41+.&%42+.)53+6&yyNFAy..-52yyWy145yyAyyKM@y/0050y
@Bp`^mbcoljPhbqqfpyKyBp`loqqebPhvdr^oaMofplkboqlp^cbqvyyNFAy..-52yyWy145yyAyyKM@y/0050y
QCfobpLsboPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..--5yyWy145yyAyyKM@y/0-15y
QBp`^mbcoljPhbqqfpyKyPhvPbodb^kqAlovk%31+2)33+2&yyNFAy..-52yyWy145yyAyyKM@y/0-15y

O?i^ab$pBadbJlrkq^fkpyKyQo^sbiql?i^ab$pBadbJlrkq^fkp%/4+3)2/+6&yyWy142y
>?lj_Qebj>d^fkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy..-/0yyWy142yyAyyKM@y/0./-y
>To^kdibJlob>bqeboO^vpyKyPhvdr^oaHe^qfb%/5+-)2.+1&yyNFAy..-33yyWy142yyAyyKM@y/0002y
>?^kfpeJlobAbjlkpyKyLmqflk^inrbpqfcvlrt^kqjlobLdof$i^Obm)lqebotfpbphfmHolkh%/5+6)24+6&yyNFAy..-2.yyWy142yyAyyLyyKM@y/0/20y
>QebObif`$pBj^k^qflkyKyLmqflk^inrbpqfcvlrt^kqjlobLdof$i^Obm)lqebotfpbphfm@er$^$ilo%/5+5)24+1&yyNFAy..-5-yyWy142yyAyyLyyKM@y/0/00y
@To^kdibJlob>bqeboO^vpyKyRpbqebTo^kdifkdOlmbql`^mqrob2>bqeboO^vpyyNFAy..-33yyRy0/365yyWy142yyAyyKM@y//.5.y
@QebObif`$pBj^k^qflkyKyVlrtfiikbba^kX>mbufpPe^oaZql_bdfk^ka`ljmibqb5pbnrbk`bp)e^sb^mbk^kam^mboe^kav^katofqbaltkqebpbnrbk`blolmbk^`e^q_lu^katefpmbovlropbicqebpbnrbk`b)rpfkdod_vcloqeb`lilopyyNFAy..-5-yyWy142yyAyyLy
@?lj_Qebj>d^fkyKyCivlsbo@^jm7To^qe_lj_fkdqeboba^ooltp%00)1-&)%03)06&)%01)10&yyNFAy..-/0yyWy142yyRy0/123yyAy
@?^kfpeJlobAbjlkpyKyRpbX?^kfpefkd@ovpq^iZ^kahfiiqebabjlkptefibpq^kafkd`ilpbqlfq%00)1-&)%03)06&)%01)10&yyNFAy..-2.yyWy142yyAyyLyyRy0/363yyKM@y/0.41)//0-1y
Q?lj_Qebj>d^fkyKyPhvPbodb^kqS^kaboifm%/4+3)2/+6&yyNFAy..-/0yyWy142yyAyyKM@y/0./-y
QTo^kdibJlob>bqeboO^vpyKyPhvdr^oaHe^qfb%/5+-)2.+1&yyNFAy..-33yyWy142yyAyyKM@y/0002y
Q?^kfpeJlobAbjlkpyKyHolkh%/5+6)24+6&yyNFAy..-2.yyWy142yyAyyLyyKM@y/0/20y
QQebObif`$pBj^k^qflkyKy@er$^$ilo%/5+5)24+1&yyNFAy..-5-yyWy142yyAyyLyyKM@y/0/00y

>>Pmb`f^iQe^khVlryKy@er$^$ilo%/5+5)24+1&yyWy142yyNFAy..-6.yyKM@y/0/00yyByyOBMy.-05)2y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
