local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Shattrath_Fishing_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Shattrath Fishing (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

OQbolhh^oClobpqyKyQo^sbiqlQbolhh^oClobpq%05+4)./+5&yyWy145y
K>``bmqA^fivNrbpqpyJAyyKy>``bmq^nrbpqcoljLiaJ^k?^oil%05+4)./+5&fkPe^qqo^qeqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqyyWy145yyKM@y/225-yyAy
>?^fq?^kafqpyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..333yyAyyKM@y/225-yyWy145y
>Cbi_illaCfiibqyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..336yyAyyKM@y/225-yyWy145y
>Peofjmfk$>fk$qB^pvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..335yyAyyKM@y/225-yyWy145y
>QebLkbQe^qDlq>t^vyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..334yyAyyKM@y/225-yyWy145y
>@ol`lifphpfkqeb@fqvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..332yyAyyKM@y/225-yyWy145y

@?^fq?^kafqpyLyyKy@^q`eX?i^`hcfkA^oqboZfkqebpj^iimlka_vPe^qqo^qebkqo^k`b%06)//&yyNFAy..333yyAyyTyyWy132y
@Cbi_illaCfiibqyLyyKy@^q`eXJlkpqolrpCbi_illaPk^mmboZfkqebMlliplc>ddolk^o%10+2)00+2&yyNFAy..336yyAyyTyyWy145y
@Peofjmfk$>fk$qB^pvyLyyKy@^q`eX?il^qba?^o_baDfiiQolrqZ^kalmbkqebjrkqfivlr`liib`q.-XDf^kqCobpet^qboPeofjmZfkRj_o^cbkI^hb%43+.)45&yyNFAy..335yyAyyTyyWy134yyRy020.0y
@QebLkbQe^qDlq>t^vyLyyKy@^q`eqebXTloia$pI^odbpqJracfpeZfki^hbPrkpmofkd)%01+1)16+4&j^hbprobprobfqp^vpI^hbPrkmofkdfkvlrojfkfj^mtebobvlr$obpq^kafkdyyNFAy..334yyAyyTyyWy144y
@@ol`lifphpfkqeb@fqvyLyyKy@^q`eX?^_v@ol`lifphZfkS^iibvlcElklo)Lodofjj^o%4.+5)06+/&yyNFAy..332yyAyyTyyWy0/.y

Q?^fq?^kafqpyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..333yyAyyKM@y/225-y
QCbi_illaCfiibqyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..336yyAyyKM@y/225-y
QPeofjmfk$>fk$qB^pvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..335yyAyyKM@y/225-y
QQebLkbQe^qDlq>t^vyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..334yyAyyKM@y/225-y
Q@ol`lifphpfkqeb@fqvyLyyKyLiaJ^k?^oil%05+4)./+5&yyNFAy..332yyAyyKM@y/225-y

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
