local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Shattrath_Cooking_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Shattrath Cooking (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

OPe^qqo^qe@fqvyKyQo^sbiqlPe^qqo^qe@fqv%3.+3).2+5&yyWy15.y
K>``bmqA^fivNrbpqpyJAyyKy>``bmq^nrbpqcoljQebOlhh%3.).2&fkPe^qqo^qeqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqyyWy15.yyKM@y/1060yyAy
>J^k^if`flrpyNFAy..05-yyKyQebOlhh%3.+3).2+5&yyWy15.yyKM@y/1060yyLyyAy
>ObsbkdbfpQ^pqvyNFAy..044yyKyQebOlhh%3.+3).2+5&yyWy15.yyKM@y/1060yyLyyAy
>PlrmcloqebPlriyNFAy..05.yyKyQebOlhh%3.).2&yyWy15.yyKM@y/1060yyLyyAy
>PrmboElqPqbtyNFAy..046yyKyQebOlhh%3.).2&yyWy15.yyKM@y/1060yyLyyAy

@J^k^if`flrpyNFAy..05-yyKy@liib`q.2XJ^k^?boofbpZcoljqebB`l*AljbpfkKbqebopqloj+%12+3)21+/&yyWy146yyL?Gy/5yyLyyAy
KXDf^kqH^ifofTfkdZyQyyNFAy..044yyKyHfiiJlkpqolrpH^ifoffkPhbqqfpcloXDf^kqH^ifofTfkdZ%31)51&yyWy145yyKM@y/0-2.yyLyyAyyIy00505y
K0XT^om?rodboZy@LyyNFAy..044yyKy@llh0XT^om?rodboZqebj^qbof^ip`^k_bc^ojcoljJlkpqolrpH^ifof^ka?i^`htfkaT^om@e^pbofkPhbqqfp+%31)51&Qebob`fmb`^k_lrdeqcoljFkkhbbmboDofih^fkPqlkb_ob^hboElia)Qbolhh^oClobpqyyWy145yyKM@y/0/.6).5624yyLyyAyyIy/43260y
@ObsbkdbfpQ^pqvyNFAy..044yyKyRpbqebX@llhfkdMlqZmolsfabatfqe0XT^om?rodboZ^kaXDf^kqH^ifofTfkdZql`ob^qbXH^ifofPqbtZyyWy15.yyLyyAyyRy00504y
K1XOl^pqba@ibcqellcZy@LyyNFAy..05.yyKy@llh1XOl^pqba@ibcqellcZ)vlr`^kdbqqebj^qbof^icolj^kv@ibcqellcfkK^do^ka%33)15&^kavlr`^kdbqqebob`fmbcolj$Kri^qeb?rq`ebo9@llhfkdPrmmifbp;$fkD^o^a^o)K^do^kayyWy144yyKM@y.5/-2)/--64yyLyyAyyIy/43251y
@PlrmcloqebPlriyNFAy..05.yyKyRpbqebX@llhfkdMlqZmolsfabatfqe1XOl^pqba@ibcqellcZql`ob^qbXPmfofqr^iPlrmZyyWy15.yyLyyAyyRy00504y
K/X@ork`evPbombkqZy@LyyNFAy..05.yyKy@llh/XOl^pqba@ibcqellcZ)vlr`^kdbqqebj^qbof^ipcoljP`^ibtfkdPbombkqfk?i^ab$pBadbJlrkq^fkp%36)36&^kavlr`^kdbqqebob`fmbcolj$Ubofkqe^O^sbkl^h9Clla#Aofkh;$fkBsbodolsb)?i^ab$pBadbJlrkq^fkpyyWy142yyKM@y/-416)/-6.3yyLyyAyyIy0.340/y
K0XJlh$K^qe^iPeloqof_pZy@LyyNFAy..05.yyKy@llh0XJlh$K^qe^iPeloqof_pZ)vlr`^kdbqqebj^qbof^ipcoljA^ddboj^tI^peq^fifk?i^ab$pBadbJlrkq^fkp%32)21&^kavlr`^kdbqqebob`fmbcolj$Ubofkqe^O^sbkl^h9Clla#Aofkh;$fkBsbodolsb)?i^ab$pBadbJlrkq^fkpyyWy142yyKM@y/-42.)/-6.3yyLyyAyyIy0.34/0y
@PrmboElqPqbtyNFAy..046yyKyHfii^k>_vpp^iCi^jb_ofkdbo)qebkrpbqeb`lompb^pcfobql`ob^qbXAbjlk?olfibaPromofpbZ%/5+5)52+3&yyWy142yyKM@y.6640yyLyyAyyRy0052/y

QJ^k^if`flrpyNFAy..05-yyKyQebOlhh%3.+3).2+5&yyWy15.yyKM@y/1060yyLyyAy
QObsbkdbfpQ^pqvyNFAy..044yyKyQebOlhh%3.+3).2+5&yyWy15.yyKM@y/1060yyLyyAy
QPlrmcloqebPlriyNFAy..05.yyKyQebOlhh%3.).2&yyWy15.yyKM@y/1060yyLyyAy
QPrmboElqPqbtyNFAy..046yyKyQebOlhh%3.).2&yyWy15.yyKM@y/1060yyLyyAy

KDrfab@ljmibqb
]]
end)
	end
	
	function Guide:Unload()
	end
end
