local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Silvermoon_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Silvermoon City Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OPfisbojllk@fqvyKyQo^sbiqlPfisbojllk@fqv%36+5)/0+1&yyWy15-y
?Jbi^ofp9>i`ebjvPrmmifbp;yKyXOb`fmb7Qo^kpjrqbMofj^iJfdeqZ5d)XOb`fmb7Bifufolc@^jlrci^dbZ0d+?rvs^oflrpifjfqbaprmmivebo_p1-`*0p%34+-).6+/&yyKM@y.331.yyWy15-y
?Ibilof^k9Fkp`ofmqflkPrmmifbp;yKyXP`of_b$pP^q`ebiZ2-p)%36+5)/0+1&yyKM@y0-4/4yyWy15-y
?Ivk^9Bk`e^kqfkdPrmmifbp;yKyXClojri^7PrmbofloTfw^oaLfiZ4d)XClojri^7I^odbMofpj^qf`Pe^oaZ3d)XClojri^7PrmbofloJ^k^LfiZ2d)XM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7JfkloTfw^oaLfiZ2p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)%4-+-)/1+3&yyKM@y.3302yyWy15-y
?V^qeblk9BkdfkbbofkdPrmmifbp;yKyXP`ebj^qf`7>a^j^kqfqbOfcibZ5d)XP`ebj^qf`7TefqbPjlhbCi^obZ3d)XP`ebj^qf`7CbiFolkQlli_luZ1d+?rvs^oflrpifjfqbaprmmivbkdfkbbofkdm^oqp.3`*0-p)%42+5)1-+3&yyKM@y.345/yyWy15-y
?Bofabk9?i^`hpjfqefkdPrmmifbp;yKyXMi^kp7>a^j^kqfqbO^mfboZ1d)XMi^kp7>a^j^kqfqb@ib^sboZ1d)XMi^kp7>a^j^kqfqbA^ddboZ1d)XMi^kp7>a^j^kqfqbJ^riZ1d)%5-+3)04+-&yyKM@y.334-yyWy15-y
?Dbi^kqefp9Gbtbi`o^cqfkdPrmmifbp;yKyXAbpfdk7Lm^iKb`hi^`blcFjm^`qZ42p)XAbpfdk7QebG^abBvbZ/2p)XAbpfdk7Eb^svDliabkKb`hi^`blc?^qqibZ.2p)XAbpfdk7>jribqlcqebJllkZ.5p)%6-+5)40+3&yyKM@y.33/1yyWy15-y
?W^o^ia^9Ib^qebotlohfkdPrmmifbp;yKyXM^qqbok7@ljcloq^_ibFkplibpZ.d)%51+3)46+3&yyKM@y.3356yyWy15-y
?Sbi^kkf9>i`ebjvPrmmifbp#Ob^dbkqp;yKyXJfkloJ^k^MlqflkZ1-`)%36+3)33+3&yyKM@y.33./yyWy15-y
?Nrbifp9@llhfkdPrmmifbp;yKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7PjlhbaP^dbcfpeZ2p)%36+3)4.+/&yyKM@y.3344yyWy15-y
?>kao^9@ilqefbo;yKy?rvs^oflrpifjfqbaprmmiv`ilqep22`*/1p)%32+3)14+5&yyKM@y.330.yyWy15-y
?Abvkk^9Q^filofkdPrmmifbp;yKyXM^qqbok7?liqlcPlri`ilqeZ1d)XM^qqbok7Kbqebotb^sbQrkf`Z1d)XM^qqbok7Kbqebotb^sbOl_bZ1d)XM^qqbok7?liqlcFj_rbaKbqebotb^sbZ1d)%23+-)2.+5&yyKM@y.3305yyWy15-y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
