local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Sons_of_Hodir")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "The Sons of Hodir (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

K@ljmibqbMob*NrbpqyKyVlrtfiikbbaql`ljmibqbPqlojMb^hp%44*5-&coljqebIbsbifkddrfabpb`qflk_bclobvlr`^krpbqefpdrfabyyNFAy.0-14y

OArkKfccbibjyKyQo^sbiqlArkKfccbibjfkPqlojMb^hp%31)3.&yyWy162y
>O^fpfkdElafo$pPmb^oyKyIlobhbbmboO^kasfo%31+5)26+.&)ElklobayyNFAy.0--.yyWy162yyKM@y0-/2/yyOBMy...6)3y
@O^fpfkdElafo$pPmb^oyKyBkqboqeb`^sb^qqebt^vmlfkq%22+6)31+3&^ka`liib`q0XBsbocolpqPe^oapZ%21+4)3-+4&coljqebabmqeplcEf_bok^i@^sbok^ka0XPqlf`J^jjlqeEfabpZcoljqebPqlf`J^jjlqepfkqebS^iibvlc>k`fbkqTfkqbopyyNFAy.0--.yyWy162yyL?Gy5/14yyKM@y0-/3-yyOBMy...6)3y
QO^fpfkdElafo$pPmb^oyKyIlobhbbmboO^kasfo%31+5)26+.&yyNFAy.0--.yyWy162yyKM@y0-/2/yyOBMy...6)3y
>Elq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWy162yyAyyL?Gy5/.5y
>?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWy162yyAyyL?Gy402/y
>MlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWy162yyAyyL?Gy5//.y
>PmvErkqboyKyColpqtlodAbkjlqebo%30+2)26+5&)ElklobayyNFAy./661yyWy162yyAyyKM@y0-/61yyOBMy...6)3y
>QeorpqfkdElafo$pPmb^oyKyElafo$pPmb^o%32)3-+6&)ElklobayyNFAy.0--0yyWy162yyAyyL?Gy5//-yyOBMy...6)3y
>Cbbafkd>okdofjyKy>okdofjqebFkp^qf^_ib%34+2)3-&)ObsbobayyNFAy.0-13yyWy162yyAyyL?Gy5/51yyOBMy...6)4y

@Cbbafkd>okdofjyKyFcvlre^sbmbqpmrqqebjfkqlm^ppfsbjlab+DlqlqebS^iibvlc>k`fbkqTfkqbop%24)31&^karpbX>okdofj$pQllqeZlkqebOl^jfkdGlojrkd^oqebob+Lk`bqebve^sb_b`ljbafpbj_lafba)vlrjrpqcfdeqqebjrkqfiqebv^obtb^hbkbayyRy1/441yyNFAy.0-13yyWy162yyAyyKM@y0-1//yyOBMy...6)4y
@PmvErkqboyKyDllrqql%24+/)31&^karpbXBqebob^iTlod$pC^kdZ^qqeb`lompb+Cliiltqebtlicqe^q^mmb^opqebkhfiiqebAt^osbptebkebpm^tkpqebj)fcvlrdolrmtfqelqebomi^vbopalfkdqefpnrbpqfqtfii_bJR@EC>PQBOyyRy1/146yyNFAy./661yyWy162yyAyyKM@y0/236)0-/.6)0-///yyOBMy...6)3y
@MlifpefkdqebEbijyKyBkqboEf_bok^i@^sboktbpqlcArkKfccbibj%22+3)3/+6&^ka`liib`q2rkfqplcXSfp`lrpLfiZcoljqebSfp`lrpLfipqebobyyNFAy.0--3yyWy162yyAyyKM@y0-0/2y
@QeorpqfkdElafo$pPmb^oyRy1/436yyKyFcvlr$obqovfkdqefpcloqeb.pqqfjbq^hblcc^iivlro^ojlofk`^pbvlrafb+RpbXPmb^olcElafoZlk^TfiaTvoj+Lk`bjlrkqbahbbmmobppfkd.^ka0)tebkvlrdbqqeb$`i^tt^okfkd$mobpp/qlaladbqebkmobpp1+Fkqebkbuqme^pb)mobpp.rkqfivlrpq^`h^qib^pq.-$Mov$^ka^qqbjmqqlhfiifq_vmobppfkd/)fcfqc^fiphbbmmobppfkd.rkqfi/_b`ljbp^s^fi^_ib^d^fkyyNFAy.0--0yyWy162yyAyyKM@y0-/42yyOBMy...6)3y
@?iltfkdElafo$pElokyKyHfii2KfccbibjClobc^qebop^ka2ObpqibppColpq_lok^qQerkaboc^ii%4.)2/&QebkrpbXElafo$pElokZlsboqebfo`lompbpyyRy1/.31yyNFAy./644yyWy162yyAyyKM@y/6641)0-.11y
HHfii?ofqqibObsbk^kqyKyHfii?ofqqibObsbk^kqp^ka`liib`q3uXBppbk`blcF`bZ%4-)26&yyIy1//133yyWy162yyKM@y0-.3-y
@Elq^ka@liayKyIllhcloQfkv_i^`hqefkdptfqepjlhb`ljfkdrmcoljqebj%41)3/&Qebv^obb^pfboqlpmlqfkqebpklt+Dbqkb^olkb)rpb^kXBppbk`blcF`bZ)qebkofdeq*`if`hillqqebjbq^ip`o^m+Alqefprkqfivlre^sb2yyRy1//13yyNFAy./65.yyWy162yyAyyL?Gy5/0.y

QElq^ka@liayKyCglok$p>ksfi%30+/)3/+6&yyNFAy./65.yyWy162yyAyyL?Gy5/.5y
Q?iltfkdElafo$pElokyKyElafo$pElok%31+/)31+1&yNFAy./644yyWy162yyAyyL?Gy402/y
QMlifpefkdqebEbijyKyElafo$pEbij%31+2)26+3&yyNFAy.0--3yyWy162yyAyyL?Gy5//.y
QPmvErkqboyKyColpqtlodAbkjlqebo%30+2)26+5&)ElklobayyNFAy./661yyWy162yyAyyKM@y0-/61yyOBMy...6)3y
QQeorpqfkdElafo$pPmb^oyKyElafo$pPmb^o%32)3-+6&)ElklobayyNFAy.0--0yyWy162yyAyyL?Gy5//-yyOBMy...6)3y
QCbbafkd>okdofjyKy>okdofjqebFkp^qf^_ib%34+2)3-&)ObsbobayyNFAy.0-13yyWy162yyAyyL?Gy5/51yyOBMy...6)4y

?XPlkplcElafo@ljjbka^qflk?^adbZyKyXPlkplcElafo@ljjbka^qflk?^adbZtef`eobt^oap2/-obmrq^qflkmlfkqp^ob^ipl^s^fi^_ibqlmro`e^pbclo.3Grpqf`bMlfkqpcoljqebIbd^`vGrpqf`bNr^oqboj^pqbofkA^i^o^k%31+3)/1+3&yyKM@y02162yyWy2-1y

]]
end)
	end
	
	function Guide:Unload()
	end
end
