local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Thunder_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Thunder Bluff Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

OQerkabo?irccyKyQo^sbiqlQerkabo?ircc%20+3)24+3&yyWy03/y
?Pe^afJfpqorkkbo9Qo^abPrmmifbp;yKyXAbpfdk7Lm^iKb`hi^`blcFjm^`qZ42p)%1-+3)30+3&yyKM@y5030yyWy03/y
?M^ibellc$p?fd?^dlcM^oqp9BkdfkbbofkdPrmmifbp;yKyAlk$q_rvXP`ebj^qf`7Pqb^jQlkh@lkqoliiboZ^pvlr`^k$qobpbiifq+?rvXP`ebj^qf`7ObaCfobtlohZ.5p^kas^oflrpifjfqbaprmmivbkdfkbbofkdm^oqp.3`*0-p)%03+5)26+/&yyKM@y2/322yyWy03/y
?J^er9Q^filofkdPrmmifbp;yKyXM^qqbok7TefqbTbaafkdAobppZ.d)XM^qqbok7Lo^kdbJ^oqf^iPefoqZ0-p)XM^qqbok7ObaTllibk?^dZ2p)XM^qqbok7ObaIfkbk?^dZ/p)%10+5)11+3&yyKM@y0--2yyWy03/y
?Hrk^Qerkaboelok9?ltvbo#Cibq`efkdDllap;yKyXJ^ppfsbIlkd_ltZ3d46p)XPqroavOb`rosbZ.d62p)XCfkbPeloq_ltZ0/p)%13+5)11+1&yyKM@y0-.2yyWy03/y
?K^q^A^tkpqofabo9Bk`e^kqfkdPrmmifbp;yKyXM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7Bk`e^kq?llqp*Jfklo>dfifqvZ.-p)XClojri^7Bk`e^kq/ETb^mlk*IbppboFkqbiib`qZ2p)XClojri^7JfkloTfw^oaLfiZ2p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)%12+-)05+3&yyKM@y0-./yyWy03/y
?K^^iJfpqorkkbo9@llhfkdPrmmifbp;yKyXOb`fmb7P^dbcfpeAbifdeqZ2-p)XOb`fmb7?ofpqibTefphbo@^qcfpeZ./p)XOb`fmb7Ilkdg^tJraPk^mmboZ1p)XOb`fmb7PjlhbaP^dbcfpeZ2p)%2.+3)2/+5&yyKM@y0-/4yyWy03/y
?AbidlO^dbqlqbj9>ubJbo`e^kq;yKyXJbo`fibpp>ubZ0d/p)%20+3)24+3&yyKM@y0-.6yyWy03/y
?Pbt^Jfpqorkkbo9CfpefkdPrmmifbp;yKyXOb`fmb7?ofpqibTefphbo@^qcfpeZ./p)XPqolkdCfpefkdMlibZ6p/`)XOb`fmb7?ofiif^kqPj^iicfpeZ1-`)%23+3)14+/&yyKM@y0-/6yyWy03/y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
