local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_ThunderBluff_Cook_Fishing")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Thunder Bluff Cooking & Fishing (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

K>``bmq@llhfkdA^fivNrbpqyKy>``bmq^nrbpqcolj>ph^Jfpqorkkbo%2.)2/+5&fkQerkabo?irccqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqloqf`hfqkltqlphfmalfkd@llhfkdA^fivyyWy03/yyKM@y0-/3y

>J^df`JrpeolljpyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/603/yyWy03/yyAyyKM@y0-/3y
>@lokJ^peyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/6031yyWy03/yyAyyKM@y0-/3y
>JridlobPmf`b?ob^ayLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/6030yyWy03/yyAyyKM@y0-/3y
>Mbocb`qivMf`hbaMloqflkpyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/3//-yyWy03/yyAyyKM@y0-/3y
>MfkfkdcloKrqpyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/6025yyWy03/yyAyyKM@y0-/3y

@@lokJ^peyLyyKyDofka3@lokHbokbipfkpfabqeberqp^olrkaQerkabo?ircc%2/+2)23+2&%26+4)2.+/&%21+.)12+5&yyNFAy/6031yyWy03/yyAyyL?Gy.-300y
K2XPmf`ba?ob^aZyLyyKy@ob^qb2XPmf`ba?ob^aZ^iifqq^hbpfp.XCilroZ^ka.XJfiaPmf`bpZtef`e`^k_bmro`e^pbacoljK^^iJfpqorkkbo%2.+5)2/+5&yyNFAy/6030yyWy03/yyAyyQyyKM@y0-/4y
@JridlobPmf`b?ob^ayLyyKyRpbXJridlobPmf`bpZtfqeXPmf`b?ob^aZql`ob^qb2XCobpeJridlobPmf`b?ob^aZyyNFAy/6030yyWy03/yyAyyRy36664y
KXCobpe*ErkqbaCltiZyNFAy/6032+1yyKy@liib`qXCobpe*ErkqbaCltiZ)clrkae^kdfkd_vqeberq%2.+./)14+23&yyQyyIy4---0yyLyyWy03/yyAyyL?Gy.-301y
KXCobpe*@^rdeqCfpeZyNFAy/6032+0yyKy@liib`qXCobpe*@^rdeqCfpeZ)clrkafkCfpefkdQo^fkbo$pqbkqe^kdfkdcoljqeb`bfifkd^qqeb_^`h%22+63)11+30&yyQyyIy4---/yyLyyWy03/yyAyyL?Gy.--01y
KXPr``ribkqPtbbqMlq^qlbpZyNFAy/6032+.yyKy@liib`qXPr``ribkqPtbbqMlq^qlbpZ+ClrkatebobqebCorfq^kaSbdbq^_ibqbkqfp%14+5.)1/+25&yyQyyIy4----yyLyyWy03/yyAyyL?Gy4161y
KXP^slovPmf`bpZyNFAy/6032+/yyKy@liib`qXP^slovPmf`bpZcoljfkqebEbo_^ifpjQo^fkbo$perq%16+35)1.+6-&yyQyyIy4---.yyLyyWy03/yyAyyL?Gy4//1y
K3XJridlobMfkb@lkbZyKy@liib`q3XJridlobMfkb@lkbpZ^qqeb_^pblc^kvqobbfkQerkabo?ircc%16+.-)20+54&%20+4.)1/+65&yyQyyLyyIy3666-6yyNFAy/6025yyWy03/yyAyyL?Gy1/1y
@MfkfkdcloKrqpyLyyKyRpb3XJridlobMfkb@lkbpZlsbo^cfobql`ob^qb0-XMfkbKrqpZ%2.)2/+5&yyNFAy/6025yyWy03/yyAyyRy3666-yyL?Gy1/1y

K>``bmqCfpefkdA^fivNrbpqyKy>``bmq^nrbpqcoljH^eJfpqorkkbo%23+3)14+3&fkQerkabo?irccqebkqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqloqf`hfqkltqlphfmalfkdCfpefkdA^fivyyWy03/yyKM@y0-/5y

>@o^sfkd@o^vcfpeyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6016yyWy03/yyAyyKM@y0-/5y
>MlkaMoba^qlopyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6012yyWy03/yyAyyKM@y0-/5y
>Pefkv?^r_ibpyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6021yyWy03/yyAyyKM@y0-/5y
>QebO^`bqlObpql`hyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6015yyWy03/yyAyyKM@y0-/5y
>QebOfkd$pqebQefkdyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6013yyWy03/yyAyyKM@y0-/5y

@J^df`JrpeolljpyLyyKyD^qebo3XJ^df`JrpeolljpZcoljqebMlliplcSfpflkfkQerkabo?ircc%//+5)/.+4&yyNFAy/603/yyWy03/yyAyyL?Gy.-30/y

@@o^sfkd@o^vcfpeyLyyKy@^q`e.-XPqlkb_rii@o^vcfpeZcoljPqlkb_riiI^hbfkJridlob%2.+4)2/+4&yyNFAy/6016yyWy6yyAyyKM@y2023.y
@MlkaMoba^qlopyLyyKy@^q`e5X>wpe^o^Pk^hbeb^acfpeZcoljqebQerkabo?irccmlka%1-+3)23&yyNFAy/6012yyWy03/yyAy
@Pefkv?^r_ibpyLyyKy@liib`q/-XPefkvPqlkbpZcolj^olrkaqeb`bkqo^iofpb$p_^pb+%34+.)24+1&%21+2)34+.&%11+5)41+6&yyNFAy/6021yyWy03/yyAyyL?Gy.-3/4y
@QebO^`bqlObpql`hyLyyKy@^q`e/XO^kavPj^iicfpeZ^ka/X>jlolrpJraPk^mmbopZcoljPqlkb_riiI^hbfkJridlob%2.+4)2/+4&yyNFAy/6015yyWy6yyAy
@QebOfkd$pqebQefkdyLyyKyCfperm^X?ifka@^sbcfpeZcoljqebMlliplcSfpflkfkQerkabo?ircc+Lk`bvlr`^q`e^`^sbcfpe)rpbfq^ka`eb`hfcfqpt^iiltbaqebofkd%/3).5&yyRy36623yyNFAy/6013yyWy03/yyAy

Q@o^sfkd@o^vcfpeyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6016yyWy03/yyAyyKM@y0-/5y
QMlkaMoba^qlopyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6012yyWy03/yyAyyKM@y0-/5y
QPefkv?^r_ibpyLyyKyK^e^of@ilra`e^pbo%02+3)20+3&yyNFAy/6021yyWy03/yyAyyKM@y2/324y
QQebO^`bqlObpql`hyLyyKyH^eJfpqorkkbo%23+3)14+3&yyNFAy/6015yyWy03/yyAyyKM@y0-/5y
QQebOfkd$pqebQefkdyLyyKyMlpehbkE^oa_fkabo%/5+5)/-+1&yyNFAy/6013yyWy03/yyAyyKM@y0-4-6y

QJ^df`JrpeolljpyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/603/yyWy03/yyAyyKM@y0-/3y
Q@lokJ^peyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/6031yyWy03/yyAyyKM@y0-/3y
QJridlobPmf`b?ob^ayLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/6030yyWy03/yyAyyKM@y0-/3y
QMbocb`qivMf`hbaMloqflkpyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/3//-yyWy03/yyAyyKM@y0-/3y
QMfkfkdcloKrqpyLyyKy>ph^Jfpqorkkbo%2.)2/+5&yyNFAy/6025yyWy03/yyAyyKM@y0-/3y

KDrfab@ljmibqbyKyQf`hql`lkqfkrbqlqebkbuqdrfaby
]]
end)


	end
	
	function Guide:Unload()
	end
end
