local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Undercity_Vendor_Run")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Vendor Supply Run|r ", "Undercity Vendor Run", nil, "Horde", "D", nil, function()
return [[
AAA

KJfppfkdFqbjpyKyFqfpkloj^iclopljbfqbjpql_bjfppfkdcoljqebsbkalo^pfqfpifjfqba^katfiiobpm^tk^cqbo./*/1elrop+Fcpljblkbbipb_lrdeqfq^eb^alcvlrqebkfqtfiikbbapljbqfjbclofqqlobpm^tk^d^fk+Vlrtfiikbbaqljlsblkqlqebkbuqsbkalo^kaelmbcriivfqtfii^mmb^oqebkbuqqfjbvlralqebsbkaloork)qf`hqefppqbmy

ORkabo`fqvyKyQo^sbiqlRkabo`fqv%/4+5)3/+5&yyWy05/y
?A^kfbi?^oqibqq9Qo^abPrmmifbp;yKyAlk$q?rvXClojri^7Bk`e^kqPefbia*Dob^qboPq^jfk^Z^pvlr`^k$qobpbiifq+?rvXAbpfdk7>jribqlcqebJllkZ.5p)%31+5)05+/&yyKM@y123.yyWy05/y
?Cbif`f^Al^k9Qo^abPrmmifbp;yKyXAbpfdk7QebG^abBvbZ/2p)%31+5)16+5&yyKM@y1442yyWy05/y
?>_fd^fiP^tvbo9?ltJbo`e^kq;yKyXJ^ppfsbIlkd_ltZ3d46p)XPqroavOb`rosbZ.d61p)XCfkbPeloq_ltZ0.p)%22+-)04+1&yyKM@y13-1yyWy05/y
?F`h^_laMfjibk9Fkp`ofmqflkPrmmifbp;yKyXP`of_b$pP^q`ebiZ2-p)%3.+3)25+3&yyKM@y0-4/6yyWy05/y
?Qe^aabrpTb__9Bk`e^kqfkdPrmmifbp;yKyXM^qqbok7Bk`e^kqbaJ^dbtb^sbMlr`eZ3-p)XClojri^7IbppboTfw^oaLfiZ1-p)XClojri^7JfkloJ^k^LfiZ0-p)XClojri^7JfkloTfw^oaLfiZ2p)XIbppboJ^df`Bppbk`bZ5p)XPqo^kdbArpqZ5p)%3/+-)3-+5&yyKM@y13.4yyWy05/y
?>idboklk9>i`ebjvPrmmifbp;yKyXOb`fmb7BifufolcPe^altMltboZ.d)%2/+3)42+-&yyKM@y13.-yyWy05/y
?GlpbmeJllob9Ib^qebotlohfkdPrmmifbp;yKyXM^qqbok7DobbkTebim?o^`bopZ/5p)XM^qqbok7?^o_^of`?o^`bopZ/-p)%4-+3)26+3&yyKM@y1256yyWy05/y
?Bifw^_bqeS^kQ^ibk9BkdfkbbofkdPrmmifbp;yKy?rvs^oflrpifjfqbaprmmivbkdfkbbofkdm^oqp.3`*0-p)%42+2)41+0&yyKM@y1254yyWy05/y
?Ifw_bqe@oljtbii9CfpefkdPrmmifbp;yKyXOb`fmb7JfqeofiEb^aQolrqZ//p)XOb`fmb7Ol`hp`^ib@laZ//p)XOb`fmb7Ilkdg^tJraPk^mmboZ1p)XPqolkdCfpefkdMlibZ6p/`)XOb`fmb7?ofiif^kqPj^iicfpeZ1-`)%5.+5)0-+3&yyKM@y1241yyWy05/y
?P^i^w^o?il`e9?llhAb^ibo;yKyXP`of_b$pP^q`ebiZ2-p)%44+/)05+3&yyKM@y125.yyWy05/y
?JfiifbDobdlof^k9Q^filofkdPrmmifbp;yKyXM^qqbok7QrubalG^`hbqZ2-p)XM^qqbok7QrubalM^kqpZ12p)XM^qqbok7QrubalPefoqZ12p)XM^qqbok7Dob^qbo>abmq$pOl_bZ5p)XM^qqbok7ObaTllibk?^dZ2p)%4-+5)/6+3&yyKM@y1244yyWy05/y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
