local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Undercity_Cook_Fishing")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Profession|r ", "Undercity Cooking & Fishing (Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

K>``bmq@llhfkdA^fivNrbpqyKy>``bmq^nrbpqcoljBrkf`b?ro`e%3/+5)11+/&fkRkabo`fqv)qf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqloqf`hfqkltqlphfmalfkd@llhfkdA^fivyyWy05/yyKM@y122/y

>Bp`^odlq>Dl*DlyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/6000yyWy05/yyAyyKM@y122/y
>Crkdrp>jlkdRpyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/60.2yyWy05/yyAyyKM@y122/y
>Ifiv)LeIfivyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/600/yyWy05/yyAyyKM@y122/y
>Ol^`e@l^`eyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/6001yyWy05/yyAyyKM@y122/y
>TlriaVlrIfhbPljbCifbpTfqeQe^q<yLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/603-yyWy05/yyAyyKM@y122/y

@TlriaVlrIfhbPljbCifbpTfqeQe^q<yLyyKy@liib`q/2X?il^qbaCifbpZcoljqebjb^qkb^oqebJb^qT^dlkp%36+2)2/+3&%50+4)32+.&%51+0)11+.&yyNFAy/603-yyWy05/yyAyyRy3666-yyL?Gy.1y
@Ol^`e@l^`eyLyyKyIllhclopj^iitllabk_lubpql`liib`q/-XMirjm@l`hol^`ebpZ+Vlr`^kcfkaqebjlkqeb_lqqljcillofkqebjfaaiblcqebqo^ab^ob^%33+5)2/+4&%4.+0)11+3&%3/+1)02+1&yyNFAy/6001yyWy05/yyAyyL?Gy003y

K>``bmqCfpefkdA^fivNrbpqyKy>``bmq^nrbpqcolj>oj^ka@oljtbii%5.)0-+5&fkRkabo`fqv)qebkqf`hqefpl_gb`qfsb>CQBOvlr^``bmqqebnrbpqloqf`hfqkltqlphfmalfkdCfpefkdA^fivyyWy05/yyKM@y1240y

>CfpeEb^ayLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60.4yyWy05/yyAyyKM@y1240y
>IfhbMfhb<yLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60/-yyWy05/yyAyyKM@y1240y
>Jl^qJlkpqboyLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/603.yyWy05/yyAyyKM@y1240y
>Q^amlibQbooloyLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60.6yyWy05/yyAyyKM@y1240y
>QfjbcloPifjbyLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60//yyWy05/yyAyyKM@y1240y

@CfpeEb^ayLyyKyCfperm^XPbsboba>_ljfk^qflkEb^aZfkRkabo`fqv%45+/)0-&yyNFAy/60.4yyW05/yyAy
@QfjbcloPifjbyLyyKy@^q`e.-XPnrfojfkdPifjbJliaZcoljRkabo`fqvPbtbop%5.)0-+5&yyRy36623yyNFAy/60//yyWy05/yyAyyKM@y202.4y
QCfpeEb^ayLyyKyJ^pqbo>mlqeb`^ovC^o^kbii%15+1)36+/&yyNFAy/60.4yyWy05/yyAyyKM@y/-22y
QQfjbcloPifjbyLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60//yyWy05/yyAyyKM@y1240y

@Crkdrp>jlkdRpyLyyKy@liib`q./XPbtbo@^mpZfkqebpbtboplcRkabo`fqv%14+.)/6+2&%1-+4)/1+4&%00+1)/6+0&yyNFAy/60.2yyWy05/yyAyyL?Gy.-3.2y

KX@lompbTlojZyLyyKyAfdrm^X@lompbTlojZcolj^afoqjlrkafkqebOrfkplcIloa^bolk`lroqv^oa%32+/).2+2&yyNFAy/60/-yyWy05/yyAyyIy366-4yyQyyL?Gy/-y
@IfhbMfhb<yLyyKyRpbX@lompbTlojZ^p_^fqql`^q`e^@lompb*CbaMfhb)tef`e`^k_bcfpebarmfk?ofdeqt^qboI^hb%36)16&yyNFAy/60/-yyWy/-yyAy
RXJl^qJlkpqboCbbafkdHfqZyKyLmbkXJl^qJlkpqboCbbafkdHfqZ^ka`liib`qX>iif^k`bAb`lvHfqZ^kaX?il^qbaColdZyyRy36666yyLyyNFAy/603.y
@Jl^qJlkpqboyLyyKyDlqlqebJl^q^qOrfkplcIloa^bolk^karpbX>iif^k`bAb`lvHfqZqlprjjlkqebjl^qjlkpqbopqebkrpbX?il^qbaColdZ^qqebjlkpqbo)obmb^qrkqfivlrcbbaqebjlkpqbo.-coldp%31+-3).5+33&yyNFAy/603.yyWy05/yyAyyRy36662yyKM@y2026-y

@Bp`^odlq>Dl*DlyLyyKy@liib`q5X?ofdeqt^qboPk^fipZfk?ofdeqt^qboI^hb%35)16&Qfofpc^iDi^abyyNFAy/6000yyWy/-yyAyyKM@y202/3y

@Q^amlibQbooloyLyyKy@^q`e5XDf^kqCibpe*B^qfkdQ^amlibpZ_v@liaEb^oqeJ^klomlka%2.+.)21+4&yyNFAy/60.6yyWy/-yyAy
@Ifiv)LeIfivyLyyKy@liib`q.-X.-Pqfiit^qboIfiifbpZ%2-+6)22+5&yyNFAy/600/yyWy/-yyAyyRy36664yyL?Gy5232y

QBp`^odlq>Dl*DlyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/6000yyWy05/yyAyyKM@y122/y
QCrkdrp>jlkdRpyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/60.2yyWy05/yyAyyKM@y122/y
QIfiv)LeIfivyLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/600/yyWy05/yyAyyKM@y122/y
QOl^`e@l^`eyLyyKy@ebc>raobv%3/+1)02+1&yyNFAy/6001yyWy05/yyAyyKM@y202/5y
QTlriaVlrIfhbPljbCifbpTfqeQe^q<yLyyKyBrkf`b?ro`e%3/+5)11+/&yyNFAy/603-yyWy05/yyAyyKM@y122/y

QIfhbMfhb<yLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60/-yyWy05/yyAyyKM@y1240y
QJl^qJlkpqboyLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/603.yyWy05/yyAyyKM@y1240y
QQ^amlibQbooloyLyyKy>oj^ka@oljtbii%5.)0-+5&yyNFAy/60.6yyWy05/yyAyyKM@y1240y

KDrfab@ljmibqb+yKyRiqfj^qbTlTDrfab+`ljy

]]
end)
	end
	
	function Guide:Unload()
	end
end
