local Guide = DugisGuideViewer:RegisterModule("DugisGuide_Dailies_Horde_En_Venture_Bay_H")
function Guide:Initialize()
	function Guide:Load()DugisGuideViewer:RegisterGuide("|cfff0c502Northrend|r ", "Venture Bay (200 Honor Daily)", nil, "Horde", "D", nil, function()
return [[
AAA

O@lknrbpqEliayKyCivql@lknrbpqEliafkDofwwivEfiip%/3+2)32+5&yyNFAy./.4-yyAyyWy16-y
>?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyAyyKM@y/4./-yyWy16-y
@?i^`hofsbo?o^tiyKyHfii.->iif^k`bKM@ploMi^vbopfk?i^`hofsboIlddfkd@^jm%/5+2)3/+3&yyNFAy./.4-yyAyyKM@y/4..4yyWy16-y
Q?i^`hofsbo?o^tiyKyO^fabo@^mq^fkHolkk%/3+2)32+5&yyNFAy./.4-yyAyyKM@y/4./-yyWy16-y

OSbkqrob?^vyKyQo^sbiqlSbkqrob?^v%//+.)5.+/&yyNFAy./0.4yyAyyWy16-y
>HbbmQebj^q?^vyKy@bkqroflkH^ddorj%.-+.)44+0&yyNFAy./0.4yyAyyKM@y/4230yyWy16-y
>@orpe@^mq^fk?ofdeqt^qboyKyDbkbo^iHe^wd^o%.-+.)44+/&yyNFAy./0.2yyAyyKM@y/420/yyWy16-y
>Pjlhb$BjLrqyKyPqlkbDr^oaO^dbqlqbj%..+0)43+5&yyNFAy./0/1yyAyyKM@y/43-3yyWy16-y
>PbbhfkdPlisbkqyLyyKyDroqlo%..+/)43+3&yyNFAy./100yyAyyKM@y/4232yyWy16-y

@Pjlhb$BjLrqyKyDlql?rkhelrpb7%.2)43&P^tjfii7%.3)43&Pq^_ibp7%.5)5-&^ka^dol^iiqebSbkqrob@ljm^kvPqo^ddibop^karpbqebXPjlhb?lj_Zlkqebdolrm`e^pfkdvlryyRy043/.yyNFAy./0/1yyAyyKM@y/424-yyWy16-y
@@orpe@^mq^fk?ofdeqt^qboyKyHfii@^mq^fk?ofdeqt^qbo%.4)5/&yyNFAy./0.2yyAyyKM@y/42-6yyWy16-y
@HbbmQebj^q?^vyKyHfii.->iif^k`bRkfqplo>iif^k`bmi^vbopfkSbkqrob?^v^ob^%.3+4)46&yyNFAy./0.4yyAyyKM@y/42-.)/42--)/422-yyWy16-y
@PbbhfkdPlisbkqyLyyKyDbqqebXBibjbkq..2ZfkqebDl_ifk_l^q%.3+2)5-+0&yyNFAy./100yyAyyL?Gy5-66yyWy16-y

QPbbhfkdPlisbkqyLyyKyDroqlo%..+/)43+3&yyNFAy./100yyAyyKM@y/4232yyWy16-y
QHbbmQebj^q?^vyKy@bkqroflkH^ddorj%.-+.)44+0&yyNFAy./0.4yyAyyKM@y/4230yyWy16-y
Q@orpe@^mq^fk?ofdeqt^qboyKyDbkbo^iHe^wd^o%.-+.)44+/&yyNFAy./0.2yyAyyKM@y/420/yyWy16-y
QPjlhb$BjLrqyKyPqlkbDr^oaO^dbqlqbj%..+0)43+5&yyNFAy./0/1yyAyyKM@y/43-3yyWy16-y

KDrfab@ljmibqb

]]
end)	end
	
	function Guide:Unload()
	end
end
